"""Boss action-menu names and 中美合 quiz."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    A = "中美合："
    return {
        "boss_4dboil_actmenu#0": "过熟煮蛋",
        "boss_4dboil_actmenu#1": "四次元陨石",
        "boss_4dboil_actmenu#2": "四次元灾变",
        "boss_4dboil_actmenu#3": "彩色异界心",
        "boss_4dboil_actmenu#4": "粉红美人",
        "boss_4dboil_actmenu#5": "力量煮蛋",
        "boss_4dboil_actmenu#6": "迷雾预言",
        "boss_4dboil_actmenu#7": "邪恶范式",
        "boss_4dboil_actmenu#8": "双电子步枪",
        "boss_4dboil_actmenu#9": "传说之夜动",
        "boss_aki_actmenu#0": "去天堂",
        "boss_aki_actmenu#1": "爱与蒙蔽",
        "boss_aki_actmenu#2": "耶——。",
        "boss_ata8_actmenu#0": "周力",
        "boss_ata8_actmenu#1": "当场打",
        "boss_ata8_actmenu#2": "再大感谢",
        "boss_ata8_actmenu#3": "回到原处",
        "boss_ata8_ans_10#0": "被骗了！",
        "boss_ata8_ans_10#1": "好过分。",
        "boss_ata8_ans_11#0": "热的东西",
        "boss_ata8_ans_11#1": "里比多",
        "boss_ata8_ans_12#0": "12点",
        "boss_ata8_ans_12#1": "很多",
        "boss_ata8_ans_13#1": "不是。",
        "boss_ata8_ans_14#1": "不是。",
        "boss_ata8_ans_15#1": "不是。",
        "boss_ata8_ans_16#1": "不是。",
        "boss_ata8_ans_17#1": "不是。",
        "boss_ata8_ans_18#1": "不是。",
        "boss_ata8_ans_19#1": "原来是这样。",
        "boss_ata8_ans_20#0": "没有。",
        "boss_ata8_ans_20#1": "不是。",
        "boss_ata8_ans_21#0": "是。",
        "boss_ata8_ans_21#1": "不是。",
        "boss_ata8_ans_26#1": "不是。",
        "boss_ata8_ans_27#1": "不是。",
        "boss_ata8_ans_5#0": "勇者斗恶龙",
        "boss_ata8_ans_5#1": "铁拳",
        "boss_ata8_ans_5#2": "半熟英雄",
        "boss_ata8_ans_5_ex#0": A + "谢谢……那么飞地送你密语当礼物。",
        "boss_ata8_ans_5_ex#1": "ファイナルクエスト装ー2インター",
        "boss_ata8_ans_6_c#1": "不是。",
        "boss_ata8_ans_7#0": "面包",
        "boss_ata8_ans_7#1": "米饭",
        "boss_ata8_ans_8#1": "不是。",
        "boss_ata8_ans_9#0": "哪有",
        "boss_ata8_ans_9#1": "骗人。",
        "boss_ata8_ans_miss": A + "果然不行啊！",
        "boss_ata8_ans_nomoney": "要大感谢的话波奇利不够！",
        "boss_ata8_que_0#0": "要大感谢的话，是要花波奇利的？",
        "boss_ata8_que_0#1": "现在的波奇利额",
        "boss_ata8_que_1": A + "还要再大感谢吗？",
        "boss_ata8_que_10": A + "骗人。",
        "boss_ata8_que_11": A + "气是什么？",
        "boss_ata8_que_12": A + "，几点？",
        "boss_ata8_que_13": A + "游戏有守一天一小时吗？",
        "boss_ata8_que_14": A + "脚只是装饰吗？",
        "boss_ata8_que_15": A + "读铅字就会平静下来？",
        "boss_ata8_que_16": A + "今天就能定下来了！",
        "boss_ata8_que_17": A + "怕明被喜欢是自己的错！",
        "boss_ata8_que_18": A + "想出道然后落选！",
        "boss_ata8_que_19#0": A + "少用带来的力今是战弱，显著减少了！",
        "boss_ata8_que_19#1": "关于那力今内容，也没有形谁力今被复述的占攻！",
        "boss_ata8_que_2": A + "真的，还要再大感谢吗？",
        "boss_ata8_que_20": A + "那场战斗里有大？分吗？",
        "boss_ata8_que_21#0": A + "求你了。就这一次换个姿",
        "boss_ata8_que_21#1": "原谅我吧。呐。呐。",
        "boss_ata8_que_22": A + "果然，还要再大感谢吗？",
        "boss_ata8_que_23": A + "认真的吗？",
        "boss_ata8_que_24": A + "变成怎样我可不管哦？",
        "boss_ata8_que_25": A + "会游戏结束哦？",
        "boss_ata8_que_26": A + "不生气吗？",
        "boss_ata8_que_27": A + "真的？",
        "boss_ata8_que_28": A + "教回定好了吗？",
        "boss_ata8_que_29": A + "那么，上吧！",
        "boss_ata8_que_3": A + "可以吧？",
        "boss_ata8_que_4": A + "真的可以吧？",
        "boss_ata8_que_5": A + "勇者斗恶龙和铁拳更喜欢哪个？",
        "boss_ata8_que_6": A + "从现在能会吗？",
        "boss_ata8_que_6_b": A + "哦。当界吗？",
        "boss_ata8_que_6_c": A + "气还记得吗？",
        "boss_ata8_que_7": A + "中餐更喜欢哪个？",
        "boss_ata8_que_8": A + "说过喜欢的事，认真？",
        "boss_ata8_que_9#0": A + "的事",
        "boss_ata8_que_9#1": "被说恶心了哦！",
        "boss_atom_actmenu#0": "打击战斗机",
        "boss_atom_actmenu#1": "毒刺",
        "boss_atom_actmenu#2": "来自地球的讯息",
        "boss_death_actmenu#0": "被阵的镰",
        "boss_death_actmenu#1": "被阵的抽",
        "boss_death_actmenu#2": "被阵的合",
        "boss_eggboil_actmenu#0": "静静伫立",
        "boss_eggboil_actmenu#1": "放臭气",
        "boss_eggboil_actmenu#2": "激烈地熟",
        "boss_eggmama_actmenu#0": "神反本威",
        "boss_eggmama_actmenu#1": "出造",
        "boss_eggmama_actmenu#2": "费",
        "boss_emtp_actmenu#0": "中潜新所友形所潜潜强",
        "boss_emtp_actmenu#1": "死形以打气间以败所",
        "boss_emtp_actmenu#2": "教友以败新",
        "boss_fly_actmenu#0": "生模式",
        "boss_fly_actmenu#1": "死模式",
        "boss_fly_actmenu#2": "使少谁惑谁少",
        "boss_full_actmenu#0": "全灯",
        "boss_full_actmenu#1": "哑铃炸弹",
        "boss_full_actmenu#2": "峰值构筑",
        "boss_haru_actmenu#0": "进终君的书",
        "boss_haru_actmenu#1": "进终君复制",
        "boss_haru_actmenu#2": "进终君入口捉",
        "boss_hell_actmenu#0": "再来一碗。",
        "boss_hell_actmenu#1": "来了——。",
        "boss_hell_actmenu#2": "要修吗。？",
        "boss_huyu_actmenu#0": "完全无敌占卜",
        "boss_huyu_actmenu#1": "最强的食气梦大",
        "boss_huyu_actmenu#2": "暖风机",
        "boss_motk_actmenu#0": "N活」",
        "boss_motk_actmenu#1": "莫特·库蒙。",
        "boss_motk_actmenu#2": "王牌库蒙。",
        "boss_mots_actmenu#0": "把斗篷闭上",
        "boss_mots_actmenu#1": "莫特·苏蒙。",
        "boss_mots_actmenu#2": "攻变之一",
        "boss_natu_actmenu#0": "次元刃",
        "boss_natu_actmenu#1": "次元体操",
        "boss_natu_actmenu#2": "大众N淋浴",
        "boss_natu_actmenu#3": "大众N淋浴反击",
        "boss_omega_actmenu#0": "夜动殿",
        "boss_omega_actmenu#1": "原子射线",
        "boss_omega_actmenu#2": "德尔塔攻击",
        "boss_omega_actmenu#3": "吃鸣门",
        "boss_omega_actmenu#4": "芥末炸弹",
        "boss_runa_actmenu#0": "兔皮诺舞",
        "boss_runa_actmenu#1": "新月",
        "boss_runa_actmenu#2": "阿弗罗13",
        "boss_tkkn_actmenu#0": "嗯夏巴·哒",
        "boss_tkkn_actmenu#1": "人的机械",
        "boss_tkkn_actmenu#2": "定体消临",
        "boss_ugok_actmenu#0": "打啊。",
        "boss_ugok_actmenu#1": "乱抓啊。",
        "boss_ugok_actmenu#2": "是猿光束啊。",
    }
