"""Power-egg encyclopedia blurbs."""
from __future__ import annotations

from zh_dic_eg_lib import e


def by_id() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(e("menu_dic_eg_pw_116", "持消通道负欲", "与本·生君（17岁）的设计。"))
    out.update(e(
        "menu_dic_eg_pw_bari",
        "指定了战场的、400战不败的人生最强之人！",
        "这种连一掺进来工作就没了，",
        "爹地和海葵杰克都嫌弃着！",
    ))
    out.update(e(
        "menu_dic_eg_pw_bldr",
        "冬天操会改，是因为蓝龙想起核现上场失败",
        "发冷才会激出来！",
        "看见飞在上天的话请间（）！",
    ))
    out.update(e(
        "menu_dic_eg_pw_boka",
        "可喜可贺逃负见进了是好，最近却是低潮气活！",
        "失所好像在以前的读星里！",
        "上场的烦躁，全在对战里发入！",
    ))
    out.update(e(
        "menu_dic_eg_pw_broc",
        "飞造的运动服把」裹上，和谁的降合战斗下去的",
        "地上正义的西兰花·李！代号是龙！",
        "最近综艺节目来的工作阵赖也很少！",
    ))
    out.update(e(
        "menu_dic_eg_pw_cycl",
        "讨厌洗澡的独眼巨人，因为那中体气味也吓人！",
        "可他惑」并不在意那种殿终，",
        "觉得只要连着骰子人气就不会掉！",
    ))
    out.update(e(
        "menu_dic_eg_pw_eggk",
        "高傲骑士之任，和蛋剑的弱力量投",
        "讨伐大地上横行的大谁之物。",
        "去吧，骑士。、！是你们变一的番军完着。",
    ))
    out.update(e(
        "menu_dic_eg_pw_hvms",
        "占把对终的气能在心里战斗下去的、帅气爸爸！",
        "孩子弱时，察觉间开的气才是逃力的他，",
        "最近，据说潜姿进了婚礼繰状人！",
    ))
    out.update(e(
        "menu_dic_eg_pw_isgn",
        "蛋怪爹地的、姿形对手！",
        "那些各式触手全都使足了劲，所以相当费人手！",
        "好像讨厌真刀真枪！",
    ))
    out.update(e(
        "menu_dic_eg_pw_kawa",
        "疯狂科学家博士开发的",
        "以恐怖临繰为长的机体！",
        "把这当降来仰的人旗也不立，最近臭负降发足了！",
    ))
    out.update(e(
        "menu_dic_eg_pw_kimr",
        "向能了的连喜和撤着的逃人朝着喜着写的家伙们！",
        "最近比起连喜／的场，反而察觉日消场的冬天反，",
        "据说进了蛋怪说唱歌手的儿子终！",
    ))
    out.update(e(
        "menu_dic_eg_pw_mggm",
        "还以为只是況占现入的大叔们，",
        "其实是为守护世界而集齐的六人气弱！",
        "开分掘藏的魅力反不低，魔坏很硬！",
    ))
    out.update(e(
        "menu_dic_eg_pw_moon",
        "飞读造星了的、月光棱镜的白体美！",
        "一边消里挑战阵白的客界，一边不垮鲜艳的上生！",
        "明里能阵好像有惑中，一被夸就会投！",
    ))
    out.update(e(
        "menu_dic_eg_pw_ngrd",
        "换乘军人心的其中一人，这么中着！",
        "真的干不下去了！最近公寓也买了",
        "人生从这儿才开始，工作却危险过头了！",
    ))
    out.update(e(
        "menu_dic_eg_pw_nymp",
        "美丽的施、可恨的目光，再加上练出来的阵白，",
        "把人激迷住的商气宁芙！他柔韧的唤",
        "被称为商气之，连在体上就会飞上天！",
    ))
    out.update(e(
        "menu_dic_eg_pw_rddr",
        "那翅膀覆着天，吐息把世界变成怪之天，",
        "弱的分不放过捉住的东西，姬怪的心」！",
        "以这收使的明为占，没有活着回去的人！",
    ))
    out.update(e(
        "menu_dic_eg_pw_roll",
        "变着滚筒的客里没人守出来，",
        "从小报起就被任着操场字备！",
        "字备时碍事的足球门逃讨厌！",
    ))
    out.update(e(
        "menu_dic_eg_pw_tagm",
        "把人体团弱的新时解大了的两人，",
        "打开效读当完逃之变，被变成水黾的姿！",
        "实验体的各位！感谢您的协助。",
    ))
    out.update(e(
        "menu_dic_eg_pw_tera",
        "使复是乐土所以去了不用费怪读的弱姫，",
        "别说使复，況字也捨不了的不军！",
        "变着箱弱，打不开弱姫信息是占讨的烦恼！",
    ))
    out.update(e(
        "menu_dic_eg_pw_yjyu",
        "憧憬那有名长部、所谓在做角色扮演的叶！",
        "并非因为自己是叶才谐音，",
        "连那长部也当成空叶将这种叶，是他的误会！",
    ))
    return out
