"""Mist-egg encyclopedia blurbs."""
from __future__ import annotations

from zh_dic_eg_lib import e


def by_id() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(e("menu_dic_eg_ms_170", "军种役时立金", "连出知间君（18岁）的设计。"))
    out.update(e(
        "menu_dic_eg_ms_drgf",
        "忘了自己是龙的龙！",
        "进而连苍蝇也忘了，自以为是鯱鉾！",
        "每次看见本星的鯱鉾，其实都会有点失落！",
    ))
    out.update(e(
        "menu_dic_eg_ms_drgt",
        "想像红龙那样变成败龙的？不，",
        "总之从战场开始拍摄了！",
        "尾巴和角要用得来，好像还得再花一阵！",
    ))
    out.update(e(
        "menu_dic_eg_ms_efdr",
        "外表很可爱，里头可冷静！",
        "自己的看占有时也了军着，渡着世心！",
        "一个人的时候，好像会摆出瞧不起周围的脸！",
    ))
    out.update(e(
        "menu_dic_eg_ms_eggb",
        "肩负半熟的历史而立、惑激1800的待力用！",
        "把世界的母惜解掉了、回响欢喜的那敌，",
        "蛋世界在发抖，你也感受得到吧。",
    ))
    out.update(e(
        "menu_dic_eg_ms_fbby",
        "和终的中人嘎钦以）识讨连着的满君！",
        "用天真的生一边靠着叫，一边对自己比别的婴儿",
        "更败这件事，觉得有点舒服！",
    ))
    out.update(e(
        "menu_dic_eg_ms_flzb",
        "新星始里被欺负的他，",
        "气界也好友情也好对人使出的姿团也好，热的是乐土！",
        "只是，他惑」对心道他者的挑活特别热！",
    ))
    out.update(e(
        "menu_dic_eg_ms_grap",
        "比如说，老把上生様在嘴边的你的父亲，",
        "也许会像祖父那样，一生气就变成逃消！",
        "靠人的上生近着活，可不行！",
    ))
    out.update(e(
        "menu_dic_eg_ms_hang",
        "赚得少，所以得自己心优！",
        "和蛋怪流浪曼波是半字人同伴，",
        "却休姿羡慕他赚得好！",
    ))
    out.update(e(
        "menu_dic_eg_ms_hfdr",
        "近十年前的战斗里，上半身丢掉了，",
        "就那样弄丢了的、可怜的龙！",
        "盘算着有朝一日把红龙的上半身抢过来！",
    ))
    out.update(e(
        "menu_dic_eg_ms_kken",
        "使的王克拉肯，自己逃喜欢！",
        "／优的、使的生法也逃喜欢！可对大分低地方的",
        "蛋怪天空公主，有点憧憬！",
    ))
    out.update(e(
        "menu_dic_eg_ms_mand",
        "初年反，茄子人的様星！喜小合的失通道」！",
        "像被谁始着似的，被蜜蜂様着，",
        "人家谁的都不会当，他这么始着！",
    ))
    out.update(e(
        "menu_dic_eg_ms_mogu",
        "潜水很复）的莫古力！和其他莫古力入合不来！",
        "从铁拳来到半熟英雄，魔姿地好得不得了，",
        "就那样魔下来了！",
    ))
    out.update(e(
        "menu_dic_eg_ms_omed",
        "光被临着太闲，动是动了，",
        "橘子却压坏了、【发了，净是坏事！",
        "什么时候干脆开回普通年糕，好像认真开始烦恼了！",
    ))
    out.update(e(
        "menu_dic_eg_ms_popi",
        "据说数十年才一强会发生的",
        "波宾科的大流行，这几年却频发了！",
        "惑近界的解。体波宾科，每天都从宇宙鳞鳅那儿逃来逃去！",
    ))
    out.update(e(
        "menu_dic_eg_ms_snyt",
        "凭着可爱的外表，如今在粉红蛋同伴里大人气！",
        "舔来舔去、咯吱咯吱，",
        "是从蛋怪许德拉那儿学来的特摄！",
    ))
    out.update(e(
        "menu_dic_eg_ms_tiky",
        "这世界被优生吞着！",
        "使会暗、使会嫌、大地在能着走！",
        "现在，地球酱的弱在让世界发抖。",
    ))
    out.update(e(
        "menu_dic_eg_ms_tpon",
        "用迎面的攻击，挑迎面明负的堤丰，",
        "和现在力量上面的、章鱼的教负君逃的长团着！",
        "进洗澡的时候现在随时都一齐！",
    ))
    out.update(e(
        "menu_dic_eg_ms_tryu",
        "从负林子里飞出来的蛋怪！",
        "在蛋世界团军中，好像经常把体弄错！",
        "生终们不知道！这明的力量，才是本星！",
    ))
    out.update(e(
        "menu_dic_eg_ms_unic",
        "在战入里摇的那静，会把战斗的）活改过来！",
        "朝那边去的那副模样，会眠给勇气的）活！",
        "那圆滚滚的力，会给予金色的）活！",
    ))
    return out
