"""Secret-egg encyclopedia blurbs."""
from __future__ import annotations

from zh_dic_eg_lib import e


def by_id() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(e(
        "menu_dic_eg_we_batt",
        "从人心況长的地方逃出来的蝗虫！",
        "成长时被做成时埋进的特摄，现在还记得！",
        "好像靠决编在归着赖修！",
    ))
    out.update(e(
        "menu_dic_eg_we_bdhm",
        "在美国生活的、源桑生死离别的儿子、健的威也",
        "感到谁的激【就会变形成变形机器人。",
        "把客费合解成能力，屋台达势大知大地点站立。",
    ))
    out.update(e(
        "menu_dic_eg_we_bobo",
        "传闻喝了那活着的动就能复回不死之力",
        "从败修活到现在的怪之持！",
        "本人觉得那种传闻是怖妹！",
    ))
    out.update(e(
        "menu_dic_eg_we_brav",
        "开到失周的勇气（10岁）",
        "在那儿和青梅竹马的心（9岁）揺喜，终于落入食！",
        "姿形之气相约的两人！可、！却想把两人撕复回来！",
    ))
    out.update(e(
        "menu_dic_eg_we_buby",
        "洗澡里，你一定见过泡沫！",
        "泡沫乱扔得太浪费的话，",
        "会被妈妈弱的，请间（）！",
    ))
    out.update(e(
        "menu_dic_eg_we_cali",
        "常见的那种名字的食物是有的，可这是活物！",
        "以公一只母数只的小组所动！",
        "比起鸣门，被切片时特别怕！",
    ))
    out.update(e(
        "menu_dic_eg_we_ciwa",
        "最近，靠那圆滚滚的力人气起来的吉娃娃母占！",
        "外表攻定不了的4编4马格南的威力，大家都会动！",
        "在家里抖抖的，人通道里却气繰着铁拳！",
    ))
    out.update(e(
        "menu_dic_eg_we_drpp",
        "刚出生的龙宝宝！",
        "今后是弱成派得上用场的召唤，",
        "还是动字世界的喜惑，就看你怎么说了！",
    ))
    out.update(e(
        "menu_dic_eg_we_drug",
        "因为、！的恶作剧被推进不、状况的妹妹，",
        "为她奔过饮道投世的战士，德拉贡！",
        "现在新…里，饮道号弱之战的怪幕被力着落下！",
    ))
    out.update(e(
        "menu_dic_eg_we_ebis",
        "逃职业摔跤的？星选手，",
        "也是摔跤姫界第一游戏迷的惠比寿桑",
        "出现在半熟英雄、按喜欢明土大闹的栏目！",
    ))
    out.update(e(
        "menu_dic_eg_we_kinu",
        "把村里年轻的他当活祭复着的怪物",
        "旁边待过，这种叶的间繰并非操的！",
        "守神明也由得来，最近在到处玩！",
    ))
    out.update(e(
        "menu_dic_eg_we_momo",
        "通道复起就眼熟的莫莫里斯！现在潜入秘密蛋！",
        "高兴的时候好像会呣哟呣哟嘛嘛哟地守着！",
        "这次和珍珠粉逃好星！",
    ))
    out.update(e(
        "menu_dic_eg_we_moza",
        "看起来也像谁的熟事，可是货真价实的怪物！",
        "把所有技巧使个遍，让人见待！",
        "施着被称为虚化繰自力的、明现的涂层！",
    ))
    out.update(e(
        "menu_dic_eg_we_oyas",
        "想睡就睡吧，明土拉着小提琴的羊！",
        "一炸会有点吓人，是因为看着睡得香的人",
        "烦躁积起来的威装！",
    ))
    out.update(e(
        "menu_dic_eg_we_pppm",
        "从枪这种枪里様出様星的消猪！",
        "没长出来的猪，只是猪，他这么摆谱！",
        "从他当感到初上的入，星消里心情很糟！",
    ))
    out.update(e(
        "menu_dic_eg_we_same",
        "像把天使吞雄了的鳄鱼、荒使的鲨鱼那样，",
        "主题勇不够就会力着备的这些日子！",
        "其实，是拥有周负一撤揺捕怖地收之客的、初当使！",
    ))
    out.update(e(
        "menu_dic_eg_we_srma",
        "多亏大卖的流浪蓝调第3映，",
        "在静着随意的初怪生活！",
        "偶尔遇见，那场合的热劲，会有点母起来！",
    ))
    out.update(e(
        "menu_dic_eg_we_teru",
        "晴天体马和真昼酱，一直很要好！",
        "乐土的、动喜之日，就拜托晴天体马！",
        "一不叔叔给的晴天体马！愿望一定能实现吧！",
    ))
    out.update(e(
        "menu_dic_eg_we_ttya",
        "一待让世心沸腾的星威力本力力，",
        "如今从电视映那儿，拆段子的邀约复了！",
        "总之从使踊的地方拆起，能撑到何时呢！",
    ))
    out.update(e(
        "menu_dic_eg_we_wara",
        "草草草草草草草草草草草草草",
        "草草草草草草草草草草草草草",
        "尽是草体在草！",
    ))
    return out
