"""Field / world / gameover / event debug menus."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    END = "结束调试模式"
    START = "看开始事件"
    WIPE = "歼灭（通关）"
    KEEP = "保持原样"
    JUMP = "跳到途中事件"
    return {
        "field_debug_ear#0": END,
        "field_debug_ear#1": START,
        "field_debug_ear#2": "把核导弹扔出去",
        "field_debug_ear#3": WIPE,
        "field_debug_gho02#0": END,
        "field_debug_gho02#1": "看出现事件",
        "field_debug_gho02#2": START,
        "field_debug_gho02#3": WIPE,
        "field_debug_main_menu#1": "铁拳队",
        "field_debug_mode": "场地调试模式搞上了啊",
        "field_debug_mode2": "结束调试模式",
        "field_debug_mon01#0": END,
        "field_debug_mon01#1": START,
        "field_debug_mon01#2": WIPE,
        "field_debug_mon03#0": END,
        "field_debug_mon03#1": START,
        "field_debug_mon03#2": "看布莱基捕获事件",
        "field_debug_mon03#3": WIPE,
        "field_debug_mon04#0": END,
        "field_debug_mon04#1": START,
        "field_debug_mon04#2": "看去伊巴拉事件",
        "field_debug_mon04#3": "看打伊巴拉事件",
        "field_debug_mon04#4": WIPE,
        "field_debug_sun01#0": END,
        "field_debug_sun01#1": START,
        "field_debug_sun01#2": "接着看】界的",
        "field_debug_sun01#3": WIPE,
        "field_debug_thu01#0": END,
        "field_debug_thu01#1": START,
        "field_debug_thu01#2": "全员ON、O铁拳掉",
        "field_debug_thu01#3": "看去、森之道事件",
        "field_debug_thu01#4": "看打、森之道事件",
        "field_debug_thu01#5": WIPE,
        "field_debug_thu02#0": END,
        "field_debug_thu02#1": "看去开始事件",
        "field_debug_thu02#2": "看打开始事件",
        "field_debug_thu02#3": "看去蜘蛛事件",
        "field_debug_thu02#4": "看打蜘蛛事件",
        "field_debug_thu02#5": WIPE,
        "field_debug_thu05#0": END,
        "field_debug_thu05#1": START,
        "field_debug_thu05#2": "看坏脑袋事件",
        "field_debug_thu05#3": WIPE,
        "field_debug_tue03#0": END,
        "field_debug_tue03#1": START,
        "field_debug_tue03#2": "看首领星出现事件",
        "field_debug_tue03#3": "看首领出现后的开始事件",
        "field_debug_tue03#4": WIPE,
        "field_debug_unitclear": "正在歼灭",
        "field_debug_wed01#0": END,
        "field_debug_wed01#1": START,
        "field_debug_wed01#2": "看去、道事件",
        "field_debug_wed01#3": "看打、道事件",
        "field_debug_wed01#4": WIPE,
        "world_debug_fri#0": KEEP,
        "world_debug_fri#1": JUMP + "1！",
        "world_debug_fri#2": JUMP + "2！",
        "world_debug_fri#3": JUMP + "3！",
        "world_debug_fri#4": "全部通关！放出场所！",
        "world_debug_gho#0": KEEP,
        "world_debug_gho#1": JUMP + "1！",
        "world_debug_gho#2": JUMP + "2！",
        "world_debug_gho#3": JUMP + "3！",
        "world_debug_thu#0": KEEP,
        "world_debug_thu#1": JUMP + "1！",
        "world_debug_thu#2": JUMP + "2！",
        "world_debug_thu#3": "全部通关！放出场所！",
        "world_debug_wed#0": KEEP,
        "world_debug_wed#1": "跳到途中事件！",
        "world_debug_wed#2": "全部通关！放出场所！",
        "gameover_debug01": "调试选择器",
        "gameover_debug02#0": KEEP,
        "gameover_debug02#1": "○人生死击",
        "gameover_debug02#2": "阿尔玛之月星坠落",
        "gameover_debug02#3": "马蒂斯死击",
        "gameover_debug02#4": "奥马尔坠落",
        "gameover_debug02#5": "核爆炸",
        "gameover_debug02#6": "伊努查看器",
        "gameover_debug03#0": KEEP,
        "gameover_debug03#1": "角色指定",
        "gameover_debug04#0": "我出击中",
        "gameover_debug04#1": "我打空中",
        "gameover_debug05#0": "伊努出击中",
        "gameover_debug05#1": "伊努打空中",
        "gameover_debug06#0": "殿下出击中",
        "gameover_debug06#1": "殿下打空中",
        "gameover_debug06#2": "姿" * 98,
        "gameover_debug06#3": "姿" * 98,
        "ev_pre_debug01#0": KEEP,
        "ev_pre_debug01#1": "月",
        "ev_pre_debug01#2": "火",
        "ev_pre_debug01#3": "水",
        "ev_pre_debug01#4": "木",
        "ev_pre_debug01#5": "金",
        "ev_pre_debug01#6": "土",
        "ev_spring_debug01#0": KEEP,
        "ev_spring_debug01#1": "巴克特之剑",
        "ev_spring_debug01#2": "能力回复",
        "ev_spring_debug01#3": "我入报场景",
        "ev_spring_debug01#4": "伊努入报场景",
        "ev_spring_debug01#5": "战场战斗",
        "ev_spring_debug01#6": "蛋回复",
        "ev_spring_debug02#0": KEEP,
        "ev_spring_debug02#1": "日",
        "ev_spring_debug02#2": "月",
        "ev_spring_debug02#3": "火",
        "ev_spring_debug02#4": "水",
        "ev_spring_debug02#5": "木",
        "ev_spring_debug02#6": "金",
        "ev_spring_debug02#8": "地球",
        "ev_spring_debug03#0": KEEP,
        "ev_spring_debug03#1": "我",
        "ev_spring_debug03#2": "伊努",
        "ev_spring_debug03#3": "我了伊努",
        "ev_spring_debug04#0": "随机",
        "ev_spring_debug04#1": "普通南瓜灯",
        "ev_spring_debug04#2": "小南瓜灯",
        "ev_spring_debug04#3": "捕动南瓜灯",
        "ev_spring_debug04#4": "妖精南瓜灯",
        "ev_spring_debug04#5": "南瓜灯蝙蝠",
        "ev_spring_debug04#6": "机械南瓜灯",
        "ev_spring_debug04#7": "写实南瓜灯",
        "ev_spring_debug05#0": "○人生",
        "ev_spring_debug05#1": "鲁奈",
        "ev_spring_debug05#2": "马蒂斯",
        "ev_spring_debug05#3": "梅尔克里",
        "ev_spring_debug05#4": "彭普蒂",
        "ev_spring_debug05#5": "弗莱迪",
        "ev_spring_debug05#6": "塞巴斯蒂安",
        "ev_comp_debug1#0": KEEP,
        "ev_comp_debug1#1": "蛋怪收集全",
        "ev_comp_debug1#2": "部队收集全",
        "ev_comp_debug2#0": "卡特莉·伊奈",
        "ev_comp_debug2#1": "卡特莉·伊努",
    }
