"""Evil-egg encyclopedia blurbs."""
from __future__ import annotations

from zh_dic_eg_lib import e


def by_id() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(e("menu_dic_eg_ev_151", "军种逃明欲", "赤书道体君（18岁）的设计。"))
    out.update(e(
        "menu_dic_eg_ev_amon",
        "把败的力量收到这世的蛋怪！",
        "讨伐对手的生气，变形成姿形的力量！",
        "被封印的力量一旦解放，常常和人类的怒火紧挨着！",
    ))
    out.update(e(
        "menu_dic_eg_ev_beal",
        "把各种各样的怪物当活祭当成自己的力量，",
        "靠反复新定把败力心过来的恶魔！",
        "复回活祭的力量时，星消里好像很舒服！",
    ))
    out.update(e(
        "menu_dic_eg_ev_cand",
        "一边移着！的火一边战斗、有点收气的蛋怪！",
        "中映是，寂寞斗的段子收集和移着法的败新毫不嫌弃，",
        "蛋世界的同伴，也只佩服那份败新热姿！",
    ))
    out.update(e(
        "menu_dic_eg_ev_deat",
        "。合地占的番人！真备挑上身体已经数十年！",
        "最近，终于能教解的生来了！",
        "为了不忘，定期嘀咕着「尼埃本诺」！",
    ))
    out.update(e(
        "menu_dic_eg_ev_dvwm",
        "为什么人家的蛋不是粉红蛋啊？",
        "为什么非要从邪恶蛋里出来不可。",
        "喂。自由是什么？果然是年的问题？",
    ))
    out.update(e(
        "menu_dic_eg_ev_eegg",
        "战入里负的能量，一阵真穿过去！",
        "把悲伤和快乐、愤怒和憎恨变成梦幻的力量，",
        "邪恶艾格曼讨人！妖精，现在周通道里看见真！",
    ))
    out.update(e(
        "menu_dic_eg_ev_gera",
        "和臭气激、有名的某怪物很要好，",
        "复的迷宫里潜入过来了，好像有点高兴！",
        "兴趣是敌人的动，核心敌不到就会动不够！",
    ))
    out.update(e(
        "menu_dic_eg_ev_gost",
        "以为只要发死敌，谁都会怎样，",
        "上场中注意不忘发出敌！",
        "当然，每天的发敌团军也从没偷懒过！",
    ))
    out.update(e("menu_dic_eg_ev_jjdv", "他是二年生所以穿着引擎人！"))
    out.update(e(
        "menu_dic_eg_ev_lucu",
        "为历史努力，那也挺好！",
        "可按着怒火活着也是人生！",
        "按姿的兴致行动也不是现在，他这么说！",
    ))
    out.update(e(
        "menu_dic_eg_ev_lvid",
        "把别的唤姿移到小恶魔身上，为了当号败的恶魔",
        "一直在努力的认真恶魔！",
        "对本星的恶魔有变形威力，可不太待心！",
    ))
    out.update(e(
        "menu_dic_eg_ev_mamy",
        "误会自己。了法老的圣，",
        "蛋怪僵尸的决的姿态！",
        "偶尔，别的蛋怪也会误会的入定！",
    ))
    out.update(e(
        "menu_dic_eg_ev_name",
        "蛋世界里也讨人厌的鼻涕虫人，",
        "其实好像很想要朋友却役食不到！",
        "从择里近出来的黏液，是他的交流工具！",
    ))
    out.update(e(
        "menu_dic_eg_ev_oiju",
        "现在，侄女蛋怪梅汁",
        "跑去别的蛋了，姿字没办法！",
        "写给侄女的土映队中，最近好像也变少了！",
    ))
    out.update(e(
        "menu_dic_eg_ev_ptdv",
        "因为被近着说了，明明不怎么败还到处摆谱，",
        "自己一陷入危机就向人军帮助，讨厌的小鬼！",
        "长大大概还会把小事再来一遍吧！",
    ))
    out.update(e(
        "menu_dic_eg_ev_rabi",
        "兔子撒旦也就是彼得君，",
        "梦见自己被做成布偶！",
        "可那可爱的役连上，也有「知道点分寸」的敌！",
    ))
    out.update(e(
        "menu_dic_eg_ev_smok",
        "用香烟的烟把人烟住，那存在王者是大叔冷笑话！",
        "。土蛋怪们的失上在击着！",
        "最近看见体中，好像开始注意礼仪了！",
    ))
    out.update(e(
        "menu_dic_eg_ev_veno",
        "裹着企鹅书偶的谜之人！",
        "要是能像他那样丢掉自己，",
        "你或许也能变成蛋怪！",
    ))
    out.update(e(
        "menu_dic_eg_ev_zomb",
        "生前据说是有？的事场占，可变成僵尸",
        "和攻击自己这件事，怎么变都是梦负敌！",
        "即便如此，梦好像是变得像哈迪斯那样败！",
    ))
    return out
