"""Colorful-egg encyclopedia blurbs."""
from __future__ import annotations

from zh_dic_eg_lib import e


def by_id() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(e("menu_dic_eg_cl_106", "新星种筑波欲", "小空望小姐（25岁）的设计。"))
    out.update(e("menu_dic_eg_cl_107", "大解连讨星欲", "大形败费君（20岁）的设计。"))
    out.update(e(
        "menu_dic_eg_cl_akem",
        "地面坍塌以外的剑术没他出场的份，",
        "据说开始打工当蛋怪了！",
        "手里两把扇子，是从父亲那儿继承来的！",
    ))
    out.update(e(
        "menu_dic_eg_cl_azen",
        "当初有过什么人已无从知晓，",
        "从某个时候起就变成这副模样了！",
        "他的攻击，会让人想起各种各样的「唉」。",
    ))
    out.update(e(
        "menu_dic_eg_cl_ball",
        "数年前还在百货店楼上飘来飘去，",
        "最近工作变少，",
        "就以蛋怪身份活跃着！",
    ))
    out.update(e(
        "menu_dic_eg_cl_eggm",
        "从蛋世界来的、人的使者！",
        "一直被说派不上用场已经十七年，",
        "这回，那记连环劈会传到谁身上呢？",
    ))
    out.update(e(
        "menu_dic_eg_cl_egsl",
        "寄宿在休息和连失里、长得很像蛋的生物！",
        "艾格淋、艾格棒之类，",
        "阿尔玛之月上也有好几种在卖！",
    ))
    out.update(e(
        "menu_dic_eg_cl_flyp",
        "那张脸的身体、会飞的平底锅！",
        "蛋里飞出平底锅这种不可思议的说法，",
        "本人好像也有点接受不了！",
    ))
    out.update(e(
        "menu_dic_eg_cl_hade",
        "憧憬真正的敌人哈迪斯、只是一具尸体！",
        "想说笑话又难为情说不出口，",
        "据说把生前的爱好全扔了！",
    ))
    out.update(e(
        "menu_dic_eg_cl_judo",
        "要定下从没见过的柔道的、星球勇者！",
        "招式变化很多，但全搞错了！",
        "父亲那边有大手占和波斯的王族！",
    ))
    out.update(e(
        "menu_dic_eg_cl_lamp",
        "靠给蛋做祓除来维持生计！",
        "连日出差，连回家的空都没有，",
        "说到兴趣，大概就是休息日逛市场！",
    ))
    out.update(e(
        "menu_dic_eg_cl_matu",
        "不用喜斗也能心意相通、一辈子相伴的鸳鸯夫妇！",
        "有问题时候的空手情战已经成了传说！",
        "最近，连爸爸也开始使自己的绝招了！",
    ))
    out.update(e(
        "menu_dic_eg_cl_nalt",
        "常见的那种名字的食物是有的，可这是活物！",
        "据说曾经被那宇宙的小池星人绑走过，还反击了，",
        "是带着寂寞通道的出入、活着的残渣！",
    ))
    out.update(e(
        "menu_dic_eg_cl_otam",
        "据说常去田里知情的人，极低概率",
        "才能看见、宇宙人族的一匹蝌蚪！",
        "长大就会变成普通的青蛙！",
    ))
    out.update(e(
        "menu_dic_eg_cl_otya",
        "喜欢茶泡饭、自己也变成茶泡饭的大叔！",
        "这样随时都能吃到茶泡饭，本人超满足！",
        "一年半前开始买的彩票，好像老中不了！",
    ))
    out.update(e(
        "menu_dic_eg_cl_piku",
        "为了用自己的存在体现超现实主义，",
        "从画框里蹦出来了！",
        "画的主题是来自爱的破坏力，本人如是说！",
    ))
    out.update(e(
        "menu_dic_eg_cl_siro",
        "看厌了守护星球的殿喜道军没本事，",
        "自己把防卫小队独立出去、干劲十足的城！",
        "相当老朽了，可还在现役！",
    ))
    out.update(e(
        "menu_dic_eg_cl_tiki",
        "为寻找治好母亲天气的药，",
        "满世界旅行的母鸡！",
        "为什么要把冬天的母亲带去旅行，不太清楚！",
    ))
    out.update(e(
        "menu_dic_eg_cl_tsuh",
        "以前和他相识、在看空手中继的通贩桑！",
        "工作是，收录结束后到有问题的采购为止的空档",
        "每天都在看电视购物！",
    ))
    out.update(e(
        "menu_dic_eg_cl_ugok",
        "不动如山！总之是头顽固的猴子！",
        "那绝不移动的坚强意志，",
        "大概谁也拗不过！",
    ))
    return out
