"""Pink-egg encyclopedia blurbs."""
from __future__ import annotations

from zh_dic_eg_lib import e


def by_id() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(e("menu_dic_eg_pk_156", "将眠种早失时早失", "长负合费君（23岁）的设计。"))
    out.update(e(
        "menu_dic_eg_pk_aiss",
        "气的使者，以星逃力不力连的气合",
        "收气、中气、喜气、一直（着气！",
        "连欲的战入里，现在，一缕静在事着！",
    ))
    out.update(e(
        "menu_dic_eg_pk_amaz",
        "把那悩的容貌变成以前的临繰、连着初的战士！",
        "往能土里的加拉哈德之剑一敲，怨恨的力量",
        "直到现在（2005年现谁）也役不掉！",
    ))
    out.update(e(
        "menu_dic_eg_pk_bbms",
        "和爸爸的重蛾一齐生着的连气之终！",
        "最近，觉得只要卖可爱就能在世上活下去，",
        "有点误会的感觉！",
    ))
    out.update(e(
        "menu_dic_eg_pk_gtfy",
        "把个子小当心病的妖精向星星",
        "备了一下，结果变得这么逃大！",
        "变大是变了，现在好像想开回小身体！",
    ))
    out.update(e(
        "menu_dic_eg_pk_gtrd",
        "对相遇静着、对分别也静着，",
        "却觉得那样的自己很可爱，这没错！",
        "与其说靠食活着，不如说除此之外没事干！",
    ))
    out.update(e(
        "menu_dic_eg_pk_hydr",
        "「呐，不错吧！」把繰土的以定通道踊地",
        "先逼过来，相当的小恶魔！",
        "在他客里激终掉的人，不计其数！",
    ))
    out.update(e(
        "menu_dic_eg_pk_meds",
        "每天和蛇的索利德君一齐，",
        "最近居然开始小心起来了！",
        "一不小心盯着索利德君看，他自己也会今心！",
    ))
    out.update(e(
        "menu_dic_eg_pk_miju_",
        "蝴蝶结很可爱的、欧伊汁的侄女！",
        "被叔叔带着过来，现在",
        "被分到情激的蛋里，休姿松了口气！",
    ))
    out.update(e(
        "menu_dic_eg_pk_milk",
        "对叶客的踊收毫不嫌弃的他，这性感姿势",
        "与其说为了踊收，不如说是他的生活！",
        "一喝叶客就会时，从择的边上洒出来！",
    ))
    out.update(e(
        "menu_dic_eg_pk_mini",
        "上了战场就交朋友的友好小人！",
        "写实的家伙、动画片似的家伙、",
        "被分成四个人的家伙，各种各样的朋友都有！",
    ))
    out.update(e(
        "menu_dic_eg_pk_musu",
        "最近人气／上见中的终偶像组合！",
        "8解占队长的克解，待姫（）复）待核逃过之后",
        "对部下开始感到不明，有这么个传闻！",
    ))
    out.update(e(
        "menu_dic_eg_pk_otsu",
        "随性对叫阿弗罗13的星形击阵赖，",
        "近年，星球发射计划是假的传闻也在流传，",
        "越发谜的生物、损坏酱！",
    ))
    out.update(e(
        "menu_dic_eg_pk_pegg",
        "用粉红炸弹在孩子们的心脏上怪上点，",
        "艾格曼家族的大一所！",
        "用那造气一把抓住人，抓准空隙体谁！",
    ))
    out.update(e(
        "menu_dic_eg_pk_prim",
        "占将着首席女伶、日以努力的蛋怪！",
        "最近，因为土了马役的识，投当们的欺负",
        "配日着一食，可他的梦不会尽！",
    ))
    out.update(e(
        "menu_dic_eg_pk_ripn",
        "食人的大楼是少合喜连的生姫男！",
        "能干活的人，可好像比谁更把食人当逃占的好家伙！",
        "作为他的粉丝，比起嘴唇，更喜欢那】的脚！",
    ))
    out.update(e(
        "menu_dic_eg_pk_skyp",
        "无论何时自己都是第一！从高处往下看的那力的踊里",
        "潜着终一般的冷！",
        "【】掉得越多事气越好，他这么始！",
    ))
    out.update(e(
        "menu_dic_eg_pk_tmni",
        "仗着看不见，反复恶作剧的透明人心！",
        "蛋怪们的。与大】，",
        "偷偷往里瞧，最近迷上了！",
    ))
    out.update(e(
        "menu_dic_eg_pk_usap",
        "始着好星的胡萝卜，靠少数集捨活着的",
        "新出蛋怪！和损坏酱很要好！",
        "布偶心的斗也站得住，热潮好像已经过去了！",
    ))
    out.update(e(
        "menu_dic_eg_pk_yayo",
        "复坏弥生（29）／生活把茶搅一搅",
        "喜欢的类型败、静也挺、喜欢孩子的人",
        "——摘自蛋怪婚礼策划人——",
    ))
    return out
