"""Mist-egg battle lines B (drgf–hfdr)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    R = "蜻蜓龙："
    O = "莫古力："
    Y = "三叶虫："
    B = "霜之宝宝："
    P = "堤丰："
    U = "天龙："
    C = "恭喜鸟："
    N = "独角兽："
    I = "波宾科："
    Q = "狛犬："
    A = "半龙："
    return {
        # --- 蜻蜓龙 ---
        "eg_ms_drgf_d": R + "蜻蜓龙的衣褪了！",
        "eg_ms_drgf_l": R + "啪叽啪叽啪叽啪叽！",
        "eg_ms_drgf_ms1": "被蜻蜓龙用尾巴啪嗒啪嗒地打了。",
        "eg_ms_drgf_ms11": "被蜻蜓龙用尾巴啪嗒啪嗒地打了。",
        "eg_ms_drgf_ms2#0": R + "蜻蜓龙浸进好油里。",
        "eg_ms_drgf_ms2#1": "炸得干香，防御上升了。。",
        "eg_ms_drgf_ms21#0": R + "香喷喷的气味让",
        "eg_ms_drgf_ms21#1": "兴奋被促进，攻击上升了。。",
        "eg_ms_drgf_ms22#0": R + "香喷喷的气味让",
        "eg_ms_drgf_ms22#1": "兴奋被促进，攻击上升了。。",
        "eg_ms_drgf_ms2_a#0": R + "蜻蜓龙浸进好油里。",
        "eg_ms_drgf_ms2_a#1": "炸得干香，防御上升了。。",
        "eg_ms_drgf_ms3": "被变成真正的鯱鉾了。",
        "eg_ms_drgf_ms31": "被变成真正的鯱鉾了。",
        "eg_ms_drgf_vo1#0": R + "这就是鯱鉾的姿势啊。",
        "eg_ms_drgf_vo1#1": "看招看招看招——。。。",
        "eg_ms_drgf_vo2": R + "哈安比巴农农！",
        "eg_ms_drgf_vo3": R + "这才是真正的鯱鉾啊。",
        "eg_ms_drgf_w": R + "赢了啊。",
        # --- 莫古力 ---
        "eg_ms_mogu_d": O + "莫古力正误会自己潜在水里。",
        "eg_ms_mogu_l": O + "莫古力被抓住了！",
        "eg_ms_mogu_ms1": "被当成字了。。",
        "eg_ms_mogu_ms11": "被当成字了。。",
        "eg_ms_mogu_ms2#0": O + "刺。",
        "eg_ms_mogu_ms2#1": "打中了要害。。",
        "eg_ms_mogu_ms21#0": O + "刺。",
        "eg_ms_mogu_ms21#1": "打中了要害。。",
        "eg_ms_mogu_ms22": "被莫古力深深地扎进去了。",
        "eg_ms_mogu_ms23": "被莫古力深深地扎进去了。",
        "eg_ms_mogu_ms3#0": O + "莫古力报告了还算准确的情报。",
        "eg_ms_mogu_ms3#1": "莫古力轻快的动作让速度上升了。。",
        "eg_ms_mogu_ms32#0": O + "莫古力报告了还算准确的情报。",
        "eg_ms_mogu_ms32#1": "正式上场和平时不一样！全部威力上升了。。",
        "eg_ms_mogu_vo1": O + "啊。是字库波！",
        "eg_ms_mogu_vo2": O + "古力古力古力——。莫——古力。。",
        "eg_ms_mogu_vo3": O + "和字桑们亲亲库波！",
        "eg_ms_mogu_w": O + "库波——。",
        # --- 三叶虫 ---
        "eg_ms_snyt_d": Y + "三叶虫好像要沉沉睡去！",
        "eg_ms_snyt_l": Y + "啾哔哔——。。",
        "eg_ms_snyt_ms1#0": Y + "三叶虫",
        "eg_ms_snyt_ms1#1": "舔了脸颊！",
        "eg_ms_snyt_ms11#0": Y + "三叶虫",
        "eg_ms_snyt_ms11#1": "舔了脸颊！",
        "eg_ms_snyt_ms2#0": Y + "三叶虫",
        "eg_ms_snyt_ms2#1": "咯吱了腋下！",
        "eg_ms_snyt_ms21#0": Y + "三叶虫",
        "eg_ms_snyt_ms21#1": "咯吱了腋下！",
        "eg_ms_snyt_ms3#0": Y + "三叶虫",
        "eg_ms_snyt_ms3#1": "在额头上啾了一下！",
        "eg_ms_snyt_ms31#0": Y + "三叶虫",
        "eg_ms_snyt_ms31#1": "在额头上啾了一下！",
        "eg_ms_snyt_vo1": Y + "舔舔舔舔舔舔！",
        "eg_ms_snyt_vo2": Y + "咯吱咯吱咯吱咯吱！",
        "eg_ms_snyt_vo3": Y + "嗯——啾。",
        "eg_ms_snyt_w": Y + "啾啾噗衣。",
        # --- 霜之宝宝 ---
        "eg_ms_fbby_d": B + "霜之宝宝的牙都快露出来了！",
        "eg_ms_fbby_l": B + "换成新身体啾！",
        "eg_ms_fbby_ms1": B + "霜之宝宝激烈地撞上了。。",
        "eg_ms_fbby_ms2": B + "霜之宝宝大口吃了高级刨冰。。",
        "eg_ms_fbby_ms21#0": B + "霜之宝宝的能力反转了。。",
        "eg_ms_fbby_ms21#1": "吃饱了，攻击上升了。。",
        "eg_ms_fbby_ms22#0": "也请人吃了刨冰。",
        "eg_ms_fbby_ms22#1": "又冷又好吃。能力反转了。。",
        "eg_ms_fbby_ms23#0": "也请人吃了刨冰。",
        "eg_ms_fbby_ms23#1": "又冷又好吃。能力反转了。。",
        "eg_ms_fbby_ms3#0": B + "霜之宝宝盛大的声音让大地震动，",
        "eg_ms_fbby_ms3#1": "引发了最大级的地震！",
        "eg_ms_fbby_vo1": B + "吧噗——————。。",
        "eg_ms_fbby_vo2": B + "好吃好吃！好吃好吃！",
        "eg_ms_fbby_vo3": B + "哇哇——————。。。",
        "eg_ms_fbby_w#0": B + "嘎钦——————。。。",
        "eg_ms_fbby_w#1": "嘎钦分明是胜利的呐喊！",
        # --- 堤丰 ---
        "eg_ms_tpon_d": P + "堤丰的身体油亮亮的！",
        "eg_ms_tpon_l": P + "挺能干的嘛！",
        "eg_ms_tpon_ms1#0": P + "从正面打过去，可拿着的落太厚了。。",
        "eg_ms_tpon_ms1#1": "堤丰也受了伤。。",
        "eg_ms_tpon_ms2#0": P + "堤丰的猛雨洒了一地，",
        "eg_ms_tpon_ms2#1": "能力反转了。。",
        "eg_ms_tpon_ms21#0": P + "堤丰的猛雨洒了一地，",
        "eg_ms_tpon_ms21#1": "能力反转了。。",
        "eg_ms_tpon_ms3": P + "堤丰把人整吞了。。",
        "eg_ms_tpon_ms31": P + "堤丰把人整吞了。。",
        "eg_ms_tpon_ms32": P + "一口咬了！",
        "eg_ms_tpon_ms33": P + "一口咬了！",
        "eg_ms_tpon_vo1": P + "抹香——————攻击————。。",
        "eg_ms_tpon_vo2": P + "抹香——————雨————。。",
        "eg_ms_tpon_vo3": P + "抹香——————咬————。。",
        "eg_ms_tpon_w": P + "碰到俺，可是会喷潮的！",
        # --- 天龙 ---
        "eg_ms_tryu_d": U + "天龙的孩子们正在欢呼！",
        "eg_ms_tryu_l": U + "天龙一动不动地缠着！",
        "eg_ms_tryu_ms1": "被热闹的样子吓了一跳。",
        "eg_ms_tryu_ms11": "被热闹的样子吓了一跳。",
        "eg_ms_tryu_ms2": "被人墙吓住了。",
        "eg_ms_tryu_ms21": "被人墙吓住了。",
        "eg_ms_tryu_ms3#0": U + "孩子们去休息不在了，",
        "eg_ms_tryu_ms3#1": "天龙自己动了起来。。",
        "eg_ms_tryu_vo1": U,
        "eg_ms_tryu_vo2#0": U + "嘿咻。嘿咻。。嘿咻。。。",
        "eg_ms_tryu_vo2#1": "嘿咻。嘿咻。。嘿咻。。。",
        "eg_ms_tryu_vo21#0": U + "索伊萨。索伊萨。。索伊萨。。。",
        "eg_ms_tryu_vo21#1": "索伊萨。索伊萨。。索伊萨。。。",
        "eg_ms_tryu_vo3": U,
        "eg_ms_tryu_w": U + "天龙高兴得扭来扭去！",
        # --- 恭喜鸟 ---
        "eg_ms_omed_d": C + "饼皮侧面裂了。",
        "eg_ms_omed_l": C + "啾！",
        "eg_ms_omed_ms1#0": C + "把上面的橘子噗啾地一压。",
        "eg_ms_omed_ms1#1": "结果汁喷出来了。。",
        "eg_ms_omed_ms21#0": C + "恭喜鸟膨胀了。",
        "eg_ms_omed_ms21#1": "没完没了！",
        "eg_ms_omed_ms22": C + "啊啪啪啪啪啪啪啪啪",
        "eg_ms_omed_ms23": C + "恭喜鸟消失得无影无踪！",
        "eg_ms_omed_ms31": C + "不知从哪出现的锤子对着恭喜鸟",
        "eg_ms_omed_ms32": C + "咔嚓地敲了啪啪啪啪啪啪",
        "eg_ms_omed_ms33": C + "恭喜鸟消失得无影无踪！",
        "eg_ms_omed_vo1": C + "橘子汁渗进眼睛了",
        "eg_ms_omed_vo3": C + "不要敲——",
        "eg_ms_omed_w": C + "恭喜鸟。",
        # --- 独角兽 ---
        "eg_ms_unic_d#0": N + "正在忍着不哭。",
        "eg_ms_unic_d#1": "加油。独角兽。",
        "eg_ms_unic_l": N + "连要冲出去的勇气都折了！",
        "eg_ms_unic_ms1#0": N + "独角兽鼓起勇气，",
        "eg_ms_unic_ms1#1": "对准冲了过去。",
        "eg_ms_unic_ms11#0": N + "独角兽鼓起勇气，",
        "eg_ms_unic_ms11#1": "对准冲了过去。",
        "eg_ms_unic_ms12": N + "独角兽刺穿了心。",
        "eg_ms_unic_ms13": N + "独角兽刺穿了心。",
        "eg_ms_unic_ms2": N + "不知怎么打中了。",
        "eg_ms_unic_ms21": N + "哎呀。没打中。",
        "eg_ms_unic_ms3#0": N + "独角兽的勇气涌出来，",
        "eg_ms_unic_ms3#1": "真正出来的却是大浪。。",
        "eg_ms_unic_w": N + "高兴得眼睛汪汪的。",
        # --- 波宾科 ---
        "eg_ms_popi_d": I + "波宾科的内脏在噗噜噗噜地颤。",
        "eg_ms_popi_l": I + "波宾科散成微尘消失了！",
        "eg_ms_popi_ms1#0": I + "波宾科的蛋一齐孵化了。",
        "eg_ms_popi_ms1#1": "哇。到处都是波宾科——。",
        "eg_ms_popi_ms21": I + "来了——。快跑——。宇宙鳞鳅——。",
        "eg_ms_popi_ms22": I + "连波宾科一起挨了宇宙鳞鳅的攻击。",
        "eg_ms_popi_ms3ms#0": I + "波宾科的蛋偏着孵化了。",
        "eg_ms_popi_ms3ms#1": "哎哟。全是母的。",
        "eg_ms_popi_ms3os#0": I + "波宾科的蛋偏着孵化了。",
        "eg_ms_popi_ms3os#1": "哎哟全是公的。",
        "eg_ms_popi_w": I + "看着像在高兴，是错觉吗？",
        # --- 狛犬 ---
        "eg_ms_kinu_ms21#0": "被狛犬吓到，",
        "eg_ms_kinu_ms21#1": "一步也动不了了！",
        "eg_ms_kinu_ms23#0": "被狛犬吓了一下，",
        "eg_ms_kinu_ms23#1": "没什么事！",
        "eg_ms_kinu_ms24#0": Q + "对视状？。",
        "eg_ms_kinu_ms24#1": "狛犬也一起动不了了。。",
        "eg_ms_kinu_ms25#0": Q + "和狛犬对视。",
        "eg_ms_kinu_ms25#1": "一起动不了了。。",
        "eg_ms_kinu_ms26#0": Q + "和狛犬对视。",
        "eg_ms_kinu_ms26#1": "一起动不了了。。",
        # --- 半龙 ---
        "eg_ms_hfdr_d": A + "半龙的上半身正在某处哭着！",
        "eg_ms_hfdr_l#0": A + "半龙",
        "eg_ms_hfdr_l#1": "还没发现自己已经被干掉了！",
        "eg_ms_hfdr_ms1": A + "半龙胡乱甩尾巴。",
        "eg_ms_hfdr_ms2": A + "半龙胡乱乱踢。",
        "eg_ms_hfdr_ms3": A + "半龙胡乱把失始白放出去了。",
        "eg_ms_hfdr_w#0": A + "半龙",
        "eg_ms_hfdr_w#1": "还没发现自己已经赢了！",
    }
