"""Mist-egg battle lines A (tiky–hang)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    T = "地球酱："
    M = "曼德拉草："
    E = "艾格宝宝："
    K = "克拉肯："
    S = "森之三："
    D = "龙？不："
    G = "祖父："
    F = "精灵龙："
    Z = "冰冻男孩："
    H = "半鱼人："
    P = "地球人："
    return {
        # --- 地球酱 ---
        "eg_ms_tiky_d": T + "在地球上，役待大的合正在守望着战斗。",
        "eg_ms_tiky_l#0": T + "邻星灭亡了！",
        "eg_ms_tiky_l#1": "来称赞英雄们吧！",
        "eg_ms_tiky_ms1#0": T + "气温9度上升／湿度8％／气压10",
        "eg_ms_tiky_ms1#1": "最新消息到了，为您播报！",
        "eg_ms_tiky_ms2": T + "大地震在全世界爆发了。。",
        "eg_ms_tiky_ms3": T + "大地震以最大规模爆发了。。",
        "eg_ms_tiky_telop": "情报新闻 特别情报",
        "eg_ms_tiky_telop2": "半熟时代，半熟遍布古今东西，宇宙正处在危机边缘",
        "eg_ms_tiky_vo2#0": P + "终、终焉了啊啊。",
        "eg_ms_tiky_vo2#1": P + "伊格柯泰尔。",
        "eg_ms_tiky_vo2#2": P + "高志桑——。地球。地球啊——。",
        "eg_ms_tiky_vo2#3": P + "我的妈呀。",
        "eg_ms_tiky_vo2#4": P + "O世纪到来O年。",
        "eg_ms_tiky_vo2#5": P + "嘿嘿嘿",
        "eg_ms_tiky_vo2#6": "反正俺们都得死啊——。。",
        "eg_ms_tiky_vo2#7": P + "大地的愤怒啊！",
        "eg_ms_tiky_vo2_man#0": T + "地球人：终、终焉了啊啊。",
        "eg_ms_tiky_vo2_man#1": T + "地球人：伊格柯泰尔。",
        "eg_ms_tiky_vo2_man#2": T + "地球人：高志桑——。地球。地球啊——。",
        "eg_ms_tiky_vo2_man#3": T + "地球人：我的妈呀。",
        "eg_ms_tiky_vo2_man#4": T + "地球人：O世纪到来O年。",
        "eg_ms_tiky_vo2_man#5": T + "嘿嘿嘿",
        "eg_ms_tiky_vo2_man#6": "反正俺们都得死啊——。。",
        "eg_ms_tiky_vo2_man#7": T + "地球人：大地的愤怒啊！",
        "eg_ms_tiky_vo2_woman#0": T + "地球人：终、终焉了啊啊。",
        "eg_ms_tiky_vo2_woman#1": T + "地球人：伊格柯泰尔。",
        "eg_ms_tiky_vo2_woman#2": T + "高志桑——。地球。地球啊——。",
        "eg_ms_tiky_vo2_woman#3": T + "地球人：我的妈呀。",
        "eg_ms_tiky_vo2_woman#4": T + "地球人：O世纪到来O年。",
        "eg_ms_tiky_vo2_woman#5": T + "地球人：嘿嘿嘿",
        "eg_ms_tiky_vo2_woman#6": "反正俺们都得死啊——。。",
        "eg_ms_tiky_vo2_woman#7": T + "地球人：大地的愤怒啊！",
        "eg_ms_tiky_w": T + "就这样，地球得救了！",
        # --- 曼德拉草 ---
        "eg_ms_mand_d": M + "曼德拉草正浮现着如梦的笑脸！",
        "eg_ms_mand_l": M + "抽泣！",
        "eg_ms_mand_ms11": M + "曼德拉草把自己的根拔出来了。",
        "eg_ms_mand_ms11_b#0": M + "听见曼德拉草的悲鸣，",
        "eg_ms_mand_ms11_b#1": "晕过去了。。",
        "eg_ms_mand_ms12#0": M + "听见曼德拉草的悲鸣，",
        "eg_ms_mand_ms12#1": "晕过去了。。",
        "eg_ms_mand_ms13#0": M + "听见了曼德拉草的悲鸣，",
        "eg_ms_mand_ms13#1": "却毫不动摇！",
        "eg_ms_mand_ms14#0": M + "听见了曼德拉草的悲鸣，",
        "eg_ms_mand_ms14#1": "却毫不动摇！",
        "eg_ms_mand_ms2#0": M + "曼德拉草把种子飞出去了。",
        "eg_ms_mand_ms2#1": "无尽的睡意和寂静袭来了。。",
        "eg_ms_mand_ms21#0": M + "曼德拉草把种子飞出去了。",
        "eg_ms_mand_ms21#1": "无尽的睡意和寂静袭来了。。",
        "eg_ms_mand_ms3": M + "曼德拉草用立体环绕声悲鸣了。。",
        "eg_ms_mand_ms31#0": M + "听见曼德拉草的悲鸣，",
        "eg_ms_mand_ms31#1": "晕过去了。。",
        "eg_ms_mand_ms32#0": M + "听见曼德拉草的悲鸣，",
        "eg_ms_mand_ms32#1": "晕过去了。。",
        "eg_ms_mand_ms33#0": M + "听见了曼德拉草的悲鸣，",
        "eg_ms_mand_ms33#1": "却毫不动摇！",
        "eg_ms_mand_ms34#0": M + "听见了曼德拉草的悲鸣，",
        "eg_ms_mand_ms34#1": "却毫不动摇！",
        "eg_ms_mand_vo1#0": M + "呀啊啊啊——。。。",
        "eg_ms_mand_vo1#1": "救命啊——。要被杀了呜——。。",
        "eg_ms_mand_vo2": M,
        "eg_ms_mand_vo3#0": M + "呀啊啊啊——。。。（呀啊啊啊——。。。）",
        "eg_ms_mand_vo3#1": "救命啊——。（要被杀了呜——。）",
        "eg_ms_mand_w": M + "呜呼呼！",
        # --- 艾格宝宝 ---
        "eg_ms_eggb_d": E + "艾格宝宝的壳刚出生，还软软的！",
        "eg_ms_eggb_l#0": E + "我是无力的啾",
        "eg_ms_eggb_l#1": "没有力量的正义，就是无力的啾！",
        "eg_ms_eggb_ms1#0": E + "对着愚蠢的",
        "eg_ms_eggb_ms1#1": "艾格宝宝的怒气讨伐了。。",
        "eg_ms_eggb_ms12#0": E + "对着愚蠢的",
        "eg_ms_eggb_ms12#1": "艾格宝宝的怒气讨伐了。。",
        "eg_ms_eggb_ms2": E + "艾格宝宝把世界的悲伤解开，盛大欢喜了！",
        "eg_ms_eggb_ms21#0": "艾格宝宝被盛大的敌人吓到，",
        "eg_ms_eggb_ms21#1": "身形涨红了！",
        "eg_ms_eggb_ms22#0": "艾格宝宝被盛大的敌人吓到，",
        "eg_ms_eggb_ms22#1": "身形涨红了！",
        "eg_ms_eggb_ms23#0": E + "玩耍",
        "eg_ms_eggb_ms23#1": "一副若无其事！",
        "eg_ms_eggb_ms24#0": E + "玩耍",
        "eg_ms_eggb_ms24#1": "一副若无其事！",
        "eg_ms_eggb_ms3": "艾格宝宝变成肉馅了。。。",
        "eg_ms_eggb_ms31": "艾格宝宝变成肉馅了。。。",
        "eg_ms_eggb_vo1#0": E + "愚蠢的大人们，",
        "eg_ms_eggb_vo1#1": "现在就在此处处刑啾。",
        "eg_ms_eggb_vo2": E + "哇啊啊啊——————————————。。。",
        "eg_ms_eggb_vo3#0": E + "血脉之中啾1800的力量，祈求啾。",
        "eg_ms_eggb_vo3#1": "要变成肉馅了啾。。。",
        "eg_ms_eggb_w#0": E + "扰乱和平的大人，",
        "eg_ms_eggb_w#1": "又埋葬了一个啾——。。",
        # --- 克拉肯 ---
        "eg_ms_kken_d": K + "克拉肯正对首次现身的大力踌躇着！",
        "eg_ms_kken_l": K + "你才配做我的对象呢！",
        "eg_ms_kken_ms1#0": "克拉肯灌了一肚子海水。",
        "eg_ms_kken_ms1#1": "非常非常咸。。",
        "eg_ms_kken_ms11#0": "克拉肯灌了一肚子海水。",
        "eg_ms_kken_ms11#1": "非常非常咸。。",
        "eg_ms_kken_ms2#0": K + "克拉肯滑溜溜的肌肤闪闪发亮。",
        "eg_ms_kken_ms2#1": "不由得看入迷了。。",
        "eg_ms_kken_ms21#0": K + "克拉肯滑溜溜的肌肤闪闪发亮。",
        "eg_ms_kken_ms21#1": "不由得看入迷了。。",
        "eg_ms_kken_ms3#0": K + "克拉肯的大力们，",
        "eg_ms_kken_ms3#1": "一齐扑了上来。。",
        "eg_ms_kken_ms32#0": K + "克拉肯的大力们，",
        "eg_ms_kken_ms32#1": "一齐扑了上来。。",
        "eg_ms_kken_vo1#0": K + "哦呵呵呵在天上活的你们也",
        "eg_ms_kken_vo1#1": "让你们尝尝海的可怕吧！",
        "eg_ms_kken_vo2#0": K + "哦呵呵呵海的神圣之物",
        "eg_ms_kken_vo2#1": "那美丽令人感激呢！",
        "eg_ms_kken_vo3#0": K + "哦呵呵呵落到我这儿的现在",
        "eg_ms_kken_vo3#1": "比马里亚纳海沟还深呢。",
        "eg_ms_kken_vo31#0": K + "惩罚的时间到了！",
        "eg_ms_kken_vo31#1": "动手吧。。。",
        "eg_ms_kken_w#0": K + "哪里有能让我溺水的",
        "eg_ms_kken_w#1": "健壮男子汉呢",
        # --- 森之三 ---
        "eg_ms_170_d": S + "森之三正在找落星！",
        "eg_ms_170_l#0": S + "撒腿就跑刷刷刷的刷！",
        "eg_ms_170_l#1": "森之三逃走了！",
        "eg_ms_170_ms1#0": S + "有一天",
        "eg_ms_170_ms1#1": "和森之三撞上了！",
        "eg_ms_170_ms12#0": S + "有一天",
        "eg_ms_170_ms12#1": "和森之三撞上了！",
        "eg_ms_170_ms2#0": S + "森之三的自坏连小",
        "eg_ms_170_ms2#1": "一击就收拾了。",
        "eg_ms_170_ms21#0": S + "森之三的自坏连小",
        "eg_ms_170_ms21#1": "一击就收拾了。",
        "eg_ms_170_ms22#0": S + "森之三的自坏连小",
        "eg_ms_170_ms22#1": "刺穿了。。",
        "eg_ms_170_ms23#0": S + "森之三的自坏连小",
        "eg_ms_170_ms23#1": "刺穿了。。",
        "eg_ms_170_ms3": S + "这种程度都能轻易埋葬，是相当强大的武器。",
        "eg_ms_170_vo1": S + "无语音！",
        "eg_ms_170_vo2": S + "无语音！",
        "eg_ms_170_vo3": S + "无语音！",
        "eg_ms_170_w#0": S + "啦啦啦啦啦啦啦！",
        "eg_ms_170_w#1": "森之三唱起来了！",
        "eg_ms_170_ap#0": "军种役时立金连出知间君（18）的设计。",
        "eg_ms_170_ap#1": "森之三！。。",
        # --- 龙？不 ---
        "eg_ms_drgt_d": D + "龙？不以这小身体来说，已经在吼了！",
        "eg_ms_drgt_l": D + "叫我？不酱！",
        "eg_ms_drgt_ms1#0": D + "龙？不激烈的组合拳",
        "eg_ms_drgt_ms1#1": "直击了。",
        "eg_ms_drgt_ms11#0": D + "龙？不激烈的组合拳",
        "eg_ms_drgt_ms11#1": "直击了。",
        "eg_ms_drgt_ms2#0": D + "龙？不上下的连打",
        "eg_ms_drgt_ms2#1": "直击了。",
        "eg_ms_drgt_ms21#0": D + "龙？不上下的连打",
        "eg_ms_drgt_ms21#1": "直击了。",
        "eg_ms_drgt_ms3": "龙？不舔了糖，能力反转了。。",
        "eg_ms_drgt_ms31": "龙？不舔了糖，能力反转了。。",
        "eg_ms_drgt_ms32#0": D + "龙？不挥鞭狠狠地",
        "eg_ms_drgt_ms32#1": "抽得睡着了。",
        "eg_ms_drgt_ms33#0": D + "龙？不挥鞭狠狠地",
        "eg_ms_drgt_ms33#1": "抽得睡着了。",
        "eg_ms_drgt_vo1#0": D + "喝啊——。应当咬。应当咬。应当咬。",
        "eg_ms_drgt_vo1#1": "应当打。应当打。应当打。",
        "eg_ms_drgt_vo2#0": D + "喝啊——。拳。拳。拳。",
        "eg_ms_drgt_vo2#1": "踢。踢。踢。",
        "eg_ms_drgt_vo3": D + "喝啊——。舔。舔。舔。",
        "eg_ms_drgt_vo31": D + "不许舔——。噼。啪。噼。",
        "eg_ms_drgt_w": D + "连甩尾巴和角攻击都用不着啊！",
        # --- 祖父 ---
        "eg_ms_grap_d1": G + "祖父正在打盹。",
        "eg_ms_grap_d2": G + "祖父暴怒模式，怒气更增了。",
        "eg_ms_grap_d2_b": G + "祖父正在暴怒。",
        "eg_ms_grap_l1": G + "呼！",
        "eg_ms_grap_l2": G + "唔哦哦哦！",
        "eg_ms_grap_ms1": G + "祖父温柔地和年轻的敌人一起上了！",
        "eg_ms_grap_ms2": G + "祖父的怒气爆发了。",
        "eg_ms_grap_ms3": G + "祖父翻倒了。",
        "eg_ms_grap_ms31": G + "祖父还很高兴着呢。。",
        "eg_ms_grap_ms32": G + "祖父暴怒了。。",
        "eg_ms_grap_ms33#0": G + "祖父变回平时的爸爸了。",
        "eg_ms_grap_ms33#1": "能力也反转了。",
        "eg_ms_grap_ms34#0": G + "祖父吼了。",
        "eg_ms_grap_ms35": G + "气到小孩子都不能看的程度，祖父发怒了。",
        "eg_ms_grap_vo1": G + "呵呵呵呵呵呵！",
        "eg_ms_grap_vo2": G + "咕哦咕哦咕哦——。。",
        "eg_ms_grap_vo31": G + "还早着呢！",
        "eg_ms_grap_vo32": G + "终于把俺惹怒了啊。。",
        "eg_ms_grap_vo33": G + "呼，气消了！",
        "eg_ms_grap_vo34": G + "忍耐忍耐！",
        "eg_ms_grap_vo35": G + "喂。给我掉进地狱。。",
        "eg_ms_grap_w1": G + "呵呵呵呵！",
        "eg_ms_grap_w2": G + "蠢货。",
        # --- 精灵龙 ---
        "eg_ms_efdr_d#0": F + "啊，看起来好可爱。",
        "eg_ms_efdr_d#1": "可那力量的影子里能感到什么。",
        "eg_ms_efdr_l#0": F + "像秋叶飘落那样，那身子落到地面上",
        "eg_ms_efdr_l#1": "舞下来了！",
        "eg_ms_efdr_ms1#0": F + "用好像一碰就会坏的小爪子",
        "eg_ms_efdr_ms1#1": "挠了一下。",
        "eg_ms_efdr_ms11#0": F + "用好像一碰就会坏的小爪子",
        "eg_ms_efdr_ms11#1": "挠了一下。",
        "eg_ms_efdr_ms2#0": F + "不可思议的微风吹过。",
        "eg_ms_efdr_ms2#1": "感到心安了。",
        "eg_ms_efdr_ms21#0": F + "不可思议的微风吹过。",
        "eg_ms_efdr_ms21#1": "感到心安了。",
        "eg_ms_efdr_ms22#0": F + "不可思议的鳞粉让眼前发黑，",
        "eg_ms_efdr_ms22#1": "速度下降了。。",
        "eg_ms_efdr_ms221#0": F + "不可思议的鳞粉让眼前发黑，",
        "eg_ms_efdr_ms221#1": "速度下降了。。",
        "eg_ms_efdr_ms3#0": F + "比起吐息，那圆圆眼睛的温柔，",
        "eg_ms_efdr_ms3#1": "让藏着的心思燃起来了。。",
        "eg_ms_efdr_ms31#0": F + "比起吐息，那圆圆眼睛的温柔，",
        "eg_ms_efdr_ms31#1": "让藏着的心思燃起来了。。",
        "eg_ms_efdr_w#0": F + "不是骗人的！",
        "eg_ms_efdr_w#1": "在那儿的是胜利的英雄！",
        # --- 冰冻男孩 ---
        "eg_ms_flzb_d": Z + "咔嚓。冰冻男孩口感轻盈！",
        "eg_ms_flzb_l": Z + "冰冻男孩的衣服破了！",
        "eg_ms_flzb_ms1#0": Z + "冰冻男孩挖出冰块",
        "eg_ms_flzb_ms1#1": "扔了过去。",
        "eg_ms_flzb_ms11#0": Z + "冰冻男孩挖出冰块",
        "eg_ms_flzb_ms11#1": "扔了过去。",
        "eg_ms_flzb_ms2#0": Z + "冰冻男孩把空调的设定温度改了！",
        "eg_ms_flzb_ms2#1": "在优温度下能力反转了。。",
        "eg_ms_flzb_ms21#0": Z + "可大家都冻得要僵了！",
        "eg_ms_flzb_ms21#1": "也就是全体伤害。。",
        "eg_ms_flzb_ms21_b#0": Z + "可大家都冻得要僵了！",
        "eg_ms_flzb_ms21_b#1": "也就是全体伤害。。",
        "eg_ms_flzb_ms2_b": Z + "冰冻男孩把空调的设定温度改了！",
        "eg_ms_flzb_ms3#0": Z + "超导电让冻僵化开了。",
        "eg_ms_flzb_ms3#1": "冰冻男孩的身体被舒舒服服地揉开了！",
        "eg_ms_flzb_vo1#0": Z + "冷风咻",
        "eg_ms_flzb_vo1#1": "哩哩哒",
        "eg_ms_flzb_vo2#0": Z + "冷风咻",
        "eg_ms_flzb_vo2#1": "哩哩啦啦",
        "eg_ms_flzb_vo3#0": Z + "冷风咻",
        "eg_ms_flzb_vo3#1": "哩哩噜",
        "eg_ms_flzb_w": Z + "冰冻男孩轻快地跳着舞退场了！",
        # --- 半鱼人 ---
        "eg_ms_hang_d": H + "半鱼人差点就被抓住了！",
        "eg_ms_hang_l#0": H + "连晚饭都抓不回去的爹地，",
        "eg_ms_hang_l#1": "原谅我咯喔！",
        "eg_ms_hang_ms1#0": H + "半鱼人当成晚饭，",
        "eg_ms_hang_ms1#1": "对准放出了鱼叉。",
        "eg_ms_hang_ms11#0": H + "半鱼人当成晚饭，",
        "eg_ms_hang_ms11#1": "对准放出了鱼叉。",
        "eg_ms_hang_ms2#0": "被半鱼人用",
        "eg_ms_hang_ms2#1": "脚鳍啪啪地抽了。",
        "eg_ms_hang_ms21#0": "被半鱼人用",
        "eg_ms_hang_ms21#1": "脚鳍啪啪地抽了。",
        "eg_ms_hang_ms3#0": H + "半鱼人拼命对准，",
        "eg_ms_hang_ms3#1": "把鱼叉连出去了。。",
        "eg_ms_hang_ms31#0": H + "半鱼人拼命对准，",
        "eg_ms_hang_ms31#1": "把鱼叉连出去了。。",
        "eg_ms_hang_vo1": H + "变成晚饭咯喔！",
        "eg_ms_hang_vo2": H + "求你了变成晚饭咯喔！",
        "eg_ms_hang_vo3#0": H + "求你了变成晚饭咯喔！",
        "eg_ms_hang_vo3#1": "咯子酱在家等着咯喔！",
        "eg_ms_hang_w#0": H + "晚饭抓到了咯喔。",
        "eg_ms_hang_w#1": "老婆这下能原谅我了咯喔。。",
    }
