"""Four-season 四次元人 battle lines (秋子 / 春子 / 夏子 / 冬子)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    A = "秋子："
    H = "春子："
    N = "夏子："
    W = "冬子："
    B = "部长："
    out: dict[str, str] = {}
    out.update(_aki(A))
    out.update(_haru(H, B))
    out.update(_natu(N))
    out.update(_fuyu(W))
    return out


def _aki(A: str) -> dict[str, str]:
    return {
        "eg_bo_aki_d1": A + "你，是不是很寂寞！",
        "eg_bo_aki_d1_y": A + "你！",
        "eg_bo_aki_d2": A + "你，把心交给本4！",
        "eg_bo_aki_d2_y": A + "这个恨！",
        "eg_bo_aki_d3": A + "你，不要丢下我走！",
        "eg_bo_aki_d3_y": A + "不会原谅你！",
        "eg_bo_aki_l": A + "你，死了的话，本4也去4！",
        "eg_bo_aki_l_y": A + "啊啊，你。马上就要死了4！",
        "eg_bo_aki_ms1#4": "冲击的事实。客席最前排的参战者，居然是萨布罗。。",
        "eg_bo_aki_ms12": A + "现身了。",
        "eg_bo_aki_ms13#0": A + "现身了。",
        "eg_bo_aki_ms13#1": "犹豫着要不要攻击。。",
        "eg_bo_aki_ms2#0": A + "以悲惨的气势攻过来了。",
        "eg_bo_aki_ms2#1": "看不到尽头的乱打！",
        "eg_bo_aki_ms21#0": A + "以悲惨的气势攻过来了。",
        "eg_bo_aki_ms21#1": "乱打！",
        "eg_bo_aki_ms23#0": A + "以悲惨的气势攻过来了。",
        "eg_bo_aki_ms23#1": "稍微往边上躲开了！",
        "eg_bo_aki_ms3#0": A + "决意了。",
        "eg_bo_aki_ms3#1": "自己也被一起带走了。。",
        "eg_bo_aki_ms31#0": A + "决意了。",
        "eg_bo_aki_ms31#1": "好险，差点被一起带走。",
        "eg_bo_aki_ms31_lose#0": A + "决意了。",
        "eg_bo_aki_ms31_lose#1": "好险，差点被一起带走。",
        "eg_bo_aki_ms3b#0": A + "决意了。",
        "eg_bo_aki_ms3b#1": "大家也被一起带走了。。",
        "eg_bo_aki_vo1_1": A + "那个人，长得像本4兄长的面影4呢",
        "eg_bo_aki_vo1_2": A + "谁也不知道的那个秘密，死也不会卖给敌人的4呢",
        "eg_bo_aki_vo1_3": A + "爱着，爱着那个人4呢",
        "eg_bo_aki_vo1_4#0": A + "啊啊，萨布罗！",
        "eg_bo_aki_vo1_4#1": "（冲击的事实。四次元军溃灭的原因，是萨布罗。。。）",
        "eg_bo_aki_vo2_1": A + "你？你，在哪里4？",
        "eg_bo_aki_vo2_2": A + "你，本4该怎么办才好4？",
        "eg_bo_aki_vo2_3": A + "忘不掉4呢那个人的话，忘不掉4呢",
        "eg_bo_aki_vo3_1#0": A + "你们也睡吧4",
        "eg_bo_aki_vo3_1#1": "一起去那个人那里4！",
        "eg_bo_aki_vo3_2#0": A + "再见了，世界！",
        "eg_bo_aki_vo3_2#1": "好喜欢4，你。",
        "eg_bo_aki_vo3_3": A + "耶——噫。。",
        "eg_bo_aki_w": A + "仇，已经报了4，你！",
        "eg_bo_aki_w_y": A + "那个人也该高兴了4！",
    }


def _haru(H: str, B: str) -> dict[str, str]:
    return {
        "eg_bo_haru_d1": H + "好厉害4哟",
        "eg_bo_haru_d1_y": H + "没用的4！",
        "eg_bo_haru_d2": H + "呜呼呼哟",
        "eg_bo_haru_d2_y": H + "才不会泄气4！",
        "eg_bo_haru_d3": H + "还早着4哟",
        "eg_bo_haru_d3_y": H + "呀嗯！",
        "eg_bo_haru_l#0": H + "四次元的各位。",
        "eg_bo_haru_l#1": "给春子一点点假。。",
        "eg_bo_haru_l_y#0": H + "不行，不许死掉4！",
        "eg_bo_haru_l_y#1": "春子，加油4。",
        "eg_bo_haru_ms1": H + "文件上也溅到茶了。。",
        "eg_bo_haru_ms2#0": H + "遭了池鱼。好大的雷",
        "eg_bo_haru_ms2#1": "也劈下来了。",
        "eg_bo_haru_ms21#0": H + "好大的雷，劈下来了。",
        "eg_bo_haru_ms21#1": "被石化了，回不到蛋里了。",
        "eg_bo_haru_ms31#0": H + "春子的情绪一下子拉满，气势猛地抬起来了。。",
        "eg_bo_haru_ms31#1": "攻击·防御·速度·精神上升了。",
        "eg_bo_haru_vo1_1": B + "春子君，茶，拜托！",
        "eg_bo_haru_vo1_2": H + "好——的哟春子马上倒4哟",
        "eg_bo_haru_vo1_3": H + "呀呼嗯。好痛4哟",
        "eg_bo_haru_vo1_4a#0": H + "呀啊啊——。电脑上。电脑上茶啊。",
        "eg_bo_haru_vo1_4a#1": "呜哦哦。好不容易汇总的资料啊啊。。",
        "eg_bo_haru_vo1_4b#0": H + "呀啊啊——。简历上。简历上茶啊。",
        "eg_bo_haru_vo1_4b#1": "呜哦哦。一个人就能推动的项目啊。。",
        "eg_bo_haru_vo1_4c#0": H + "呀啊啊——。饭碗上。饭碗上茶啊。",
        "eg_bo_haru_vo1_4c#1": "呜哦哦。鼻子里冒热气出来了。。",
        "eg_bo_haru_vo1_5": H + "诶嘿哟别闷闷不乐哟春子加油4哟",
        "eg_bo_haru_vo2_1#0": B + "春子君，把这份文件复印一下！",
        "eg_bo_haru_vo2_1#1": "重要案件，务必小心对待！",
        "eg_bo_haru_vo2_1_ex#0": B + "春子君，把这份文件复印一下！",
        "eg_bo_haru_vo2_1_ex#1": B + "重要案件，务必小心对待！",
        "eg_bo_haru_vo2_1_ex#2": "好——的哟春子收到4哟",
        "eg_bo_haru_vo2_1_ex2": B + "重要案件，务必小心对待！",
        "eg_bo_haru_vo2_1_ex3#0": B + "春子君，把这份文件复印一下！",
        "eg_bo_haru_vo2_1_ex3#1": "重要案件，务必小心对待！",
        "eg_bo_haru_vo2_2": H + "好——的哟春子收到4哟",
        "eg_bo_haru_vo2_3a#0": B + "春子君。那是碎纸机啊。。",
        "eg_bo_haru_vo2_3a#1": "重要文件怎么能切成碎末啊。。",
        "eg_bo_haru_vo2_3b#0": B + "春子君。那是传真机啊。。",
        "eg_bo_haru_vo2_3b#1": "重要文件你往哪儿发啊。？",
        "eg_bo_haru_vo2_3c#0": B + "春子君。那是山羊啊。。",
        "eg_bo_haru_vo2_3c#1": "重要文件怎么能喂它吃啊。。",
        "eg_bo_haru_vo2_3d1#0": H + "看招！乘着春子的纸",
        "eg_bo_haru_vo2_3d1#1": "飞到天边去4！",
        "eg_bo_haru_vo2_3d2#0": B + "春子君。飞得还挺好嘛！",
        "eg_bo_haru_vo2_3d2#1": "重要文件可不能拿来玩。。",
        "eg_bo_haru_vo2_3e1#0": H + "致各位。爱的使者4！",
        "eg_bo_haru_vo2_3e1#1": "白色圣诞节来了4！",
        "eg_bo_haru_vo2_3e2#0": B + "春子君，雪真美啊！你更美！",
        "eg_bo_haru_vo2_3e2#1": "重要文件可不能拿来撒纸吹雪。。",
        "eg_bo_haru_vo2_4#0": B + "这下完了。完了啊。。春子君。。",
        "eg_bo_haru_vo2_4#1": "再来一次，从头把文件做出来！",
        "eg_bo_haru_vo2_5#0": H + "啊哈哟又闯祸了哟",
        "eg_bo_haru_vo2_5#1": "不过，永不放弃4哟",
        "eg_bo_haru_vo2_5a": H + "啊哈哟又闯祸了哟",
        "eg_bo_haru_vo2_5b": H + "不过，永不放弃4哟",
        "eg_bo_haru_vo2_6#0": H + "挺好的嘛。",
        "eg_bo_haru_vo2_6#1": "这次失败也是上司爱的考验哟。",
        "eg_bo_haru_vo3_1": B + "春子君，白带的剑尖可要握紧了！",
        "eg_bo_haru_vo3_2": H + "是4哟春子加油拿下这把剑4哟",
        "eg_bo_haru_vo3_3a#0": H + "一个人也不许踏进这片领地4。",
        "eg_bo_haru_vo3_3a#1": "呀呀呀呀呀——。。",
        "eg_bo_haru_vo3_3b#0": H + "春子的一切都赌在这把剑上4。",
        "eg_bo_haru_vo3_3b#1": "斩过去——。哈啊——。。",
        "eg_bo_haru_vo3_3c#0": H + "星之国的和平里，睡着牺牲！",
        "eg_bo_haru_vo3_3c#1": "来抢这把剑的勇者们的牺牲4。。",
        "eg_bo_haru_vo3_4#0": B + "呀春子君，辛苦了！哎呀哟得救了！",
        "eg_bo_haru_vo3_4#1": "春子君？春子君。？哪、谁呀嘎啊啊！",
        "eg_bo_haru_w": H + "春子，说不定超厉害的4哟",
        "eg_bo_haru_w_y": H + "春子做得好4哟部长喜欢上我了4哟",
    }


def _natu(N: str) -> dict[str, str]:
    return {
        "eg_bo_natu_d1": N + "打得漂亮4。",
        "eg_bo_natu_d1_y": N + "啊啊啊——。",
        "eg_bo_natu_d2": N + "还早4。",
        "eg_bo_natu_d2_y": N + "嗯呼啊。",
        "eg_bo_natu_d3": N + "再来。再来4。",
        "eg_bo_natu_d3_y": N + "嗯嗯。",
        "eg_bo_natu_l": N + "拜拜，各位4！",
        "eg_bo_natu_l_y": N + "好，出汗了4！",
        "eg_bo_natu_ms1#0": N + "也跟着夏子一起活动身体了！",
        "eg_bo_natu_ms1#1": "太拼了，肌肉好痛。。",
        "eg_bo_natu_ms12#0": N + "也跟着夏子一起活动身体了！",
        "eg_bo_natu_ms12#1": "做过火对身体不好。中毒了。。",
        "eg_bo_natu_ms2": N + "也跟着夏子一起活动身体了。",
        "eg_bo_natu_ms21#0": N + "也跟着夏子一起活动身体了。",
        "eg_bo_natu_ms21#1": "太拼命，全部能力掉了。。",
        "eg_bo_natu_ms3#0": N + "夏子开始放热力淋浴了！",
        "eg_bo_natu_ms3#1": "在挑衅！",
        "eg_bo_natu_ms31#0": N + "挨了",
        "eg_bo_natu_ms31#1": "严厉的反击。",
        "eg_bo_natu_ms3_b#0": N + "夏子正在放热力淋浴！",
        "eg_bo_natu_ms3_b#1": "在挑衅！",
        "eg_bo_natu_vo1_1#0": N + "这把次元刃，家里也好办公室也好。",
        "eg_bo_natu_vo1_1#1": "随时随地塑形都没问题4。",
        "eg_bo_natu_vo1_2#0": N + "这把次元刃，下垂的胸部也能",
        "eg_bo_natu_vo1_2#1": "变成憧憬的碗型。",
        "eg_bo_natu_vo1_3#0": N + "这把次元刃，现在购买的话居然。",
        "eg_bo_natu_vo1_3#1": "再送一份，超划算4。",
        "eg_bo_natu_vo2_1#0": N + "哪个次元都能开心地操练。",
        "eg_bo_natu_vo2_1#1": "1·2·3·吼哦——。1·2·3·吼哦——。。",
        "eg_bo_natu_vo2_2#0": N + "今天，完完全全加硬4哟",
        "eg_bo_natu_vo2_2#1": "1·2·3·吼哦——。1·2·3·吼哦——。。",
        "eg_bo_natu_vo2_3#0": N + "朝着夏，练出完美身体4哟",
        "eg_bo_natu_vo2_3#1": "1·2·3·吼哦——。1·2·3·吼哦——。。",
        "eg_bo_natu_vo3_1": N + "运动后的淋浴，是常识4。。",
        "eg_bo_natu_vo3_2": N + "流的汗，也要注意礼仪4。",
        "eg_bo_natu_vo3_3": N + "4444444哟",
        "eg_bo_natu_vo3_4": N + "偷看的是谁4。？",
        "eg_bo_natu_vo3_5": N + "那边4——。。",
        "eg_bo_natu_vo3_6": N + "居然偷看本夏子，次元走眼了4。",
        "eg_bo_natu_w": N + "对懒散的你也。次元刃4。",
        "eg_bo_natu_w_y": N + "对身材走样的星际人，次元操练4。",
    }


def _fuyu(W: str) -> dict[str, str]:
    eggs = [
        ("ms1", "彩色蛋"),
        ("ms2", "粉红蛋"),
        ("ms3", "力量蛋"),
        ("ms4", "迷雾蛋"),
        ("ms5", "邪恶蛋"),
        ("ms6", "电子蛋"),
        ("ms7", "传说蛋"),
        ("ms8", "迷宫蛋"),
        ("ms9", "秘密蛋"),
    ]
    letters = "abcdefghi"
    out: dict[str, str] = {
        "eg_bo_fuyu_d1": W + "！",
        "eg_bo_fuyu_d1_y": W + "！",
        "eg_bo_fuyu_d2": W + "哪儿的话！",
        "eg_bo_fuyu_d2_y": W + "嘛，对手4！",
        "eg_bo_fuyu_d3": W + "哼哼哼哼哼哼哼哼！",
        "eg_bo_fuyu_d3_y": W + "哎呀不行4！",
        "eg_bo_fuyu_l": W + "为啥4，为啥4。？",
        "eg_bo_fuyu_l_y": W + "要是多读点《四四》就好了4！",
        "eg_bo_fuyu_ms2_1#0": W + "冬子喜欢大号。",
        "eg_bo_fuyu_ms2_1#1": "大号蛋怪，受到了冲击。。",
        "eg_bo_fuyu_ms2_2#0": W + "冬子喜欢中号。",
        "eg_bo_fuyu_ms2_2#1": "中号蛋怪，受到了冲击。。",
        "eg_bo_fuyu_ms2_3#0": W + "冬子喜欢小号。",
        "eg_bo_fuyu_ms2_3#1": "小号蛋怪，受到了冲击。。",
        "eg_bo_fuyu_ms2_4#0": W + "冬子喜欢大号。",
        "eg_bo_fuyu_ms2_4#1": "可是大号蛋怪没有！",
        "eg_bo_fuyu_ms2_5#0": W + "冬子喜欢中号。",
        "eg_bo_fuyu_ms2_5#1": "可是中号蛋怪没有！",
        "eg_bo_fuyu_ms2_6#0": W + "冬子喜欢小号。",
        "eg_bo_fuyu_ms2_6#1": "可是小号蛋怪没有！",
        "eg_bo_fuyu_ms31": W + "被碳气扑上来了。。",
        "eg_bo_fuyu_ms31_b": W + "被碳气扑上来了。。",
        "eg_bo_fuyu_ms32": W + "臭得昏过去了。。",
        "eg_bo_fuyu_ms32_b#0": W + "和对方，",
        "eg_bo_fuyu_ms32_b#1": "臭得昏过去了。。",
        "eg_bo_fuyu_ms32_c": W + "臭得昏过去了。。",
        "eg_bo_fuyu_ms33#0": W + "虽然臭，",
        "eg_bo_fuyu_ms33#1": "总算忍住了！",
        "eg_bo_fuyu_ms33_b#0": W + "虽然臭，",
        "eg_bo_fuyu_ms33_b#1": "总算忍住了！",
        "eg_bo_fuyu_vo1_1": W + "占卜的事，得拿《四四》来决胜负4！",
        "eg_bo_fuyu_vo1_2a#0": W + "【金运一起在涨】【凭气势往前冲】",
        "eg_bo_fuyu_vo1_2a#1": "俺家体型那儿，到底写了啥呐？",
        "eg_bo_fuyu_vo1_2b#0": W + "【运势上升】【把寿命拉长吧】",
        "eg_bo_fuyu_vo1_2b#1": "俺家体型那儿，到底写了啥呐？",
        "eg_bo_fuyu_vo1_2c#0": W + "【使真心的时候】【运气会冒出来】",
        "eg_bo_fuyu_vo1_2c#1": "俺家体型那儿，到底写了啥呐？",
        "eg_bo_fuyu_vo1_2d#0": W + "【健康运】【好像一切都会突然变糟】",
        "eg_bo_fuyu_vo1_2d#1": "俺家体型那儿，到底写了啥呐？",
        "eg_bo_fuyu_vo1_2e#0": W + "【该把全力使出来】【该把身体狠狠练的时候】",
        "eg_bo_fuyu_vo1_2e#1": "俺家体型那儿，到底写了啥呐？",
        "eg_bo_fuyu_vo1_2f#0": W + "【开朗的想法要丢掉】【要做到最后】",
        "eg_bo_fuyu_vo1_2f#1": "俺家体型那儿，到底写了啥呐？",
        "eg_bo_fuyu_vo2_1#0": W + "俺家体型，写错了呐！",
        "eg_bo_fuyu_vo2_1#1": "得让《四四》改过来4！",
        "eg_bo_fuyu_vo2_2a": W + "【吵架之后，是对方先道歉】4？",
        "eg_bo_fuyu_vo2_2b": W + "【一被央求就拒绝不了】4？",
        "eg_bo_fuyu_vo2_3a": W + "【对方是长男】4？",
        "eg_bo_fuyu_vo2_3b": W + "【觉得对方是乐天派】4？",
        "eg_bo_fuyu_vo2_4a": W + "【做饭与其放真心，不如砸钱】4？",
        "eg_bo_fuyu_vo2_4b": W + "【是会沉迷进去的类型】4？",
        "eg_bo_fuyu_vo2_5": W + "【喜欢强的人】4？",
        "eg_bo_fuyu_vo2_6a": W + "那个，俺家喜欢温柔的人4！",
        "eg_bo_fuyu_vo2_6b": W + "那个，俺家喜欢有趣的人4！",
        "eg_bo_fuyu_vo2_6c": W + "那个，俺家喜欢块头大的人4！",
        "eg_bo_fuyu_vo2_no": W + "不呐！",
        "eg_bo_fuyu_vo2_yes": W + "是呐！",
        "eg_bo_fuyu_vo3_1#0": W + "特辑的【联谊上钓到新恋】呀",
        "eg_bo_fuyu_vo3_1#1": "啧啧，俺家连缘分都没沾上4！",
        "eg_bo_fuyu_vo3_2#0": W + "特辑的【撩心小动作一百选】呀",
        "eg_bo_fuyu_vo3_2#1": "啧啧啧，恋爱是看对方喜好的4！",
        "eg_bo_fuyu_vo3_3#0": W + "特辑的【烂恋心理彻底解剖】呀",
        "eg_bo_fuyu_vo3_3#1": "啧啧，跟寻宝似的4！",
        "eg_bo_fuyu_w#0": W + "果然还是读《四四》",
        "eg_bo_fuyu_w#1": "拿来参考才对4！",
        "eg_bo_fuyu_w_y#0": W + "《四四》里还有好多",
        "eg_bo_fuyu_w_y#1": "俺家够不着的事，写了一堆4！",
    }
    for key, name in eggs:
        out[f"eg_bo_fuyu_{key}#0"] = W + f"{name}的蛋怪蔫掉了，"
        out[f"eg_bo_fuyu_{key}_n"] = W + f"{name}的蛋怪没有！"
    for i, (_key, name) in enumerate(eggs):
        letter = letters[i]
        out[f"eg_bo_fuyu_vo1_3{letter}#0"] = W + f"哎呀这4！{name}的蛋怪！"
        out[f"eg_bo_fuyu_vo1_3{letter}#1"] = "跟俺家超合拍，上面这么写着4！"
    return out
