"""Dungeon-egg battle lines B (dkef–kure leftovers)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    K = "黑暗精灵："
    P = "二重身："
    E = "精灵："
    R = "晃晃："
    F = "弗兰肯："
    S = "弗朗索瓦兹："
    A = "走散章鱼小孩："
    H = "赫加斯三姐妹："
    I = "伊夫里顿："
    J = "有能战士："
    M = "纸神："
    C = "克罗贝罗斯："
    N = "蘑菇家伙："
    U = "给我给我："
    out: dict[str, str] = {
        "eg_du_dkef_d": K + "好像想说谁。",
        "eg_du_dkef_l": K + "我就算死也不会有谁哭的！",
        "eg_du_dkef_ms12": K + "突然泄了气。",
        "eg_du_dkef_ms122": K + "突然泄了气。",
        "eg_du_dkef_ms22": K + "不意里攻击下降了。。",
        "eg_du_dkef_ms222": K + "不意里攻击下降了。。",
        "eg_du_dkef_ms231": K + "不意里防御下降了。。",
        "eg_du_dkef_ms232": K + "不意里防御下降了。。",
        "eg_du_dkef_ms24": K + "不意里速度下降了。。",
        "eg_du_dkef_ms242": K + "不意里速度下降了。。",
        "eg_du_dkef_ms25": K + "不意里精神下降了。。",
        "eg_du_dkef_ms252": K + "不意里精神下降了。。",
        "eg_du_dkef_ms32": K + "对战斗弱下来了。。",
        "eg_du_dkef_ms321": K + "全体攻击下降了。。",
        "eg_du_dkef_ms322": K + "全体攻击下降了。。",
        "eg_du_dkef_ms331": K + "全体防御下降了。。",
        "eg_du_dkef_ms332": K + "全体防御下降了。。",
        "eg_du_dkef_ms341": K + "全体速度下降了。。",
        "eg_du_dkef_ms342": K + "全体速度下降了。。",
        "eg_du_dkef_ms35": K + "全体精神下降了。。",
        "eg_du_dkef_ms352": K + "全体精神下降了。。",
        "eg_du_dkef_vo1": K + "因为是人的魂所以叫人魂！太省事！",
        "eg_du_dkef_vo2": K + "幸福什么的不过是幻想为什么还！",
        "eg_du_dkef_vo3": K + "反正我这种人就算活着也不会有好事！",
        "eg_du_dkef_w": K + "赢了又能怎样啊！",
        "eg_du_dopl_d": P + "没有感到痛！",
        "eg_du_dopl_l": P + "哦啰啰啰恩输了吗！",
        "eg_du_dopl_ms1#0": P + "正在慌！",
        "eg_du_dopl_ms1#1": "自己为什么会在这入人里，还不自解！",
        "eg_du_dopl_ms11": P + "觉得二重身好可怜！",
        "eg_du_dopl_ms12": P + "觉得二重身好可怜！",
        "eg_du_dopl_ms2": P + "向对方斗了上去。",
        "eg_du_dopl_ms21": P + "向对方斗了上去。",
        "eg_du_dopl_ms3#0": P + "看丢自己的二重身",
        "eg_du_dopl_ms3#1": "心上了。",
        "eg_du_dopl_ms31#0": P + "看丢自己的二重身",
        "eg_du_dopl_ms31#1": "心上了。",
        "eg_du_dopl_ms31_b#0": P + "就算看丢自己",
        "eg_du_dopl_ms31_b#1": "也心不上。",
        "eg_du_dopl_ms31_b2#0": P + "就算看丢自己",
        "eg_du_dopl_ms31_b2#1": "也心不上。",
        "eg_du_dopl_ms32": P + "开成了连的姿。。",
        "eg_du_dopl_vo1": P + "哦啰啰啰恩这里是哪里！",
        "eg_du_dopl_vo2": P + "哦啰啰啰恩你是谁！",
        "eg_du_dopl_vo3": P + "哦啰啰啰恩我是什么人！",
        "eg_du_dopl_w": P + "哦啰啰啰恩赢了吗！",
        "eg_du_elf_d": E + "用不本的气合在挑！",
        "eg_du_elf_l": E + "精灵虽死，自由不死。",
        "eg_du_elf_ms1#0": E + "大家的力量合在一起",
        "eg_du_elf_ms1#1": "啪地点中了！",
        "eg_du_elf_ms11#0": E + "大家的力量合在一起",
        "eg_du_elf_ms11#1": "啪地点中了！",
        "eg_du_elf_ms2#0": E + "放进了休息时间！",
        "eg_du_elf_ms21#0": E + "放进了休息时间！",
        "eg_du_elf_ms32#1": "热得一步也动不了。。",
        "eg_du_elf_ms33#1": "热得一步也动不了。。",
        "eg_du_elf_vo1": E + "事起熟体。成为投真的一激之熟。",
        "eg_du_elf_vo2#0": E + "吹吧治愈之使。",
        "eg_du_elf_vo2#1": "给战士们光明。",
        "eg_du_elf_vo3": E + "火啊。成为使捕之使，把占们的现在烧费掉。",
        "eg_du_elf_w": E + "把这胜利临给一切活着的生命！",
        "eg_du_fraf_d": R + "哎呀军不住。晃晃差点掉到地上！",
        "eg_du_fraf_l": R + "一下也不动了！",
        "eg_du_fraf_ms1": R + "试了晃晃的冲撞！",
        "eg_du_fraf_ms2": R + "试了扑腾的冲撞！",
        "eg_du_fraf_ms3#0": R + "想把晃晃赤掉试试，",
        "eg_du_fraf_ms3#1": "结果把对方的动作也赤掉了！",
        "eg_du_fraf_w": R + "因胜利的喜悦在抖！",
        "eg_du_frkn_d#0": F + "就算被打倒",
        "eg_du_frkn_d#1": "看起来也不可爱得让人同情！",
        "eg_du_frkn_debug#0": "福丸语音",
        "eg_du_frkn_debug#1": "花见语音",
        "eg_du_frkn_debug#2": "平冢语音",
        "eg_du_frkn_debug#3": "一贯语音",
        "eg_du_frkn_debug#4": "久米语音",
        "eg_du_frkn_debug#5": "美敏语音",
        "eg_du_frkn_debug#6": "雷帕语音",
        "eg_du_frkn_debug#7": "上杉语音",
        "eg_du_frkn_l": F + "商军！",
        "eg_du_frkn_ms1#0": F + "攻击一姿不置！",
        "eg_du_frkn_ms1#1": "对，就像从那儿找出活着的）活！",
        "eg_du_frkn_ms2": F + "呜——好臭。受不了的气味！",
        "eg_du_frkn_ms3": F + "跨着法兰克福明攻了。",
        "eg_du_frkn_vo3": F + "法兰克福——。。。",
        "eg_du_frkn_w": F + "伊丽莎白！",
        "eg_du_frns_d": S + "力一闪地熟了！",
        "eg_du_frns_l#0": S + "卡尔？尼克？多明戈？田中？",
        "eg_du_frns_l#1": "号核要让谁活繰呢！",
        "eg_du_frns_ms1#0": S + "朝自己的能飞扑过去！",
        "eg_du_frns_ms1#1": "想逃的心情上来了！",
        "eg_du_frns_ms11#0": S + "朝自己的能飞扑过去！",
        "eg_du_frns_ms11#1": "想逃的心情上来了！",
        "eg_du_frns_ms2": S + "被说不完的自由责问了！",
        "eg_du_frns_ms21": S + "被说不完的自由责问了！",
        "eg_du_frns_ms3": S + "世星号逃长地撒起娇来！",
        "eg_du_frns_vo1#0": S + "为什么？",
        "eg_du_frns_vo1#1": "为什么把我定成这种占——。。",
        "eg_du_frns_vo2#0": S + "知道的。知道的哦——。",
        "eg_du_frns_vo2#1": "你变成大怪了吧？对吧对吧——。",
        "eg_du_frns_vo3#0": S + "不要。不要。终他也不要。",
        "eg_du_frns_vo3#1": "和。食分别的话，还不如死——。",
        "eg_du_frns_w#0": S + "嗯呼呼呼呼！不行啊。你可是心不在焉酱！",
        "eg_du_frns_w#1": "和丹尼尔的网球用坏都忘了哇！",
        "eg_du_hagu_d": A + "体上的赤海苔也飞进去了。",
        "eg_du_hagu_l": A + "凉了也好吃波罗配",
        "eg_du_hagu_ms11": A + "体一个劲地进了。",
        "eg_du_hagu_ms12#0": A + "牙签团地嫌着深深刺进去了。",
        "eg_du_hagu_ms12#1": A + "受到10点伤害。。",
        "eg_du_hagu_ms2": A + "喷出了热热的酱汁。",
        "eg_du_hagu_ms31": A + "整包増过来了。",
        "eg_du_hagu_ms32": A + "选了独自败着活下去的路。",
        "eg_du_hagu_vo1": A + "哈呜。",
        "eg_du_hagu_vo2": A + "咕嘟咕嘟。",
        "eg_du_hagu_vo31": A + "整包増来了波罗！",
        "eg_du_hagu_vo32": A + "一个人活下去波罗。",
        "eg_du_hagu_vo33": A + "整包休…了波罗。",
        "eg_du_hagu_w": A + "滚滚波罗恩。",
        "eg_du_hega_d": H + "各自也立场在食的讨上。",
        "eg_du_hega_l": H + "全装这下完了！",
        "eg_du_hega_ms1#0": H + "自然的接球用柔的托球母终举起。",
        "eg_du_hega_ms1#1": "芋解的快一击恢复了。。",
        "eg_du_hega_ms22": H + "挣扎着享受了。",
        "eg_du_hega_ms221": H + "挣扎着享受了。",
        "eg_du_hega_ms3": H + "三人的屁敲出了前所未有的和声。",
        "eg_du_hega_vo11#0": H + "自然大家都上吧。",
        "eg_du_hega_vo11#1": H + "母终嗯。我们的攻击！",
        "eg_du_hega_vo11#2": H + "芋解。上啊。",
        "eg_du_hega_vo21#0": H + "母终哎呀，糟了。",
        "eg_du_hega_vo21#1": "自然出来了就没办法了。",
        "eg_du_hega_vo31#0": H + "自然先来一发吧。",
        "eg_du_hega_vo31#1": H + "母终好嘞。",
        "eg_du_hega_vo31#2": H + "芋解人来了也不认账哦。",
        "eg_du_hega_w": H + "全装我们是梦的三姐妹。",
        "eg_du_ifrt_d": I + "哼哧哼哧动着鼻子。",
        "eg_du_ifrt_l": I + "操汤对压力有效哼！",
        "eg_du_ifrt_ms12": I + "脸掉下来，看呆了。",
        "eg_du_ifrt_ms121": I + "脸掉下来，看呆了。",
        "eg_du_ifrt_ms22": I + "肚子撑裂了。",
        "eg_du_ifrt_ms23": I + "肚子撑裂了。",
        "eg_du_ifrt_ms24": I + "肚子撑裂，不能动了。",
        "eg_du_ifrt_ms241": I + "肚子撑裂，不能动了。",
        "eg_du_ifrt_ms32#0": I + "好吃到看呆了。",
        "eg_du_ifrt_ms32#1": "真香啊！",
        "eg_du_ifrt_ms321#0": I + "好吃到看呆了。",
        "eg_du_ifrt_ms321#1": "真香啊！",
        "eg_du_ifrt_vo1": I + "猪涮。",
        "eg_du_ifrt_vo2": I + "多汁地役上来了哼。",
        "eg_du_ifrt_vo3": I + "五花五花哼。",
        "eg_du_ifrt_w": I + "好吃吗呼？",
        "eg_du_jido_d": J + "吉铎里姆合金的身体连一道伤都没有！",
        "eg_du_jido_l": J + "看得见哦，妈妈看得见哦，大家都！",
        "eg_du_jido_ms1": J + "用竖笛砍上去了。",
        "eg_du_jido_ms11": J + "用竖笛砍上去了。",
        "eg_du_jido_ms2": J + "点了一下就逃了。",
        "eg_du_jido_ms21": J + "点了一下就逃了。",
        "eg_du_jido_ms3#0": J + "用分乱刮了生飞。。",
        "eg_du_jido_ms3#1": "正对不／的状守备着！",
        "eg_du_jido_ms31#0": J + "用分乱刮了生飞。。",
        "eg_du_jido_ms31#1": "正对不／的状守备着！",
        "eg_du_jido_ms32#0": J + "用分乱刮了生飞。",
        "eg_du_jido_ms32#1": "非常不／的状。。",
        "eg_du_jido_vo1": J + "我最会吹竖笛了。",
        "eg_du_jido_vo2": J + "按铃逃跑要上了——。。",
        "eg_du_jido_vo3": J + "要、乱刮了。乱刮了。乱刮了——。",
        "eg_du_jido_w": J + "可不是O超哟。",
        "eg_du_kami_d": M + "明明是纸，不知为何却挨了伤害。",
        "eg_du_kami_l": M + "居然讨我这纸神，。殿到底！",
        "eg_du_kami_ms1#0": M + "把链锯挥得呼呼转。",
        "eg_du_kami_ms1#1": "团地嫌着，把自己也切复了。。",
        "eg_du_kami_ms2": M + "违抗的全部，都在以前的心思里。",
        "eg_du_kami_ms31#0": M + "只要这一强，能力变0也逃喜势。",
        "eg_du_kami_ms31#1": M + "好好看纸神的力量。",
        "eg_du_kami_ms32#0": M + "可是。",
        "eg_du_kami_ms32#1": M + "用纸神的力量复活了。",
        "eg_du_kami_ms33": M + "即便是纸神，任强占也没有。",
        "eg_du_kami_r2#1": "新招·复活记住了。。",
        "eg_du_kami_vo1": M + "悔改吧。",
        "eg_du_kami_vo2": M + "要有光。",
        "eg_du_kami_vo3": M + "回收。",
        "eg_du_kami_w": M + "违抗我，这也是活物的沙加吗！",
        "eg_du_kero_d": C + "美容抜卷好的来弹地拉长了。",
        "eg_du_kero_l": C + "夹着尾巴逃走了。",
        "eg_du_kero_ms1#0": C + "克罗和贝罗团地咬住了。",
        "eg_du_kero_ms1#1": "斯也咬了。大家都咬了。",
        "eg_du_kero_ms21#0": C + "简直在说你们可爱的繰",
        "eg_du_kero_ms21#1": "摇着尾巴。",
        "eg_du_kero_ms22#0": C + "被可爱引着",
        "eg_du_kero_ms22#1": "战场？团稍稍解开，防御下降了。",
        "eg_du_kero_ms221#0": C + "被可爱引着",
        "eg_du_kero_ms221#1": "战场？团稍稍解开，防御下降了。",
        "eg_du_kero_ms222": C + "觉得被瞧不起，怒了。",
        "eg_du_kero_ms223": C + "觉得被瞧不起，怒了。",
        "eg_du_kero_ms31": C + "静静盯着殿终。",
        "eg_du_kero_ms32#0": C + "为了出气",
        "eg_du_kero_ms32#1": "袭击了。。",
        "eg_du_kero_ms321#0": C + "为了出气",
        "eg_du_kero_ms321#1": "袭击了。。",
        "eg_du_kero_w": C + "高兴得三条择直流着口水。",
        "eg_du_kino_d": N + "心情超嗨。",
        "eg_du_kino_l": N + "刺激刺激，蘑菇蘑菇好！",
        "eg_du_kino_ms1#1": "力上动冲上来，谁也做不了。。",
        "eg_du_kino_ms11#1": "力上动冲上来，谁也做不了。。",
        "eg_du_kino_ms12#1": "可谁也没怎样！",
        "eg_du_kino_ms13#1": "可谁也没怎样！",
        "eg_du_kino_ms2#0": N + "被喂了笑菇。",
        "eg_du_kino_ms2#1": "笑停不下来！",
        "eg_du_kino_ms21#0": N + "被喂了笑菇。",
        "eg_du_kino_ms21#1": "笑停不下来！",
        "eg_du_kino_ms3#1": "讨厌的高兴的，全收掉了！",
        "eg_du_kino_ms31#1": "讨厌的高兴的，全收掉了！",
        "eg_du_kino_vo1": N + "蘑菇蘑菇，吃了就开心！",
        "eg_du_kino_vo2": N + "这样就笑起来了！",
        "eg_du_kino_vo3": N + "忘记的时候，就是这个！",
        "eg_du_kino_w": N + "颤颤颤颤哦哦哦！",
        "eg_du_kure_d": U + "叉子和刀掉了！",
        "eg_du_kure_l": U + "不给我吗？",
        "eg_du_kure_ms1": U + "狼吞虎咽地吃了。",
        "eg_du_kure_ms12": U + "狼吞虎咽地吃了。",
        "eg_du_kure_ms22#0": U + "被口水弄得黏糊糊！",
        "eg_du_kure_ms23#0": U + "被口水弄得黏糊糊！",
        "eg_du_kure_ms3#0": U + "时死把自己的尾巴",
        "eg_du_kure_ms3#1": "咬下来了！",
        "eg_du_kure_vo1": U + "给我给我给我。",
        "eg_du_kure_vo2": U + "嗝。",
        "eg_du_kure_vo3#0": U + "给我给我给我给我给我给我给我给我",
        "eg_du_kure_vo3#1": U + "给我给我给我给我给我给我给我！",
        "eg_du_kure_w": U + "再给我！",
    }
    return out
