"""Cyber-egg battle lines A (pwra–atom)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    L = "动力女士："
    Mi = "米卡："
    Gd = "盖多："
    Ro = "机器人："
    A = "亚历克桑达："
    P = "解谜3："
    Ani = "长兄："
    Nji = "次兄："
    San = "三男："
    W = "莱特母鸡："
    Bro = "兄："
    Sis = "弟："
    B = "巴里佐贡："
    M = "机械艾格曼："
    K = "机械医生夫妇："
    S = "性感炸弹："
    C = "不想的人："
    T = "阿特美："
    return {
        # --- 动力女士 ---
        "eg_cv_pwra_d": L + "动力女士正怒着。",
        "eg_cv_pwra_l#0": Gd + "说到底，不过是人心造出来的机器人！",
        "eg_cv_pwra_l#1": "去叹无力、朽掉吧。",
        "eg_cv_pwra_ms1#0": L + "对新英雄登场的预感，",
        "eg_cv_pwra_ms1#1": "心里扑通扑通。。",
        "eg_cv_pwra_ms11#0": L + "对新英雄登场的预感，",
        "eg_cv_pwra_ms11#1": "心里扑通扑通。。",
        "eg_cv_pwra_ms2#0": L + "动力女士从孩子手里抢走变身器，",
        "eg_cv_pwra_ms2#1": "朝那边扔掉了。。",
        "eg_cv_pwra_ms21#0": L + "动力女士从孩子手里抢走变身器，",
        "eg_cv_pwra_ms21#1": "朝那边扔掉了。。",
        "eg_cv_pwra_ms3": L + "机器人向米卡的心意变成了牺牲。。",
        "eg_cv_pwra_ms31#0": L + "可机器人又若无其事地回来了！",
        "eg_cv_pwra_ms31#1": "原来被藏起来了呢！",
        "eg_cv_pwra_vo1#0": L + "第1话",
        "eg_cv_pwra_vo1#1": L + "登场。",
        "eg_cv_pwra_vo11#0": Mi + "我的名字是魔力米卡，",
        "eg_cv_pwra_vo11#1": "人家叫我动力女士。。",
        "eg_cv_pwra_vo12#0": Mi + "乘着爷爷开发的人型时限决战兵器，",
        "eg_cv_pwra_vo12#1": "日夜和盖多军战斗。。",
        "eg_cv_pwra_vo13#0": Mi + "密语是——。。",
        "eg_cv_pwra_vo13#1": "小孩子也能当英雄的。",
        "eg_cv_pwra_vo2#0": L + "第16话",
        "eg_cv_pwra_vo2#1": "变身器被夺",
        "eg_cv_pwra_vo21#0": Gd + "哇哈哈。新兵器终于完成了。",
        "eg_cv_pwra_vo21#1": "就用这家伙把世界掀翻——。。",
        "eg_cv_pwra_vo22": "孩子：要不要尿尿啾？",
        "eg_cv_pwra_vo23#0": Mi + "危——险。。",
        "eg_cv_pwra_vo23#1": "那是盖多的新兵器变身器哟——。。",
        "eg_cv_pwra_vo24#0": "孩子：呜哇——",
        "eg_cv_pwra_vo24#1": "奇怪的人把人家的变身器拿走了啊——。。",
        "eg_cv_pwra_vo3#0": L + "最终话",
        "eg_cv_pwra_vo3#1": "牺牲",
        "eg_cv_pwra_vo31": Mi + "哈啊哈啊！",
        "eg_cv_pwra_vo32#0": Gd + "哇哈哈。可怜的少女。",
        "eg_cv_pwra_vo32#1": "永远把希望啊梦啊挂在嘴边就够了！",
        "eg_cv_pwra_vo33#0": Mi + "米卡好像回不来了",
        "eg_cv_pwra_vo33#1": "对不起对不起！",
        "eg_cv_pwra_vo34#0": Ro + "米卡酱在哭吗？",
        "eg_cv_pwra_vo34#1": "欺负米卡酱的家伙不可饶恕。。",
        "eg_cv_pwra_vo35": Mi + "机——器——人——————。。",
        "eg_cv_pwra_w#0": Mi + "来。变成动力女士",
        "eg_cv_pwra_w#1": "小孩子也能当英雄的。",
        # --- 亚历克桑达 ---
        "eg_cv_alec_d": A + "亚历克桑达正等着。",
        "eg_cv_alec_l#0": A + "Oh no.",
        "eg_cv_alec_l#1": "明明该更成熟了的！",
        "eg_cv_alec_ms1#0": A + "手忙脚乱起来。",
        "eg_cv_alec_ms11#0": A + "手忙脚乱起来。",
        "eg_cv_alec_ms12#0": A + "是啊。",
        "eg_cv_alec_ms12#1": "表示同意了。",
        "eg_cv_alec_ms13#0": A + "是啊。",
        "eg_cv_alec_ms13#1": "表示同意了。",
        "eg_cv_alec_ms21": A + "陷入混乱了。",
        "eg_cv_alec_ms211": A + "陷入混乱了。",
        "eg_cv_alec_ms22": A + "乖乖听完了话。",
        "eg_cv_alec_ms221": A + "乖乖听完了话。",
        "eg_cv_alec_ms23": A + "对混乱毫不动摇。",
        "eg_cv_alec_ms231": A + "对混乱毫不动摇。",
        "eg_cv_alec_ms24#0": A + "起了兴趣。",
        "eg_cv_alec_ms24#1": "就这样而已啊。",
        "eg_cv_alec_ms241#0": A + "起了兴趣。",
        "eg_cv_alec_ms241#1": "就这样而已啊。",
        "eg_cv_alec_ms3": A + "陷入恐慌状态了。",
        "eg_cv_alec_ms31": A + "陷入恐慌状态了。",
        "eg_cv_alec_vo1#0": A + "你好。我是亚历克桑达。",
        "eg_cv_alec_vo1#1": "从今天起，是朋友呢。",
        "eg_cv_alec_vo21": A + "Yellow card.",
        "eg_cv_alec_vo22": A + "Red card.",
        "eg_cv_alec_vo23#0": A + "Green card.",
        "eg_cv_alec_vo23#1": "要不要来美国住住看？",
        "eg_cv_alec_vo31#0": A + "I am speaking at native speed now.",
        "eg_cv_alec_vo31#1": "Please try to keep up with me.",
        "eg_cv_alec_vo32#0": A + "How are you doing today my friend?",
        "eg_cv_alec_vo32#1": "This is how we talk in America.",
        "eg_cv_alec_vo32#2": A + "Nice to meet you.",
        "eg_cv_alec_vo33#0": A + "Actually I have been studying Japanese.",
        "eg_cv_alec_vo33#1": "But native conversation is still quite hard.",
        "eg_cv_alec_vo33#2": A + "Would you like to live in the United States?",
        "eg_cv_alec_vo34#0": A + "Let's be friends and visit America together.",
        "eg_cv_alec_vo34#1": "I hope you can understand what I am saying.",
        "eg_cv_alec_w": A + "做得好。",
        # --- 解谜3 ---
        "eg_cv_paz3_d": P + "解谜3为了你们正拼命呼喊。。",
        "eg_cv_paz3_l1#0": Ani + "怎、怎么。",
        "eg_cv_paz3_l1#1": "次兄：俺们会输？",
        "eg_cv_paz3_l2": San + "可以睡了吧？",
        "eg_cv_paz3_ms1": "解谜3摔了个狗吃屎。",
        "eg_cv_paz3_ms11": "解谜3摔了个狗吃屎。",
        "eg_cv_paz3_ms12#0": P + "。",
        "eg_cv_paz3_ms12#1": "可身体还紧紧粘在一起！",
        "eg_cv_paz3_ms2#0": P + "三男力气尽了。",
        "eg_cv_paz3_ms2#1": "长兄、次兄也累垮了。。",
        "eg_cv_paz3_ms21#0": "解谜3靠长兄次兄把身体团了起来",
        "eg_cv_paz3_ms212#0": "解谜3靠长兄次兄把身体团了起来",
        "eg_cv_paz3_ms32": P + "三男向新世界迈出了第一步！",
        "eg_cv_paz3_ms33#0": P + "可大家都回来了！",
        "eg_cv_paz3_ms33#1": "果然还是粘在一起的世界啊。",
        "eg_cv_paz3_vo11#0": Ani + "好。要分开了。",
        "eg_cv_paz3_vo11#1": "次兄：知道了。大哥。",
        "eg_cv_paz3_vo13": San + "好、好嘞。",
        "eg_cv_paz3_vo14": P + "全体开解开谜人。。",
        "eg_cv_paz3_vo21": San + "啊，已经累了！",
        "eg_cv_paz3_vo22#0": Nji + "长兄正说着呢。",
        "eg_cv_paz3_vo22#1": "长兄：战斗从现在才开始。",
        "eg_cv_paz3_vo24": San + "对、对不起，各位！",
        "eg_cv_paz3_vo25": Ani + "次兄。。",
        "eg_cv_paz3_vo31": San + "真是受够了啊啊啊啊。",
        "eg_cv_paz3_vo32#0": Ani + "呐，要分吗？",
        "eg_cv_paz3_vo32#1": "次兄：别、别。。",
        "eg_cv_paz3_vo34": Ani + "次兄：哇啊啊啊。。",
        "eg_cv_paz3_vo35": San + "啊。我要一个人活下去。",
        "eg_cv_paz3_w1#0": Ani + "哈哈。看见了吗。",
        "eg_cv_paz3_w1#1": "次兄：俺们早欲界的可怕。",
        "eg_cv_paz3_w1#2": San + "这种生活是地狱啊！",
        "eg_cv_paz3_w2": San + "这种生活是地狱啊！",
        # --- 莱特母鸡 ---
        "eg_cv_ligt_d": W + "啊。莱特母鸡要裂开了要裂开了。。",
        "eg_cv_ligt_l#0": Bro + "来世要以100瓦出生吧！",
        "eg_cv_ligt_l#1": "弟：捨所以新。？",
        "eg_cv_ligt_ms1#0": W + "兄弟使出了世界最初的飞！",
        "eg_cv_ligt_ms1#1": "正在打盹！",
        "eg_cv_ligt_ms11#0": W + "兄弟使出了世界最初的飞！",
        "eg_cv_ligt_ms11#1": "正在打盹！",
        "eg_cv_ligt_ms2#0": W + "吵架摩擦，莱特母鸡闪闪发热。",
        "eg_cv_ligt_ms2#1": "刺眼。。",
        "eg_cv_ligt_ms21#0": W + "吵架摩擦，莱特母鸡闪闪发热。",
        "eg_cv_ligt_ms21#1": "刺眼。。",
        "eg_cv_ligt_ms3#0": W + "莱特母鸡挑战把不可能变成可能，",
        "eg_cv_ligt_ms3#1": "不可能还是不可能！",
        "eg_cv_ligt_ms31": "被莱特母鸡的挑战精神感动了。。",
        "eg_cv_ligt_ms32": "被莱特母鸡的挑战精神感动了。。",
        "eg_cv_ligt_ms33#0": W + "莱特母鸡挑战把不可能变成可能。",
        "eg_cv_ligt_ms33#1": "被两人的挑战精神感动了。",
        "eg_cv_ligt_ms34#0": W + "莱特母鸡挑战把不可能变成可能。",
        "eg_cv_ligt_ms34#1": "被两人的挑战精神感动了。",
        "eg_cv_ligt_vo1#0": Bro + "弟桑。用哥哥的招！",
        "eg_cv_ligt_vo1#1": "弟：兄艾迪生————。。。",
        "eg_cv_ligt_vo2#0": Bro + "弟桑真是不懂啊。",
        "eg_cv_ligt_vo2#1": "弟：喂。对着弟乱造択的「才是食。",
        "eg_cv_ligt_vo3#0": Bro + "弟桑。我相信弟桑。",
        "eg_cv_ligt_vo3#1": "弟：大喜势。既然俺说了就是绝对。。",
        "eg_cv_ligt_vo31#0": Bro + "飞吧——。。载上我们的梦。",
        "eg_cv_ligt_vo31#1": "弟：飞吧——。。载上俺们的使命。",
        "eg_cv_ligt_w#0": Bro + "这感动收不住啊闪闪——。",
        "eg_cv_ligt_w#1": "弟：俺也俺也。闪闪——。。",
        # --- 巴里佐贡 ---
        "eg_cv_bari_d": B + "巴里佐贡对互殴很怕！",
        "eg_cv_bari_l": B + "俺在吵架里输了？",
        "eg_cv_bari_ms1": B + "心跳。被揭了老底！",
        "eg_cv_bari_ms11": B + "心跳。被揭了老底！",
        "eg_cv_bari_ms11_man#0": B + "心跳。被揭了老底！",
        "eg_cv_bari_ms11_man#1": "一定在脑子里忘不掉。",
        "eg_cv_bari_ms1_man#0": B + "心跳。被揭了老底！",
        "eg_cv_bari_ms1_man#1": "一定在脑子里忘不掉。",
        "eg_cv_bari_ms2": B + "啪。是不能被乐的秘密！",
        "eg_cv_bari_ms21": B + "啪。是不能被乐的秘密！",
        "eg_cv_bari_ms3": B + "噗。心里有什么断了！",
        "eg_cv_bari_ms32": B + "噗。心里有什么断了！",
        "eg_cv_bari_ms_miss#0": B + "哈。？",
        "eg_cv_bari_ms_miss#1": "对巴里佐贡的揭底毫不动摇！",
        "eg_cv_bari_ms_miss2#0": B + "哈。？",
        "eg_cv_bari_ms_miss2#1": "对巴里佐贡的揭底毫不动摇！",
        "eg_cv_bari_vo1#0": B + "小学时，在厕所和班上孩子比谁尿得远的",
        "eg_cv_bari_vo1#1": "是谁——。。",
        "eg_cv_bari_vo2#0": B + "试胆时尿裤子哭了，",
        "eg_cv_bari_vo2#1": "被叫尿裤子妖怪的是谁——。。",
        "eg_cv_bari_vo3#0": B + "时尚品味也没有钱，也没有恋人。",
        "eg_cv_bari_vo3#1": "你那主张的自由，到底是什么？",
        "eg_cv_bari_w": B + "俺就是巴里佐贡。",
        # --- 机械艾格曼 ---
        "eg_cv_megg_d": M + "机械艾格曼的头盔歪了1军！",
        "eg_cv_megg_l": M + "。。系统关闭。",
        "eg_cv_megg_ms1": M + "机械艾格曼把鸡冠飞出去了。",
        "eg_cv_megg_ms2#0": M + "机械艾格曼打扮了一下，",
        "eg_cv_megg_ms2#1": "好像没什么兴趣！",
        "eg_cv_megg_ms21#0": M + "机械艾格曼打扮了一下，",
        "eg_cv_megg_ms21#1": "好像没什么兴趣！",
        "eg_cv_megg_ms22#0": M + "机械艾格曼打扮了一下！",
        "eg_cv_megg_ms22#1": "看入迷了。。",
        "eg_cv_megg_ms23#0": M + "机械艾格曼打扮了一下！",
        "eg_cv_megg_ms23#1": "看入迷了。。",
        "eg_cv_megg_ms3#0": M + "机械艾格曼到底在哪，",
        "eg_cv_megg_ms3#1": "没法操作。",
        "eg_cv_megg_ms31#0": M + "机械艾格曼到底在哪，",
        "eg_cv_megg_ms31#1": "没法操作。",
        "eg_cv_megg_ms32": "被合进少早-03里面了！",
        "eg_cv_megg_ms33": "被合进少早-03里面了！",
        "eg_cv_megg_vo1": M + "攻击模式1。艾格斯拉格。",
        "eg_cv_megg_vo2": M + "攻击模式2。蛋变身。",
        "eg_cv_megg_vo3#0": M + "攻击模式3。",
        "eg_cv_megg_vo3#1": "体知小小少早-03。",
        "eg_cv_megg_w": M + "任务完成。",
        # --- 机械医生夫妇 ---
        "eg_cv_mkai_d": K + "和势地星的对战，不像想的那样顺利。",
        "eg_cv_mkai_l": K + "势地灭亡了！",
        "eg_cv_mkai_ms1#0": K + "从两人眉间飞出的怪光",
        "eg_cv_mkai_ms1#1": "对准飞了过去。",
        "eg_cv_mkai_ms12#0": K + "从两人眉间飞出的怪光",
        "eg_cv_mkai_ms12#1": "对准飞了过去。",
        "eg_cv_mkai_ms2": K + "巨大的冲击星贯穿射击了。",
        "eg_cv_mkai_ms21": K + "巨大的冲击星贯穿射击了。",
        "eg_cv_mkai_ms22": K + "巨大的冲击星一声不吭！",
        "eg_cv_mkai_ms3": K + "机械老婆被发射了。。",
        "eg_cv_mkai_ms31": K + "机械医生夫妇报告了故障！",
        "eg_cv_mkai_vo21#0": K + "能源输出10％。",
        "eg_cv_mkai_vo21#1": "。发射了。",
        "eg_cv_mkai_vo22": K + "能源输出30％。",
        "eg_cv_mkai_vo23": K + "能源输出65％。",
        "eg_cv_mkai_vo24#0": K + "最大输出。。",
        "eg_cv_mkai_vo24#1": "最大模式发射。",
        "eg_cv_mkai_vo31": K + "锁定目标！",
        "eg_cv_mkai_vo32": K + "系统解除。锁定解锁！",
        "eg_cv_mkai_vo33": K + "全部绿灯。。发射。",
        "eg_cv_mkai_w": K + "战场模式解锁！",
        # --- 性感炸弹 ---
        "eg_cv_sexy_d": S + "性感炸弹感觉好极了。",
        "eg_cv_sexy_l": S + "呵呵，不赖嘛，小鬼。",
        "eg_cv_sexy_ms1": "性感炸弹燃起来了。",
        "eg_cv_sexy_ms11": "性感炸弹燃起来了。",
        "eg_cv_sexy_ms2": "性感炸弹和导弹君激烈起来了！",
        "eg_cv_sexy_ms21": "性感炸弹和导弹君激烈起来了！",
        "eg_cv_sexy_ms3#0": S + "对着性感炸弹的炸药身材，",
        "eg_cv_sexy_ms3#1": "心要引爆了。",
        "eg_cv_sexy_ms31#0": S + "对着性感炸弹的炸药身材，",
        "eg_cv_sexy_ms31#1": "心要引爆了。",
        "eg_cv_sexy_ms32#0": S + "对着性感炸弹的炸药身材，",
        "eg_cv_sexy_ms32#1": "心引爆了。。",
        "eg_cv_sexy_ms33#0": S + "对着性感炸弹的炸药身材，",
        "eg_cv_sexy_ms33#1": "心引爆了。。",
        "eg_cv_sexy_vo1#0": S + "火已经点着了——再也停不下来了。",
        "eg_cv_sexy_vo1#1": "接住俺的姿——。",
        "eg_cv_sexy_vo2#0": S + "飞出去——。别停——。",
        "eg_cv_sexy_vo2#1": "狠狠撞过来——。",
        "eg_cv_sexy_vo3": S + "让你的心，爆炸给你看——。",
        "eg_cv_sexy_w": S + "变成大人后再来玩啊！",
        # --- 不想的人 ---
        "eg_cv_kang_d": C + "不想的人正努力不去想伤害。",
        "eg_cv_kang_l": C + "不想的人把一协败所给想了。",
        "eg_cv_kang_ms1": C + "不想的人无论何时都正向。",
        "eg_cv_kang_ms12": "不想的人生气了，给姿100点伤害。",
        "eg_cv_kang_ms121": "不想的人生气了，给姿100点伤害。",
        "eg_cv_kang_ms121_m": "不想的人生气了，给姿伤害。",
        "eg_cv_kang_ms12_m": "不想的人生气了，给姿伤害。",
        "eg_cv_kang_ms2#0": C + "不想的人，想了！",
        "eg_cv_kang_ms2#1": "只是假装在想。",
        "eg_cv_kang_ms22": "不想的人被傻赢了。",
        "eg_cv_kang_ms221": "不想的人被傻赢了。",
        "eg_cv_kang_ms3#0": C + "不想的人发现，自己为了不想而在想。",
        "eg_cv_kang_ms3#1": "注意到了。",
        "eg_cv_kang_ms32": C + "不想的人终于抵达了无想的境地。",
        "eg_cv_kang_ms33": C + "无我之境的姿挡在了谁面前。",
        "eg_cv_kang_vo1": C + "！",
        "eg_cv_kang_vo2": C + "！",
        "eg_cv_kang_vo3": C + "。",
        "eg_cv_kang_w": C + "不去想这件事，有时也会作为等待带来胜利。",
        # --- 阿特美 ---
        "eg_cv_atom_d": T + "阿特美泪汪汪的！",
        "eg_cv_atom_l": T + "绝对要报仇的呀——。。",
        "eg_cv_atom_ms1": T + "阿特美变成战场火箭冲过去了。。",
        "eg_cv_atom_ms2": T + "阿特美眼里的阿特美枪打出了光。。",
        "eg_cv_atom_ms3#0": T + "陨石飞来了，阿特美正拼命躲——。",
        "eg_cv_atom_ms3#1": "啊。阿特美放弃了——。。",
        "eg_cv_atom_ms31#0": T + "陨石飞来了，阿特美正拼命躲，可！",
        "eg_cv_atom_ms31#1": "轻易放弃了！",
        "eg_cv_atom_vo1": T + "给你们看阿特美性感的变形！",
        "eg_cv_atom_vo12": T + "嗯嗯嗯啊啊啊啊————。。。",
        "eg_cv_atom_vo2": T + "用阿特美的秘密兵器，去睡觉吧！",
        "eg_cv_atom_vo3": T + "啊是陨石好危险呀。",
        "eg_cv_atom_vo31": T + "阿特美力量最大呀！",
        "eg_cv_atom_vo32": T + "嘿嘿！",
        "eg_cv_atom_vo33#0": T + "啊是陨石好危险呀。",
        "eg_cv_atom_vo33#1": "阿特美力量最大呀。。",
        "eg_cv_atom_w": T + "呀呼——赢了呀。。",
    }
