"""Arena-egg battle lines (omeg / tken / mhel / flya)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    O = "欧米茄："
    N = "鸣门："
    M = "机械鸣门："
    F = "欧米茄飞手："
    T = "星空动备持勇："
    Y = "勇："
    H = "通贩桑地狱："
    Hu = "丈夫："
    W = "妻子："
    A = "播报："
    return {
        # --- 欧米茄 ---
        "eg_tg_omeg_d1": O + "滑。驾驶舱的鸣门化开了！",
        "eg_tg_omeg_d2": O + "糊。驾驶舱的鸣门化开了！",
        "eg_tg_omeg_d3": O + "粘。驾驶舱的鸣门化开了！",
        "eg_tg_omeg_event1": N + "可恶——。机械鸣门哦——。。",
        "eg_tg_omeg_event1#0": "鸣门变成了超级鸣门。。",
        "eg_tg_omeg_event1#1": "全部威力上升了。。",
        "eg_tg_omeg_event1_m": M + "可恶——。鸣门哦——。。",
        "eg_tg_omeg_event2": N + "把机械鸣门怎么了。。",
        "eg_tg_omeg_event2_m": M + "把鸣门怎么了。。",
        "eg_tg_omeg_event2_m_onaji": M + "把机械鸣门怎么了。。",
        "eg_tg_omeg_event2_onaji": N + "把鸣门怎么了。。",
        "eg_tg_omeg_event3#0": "可没有时间了！",
        "eg_tg_omeg_event3#1": "你把那个鸣门还给我！",
        "eg_tg_omeg_event4": N + "那个鸣门。？是机械鸣门的事！",
        "eg_tg_omeg_event4_m": M + "那个鸣门。？是鸣门的事！",
        "eg_tg_omeg_event4_m_onaji": M + "那个鸣门。？是机械鸣门的事！",
        "eg_tg_omeg_event4_onaji": N + "那个鸣门。？是鸣门的事！",
        "eg_tg_omeg_l": O + "击是鸣门的一部啊，合而临鸣门！",
        "eg_tg_omeg_love": "迪卡查。迪卡查。迪卡查。",
        "eg_tg_omeg_love_ms": O + "欧米茄因无法理解的占数冻结了。。",
        "eg_tg_omeg_love_ms2": O + "欧米茄好歹回复了。",
        "eg_tg_omeg_ms1": "欧米茄成了夜动殿的／。。",
        "eg_tg_omeg_ms2#0": "欧米茄被",
        "eg_tg_omeg_ms2#1": "原子射线扫过了。。",
        "eg_tg_omeg_ms3#0": O + "欧米茄和飞手们的",
        "eg_tg_omeg_ms3#1": "三角击攻所了。。",
        "eg_tg_omeg_ms4#0": O + "欧米茄把库存的鸣门吃了。。",
        "eg_tg_omeg_ms5#0": "对着欧米茄的攻击，",
        "eg_tg_omeg_ms5#1": "欧米茄用芥末弹反击。。",
        "eg_tg_omeg_ms52#0": O + "欧米茄",
        "eg_tg_omeg_ms52#1": "成了反击的打空状态。。",
        "eg_tg_omeg_vo11": O + "心与俺与进能报末箱能鸣门漩涡！",
        "eg_tg_omeg_vo12": O + "衔尾蛇战土费疲起鸣门漩涡！",
        "eg_tg_omeg_vo13": O + "状打的螺旋改复N知鸣门漩涡！",
        "eg_tg_omeg_vo21": O + "星字潜协的」任之形N鸣门漩涡！",
        "eg_tg_omeg_vo22": O + "属与明进回报的谁书星鸣门漩涡！",
        "eg_tg_omeg_vo23": O + "向捨的全操与战人的守鸣门漩涡！",
        "eg_tg_omeg_vo31": O + "大力怪连下去的心鸣门漩涡！",
        "eg_tg_omeg_vo32": O + "自的螺旋所打的十感鸣门漩涡！",
        "eg_tg_omeg_vo33": O + "击！嫌发完鸣门漩涡！",
        "eg_tg_omeg_vo41": O + "报末箱能打的识失鸣门漩涡！",
        "eg_tg_omeg_vo42": O + "军雄本失间而成为番的鸣门漩涡！",
        "eg_tg_omeg_vo43": O + "被造嫌的字负打的今鸣门漩涡！",
        "eg_tg_omeg_vo51": O + "希望的本失了由饮了由鸣门漩涡！",
        "eg_tg_omeg_vo52": O + "我集与编置将是莫比乌斯鸣门漩涡！",
        "eg_tg_omeg_vo53": O + "容战的收旋转木马鸣门漩涡！",
        "eg_tg_omeg_vo_ex": O + "鸣门漩涡！",
        "eg_tg_omeg_vo_ex2": O + "原来如此漩涡！",
        "eg_tg_omeg_w#0": O + "仰望天比谁都高，以俺为目标比谁都热的勇",
        "eg_tg_omeg_w#1": "既是人又是被选者，投身无尽之阵的鸣门！",
        # --- 星空动备持勇 ---
        "eg_tg_tken_d1": T + "危险危险危险。",
        "eg_tg_tken_d2": T + "好疼！",
        "eg_tg_tken_d3": T + "请停下来！",
        "eg_tg_tken_d4": T + "那种我讨厌！",
        "eg_tg_tken_d5": T + "别打！",
        "eg_tg_tken_d6": T + "明明是机械却好疼。",
        "eg_tg_tken_l1": T + "咦？又输了？",
        "eg_tg_tken_l2": T + "来。下次才赢，你给我等着——。",
        "eg_tg_tken_l3": T + "辛苦了？变战",
        "eg_tg_tken_l4#0": T + "啊，稍等。让开。让开。",
        "eg_tg_tken_l4#1": "危险。危险。要撞上——。",
        "eg_tg_tken_ms13": T + "星空动备持勇把历史的笑话讲了！",
        "eg_tg_tken_ms2": T + "嗯沙巴哒——",
        "eg_tg_tken_ms21#0": T + "从星空动备持勇里",
        "eg_tg_tken_ms21#1": "人的惊吓勇机械出发了！",
        "eg_tg_tken_ms31": T + "？勇呜哦哦哦哦哦。",
        "eg_tg_tken_ms32": T + "？勇啊！梦自！",
        "eg_tg_tken_ms33#0": T + "】勇跟得上我的速度吗？。",
        "eg_tg_tken_ms33#1": "开铁拳。。",
        "eg_tg_tken_ms34": T + "】勇铁拳钻。。。",
        "eg_tg_tken_ms35": T + "】勇停停停停停停。",
        "eg_tg_tken_ms36#0": T + "勇这一下是最后一击。",
        "eg_tg_tken_ms36#1": "开铁拳。。",
        "eg_tg_tken_ms37": T + "勇铁拳光————束。",
        "eg_tg_tken_ms38": T + "勇！",
        "eg_tg_tken_ms39": "还以为是既视感！",
        "eg_tg_tken_st1": T + "你好！你好！我的名字是勇！",
        "eg_tg_tken_st2#0": T + "按攻略本拍的那样",
        "eg_tg_tken_st2#1": "啊变成机械回来了！",
        "eg_tg_tken_st3#0": T + "。我的役是隐藏首领，据说",
        "eg_tg_tken_st3#1": "是这游戏里最强的！",
        "eg_tg_tken_st4": T + "那么，差不多要上了！",
        "eg_tg_tken_st5": T + "星空动备持勇嗯嗯嗯。。。",
        "eg_tg_tken_vo11#0": T + "大家都知道吧？",
        "eg_tg_tken_vo11#1": "那就一起！",
        "eg_tg_tken_vo12#0": T + "嗯沙巴哒——嗯沙巴哒——",
        "eg_tg_tken_vo12#1": "嗯沙巴哒——嗯沙巴哒——！",
        "eg_tg_tken_vo21#0": T + "这就是我的必杀星！",
        "eg_tg_tken_vo21#1": "那我开动了！",
        "eg_tg_tken_vo22#0": T + "准备好了所以",
        "eg_tg_tken_vo22#1": "人的惊吓勇机械出发！",
        "eg_tg_tken_vo3#0": T + "？勇这里交给我。",
        "eg_tg_tken_vo3#1": "开铁拳。。",
        "eg_tg_tken_w": T + "开铁拳。。",
        # --- 通贩桑地狱 ---
        "eg_tg_mhel_d1": H + "地狱的殿终不太妙啊。",
        "eg_tg_mhel_d2": H + "地狱的殿终正在殿捕。",
        "eg_tg_mhel_d3": H + "地狱要燃起来的飞开。",
        "eg_tg_mhel_l#0": W + "俺稍微出门一下！",
        "eg_tg_mhel_l#1": "骷髅，帮看着点！",
        "eg_tg_mhel_ms1#0": H + "两人的捨栏，对着",
        "eg_tg_mhel_ms1#1": "气或形的」（乐现，叫教了起来。",
        "eg_tg_mhel_ms2#0": H + "也和丈夫一起把尸体",
        "eg_tg_mhel_ms2#1": "立能，心里扑通扑通。",
        "eg_tg_mhel_ms3": Hu + "超可置负地逃了。了。。",
        "eg_tg_mhel_ms31": H + "也，【地想了。",
        "eg_tg_mhel_vo11#0": Hu + "再来一碗！",
        "eg_tg_mhel_vo11#1": "妻子好的好的！",
        "eg_tg_mhel_vo12#0": Hu + "再来一碗，啊，轻一点！",
        "eg_tg_mhel_vo12#1": "妻子好的好的！",
        "eg_tg_mhel_vo13#0": Hu + "稍微热一下！",
        "eg_tg_mhel_vo13#1": "妻子好的好的！",
        "eg_tg_mhel_vo20#0": A + "哦。已经）落了——。。",
        "eg_tg_mhel_vo20#1": "抓到）第○了——。。",
        "eg_tg_mhel_vo21#0": A + "来，尸体的流",
        "eg_tg_mhel_vo21#1": "最初的进负，早任的明攻超了————。。",
        "eg_tg_mhel_vo211": Hu + "嗯嗯！",
        "eg_tg_mhel_vo22#0": W + "请用！",
        "eg_tg_mhel_vo22#1": "丈夫嗯嗯！",
        "eg_tg_mhel_vo23#0": A + "友打——。",
        "eg_tg_mhel_vo23#1": "友慢慢地，尸体的流过来了。",
        "eg_tg_mhel_vo24#0": W + "怎么样？",
        "eg_tg_mhel_vo24#1": "丈夫嗯嗯！",
        "eg_tg_mhel_vo25#0": A + "请看。是。。",
        "eg_tg_mhel_vo25#1": "有几具尸体的流。。",
        "eg_tg_mhel_vo26#0": W + "今天，好像能来很多？",
        "eg_tg_mhel_vo26#1": "丈夫嗯嗯！",
        "eg_tg_mhel_vo27#0": A + "哦哦。。。什么与。",
        "eg_tg_mhel_vo27#1": "来与的强者啊——。号码布快点切。",
        "eg_tg_mhel_vo31#0": A + "阎魔大力披上了。终于超决了——。",
        "eg_tg_mhel_vo31#1": "来，这具尸体会怎样？出来了啊——。。",
        "eg_tg_mhel_vo33": A + "、【。。出局————。。",
        "eg_tg_mhel_vo34#0": A + "进去了——。。。地狱————。。",
        "eg_tg_mhel_vo34#1": "丈夫修得了吗？修得了。？修得了啊。。",
        "eg_tg_mhel_w#0": A + "、【不过，转播到此结束！",
        "eg_tg_mhel_w#1": "丈夫妻子，地狱收音机！",
        # --- 欧米茄飞手 ---
        "eg_tg_flya_d1": F + "嘎沙。差点把鸣门弄掉。",
        "eg_tg_flya_d2": F + "咯噔。差点把鸣门弄掉。",
        "eg_tg_flya_d3": F + "滑。差点把鸣门弄掉。",
        "eg_tg_flya_l#0": F + "欧米茄飞手把鸣门弄掉了。",
        "eg_tg_flya_l#1": "活动停止了。。",
        "eg_tg_flya_ms1#0": F + "欧米茄飞手",
        "eg_tg_flya_ms1#1": "对着人射击。。",
        "eg_tg_flya_ms21#0": F + "欧米茄飞手的毒弹。",
        "eg_tg_flya_ms21#1": "中毒了。。",
        "eg_tg_flya_ms22#0": F + "欧米茄飞手的停止弹。",
        "eg_tg_flya_ms22#1": "变得所动不威了。。",
        "eg_tg_flya_ms23#0": F + "欧米茄飞手的镇静弹。",
        "eg_tg_flya_ms24#0": F + "欧米茄飞手的裸弹。",
        "eg_tg_flya_ms24#1": "防御下降了。。",
        "eg_tg_flya_ms25#0": F + "欧米茄飞手的缓慢弹。",
        "eg_tg_flya_ms25#1": "速度下降了。。",
        "eg_tg_flya_ms26#0": F + "欧米茄飞手的精神弹。",
        "eg_tg_flya_ms26#1": "精神下降了。。",
        "eg_tg_flya_ms3#0": F + "欧米茄飞手",
        "eg_tg_flya_ms3#1": "用欧米茄库存的鸣门使军复活了。。",
        "eg_tg_flya_ms31#0": F + "欧米茄飞手想复活，可",
        "eg_tg_flya_ms31#1": "欧米茄已经没有库存鸣门了。。",
        "eg_tg_flya_ms32#0": F + "欧米茄飞手想复活，可",
        "eg_tg_flya_ms32#1": "欧米茄已经被干掉了。。",
        "eg_tg_flya_ms33#0": F + "2空的欧米茄飞手",
        "eg_tg_flya_ms33#1": "用欧米茄库存的鸣门使军复活了。。",
        "eg_tg_flya_vo1": F,
        "eg_tg_flya_w#0": O + "仰望天比谁都高，以俺为目标比谁都热的勇",
        "eg_tg_flya_w#1": "既是人又是被选者，投身无尽之阵的鸣门！",
    }
