"""Cyber-egg battle lines B (mnal–yata)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    N = "机械鸣门："
    G = "绿锤："
    B = "罗宋汤："
    W = "木头球："
    C = "加农姐妹："
    M1 = "一号："
    M2 = "二号："
    U = "机械不动猿："
    H = "机器人捕快："
    K = "机体骑士："
    T = "铁人8号："
    Y = "屋台达："
    return {
        # --- 机械鸣门 ---
        "eg_cv_mnal_d#0": N + "疼还是不疼，说不清。",
        "eg_cv_mnal_d#1": "用人事来说，就是感觉不明。",
        "eg_cv_mnal_l": N + "怎么说呢，好像输了！",
        "eg_cv_mnal_ms1#0": "机械鸣门忍不住贴了脸。",
        "eg_cv_mnal_ms1#1": "咯吱咯吱！",
        "eg_cv_mnal_ms11#0": "机械鸣门忍不住贴了脸。",
        "eg_cv_mnal_ms11#1": "咯吱咯吱！",
        "eg_cv_mnal_ms12": "机械鸣门的脸满是伤。",
        "eg_cv_mnal_ms121": "机械鸣门的脸满是伤。",
        "eg_cv_mnal_ms2": "机械鸣门看见了机械鸣门的漩涡中心。",
        "eg_cv_mnal_ms21": "机械鸣门看见了机械鸣门的漩涡中心。",
        "eg_cv_mnal_ms22#0": "机械鸣门眼睛转了。",
        "eg_cv_mnal_ms221#0": "机械鸣门眼睛转了。",
        "eg_cv_mnal_ms23": "机械鸣门原来喜欢机械啊",
        "eg_cv_mnal_ms231": "机械鸣门原来喜欢机械啊",
        "eg_cv_mnal_ms3": N + "被切片的机械鸣门叠起来了。",
        "eg_cv_mnal_w": N + "总之，好像赢了。",
        # --- 绿锤 ---
        "eg_cv_166_d": G + "绿锤正是沙袋状态！",
        "eg_cv_166_l": G + "手也脚也伸不出，说的就是这！",
        "eg_cv_166_ms1#0": G + "可因为是合体形状，",
        "eg_cv_166_ms1#1": "没法用绿锤！",
        "eg_cv_166_ms2#0": G + "可因为是合体形状，",
        "eg_cv_166_ms2#1": "没法用绿火箭筒！",
        "eg_cv_166_ms3#0": G + "可因为还没合体，",
        "eg_cv_166_ms3#1": "没法用半熟初英雄收使容！",
        "eg_cv_166_vo1": G + "接招。绿锤——。",
        "eg_cv_166_vo2": G + "用绿火箭筒能回。。",
        "eg_cv_166_vo3#0": G + "巨大机器人必杀回转、砸碎大地的终章大作。",
        "eg_cv_166_vo3#1": "半熟初英雄收使容——。。",
        "eg_cv_166_w#0": G + "只靠右脚就赢了。？",
        "eg_cv_166_w#1": "有志者事竟成。",
        "eg_cv_166_ap#0": "持消」小知O大·负道君（23）的设计。",
        "eg_cv_166_ap#1": "绿锤！。。",
        # --- 罗宋汤 ---
        "eg_cv_borc_d": B + "瘪哦。罗宋汤瘪进去了。。。",
        "eg_cv_borc_l#0": B + "讨厌，说了只是吃罗宋汤",
        "eg_cv_borc_l#1": "啊！嗯！",
        "eg_cv_borc_ms1#0": B + "酱，这冲鼻的香",
        "eg_cv_borc_ms1#1": "把食欲刺激了。。",
        "eg_cv_borc_ms11#0": B + "酱，这冲鼻的香",
        "eg_cv_borc_ms11#1": "把食欲刺激了。。",
        "eg_cv_borc_ms2#0": B + "超辣咖喱那香喷喷的香",
        "eg_cv_borc_ms2#1": "把食欲刺激了。。",
        "eg_cv_borc_ms21#0": B + "超辣咖喱那香喷喷的香",
        "eg_cv_borc_ms21#1": "把食欲刺激了。。",
        "eg_cv_borc_ms3#0": B + "空气精华协潜的汤里慢慢炖的白，",
        "eg_cv_borc_ms3#1": "把兴奋中枢刺激——。。",
        "eg_cv_borc_ms31#0": B + "空气精华协潜的汤里慢慢炖的白，",
        "eg_cv_borc_ms31#1": "把兴奋中枢刺激——。。",
        "eg_cv_borc_w": B + "俺的罗宋汤！再多吃点啊。",
        # --- 木头球 ---
        "eg_cv_wood_d": W + "木头球落下来了。。",
        "eg_cv_wood_l": W + "好想爆开啊！",
        "eg_cv_wood_ms1#0": W + "木头球破裂，",
        "eg_cv_wood_ms1#1": "激烈的什么飞了出来。",
        "eg_cv_wood_ms2#0": W + "木头球炸裂，舒服的什么飞出来",
        "eg_cv_wood_ms21": W + "被干掉的将军们也回来了。。",
        "eg_cv_wood_ms22#0": W + "被干掉的将军们也回来了。",
        "eg_cv_wood_ms22#1": "坏掉的蛋也复活了。。",
        "eg_cv_wood_ms2_a#0": W + "木头球炸裂，舒服的什么飞出来",
        "eg_cv_wood_ms2_a#1": "全部完全反转了。",
        "eg_cv_wood_ms3#0": W + "木头球爆裂，",
        "eg_cv_wood_ms3#1": "激烈的什么狠狠飞了出来。。",
        "eg_cv_wood_vo1": W + "破裂定妆。",
        "eg_cv_wood_vo2": W + "炸裂定妆。",
        "eg_cv_wood_vo3": W + "爆裂定妆。。。",
        "eg_cv_wood_w": W + "木头球定妆。。",
        # --- 加农姐妹 ---
        "eg_cv_cann_d": C + "加农姐妹对没主题的气役打已经厌烦了。",
        "eg_cv_cann_l1#0": M1 + "我们居然！",
        "eg_cv_cann_l1#1": "二号：败北什么的！",
        "eg_cv_cann_ms1#0": C + "从一号的豪华身材里",
        "eg_cv_cann_ms1#1": "爆发96来加农殿把光射了出去。",
        "eg_cv_cann_ms2#0": C + "从二号的动感身材里",
        "eg_cv_cann_ms2#1": "爆发98来加农殿把光射了出去。",
        "eg_cv_cann_ms3#0": C + "一号和二号指定播放的特摄。",
        "eg_cv_cann_ms3#1": "炸药性感射击回复。。",
        "eg_cv_cann_vo1": M1 + "这里交给我。",
        "eg_cv_cann_vo2": M2 + "这次是我的攻击。",
        "eg_cv_cann_vo31": M1 + "二号。组合攻击哦。",
        "eg_cv_cann_vo32": M2 + "了解，一号。",
        "eg_cv_cann_vo33": C + "一号了二号豪华加农。咻。。",
        "eg_cv_cann_w": M1 + "紫外线对皮肤不好！",
        # --- 机械不动猿 ---
        "eg_cv_mugo_d#0": U + "打了也不动的样子。",
        "eg_cv_mugo_d#1": "变成机械后可能打不疼。",
        "eg_cv_mugo_l": U + "咱死也不动啊。？",
        "eg_cv_mugo_ms1": U + "正发呆。",
        "eg_cv_mugo_ms11": "机械不动猿脸上漏出了笑。",
        "eg_cv_mugo_ms2": U + "觉得是个可怜的家伙。",
        "eg_cv_mugo_ms21": U + "觉得是这家伙就好了。",
        "eg_cv_mugo_ms3": U + "用少见的表情点了头！",
        "eg_cv_mugo_ms31": U + "理解了。。",
        "eg_cv_mugo_vo1": U + "咱不动！",
        "eg_cv_mugo_vo2": U + "吵死了总之不动！",
        "eg_cv_mugo_vo3": U + "哼。咱不管！",
        "eg_cv_mugo_w": U + "不动如山！",
        # --- 机器人捕快 ---
        "eg_cv_heij_d": H + "大哥的护身符晃悠悠要掉。",
        "eg_cv_heij_l": H + "哦、哦江户的和平是！",
        "eg_cv_heij_ms1": H + "机器人捕快伏特拉格失败，受到30点伤害。",
        "eg_cv_heij_ms2": H + "机器人捕快把犯人追紧了。",
        "eg_cv_heij_ms31#0": H + "伟大的中逃母亲出现，",
        "eg_cv_heij_ms31#1": "大气里】飞出去。。",
        "eg_cv_heij_ms32": H + "机器人捕快勇气涌上来了。",
        "eg_cv_heij_vo1": H + "他妈的。就这也能接着啊。",
        "eg_cv_heij_vo2": H + "造军。造军啊。情【啊。",
        "eg_cv_heij_vo3": H + "母亲啊。。咱是咱啊！",
        "eg_cv_heij_w": H + "赢了。。",
        # --- 机体骑士 ---
        "eg_cv_mkni_d": K + "机体骑士漏油了。",
        "eg_cv_mkni_l": K + "动啊。动起来。机体骑士。。",
        "eg_cv_mkni_ms1": K + "加速拳把人打飞了。",
        "eg_cv_mkni_ms11": K + "加速拳把人打飞了。",
        "eg_cv_mkni_ms2": K + "从机体骑士里，小机体骑士冲撞了过来。",
        "eg_cv_mkni_ms3#0": K + "机体骑士为了守护世界的和平，",
        "eg_cv_mkni_ms3#1": "让地的任爆发了！",
        "eg_cv_mkni_vo1": K + "加速拳————。。。",
        "eg_cv_mkni_vo2": K + "求你了。机体骑士。。",
        "eg_cv_mkni_vo3": K + "吃下。原子爆发————。。",
        "eg_cv_mkni_w": K + "到底是爷爷的机体骑士啊。",
        # --- 铁人8号 ---
        "eg_cv_tetu_d": T + "铁人8号巨大的大炮飞走了！",
        "eg_cv_tetu_l#0": T + "十万年的",
        "eg_cv_tetu_l#1": "空白好难受呀！",
        "eg_cv_tetu_ms1": T + "是用解的导弹，好歹发射出去了！",
        "eg_cv_tetu_ms2": T + "铁人8号眼里看着的力量被引出来了！",
        "eg_cv_tetu_ms3": T + "铁人8号自己按了开关！",
        "eg_cv_tetu_vo1": T + "是导弹呀！",
        "eg_cv_tetu_vo2": T + "一直在充电呀！",
        "eg_cv_tetu_vo3#0": T + "啊、啊、要按下去了呀",
        "eg_cv_tetu_vo3#1": "按一下！",
        "eg_cv_tetu_w": T + "我回来了呀！",
        # --- 屋台达 ---
        "eg_cv_yata_d": Y + "十夜盖饭叮铃铃响着。",
        "eg_cv_yata_l": Y + "我、我的事小——。？",
        "eg_cv_yata_ms1": Y + "从屋台达的烟囱里，中逃的殿】被引出来了。。",
        "eg_cv_yata_ms2": Y + "事小的椅子飞出去了。",
        "eg_cv_yata_ms31": Y + "你说了你没合体。",
        "eg_cv_yata_ms32#0": Y + "把消临说成合体的屋台达",
        "eg_cv_yata_ms32#1": "难为情，放出了自暴自弃光环。",
        "eg_cv_yata_vo1": Y + "屋台达。烟囱加农。",
        "eg_cv_yata_vo2": Y + "屋台达。椅子导弹射。。",
        "eg_cv_yata_vo3": Y + "天神合体。。屋台达。",
        "eg_cv_yata_w": Y + "俺的和平，由这屋台达来守护。",
    }
