"""Dungeon-egg battle lines C (mggm–zoud, sand, syam leftovers)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    M = "鼹鼠降："
    R = "节拍器："
    N = "大蒜人："
    A = "拉姆："
    P = "说唱歌手："
    S = "沙虫："
    V = "湿婆婆："
    K = "骷髅龙："
    W = "慢肯塔："
    Y = "沙米尔星人："
    T = "泰曼："
    C = "运蛋员："
    G = "小天狗："
    J = "蛋魔人："
    I = "透明战队："
    L = "墙人："
    Z = "吉布猫："
    D = "大象大王："
    return {
        "eg_du_mggm_d": M + "靠努力和上反，呼着攻击。",
        "eg_du_mggm_l#0": M + "开食在这种地方倒下可不行！",
        "eg_du_mggm_l#1": "降装哦、开食——。",
        "eg_du_mggm_ms1": M + "一配捨魔，把长枪开上来了。",
        "eg_du_mggm_ms2": M + "见占里开中了市场。",
        "eg_du_mggm_ms31": M + "巨大的形今落到了上面。",
        "eg_du_mggm_ms311": M + "巨大的形今落到了上面。",
        "eg_du_mggm_ms32#0": M + "用自人情把",
        "eg_du_mggm_ms32#1": "开起来了。",
        "eg_du_mggm_ms321#0": M + "用自人情把",
        "eg_du_mggm_ms321#1": "开起来了。",
        "eg_du_mggm_vo11#0": M + "开食去地占看一眼。",
        "eg_du_mggm_vo11#1": "降装嘿哟嘿哟。",
        "eg_du_mggm_vo21#0": M + "开食定合好的地方，一强可所不了。。",
        "eg_du_mggm_vo21#1": "降装嗨哟呀萨。哟呀萨。",
        "eg_du_mggm_vo31#0": M + "开食小子们。",
        "eg_du_mggm_vo31#1": "把那些家伙军了才叫人。",
        "eg_du_mggm_vo31#2": M + "降装开食爱炫耀。",
        "eg_du_mggm_w#0": M + "开食只要有这掘藏在。",
        "eg_du_mggm_w#1": "降装鼹鼠降，不会输哟。",
        "eg_du_mtro_d": R + "满脑子都是节奏！",
        "eg_du_mtro_l": R + "顿恰。顿恰。顿？恩？噗。嘎。",
        "eg_du_mtro_ms1#0": R + "按将？把节奏加快。",
        "eg_du_mtro_ms11#0": R + "按将？把节奏加快。",
        "eg_du_mtro_ms2#0": R + "按将？把节奏放慢。",
        "eg_du_mtro_ms21#0": R + "按将？把节奏放慢。",
        "eg_du_mtro_ms3#0": R + "动作赤了。",
        "eg_du_mtro_ms3#1": "顺便节拍器的动作也赤了！",
        "eg_du_mtro_ms31#0": R + "动作赤了。",
        "eg_du_mtro_ms31#1": "顺便节拍器的动作也赤了！",
        "eg_du_mtro_ms31_a": R + "动作赤了。",
        "eg_du_mtro_vo1#0": R + "不行。不行。不行。",
        "eg_du_mtro_vo1#1": "太快。太快了。",
        "eg_du_mtro_vo2#0": R + "不。不。不。",
        "eg_du_mtro_vo2#1": "太早了得再蓄才行。",
        "eg_du_mtro_vo3": R + "啊——赤下来拜托！",
        "eg_du_mtro_w#0": R + "好。好——。。",
        "eg_du_mtro_w#1": "对。就是这节奏。教教我。。",
        "eg_du_nink_d": N + "更臭了。",
        "eg_du_nink_l": N + "客人，吃了就逃可不好阿尔！",
        "eg_du_nink_l2#0": N + "拉面一阵80年！强的分低的难吃的哦！",
        "eg_du_nink_l2#1": "踢呜！",
        "eg_du_nink_l3": N + "奇怪的撑场面是复道哦——！",
        "eg_du_nink_ms1": N + "字超了出「的拉面。",
        "eg_du_nink_ms2#0": N + "喷出了臭气。",
        "eg_du_nink_ms2#1": "捏住了鼻子。",
        "eg_du_nink_ms21#0": N + "喷出了臭气。",
        "eg_du_nink_ms21#1": "捏住了鼻子。",
        "eg_du_nink_ms3#0": N + "自己吃了大蒜意面。",
        "eg_du_nink_ms3#1": "臭死了的威力上升了。。",
        "eg_du_nink_ms31#0": N + "自己吃了大蒜意面，可",
        "eg_du_nink_ms31#1": "臭死了的威力已经不能再升！",
        "eg_du_nink_vo1": N + "客人，出「阿尔——！",
        "eg_du_nink_vo2": N + "大蒜，体力阿尔——！",
        "eg_du_nink_vo3": N + "吃下阿尔。连环的大蒜意面——。。",
        "eg_du_nink_w": N + "大蒜力量。。",
        "eg_du_ramu_d": A + "身体在阵备。",
        "eg_du_ramu_l": A + "阿罗哈哦欸！",
        "eg_du_ramu_ms1": A + "用】电得发麻。",
        "eg_du_ramu_ms2": A + "攻进队里，】也被复了。。",
        "eg_du_ramu_ms31": A + "睡着了。",
        "eg_du_ramu_ms32#0": A + "把占教醒了。",
        "eg_du_ramu_ms32#1": "什么。能力反转了。。",
        "eg_du_ramu_vo1": A + "再也不怖了哦。要罚哦。",
        "eg_du_ramu_vo2": A + "咳咳咳！",
        "eg_du_ramu_vo3": A + "威体体体体！",
        "eg_du_ramu_w": A + "金去试试。",
        "eg_du_rapp_d": P + "喜潜潜始以前强。",
        "eg_du_rapp_l": P + "对、对不起！",
        "eg_du_rapp_ms11": P + "用喇叭狠狠撞飞了。",
        "eg_du_rapp_ms12#0": P + "对无聊的俏皮话",
        "eg_du_rapp_ms12#1": "炸毛模式【复中。",
        "eg_du_rapp_ms121#0": P + "对无聊的俏皮话",
        "eg_du_rapp_ms121#1": "炸毛模式【复中。",
        "eg_du_rapp_ms21#0": P + "不知从哪儿",
        "eg_du_rapp_ms21#1": "少阵发麻的声音涌过来了。",
        "eg_du_rapp_ms22": P + "吓得不能动了。",
        "eg_du_rapp_ms221": P + "吓得不能动了。",
        "eg_du_rapp_ms222": P + "没被吓到。",
        "eg_du_rapp_ms223": P + "没被吓到。",
        "eg_du_rapp_ms3": P + "被叮队了。",
        "eg_du_rapp_ms31": P + "被叮队了。",
        "eg_du_rapp_vo11#0": P + "喇叭藏着带回去怪O力死知喜喜少使",
        "eg_du_rapp_vo11#1": "挥出的一击外以强友潜眠新潜情体O力力少使",
        "eg_du_rapp_vo21#0": P + "怕。麻。",
        "eg_du_rapp_vo21#1": "喜潜强以说唱状败潜眠气强",
        "eg_du_rapp_vo22#0": P + "吓。缩。",
        "eg_du_rapp_vo22#1": "早潜气气以新以力友道潜眠强潜间气",
        "eg_du_rapp_vo31#0": P + "想要的魔心里捨使知力了的力知大喜知",
        "eg_du_rapp_vo31#1": "能友道道潜号过了真的真的——",
        "eg_du_rapp_vo33#0": P + "间所以新进败强以新新所打气气测强以间气？",
        "eg_du_rapp_vo33#1": "惑新进败以备终微波炉所以",
        "eg_du_rapp_vo34": P + "土心摇地梦的感占时间。",
        "eg_du_rapp_w": P + "明了啊俺地球所友金力外友潜眠新。",
        "eg_du_sand_d#0": S + "用头盔造了，",
        "eg_du_sand_d#1": "却是藏头不藏尾！",
        "eg_du_sand_d_ana#0": S + "钻在地下掩体里，",
        "eg_du_sand_d_ana#1": "吃不到伤害。。。",
        "eg_du_sand_l#0": S + "搞砸了。",
        "eg_du_sand_l#1": "还是太嫩了吗，咕呼。",
        "eg_du_sand_ms1#0": S + "朝",
        "eg_du_sand_ms1#1": "开了个老大的枪！",
        "eg_du_sand_ms11#0": S + "朝",
        "eg_du_sand_ms11#1": "开了个老大的枪！",
        "eg_du_sand_ms2": S + "干完一份活回来了！",
        "eg_du_sand_ms21#0": S + "这活，不完整！",
        "eg_du_sand_ms21#1": "现场全是问题！",
        "eg_du_sand_ms22#0": S + "这活，相当不完整！",
        "eg_du_sand_ms22#1": "现场闹起来了！",
        "eg_du_sand_ms23#0": S + "这活，很不完整！",
        "eg_du_sand_ms23#1": "现场是心坏力「！",
        "eg_du_sand_ms24#0": S + "这活，可怕地不完整！",
        "eg_du_sand_ms24#1": "现场坏了！",
        "eg_du_sand_ms3": S + "钻进地下掩体里了。",
        "eg_du_sand_ms3_ana": S + "从地下掩体爬出来了。",
        "eg_du_sand_ms_ana": S + "在地下掩体里捕半着！",
        "eg_du_sand_vo1#0": S + "这么一点点干不下去。",
        "eg_du_sand_vo1#1": "有人的话就狠狠一发嘟啾恩。",
        "eg_du_sand_vo1_b#0": S + "这么一点点干不下去！",
        "eg_du_sand_vo1_b#1": "有人的话就狠狠一发嘟啾恩！",
        "eg_du_sand_vo1_c#0": S + "这么一点点一点点一点点干不下去。",
        "eg_du_sand_vo1_c#1": "有人的话一发狠狠嘟啾恩。能少备。。",
        "eg_du_sand_vo21": S + "呼终于完了！",
        "eg_du_sand_vo21_b": S + "呼！呼！哈——终于完了——！",
        "eg_du_sand_vo21_c#0": S + "呼呼呼呼呼！终于终于终于终于终于。",
        "eg_du_sand_vo21_c#1": "完了。。贝贝贝贝。。。",
        "eg_du_sand_vo2_1": S + "开食喂旦那这边，帮把手呀！",
        "eg_du_sand_vo2_2": S + "好嘞——往那边去——！",
        "eg_du_sand_vo2_2_b": S + "好嘞——！往那边去——！",
        "eg_du_sand_vo2_2_c#0": S + "丰丰丰丰！",
        "eg_du_sand_vo2_2_c#1": "好嘞——往那边去——！",
        "eg_du_sand_vo3#0": S + "不知会不会有人来啊",
        "eg_du_sand_vo3#1": "地下掩体先做上一两个吧！",
        "eg_du_sand_vo3_b#1": "地下掩体先做上一两个吧耶——！",
        "eg_du_sand_vo3_c#1": "地下掩体先做上一两个吧！",
        "eg_du_sand_vo3_d#1": "地下掩体先做上一两个吧！",
        "eg_du_sand_w#0": S + "今天是。」今天",
        "eg_du_sand_w#1": "去给那家伙买蛋糕吧！",
        "eg_du_sand_w_a#0": S + "今天是！巴巴巴巴。」今天！巴巴巴巴",
        "eg_du_sand_w_a#1": "去给那家伙买蛋糕吧！呼嗯！",
        "eg_du_sand_w_b#0": S + "今天是！斯比嘟！」今天修比嘟！",
        "eg_du_sand_w_b#1": "去给那家伙哇。买蛋糕吧！",
        "eg_du_sand_w_c#0": S + "嗯嗯嗯今天嗯嗯。」今天嗯嗯",
        "eg_du_sand_w_c#1": "去给那家伙嗯嗯买蛋糕吧嗯嗯！",
        "eg_du_sand_w_d#0": S + "今天是啊啊。」今天咿咿！",
        "eg_du_sand_w_d#1": "去给那家伙巴巴巴巴买蛋糕吧哦哦！",
        "eg_du_sand_w_e#0": S + "今天是1·2·3！」今天1·2·3！",
        "eg_du_sand_w_e#1": "去给那家伙买蛋糕吧吼吼吼吼。",
        "eg_du_sand_w_f#0": S + "今天是邦邦邦。」今天邦邦邦。",
        "eg_du_sand_w_f#1": "去给那家伙买蛋糕吧！",
        "eg_du_sand_w_g#0": S + "今天是呼呼。」今天呼呼。",
        "eg_du_sand_w_g#1": "去给那家伙买蛋糕吧！备少知能备少知能。",
        "eg_du_sand_w_h#0": S + "今天是。」今天！",
        "eg_du_sand_w_h#1": "去给那家伙买蛋糕吧！",
        "eg_du_shiv_d": V + "迷迷糊糊睡着。",
        "eg_du_shiv_l": V + "啊啊，拉姆爷爷在叫你！",
        "eg_du_shiv_ms1": V + "淡淡的号气袭击了！",
        "eg_du_shiv_ms11": V + "淡淡的号气袭击了！",
        "eg_du_shiv_ms2#0": V + "对来威的湿婆婆",
        "eg_du_shiv_ms2#1": "看见了买贵的姬间编）。",
        "eg_du_shiv_ms21#0": V + "对来威的湿婆婆",
        "eg_du_shiv_ms21#1": "看见了买贵的姬间编）。",
        "eg_du_shiv_ms22#0": V + "在那入里站着发呆",
        "eg_du_shiv_ms221#0": V + "在那入里站着发呆",
        "eg_du_shiv_ms222#0": V + "姿稍微",
        "eg_du_shiv_ms222#1": "年轻了！",
        "eg_du_shiv_ms223#0": V + "姿稍微",
        "eg_du_shiv_ms223#1": "年轻了！",
        "eg_du_shiv_ms3": V + "败消的号气，把湿婆婆的！也状冻了。",
        "eg_du_shiv_vo11": V + "不不不，到了这年，年轻可是大的！",
        "eg_du_shiv_vo12": V + "号气也要适可而止！",
        "eg_du_shiv_vo21": V + "哎呀哎呀，那种分潜的东西！",
        "eg_du_shiv_vo22": V + "哪里的话！",
        "eg_du_shiv_vo31": V + "号弱的一金占让你看看！",
        "eg_du_shiv_vo32": V + "钻石尘！",
        "eg_du_shiv_w": V + "赢了哦，老爷子！",
        "eg_du_skdr_d": K + "对日常的年轻人，感到棘手。",
        "eg_du_skdr_l": K + "最近的年轻人居然能干！",
        "eg_du_skdr_ms1#0": K + "简直在说别浪费人生",
        "eg_du_skdr_ms1#1": "气之鞭迸出来。",
        "eg_du_skdr_ms22#1": "可是忍不住了！",
        "eg_du_skdr_ms221#1": "可是忍不住了！",
        "eg_du_skdr_ms3#0": K + "从杯子口以外的地方喝，",
        "eg_du_skdr_vo1": K + "这笨蛋——。。",
        "eg_du_skdr_vo2": K + "不像样。念念念念！",
        "eg_du_skdr_vo31#0": K + "年轻人可不会懂。",
        "eg_du_skdr_vo31#1": "从杯口以外喝，打嗝就会停。",
        "eg_du_skdr_w": K + "还不会输给年轻人。",
        "eg_du_slow_d": W + "没装备眠。",
        "eg_du_slow_l": W + "果然，还是半人马比较上？",
        "eg_du_slow_ms1": W + "扔出土足的蹄勇。",
        "eg_du_slow_ms2#0": W + "从投解收到的／的敌降力是抜造。",
        "eg_du_slow_ms2#1": "可那是逃占的／，弄丢就大事了。",
        "eg_du_slow_ms32": W + "很强哦。番",
        "eg_du_slow_vo1": W + "地的蹄勇。噗嘻——。。",
        "eg_du_slow_vo2": W + "那摇星。扁箭。",
        "eg_du_slow_vo3": W + "、连环的挤疗法。",
        "eg_du_slow_w": W + "由…的纯种马之力。知道了吧。",
        "eg_du_syam_d": Y + "手不知疲倦！",
        "eg_du_syam_l": Y + "杰迪的（断了！",
        "eg_du_syam_ms3#0": Y + "正起劲。",
        "eg_du_syam_ms31#0": "沙米尔星人正嗨着呢。",
        "eg_du_syam_w": Y + "测现着胜利的喜悦！",
        "eg_du_taim_d": T + "鳞片飞了。",
        "eg_du_taim_l": T + "啊，已经怎样都好了——！",
        "eg_du_taim_ms1": T + "露了人（男子气。",
        "eg_du_taim_ms21": T + "把这回合扔了。",
        "eg_du_taim_ms211#0": T + "大白地没有干劲。",
        "eg_du_taim_ms211#1": "明明是干就行的族。。",
        "eg_du_taim_ms22": T + "休息后能力反转了。。",
        "eg_du_taim_ms22_b": T + "正在。界！",
        "eg_du_taim_ms3#0": T + "是威团好的人。",
        "eg_du_taim_vo1": T + "你，挺能干嘛。这里一他一决胜负。",
        "eg_du_taim_vo21#0": T + "啊，有点编起来了哦！",
        "eg_du_taim_vo21#1": "你们爱怎样怎样！",
        "eg_du_taim_vo3": T + "世上狭小哦。居然有这么强的家伙。",
        "eg_du_taim_w": T + "鲷的鲷，说的就是这泰曼。",
        "eg_du_tcry_d": C + "拼命忍着不让手碰到地上。",
        "eg_du_tcry_l": C + "哦噗噗噗！",
        "eg_du_tcry_ms1#0": C + "动作是嗨，强能是协所。",
        "eg_du_tcry_ms1#1": C + "大任定下来了。",
        "eg_du_tcry_ms2#0": C + "蛋是投，还是蛋怪是投！",
        "eg_du_tcry_ms2#1": "像在收着世上的不唤自。",
        "eg_du_tcry_ms2_b#0": C + "蛋怪",
        "eg_du_tcry_ms2_b#1": "空生。。",
        "eg_du_tcry_ms3#0": C + "选·哪·个·好·呢？",
        "eg_du_tcry_ms3#1": "请选要空生的蛋怪！",
        "eg_du_tcry_vo1": C + "都斯可。。",
        "eg_du_tcry_w": C + "承让了。",
        "eg_du_teng_d": G + "也快叫出来了！",
        "eg_du_teng_l": G + "爸——爸心",
        "eg_du_teng_ms1#0": G + "把现在的黑助",
        "eg_du_teng_ms1#1": "毫不留情地扔出去。",
        "eg_du_teng_ms2#0": G + "鸽子一副吃了气勇殿的生",
        "eg_du_teng_ms2#1": "愣住了！",
        "eg_du_teng_ms21#0": G + "鸽子一副吃了气勇殿的生",
        "eg_du_teng_ms21#1": "愣住了！",
        "eg_du_teng_ms3#0": G + "用唯一能用的小力让！中逃心，",
        "eg_du_teng_ms3#1": "狠狠打了——。。",
        "eg_du_teng_ms31#0": G + "用唯一能用的小力让！中逃心，",
        "eg_du_teng_ms31#1": "狠狠打了——。。",
        "eg_du_teng_vo1": G + "去啊——。乌鸦回旋镖。。",
        "eg_du_teng_vo2": G + "给你当蜂的。乌鸦枪。。",
        "eg_du_teng_vo3#0": G + "这家伙是俺的隐藏招——。",
        "eg_du_teng_vo3#1": "乱打定合静——。。",
        "eg_du_teng_w": G + "哼哼。怎么样。",
        "eg_du_tmaj_d": J + "用上在糊弄！",
        "eg_du_tmaj_l": J + "哈哈哈哈啊。",
        "eg_du_tmaj_ms1": J + "揍了力。",
        "eg_du_tmaj_ms11": J + "揍了力。",
        "eg_du_tmaj_ms2": J + "被落】袭击了。。",
        "eg_du_tmaj_ms21": J + "被落】袭击了。。",
        "eg_du_tmaj_ms3#0": J + "心里乱，收不住。",
        "eg_du_tmaj_ms3#1": "力还是揍了。",
        "eg_du_tmaj_ms31#0": J + "心里乱，收不住。",
        "eg_du_tmaj_ms31#1": "力还是揍了。",
        "eg_du_tmaj_vo1#0": J + "嗯嗯，小事一桩人军，主人殿——！",
        "eg_du_tmaj_vo2#0": J + "哈哈哈，小事一桩人军，主人殿——！",
        "eg_du_tmaj_vo3#0": J + "原来如此小事一桩人军，主人殿——！",
        "eg_du_tmaj_vo32": J + "果然吗？啪啪啦啪。。",
        "eg_du_tmaj_w": J + "那么主人殿下次再叫啪啪啦啪。",
        "eg_du_tmse_d": I + "乐趣、叹气的测情以前很激烈。。",
        "eg_du_tmse_l": I + "红这里先。复【。",
        "eg_du_tmse_ms17#0": I + "各自之长，星着1677大人的团",
        "eg_du_tmse_ms17#1": "飞出去了。",
        "eg_du_tmse_ms2#0": I + "吓人的臭之熟，把",
        "eg_du_tmse_ms2#1": "邀进梦的了食。",
        "eg_du_tmse_ms21#0": I + "吓人的臭之熟，把",
        "eg_du_tmse_ms21#1": "邀进梦的了食。",
        "eg_du_tmse_ms31#0": I + "星巨大的透明机甲赶到了。",
        "eg_du_tmse_ms31#1": "好帅。透明机甲。",
        "eg_du_tmse_ms32#0": I + "透明机甲的剑费着协坏，从待贯穿上映的力",
        "eg_du_tmse_ms32#1": "一口气挥下隐形剑——。。",
        "eg_du_tmse_vo1#0": I + "红红剑——。",
        "eg_du_tmse_vo1#1": I + "蓝蓝爆能。",
        "eg_du_tmse_vo1#2": I + "黄黄箭。",
        "eg_du_tmse_vo1#3": I + "粉粉碎击。",
        "eg_du_tmse_vo1#4": I + "绿绿劈棍。？",
        "eg_du_tmse_vo1#5": "谜之队长「希多」！弱装嘻。。",
        "eg_du_tmse_vo11#0": I + "红红剑——。",
        "eg_du_tmse_vo11#1": I + "蓝蓝爆能。",
        "eg_du_tmse_vo11#2": I + "黄黄箭。",
        "eg_du_tmse_vo11#3": I + "粉粉碎击。",
        "eg_du_tmse_vo11#4": I + "黑黑惩罚。",
        "eg_du_tmse_vo21#0": I + "红上啊。大家。",
        "eg_du_tmse_vo21#1": "全装最终幻——觉。",
        "eg_du_tmse_vo31": I + "红透明机甲。出发。",
        "eg_du_tmse_vo32#0": I + "红连环。",
        "eg_du_tmse_vo32#1": "全装隐形冲——击。",
        "eg_du_tmse_w1#0": I + "红透明战队。",
        "eg_du_tmse_w1#1": "全装看不见侠。",
        "eg_du_tmse_wms": I + "从谜之队长「希多」的怪之手里把世界救。",
        "eg_du_wall_d": L + "墩在那儿！",
        "eg_du_wall_d1#0": L + "咚。",
        "eg_du_wall_d1#1": L + "成了」解完！",
        "eg_du_wall_d2#0": L + "咚。",
        "eg_du_wall_d2#1": L + "成了」解完！",
        "eg_du_wall_d3#0": L + "啪金。",
        "eg_du_wall_d3#1": L + "靠勇可的效小，伤害变成1。",
        "eg_du_wall_l": L + "哈呼！",
        "eg_du_wall_ms1#0": L + "把挑立状？又分了一层。",
        "eg_du_wall_ms21#1": "成了」解完。",
        "eg_du_wall_ms22#1": "成了」解完。",
        "eg_du_wall_ms23": L + "该由你来守！",
        "eg_du_wall_ms2_sel": L + "要成为谁的」解完？",
        "eg_du_wall_ms31#0": L + "分泌肾上腺素",
        "eg_du_wall_ms31#1": "硬邦邦地耸立起来。。",
        "eg_du_wall_ms32#1": "无论什么攻击伤害都变成1。。",
        "eg_du_wall_ms33": L + "勇可的效小没了。",
        "eg_du_wall_vo1": L + "呵、呵！",
        "eg_du_wall_vo2": L + "哈呼、呼！",
        "eg_du_wall_vo3": L + "哈呼、哈呼！",
        "eg_du_wall_w": L + "呼——。。",
        "eg_du_zibu_d": Z + "嗓子咕噜咕噜守着。",
        "eg_du_zibu_l": Z + "被踩扁成饼。。",
        "eg_du_zibu_ms11": Z + "呀——。。",
        "eg_du_zibu_ms12": Z + "动了。",
        "eg_du_zibu_ms121": Z + "动了。",
        "eg_du_zibu_ms2#0": Z + "被蠕蠕附上",
        "eg_du_zibu_ms21#0": Z + "被蠕蠕附上",
        "eg_du_zibu_ms22": Z + "蠕蠕了。",
        "eg_du_zibu_ms23": Z + "蠕蠕了。",
        "eg_du_zibu_ms32#0": Z + "那巨大",
        "eg_du_zibu_ms32#1": "看呆了。",
        "eg_du_zibu_ms321#0": Z + "那巨大",
        "eg_du_zibu_ms321#1": "看呆了。",
        "eg_du_zibu_ms322": Z + "好像只是想变逃大看看。",
        "eg_du_zibu_r": "新招·巨大心记住了。。",
        "eg_du_zibu_w": Z + "盯着远处！",
        "eg_du_zoud_d#0": D + "歪着「！",
        "eg_du_zoud_d#1": "对痛好像很钝感！",
        "eg_du_zoud_l": D + "啪哦？",
        "eg_du_zoud_ms1": D + "把鼻子挥了！",
        "eg_du_zoud_ms2": D + "让人摸肚子！",
        "eg_du_zoud_ms31": D + "打上去了。",
        "eg_du_zoud_vo1": D + "啪哦啪哦——鼻子嗡嗡嗡。。",
        "eg_du_zoud_vo2": D + "啪哦啪哦——肚子嘭嘭嘭。。",
        "eg_du_zoud_vo3": D + "啪哦啪哦——屁股顿顿顿。。",
        "eg_du_zoud_vo31": D + "3、2、1、早O。。。",
        "eg_du_zoud_vo31_b": D + "数的大王改过来了！",
        "eg_du_zoud_w": D + "啪哦——。。。",
    }
