"""Pink-egg battle lines B (otsu–mini)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    O = "损坏酱："
    P = "首席："
    A = "亚马逊："
    Y = "弥生："
    M = "美杜莎："
    U = "兔皮诺："
    J = "梅汁："
    F = "巨型妖精："
    D = "发殿美人："
    S = "天空公主："
    N = "最小人："
    return {
        # --- 损坏酱 ---
        "eg_pk_otsu_d#0": O + "呐损坏酱，痛？不痛？",
        "eg_pk_otsu_d#1": "到底怎样？",
        "eg_pk_otsu_l#0": O + "损坏酱对冲击",
        "eg_pk_otsu_l#1": "好像没怎么当回事！",
        "eg_pk_otsu_ms1#0": O + "兔皮诺是损坏酱的朋友。",
        "eg_pk_otsu_ms1#1": "所以跳舞，让她合起来。",
        "eg_pk_otsu_ms11#0": O + "好。兔皮诺。",
        "eg_pk_otsu_ms11#1": "损坏酱一定可了。",
        "eg_pk_otsu_ms21": O + "损坏酱把自己的姿藏起来了。",
        "eg_pk_otsu_ms23": O + "损坏酱现身了。",
        "eg_pk_otsu_ms24": O + "损坏酱把姿藏着。",
        "eg_pk_otsu_ms31": O + "花100波奇里动费吗？",
        "eg_pk_otsu_ms32": O + "损坏酱向爆炸头13阵靠了。",
        "eg_pk_otsu_ms33#0": O + "损坏酱因为零花钱心疼",
        "eg_pk_otsu_ms33#1": "把阵靠忍住了。",
        "eg_pk_otsu_ms34#0": O + "爆炸头13从上大",
        "eg_pk_otsu_ms34#1": "形击了。。",
        "eg_pk_otsu_ms35#0": O + "爆炸头13从上大",
        "eg_pk_otsu_ms35#1": "形击了。。",
        "eg_pk_otsu_ms36": O + "波奇里不够哦配",
        "eg_pk_otsu_w#0": O + "损坏酱对可的测现的役食",
        "eg_pk_otsu_w#1": "也许并不知道！",
        # --- 首席 ---
        "eg_pk_prim_d": P + "首席不把协编的上放在心上！",
        "eg_pk_prim_l#0": P + "不哭。不哭。",
        "eg_pk_prim_l#1": "直到成为首席女主之前。",
        "eg_pk_prim_ms1": "对着首席核恼的足尖踢定住了。",
        "eg_pk_prim_ms11": "对着首席核恼的足尖踢定住了。",
        "eg_pk_prim_ms2#0": P + "足尖鞋里末号役生着。。",
        "eg_pk_prim_ms2#1": "首席不把欺负当本。",
        "eg_pk_prim_ms21#0": P + "首席的金任里",
        "eg_pk_prim_ms21#1": "姿被时住了！",
        "eg_pk_prim_ms22#0": P + "首席的金任里",
        "eg_pk_prim_ms22#1": "姿被时住了！",
        "eg_pk_prim_ms23#0": P + "首席的金任",
        "eg_pk_prim_ms23#1": "被感姿了！",
        "eg_pk_prim_ms24#0": P + "首席的金任",
        "eg_pk_prim_ms24#1": "被感姿了！",
        "eg_pk_prim_ms3": P + "首席把核恼的负休完了！",
        "eg_pk_prim_vo1": P + "是天鹅湖落",
        "eg_pk_prim_vo2#0": P + "一痛心不心痛。",
        "eg_pk_prim_vo2#1": "才没有痛这种事。。",
        "eg_pk_prim_vo3#0": P + "待备还好吗？上了哟！",
        "eg_pk_prim_vo3#1": "看，一、二、三，一、二、三",
        "eg_pk_prim_w": P + "○役的识是不会来的哦",
        # --- 亚马逊 ---
        "eg_pk_amaz_d": A + "亚马逊好像在合着痛。",
        "eg_pk_amaz_l": A + "是我输了。随你便。",
        "eg_pk_amaz_ms1#0": A + "拔出的火现了「，把白体",
        "eg_pk_amaz_ms1#1": "力复了。",
        "eg_pk_amaz_ms11#0": A + "拔出的火现了「，把白体",
        "eg_pk_amaz_ms11#1": "力复了。",
        "eg_pk_amaz_ms21": A + "终的现把逃气中的状分状起来，把效的挑敲醒。",
        "eg_pk_amaz_ms22": "给白体负了状靠。",
        "eg_pk_amaz_ms221": "给白体负了状靠。",
        "eg_pk_amaz_ms223#0": "把阵白状了起来。",
        "eg_pk_amaz_ms224#0": "把阵白状了起来。",
        "eg_pk_amaz_ms225": "身体状上了。",
        "eg_pk_amaz_ms226": "身体状上了。",
        "eg_pk_amaz_ms3": A + "火着的合新初负，了向死。",
        "eg_pk_amaz_ms31": A + "终和火，把白体世了。",
        "eg_pk_amaz_ms312": A + "终和火，把白体世了。",
        "eg_pk_amaz_vo1": A + "啰嗦。。",
        "eg_pk_amaz_vo2": A + "赶紧役了吧。",
        "eg_pk_amaz_vo3": A + "教回推。",
        "eg_pk_amaz_w": A + "对手谁了呢。",
        # --- 弥生 ---
        "eg_pk_yayo_d": Y + "弥生脚麻得晃了一下。",
        "eg_pk_yayo_l": Y + "承情的土「了！",
        "eg_pk_yayo_ms1": Y + "猛灌了美的茶。。",
        "eg_pk_yayo_ms11": Y + "猛灌了美的茶。。",
        "eg_pk_yayo_ms2": Y + "弥生端出了看起来近的茶点。",
        "eg_pk_yayo_ms21#0": Y + "把造姿团稍微解开，",
        "eg_pk_yayo_ms22#0": Y + "把造姿团稍微解开，",
        "eg_pk_yayo_ms23": Y + "吃得津津有味。",
        "eg_pk_yayo_ms24": Y + "吃得津津有味。",
        "eg_pk_yayo_ms31": Y + "弥生带来的土产，攻是",
        "eg_pk_yayo_ms32": Y + "【】。",
        "eg_pk_yayo_ms33": Y + "分长本本点。。",
        "eg_pk_yayo_ms33_1#0": Y + "分长的活里逃协足。",
        "eg_pk_yayo_ms33_2#0": Y + "分长的活里逃协足。",
        "eg_pk_yayo_ms34": Y + "弥生桑心",
        "eg_pk_yayo_vo1": Y + "好本！",
        "eg_pk_yayo_vo2": Y + "茶点也请用！",
        "eg_pk_yayo_vo3": Y + "不成敬意！",
        "eg_pk_yayo_w": Y + "好现了！",
        # --- 美杜莎 ---
        "eg_pk_meds_d": M + "居然对主事出手。可怕呀。",
        "eg_pk_meds_l": M + "嘁。给我记住。。",
        "eg_pk_meds_ms1": "美杜莎的脸蛋肿起来了。",
        "eg_pk_meds_ms11": "美杜莎的脸蛋肿起来了。",
        "eg_pk_meds_ms2#0": "怕得太过，",
        "eg_pk_meds_ms2#1": "身体教得硬邦邦。",
        "eg_pk_meds_ms21#0": "怕得太过，",
        "eg_pk_meds_ms21#1": "身体教得硬邦邦。",
        "eg_pk_meds_ms22#0": "没想到会那么【",
        "eg_pk_meds_ms22#1": "！",
        "eg_pk_meds_ms23#0": "没想到会那么【",
        "eg_pk_meds_ms23#1": "！",
        "eg_pk_meds_ms3": M + "宠物固体君（蛇）逃逃了。",
        "eg_pk_meds_vo1": M + "就算这样也感来。",
        "eg_pk_meds_vo2": M + "看——见——了呢？",
        "eg_pk_meds_vo3": M + "固体。下手。",
        "eg_pk_meds_w": M + "嫩呢！硬成这样了繰",
        # --- 兔皮诺 ---
        "eg_pk_usap_d": U + "好痛配",
        "eg_pk_usap_l": U + "不————。。",
        "eg_pk_usap_ms1": U + "兔皮诺翻跟头逃复）的。。",
        "eg_pk_usap_ms2": U + "胡萝卜导弹朝置飞去。",
        "eg_pk_usap_ms21": U + "胡萝卜导弹朝置飞去。",
        "eg_pk_usap_ms3#0": U + "转转转转转转！",
        "eg_pk_usap_ms3#1": "兔皮诺把、理合地。了。",
        "eg_pk_usap_ms31#0": U + "转转转转转转！",
        "eg_pk_usap_ms31#1": "兔皮诺把、理合地。了。",
        "eg_pk_usap_ms311": U + "把占。了。",
        "eg_pk_usap_ms312": U + "把占。了。",
        "eg_pk_usap_ms32": U + "好无聊。番",
        "eg_pk_usap_ms322": U + "好无聊。番",
        "eg_pk_usap_vo1": U + "的。。",
        "eg_pk_usap_vo2": U + "的的的——。。",
        "eg_pk_usap_vo3": U + "的的的的的的的的的的！",
        "eg_pk_usap_w": U + "的的的的。。",
        # --- 梅汁 ---
        "eg_pk_miju_d": J + "力的效让平衡失了。",
        "eg_pk_miju_l": J + "要吃的话，放进炖菜里薯！",
        "eg_pk_miju_ms1": J + "梅汁力的食在发晕。。",
        "eg_pk_miju_ms21#0": J + "靠梅汁的骨碌酱",
        "eg_pk_miju_ms21#1": "的防御下降了。。",
        "eg_pk_miju_ms22#0": J + "靠梅汁的骨碌酱",
        "eg_pk_miju_ms22#1": "的防御下降了。。",
        "eg_pk_miju_ms23": J + "梅汁的骨碌酱核恼地定住了。",
        "eg_pk_miju_ms3#0": J + "切片的新土豆",
        "eg_pk_miju_ms3#1": "把对方力嫌了。",
        "eg_pk_miju_ms31#0": J + "切片的新土豆",
        "eg_pk_miju_ms31#1": "把对方力嫌了。",
        "eg_pk_miju_vo1": J + "虽然痛，忍着薯。",
        "eg_pk_miju_vo2": J + "薯薯薯薯薯！",
        "eg_pk_miju_vo3": J + "低热量的，怕着薯！",
        "eg_pk_miju_w": J + "不输给大叔，加油薯。",
        # --- 巨型妖精 ---
        "eg_pk_gtfy_d": F + "鼓着嘴。",
        "eg_pk_gtfy_d1": F + "鼓着嘴。",
        "eg_pk_gtfy_l": F + "操的，停下。。",
        "eg_pk_gtfy_ms1": F + "开心地跳着步。",
        "eg_pk_gtfy_ms11": F + "开心地跳着步。",
        "eg_pk_gtfy_ms2#0": F + "使性子了。",
        "eg_pk_gtfy_ms2#1": "从未有过的强，袭向了休。。",
        "eg_pk_gtfy_ms21#0": F + "使性子了。",
        "eg_pk_gtfy_ms21#1": "从未有过的强，袭向了休。。",
        "eg_pk_gtfy_ms3": F + "从弱当的分，中逃的臀落到地上。。",
        "eg_pk_gtfy_vo1": F + "哼哼哼，天气真好攻",
        "eg_pk_gtfy_vo2": F + "破坏休的惑近配操的，停下。。",
        "eg_pk_gtfy_vo31": F + "再也不原谅了。番",
        "eg_pk_gtfy_vo32": F + "好痛团",
        "eg_pk_gtfy_w": F + "这样休里的食就回来了哟",
        # --- 发殿美人 ---
        "eg_pk_156_d": D + "发殿美人对自己的枪型看得入迷！",
        "eg_pk_156_l": D + "太过分了大家都喜欢的！",
        "eg_pk_156_ms1": D + "发殿美人对气道的气味看得入迷！",
        "eg_pk_156_ms2": D + "发殿美人对怪的动看得入迷！",
        "eg_pk_156_ms3#0": D + "发殿美人对开了的使撤",
        "eg_pk_156_ms3#1": "看得入迷！",
        "eg_pk_156_ms31#0": D + "发殿美人对开了的使撤",
        "eg_pk_156_ms31#1": "看得入迷！",
        "eg_pk_156_vo1": D + "这气道最喜欢！",
        "eg_pk_156_vo2": D + "这动最喜欢！",
        "eg_pk_156_vo3": D + "那使撤最喜欢！",
        "eg_pk_156_w": D + "大家都喜欢！",
        "eg_pk_156_ap#0": "将眠弱早失时早失长负合费君（23岁）的设计。",
        "eg_pk_156_ap#1": "发殿美人！。。",
        # --- 天空公主 ---
        "eg_pk_skyp_d": S + "天空公主中不了自己挨了打。",
        "eg_pk_skyp_l": S + "怎么会，这个我。？",
        "eg_pk_skyp_ms1": S + "天空公主把凝固汽油弹如字一般改了出去。",
        "eg_pk_skyp_ms22": S + "静停不下来了。",
        "eg_pk_skyp_ms221": S + "静停不下来了。",
        "eg_pk_skyp_ms222": S + "静没有攻定。",
        "eg_pk_skyp_ms223": S + "静没有攻定。",
        "eg_pk_skyp_ms22_a#0": S + "和对方",
        "eg_pk_skyp_ms22_a#1": "静停不下来了。",
        "eg_pk_skyp_ms3": S + "不得了的使，给周围带来了安静。",
        "eg_pk_skyp_vo1": S + "嚯嚯嚯嚯。来自本4的礼物哟落",
        "eg_pk_skyp_vo2": S + "来，起来吧。讨激的体们。",
        "eg_pk_skyp_vo3": S + "玩，也差不多该结束了。",
        "eg_pk_skyp_w": S + "日安哟，哦嚯嚯嚯。",
        # --- 最小人 ---
        "eg_pk_mini_d": N + "最小人靠着在抽泣！",
        "eg_pk_mini_l": N + "呀呼嗯。",
        "eg_pk_mini_ms1": N + "最小人打出了最小的攻击！",
        "eg_pk_mini_ms2#0": N + "最小人和对方",
        "eg_pk_mini_ms2#1": "好像想长团起来！",
        "eg_pk_mini_ms21#0": N + "最小人和对方",
        "eg_pk_mini_ms21#1": "好像想长团起来！",
        "eg_pk_mini_ms3": N + "最小人的朋友连上了！",
        "eg_pk_mini_vo1": N + "让你喊呀呼！",
        "eg_pk_mini_vo12": N + "嘿。嘿。呀。嗒。",
        "eg_pk_mini_vo2": N + "初次见面，我是最小人！",
        "eg_pk_mini_vo3": N + "和朋友合体攻击了！",
        "eg_pk_mini_w": N + "好耶赢了。",
    }
