"""Secret-egg battle lines A (buby–ebis)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    U = "泡沫："
    V = "勇气："
    H = "心："
    C = "吉娃娃母占："
    D = "德拉贡："
    R = "龙："
    T = "晴天体马："
    S = "流浪曼波："
    P = "龙宝宝："
    G = "祖父："
    K = "狛犬："
    I = "刺刺猪："
    E = "惠比寿桑："
    return {
        # --- 泡沫 ---
        "eg_we_buby_d": U + "啪唧、啪唧。泡破了好几个！",
        "eg_we_buby_l#0": U + "噗哇！",
        "eg_we_buby_l#1": "一颗肥皂泡飞到不知哪儿去了！",
        "eg_we_buby_ms1#0": U + "泡沫把自己的泡，对着对方鼓了起来。",
        "eg_we_buby_ms1#1": "全部能力下降了10个百分点。。",
        "eg_we_buby_ms11": U + "被泡缠住，啊哇哇了。。",
        "eg_we_buby_ms12": U + "被泡缠住，啊哇哇了。。",
        "eg_we_buby_ms1b#0": U + "泡沫把自己的泡，对着对方鼓了起来。",
        "eg_we_buby_ms1b#1": "全部能力下降了10个百分点。。",
        "eg_we_buby_ms2#0": U + "泡沫把自己的泡，对着同伴们噗噗地鼓。",
        "eg_we_buby_ms2#1": "全部能力下降了10个百分点。。",
        "eg_we_buby_ms21#0": U + "泡沫、、的",
        "eg_we_buby_ms21#1": "攻击·防御分别上升了。。",
        "eg_we_buby_ms22#0": U + "泡沫、、的",
        "eg_we_buby_ms22#1": "攻击·防御分别上升了。。",
        "eg_we_buby_ms23#0": U + "泡沫、的",
        "eg_we_buby_ms23#1": "攻击·防御分别上升了。。",
        "eg_we_buby_ms24#0": U + "泡沫、的",
        "eg_we_buby_ms24#1": "攻击·防御分别上升了。。",
        "eg_we_buby_ms25": U + "泡沫的攻击·防御上升了。。",
        "eg_we_buby_ms3#0": U + "泡沫把自己的泡，对着同伴们沙沙地抹。",
        "eg_we_buby_ms3#1": "全部能力下降了10个百分点。。",
        "eg_we_buby_ms31#0": U + "泡沫、、的",
        "eg_we_buby_ms31#1": "能力分别反转了。。",
        "eg_we_buby_ms32#0": U + "泡沫、、的",
        "eg_we_buby_ms32#1": "能力分别反转了。。",
        "eg_we_buby_ms33#0": U + "泡沫、的",
        "eg_we_buby_ms33#1": "能力分别反转了。。",
        "eg_we_buby_ms34#0": U + "泡沫、的",
        "eg_we_buby_ms34#1": "能力分别反转了。。",
        "eg_we_buby_ms35": U + "泡沫的能力反转了。。",
        "eg_we_buby_vo1": U + "鼓噜噜噜哦——！",
        "eg_we_buby_vo2": U + "噗咕噗咕噗咕噗咕噗咕！",
        "eg_we_buby_vo3": U + "沙哇沙哇沙哇哇啊——！",
        "eg_we_buby_w#0": U + "闪闪杀——！",
        "eg_we_buby_w#1": U + "泡沫在向敌军做事。",
        # --- 勇敢之心 ---
        "eg_we_brav_d": V + "勇气正挺身挡在心前面守着！",
        "eg_we_brav_l#0": V + "勇气力子，俺不行了！",
        "eg_we_brav_l#1": "没有力量的勇气只是空想。",
        "eg_we_brav_ms1": V + "把土紧紧握在手里。",
        "eg_we_brav_ms11": V + "把土紧紧握在手里。",
        "eg_we_brav_ms2": V + "心里扑通扑通紧张起来。",
        "eg_we_brav_ms21": V + "心里扑通扑通紧张起来。",
        "eg_we_brav_ms31": V + "松了一口气！",
        "eg_we_brav_ms32": V + "松了一口气！",
        "eg_we_brav_ms3_4": V + "勇气！",
        "eg_we_brav_r2#1": "新招·守护的勇气记住了。。",
        "eg_we_brav_vo1": V + "空团将咕噜噜噜。。",
        "eg_we_brav_vo1_2#0": H + "呀。野狗啊。勇气救命。。",
        "eg_we_brav_vo1_2#1": "勇气交给俺。危险就往后退。",
        "eg_we_brav_vo1_3#0": V + "来啊。你的对手是俺。",
        "eg_we_brav_vo1_3#1": "连一根手指也不许碰心——。",
        "eg_we_brav_vo2_1#0": H + "呀。不行啊，下不来！",
        "eg_we_brav_vo2_1#1": "这么高的地方，我做不到！",
        "eg_we_brav_vo2_2#0": V + "没事的。心的话做得到。",
        "eg_we_brav_vo2_2#1": "相信俺。",
        "eg_we_brav_vo2_3#0": H + "对啊！我要是不信",
        "eg_we_brav_vo2_3#1": "还有谁会相信勇气！",
        "eg_we_brav_vo2_4": H + "知道了！我上。看着啊勇气！",
        "eg_we_brav_vo3_0": "威布鲁噜噜。叽叽叽咿。。",
        "eg_we_brav_vo3_1#0": H + "呀。车啊。勇气救命。。",
        "eg_we_brav_vo3_1#1": "勇气心——。你逃。",
        "eg_we_brav_vo3_2#0": V + "你逃，活下去。",
        "eg_we_brav_vo3_2#1": "然后，给俺生孩子！",
        "eg_we_brav_vo3_3": H + "难道，是死志？勇气。",
        "eg_we_brav_vo3_5#0": H + "我也留下！想在一起。",
        "eg_we_brav_vo3_5#1": "没有勇气的生活，太无聊了！",
        "eg_we_brav_vo3_6#0": H + "不行？",
        "eg_we_brav_vo3_6#1": "勇气笨蛋！",
        "eg_we_brav_w": H + "勇气好厉害。勇气好帅。",
        # --- 吉娃娃母占 ---
        "eg_we_ciwa_d": C + "吉娃娃母占在抖！",
        "eg_we_ciwa_l": C + "呜——！",
        "eg_we_ciwa_ms1#0": C + "骑上生摩托出动了。",
        "eg_we_ciwa_ms1#1": "拐弯太急，撞上去了。",
        "eg_we_ciwa_ms11#0": C + "骑上生摩托出动了。",
        "eg_we_ciwa_ms11#1": "拐弯太急，撞上去了。",
        "eg_we_ciwa_ms12": C + "把事情解决回来了。。",
        "eg_we_ciwa_ms2#0": C + "把4编4马格南拔枪打了。",
        "eg_we_ciwa_ms2#1": "空枪了。。",
        "eg_we_ciwa_ms21#0": C + "把4编4马格南拔枪打了。",
        "eg_we_ciwa_ms21#1": "那种程度，不值一提。",
        "eg_we_ciwa_ms22#0": C + "把4编4马格南拔枪打了。",
        "eg_we_ciwa_ms22#1": "那种程度，不值一提。",
        "eg_we_ciwa_ms23": C + "的4编4马格南走火了。。",
        "eg_we_ciwa_ms3": C + "用圆圆的眼想让人投降！",
        "eg_we_ciwa_ms31#0": C + "什么。投降成功了。",
        "eg_we_ciwa_ms31#1": "投过来了。。",
        "eg_we_ciwa_ms31_a#0": C + "什么。投降成功了。",
        "eg_we_ciwa_ms31_a#1": "回到蛋里了。。",
        "eg_we_ciwa_ms31_b#0": C + "什么。投降成功了。",
        "eg_we_ciwa_ms31_b#1": "回到蛋里去了。。",
        "eg_we_ciwa_ms32#0": C + "什么。投降成功了。",
        "eg_we_ciwa_ms32#1": "投过来了。。",
        "eg_we_ciwa_ms33": "没有被圆圆的眼骗到。",
        "eg_we_ciwa_ms34": "没有被圆圆的眼骗到。",
        "eg_we_ciwa_vo1#0": C + "什么。？真的？",
        "eg_we_ciwa_vo1#1": "知道了！马上过去。。",
        "eg_we_ciwa_vo2#0": C + "住手。不住手的话",
        "eg_we_ciwa_vo2#1": "俺的马格南可要走火了。。",
        "eg_we_ciwa_vo3#0": C + "别干蠢事。",
        "eg_we_ciwa_vo3#1": "星上的老妈在等着。。",
        "eg_we_ciwa_w": C + "真拿你们没办法。。",
        # --- 德拉贡 ---
        "eg_we_drug_d": R + "龙给德拉贡做了止痛！",
        "eg_we_drug_l": R + "龙，久等了！",
        "eg_we_drug_ms1#0": R + "龙给德拉贡做了处理。",
        "eg_we_drug_ms1#1": "德拉贡痛得跳起来了。。",
        "eg_we_drug_ms11": D + "落下来了。。",
        "eg_we_drug_ms12#0": D + "好耶。德拉贡正在跳，",
        "eg_we_drug_ms12#1": "所以没挨到攻击。。",
        "eg_we_drug_ms13#0": D + "、开。德拉贡正在跳，",
        "eg_we_drug_ms13#1": "所以没能攻击。。",
        "eg_we_drug_ms2": D + "对自己的身体特别在意。",
        "eg_we_drug_ms21": D + "对自己的身体特别在意。",
        "eg_we_drug_ms3": D + "协助了手术。",
        "eg_we_drug_ms31": D + "协助了手术。",
        "eg_we_drug_ms32#0": R + "龙把那手术移植给了德拉贡。",
        "eg_we_drug_ms32_a#0": D + "协助了手术。",
        "eg_we_drug_ms32_a#1": "龙把那手术移植给德拉贡，能力反转了。。",
        "eg_we_drug_ms32_b#0": D + "协助了手术。",
        "eg_we_drug_ms32_b#1": "龙把那手术移植给德拉贡，能力反转了。。",
        "eg_we_drug_vo1#0": R + "龙说是。不痛的哦！",
        "eg_we_drug_vo1#1": "要是痛的话，请说痛！",
        "eg_we_drug_vo12": D + "好——痛——。。。",
        "eg_we_drug_vo2#0": R + "龙来，哼，哦哦，原来如此。",
        "eg_we_drug_vo2#1": "嗯？嗯。？什么。？这、这可不得了。。",
        "eg_we_drug_vo21#0": R + "龙啊咳、咳。大、大势喜哦！",
        "eg_we_drug_vo21#1": "没什么事哦！一并开药给您！",
        "eg_we_drug_vo3": R + "龙请协助手术！",
        "eg_we_drug_w#0": R + "龙我是酒体。",
        "eg_we_drug_w#1": "用！的事，可看不下去。",
        # --- 晴天体马 ---
        "eg_we_teru_d": T + "晴天体马晃来晃去！",
        "eg_we_teru_l": T + "阿姨真昼——？快点下来！",
        "eg_we_teru_ms1": T + "晴天体马为了真昼酱把太阳请出来了。",
        "eg_we_teru_ms11#0": T + "盼着远足的真昼酱",
        "eg_we_teru_ms11#1": "天气变好，好开心。",
        "eg_we_teru_ms12#0": T + "日本来好清爽！",
        "eg_we_teru_ms12#1": "大家的能力反转了。。",
        "eg_we_teru_ms13#0": T + "日本来好清爽！",
        "eg_we_teru_ms13#1": "大家的能力反转了。。",
        "eg_we_teru_ms2#0": T + "变成落的晴天体马",
        "eg_we_teru_ms2#1": "为了真昼酱，让字跑了起来。",
        "eg_we_teru_ms21#0": T + "、动很乐土的真昼酱",
        "eg_we_teru_ms21#1": "、动喜字待中赤了，有点开心！",
        "eg_we_teru_ms22#0": T + "是，",
        "eg_we_teru_ms22#1": "、动喜字待中赤了，好想要。",
        "eg_we_teru_ms23#0": T + "是，",
        "eg_we_teru_ms23#1": "、动喜字待中赤了，好想要。",
        "eg_we_teru_ms3#0": T + "真昼酱没能忘掉逃力的朋友！",
        "eg_we_teru_ms3#1": "感动了，能力反转了。。",
        "eg_we_teru_ms31": T + "真昼酱把晴天体马带走了！",
        "eg_we_teru_ms32#0": T + "真昼酱没能忘掉逃力的朋友！",
        "eg_we_teru_ms32#1": "感动了，能力反转了。。",
        "eg_we_teru_ms32_a": T + "真昼酱把晴天体马带走了！",
        "eg_we_teru_vo2": T,
        "eg_we_teru_vo3#0": T + "阿姨真昼——？在造什么——？",
        "eg_we_teru_vo3#1": "出发的待心哟——。快点来！",
        "eg_we_teru_w": T + "阿姨真昼——？勇气君又来了哟！",
        # --- 流浪曼波 ---
        "eg_we_srma_d": S + "流浪曼波正用捕挑想把场队走！",
        "eg_we_srma_l#0": S + "再见，替我告诉那孩子哟",
        "eg_we_srma_l#1": "拜拜，拜拜，还能再见就好，就是这样！",
        "eg_we_srma_ms1": "一股惆怅袭向了流浪曼波。。",
        "eg_we_srma_ms11": "一股惆怅袭向了流浪曼波。。",
        "eg_we_srma_ms2#0": S + "被鼓起了勇气，",
        "eg_we_srma_ms21#0": S + "被鼓起了勇气，",
        "eg_we_srma_ms22#0": S + "被鼓起了勇气，",
        "eg_we_srma_ms22#1": "下回合能力会反转。。",
        "eg_we_srma_ms23#0": S + "被鼓起了勇气，",
        "eg_we_srma_ms23#1": "下回合能力会反转。。",
        "eg_we_srma_ms24#0": S + "流浪曼波给自己鼓了勇气！",
        "eg_we_srma_ms24#1": "下回合能力会反转。。",
        "eg_we_srma_ms2_sel": S + "给谁鼓勇气？",
        "eg_we_srma_ms2_sel2#0": S,
        "eg_we_srma_ms3": S + "在场上被造了起来。",
        "eg_we_srma_ms31": S + "在场上被造了起来。",
        "eg_we_srma_vo1#0": S + "啊啊在「」里」过的那以哟",
        "eg_we_srma_vo1#1": "你的力啊，还做事着呢哟",
        "eg_we_srma_vo2#0": S + "不看弱，只盯着「看吧哟",
        "eg_we_srma_vo2#1": "啊啊？站着的你的足修力挂上去哟",
        "eg_we_srma_vo3#0": S + "为什么俺为什么俺要流浪啊哟",
        "eg_we_srma_vo3#1": "因为有人啊军了有人啊军了在叫哟",
        "eg_we_srma_w#0": S + "直到找到气的那天哟",
        "eg_we_srma_w#1": "俺会一直流浪下去哟",
        "eg_we_srma_w#2": S + "流浪流浪流浪哟",
        # --- 龙宝宝 ---
        "eg_we_drpp_d": P + "龙宝宝逃进蛋里了！",
        "eg_we_drpp_l": P + "宝宝？宝宝皮？",
        "eg_we_drpp_ms1": P + "龙宝宝喷出刚记住的火！",
        "eg_we_drpp_ms2#0": "对着龙宝宝的护盾喊痛！",
        "eg_we_drpp_ms2#1": "攻击下降了。。",
        "eg_we_drpp_ms21#0": "对着龙宝宝的护盾喊痛！",
        "eg_we_drpp_ms21#1": "攻击下降了。。",
        "eg_we_drpp_ms22#0": "对着龙宝宝的护盾喊痛！",
        "eg_we_drpp_ms22#1": "可是，对方完全不当回事！",
        "eg_we_drpp_ms23#0": "对着龙宝宝的护盾喊痛！",
        "eg_we_drpp_ms23#1": "可是，对方完全不当回事！",
        "eg_we_drpp_ms3": P + "龙宝宝严厉的星状夜攻击！",
        "eg_we_drpp_ms32#0": P + "正为把龙宝宝弄哭而弱！",
        "eg_we_drpp_ms32#1": "攻击上升了。。",
        "eg_we_drpp_ms33#0": P + "正为把龙宝宝弄哭而弱！",
        "eg_we_drpp_ms33#1": "攻击上升了。。",
        "eg_we_drpp_ms34#0": P + "和对方",
        "eg_we_drpp_ms34#1": "被弄哭龙宝宝而弱了。攻击上升了。。",
        "eg_we_drpp_ms35#0": P + "被弄哭龙宝宝而弱了。",
        "eg_we_drpp_ms35_2#0": P + "被弄哭龙宝宝而弱了。",
        "eg_we_drpp_ms36": P + "龙宝宝哭了也没人护着！",
        "eg_we_drpp_vo1": P + "宝宝——姆！",
        "eg_we_drpp_vo2": P + "宝宝皮皮喵——！",
        "eg_we_drpp_vo3": P + "乒呀啊啊——！",
        "eg_we_drpp_w": P + "宝宝皮啊！",
        # --- 祖父 ---
        "eg_we_grap_d1": G + "祖父正在忍痛。",
        "eg_we_grap_d2": G + "祖父暴怒模式的怒气更复了。",
        "eg_we_grap_l1": G + "呼！",
        "eg_we_grap_l2": G + "唔哦哦哦！",
        "eg_we_grap_ms1": G + "祖父用金新柔软的手掌拍上去了！",
        "eg_we_grap_ms2": G + "祖父的怒气爆发了。",
        "eg_we_grap_ms3": G + "祖父翻过去了。",
        "eg_we_grap_ms31": G + "祖父心情还很好。。",
        "eg_we_grap_ms32": G + "祖父暴怒了。。",
        "eg_we_grap_ms33": G + "祖父变回平时的爸爸了。",
        "eg_we_grap_ms34#0": G + "祖父看见了。",
        "eg_we_grap_ms34#1": "祖父的防御上升了。。",
        "eg_we_grap_ms35": G + "孩子们不该看，祖父弱成这样。",
        "eg_we_grap_vo1": G + "呵呵呵呵呵呵攻",
        "eg_we_grap_vo2": G + "咕哦咕哦咕哦——。。",
        "eg_we_grap_vo31": G + "还早着呐！",
        "eg_we_grap_vo32": G + "终于把俺惹怒了啊。。",
        "eg_we_grap_vo33": G + "呼，气顺了！",
        "eg_we_grap_vo34": G + "忍着忍着！",
        "eg_we_grap_vo35": G + "喂。到地占来。。",
        "eg_we_grap_w1": G + "呵呵呵呵！",
        "eg_we_grap_w2": G + "愚蠢的家伙。番",
        # --- 狛犬 ---
        "eg_we_kinu_d": K + "啪叽。狛犬的身体裂开了！",
        "eg_we_kinu_l#0": K + "嘎啦嘎啦嘎啦咕隆咚",
        "eg_we_kinu_l#1": "狛犬心坏了！",
        "eg_we_kinu_ms1#0": "牙齿被狛犬咬了。",
        "eg_we_kinu_ms1#1": "这样牙就会变好吧！",
        "eg_we_kinu_ms11#0": "牙齿被狛犬咬了。",
        "eg_we_kinu_ms11#1": "这样牙就会变好吧！",
        "eg_we_kinu_ms12#0": "牙齿被狛犬咬了。",
        "eg_we_kinu_ms12#1": "牙居然变好了。精神上升了。。",
        "eg_we_kinu_ms13#0": "牙齿被狛犬咬了。",
        "eg_we_kinu_ms13#1": "牙居然变好了。精神上升了。。",
        "eg_we_kinu_ms2#0": "被狛犬吓到，",
        "eg_we_kinu_ms2#1": "一步也动不了了！",
        "eg_we_kinu_ms22#0": "被狛犬吓了一下，",
        "eg_we_kinu_ms22#1": "没什么事！",
        "eg_we_kinu_ms3#0": K + "界的运来了",
        "eg_we_kinu_ms3#1": "两熟一起施下去了。",
        "eg_we_kinu_vo1": K + "啊——嗯！",
        "eg_we_kinu_vo2": K + "啊嗯。？",
        "eg_we_kinu_vo3#0": K + "啊！",
        "eg_we_kinu_vo3#1": "呜——————嗯！",
        "eg_we_kinu_w": K + "狛犬变回摇本弱了！",
        # --- 刺刺猪 ---
        "eg_we_pppm_d": I + "刺刺猪在哼哼地弱！",
        "eg_we_pppm_l#0": I + "噗喵！",
        "eg_we_pppm_l#1": "刺刺猪灰溜溜逃走了！",
        "eg_we_pppm_ms1": I + "鞭子呼啸着飞出来。",
        "eg_we_pppm_ms12#0": I + "鞭子呼啸着飞出来。",
        "eg_we_pppm_ms12#1": "中毒了。。",
        "eg_we_pppm_ms13#0": I + "鞭子呼啸着飞出来。",
        "eg_we_pppm_ms13#1": "中毒了。。",
        "eg_we_pppm_ms2#0": I + "周围",
        "eg_we_pppm_ms2#1": "弥漫着清爽的今香！",
        "eg_we_pppm_ms21#0": I + "周围",
        "eg_we_pppm_ms21#1": "弥漫着清爽的今香！",
        "eg_we_pppm_ms3": I + "刺刺猪也进了金，打扮得漂漂亮亮。",
        "eg_we_pppm_ms31#0": I + "刺刺猪也进了金，打扮得漂漂亮亮。",
        "eg_we_pppm_ms31#1": "看呆了。精神下降了。。",
        "eg_we_pppm_ms32#0": I + "刺刺猪也进了金，打扮得漂漂亮亮。",
        "eg_we_pppm_ms32#1": "看呆了。精神下降了。。",
        "eg_we_pppm_vo1": I + "叭咻噜蹦。。。",
        "eg_we_pppm_vo2": I,
        "eg_we_pppm_vo3": I + "噗嘻嘻噗嘻嘻！",
        "eg_we_pppm_w#0": I + "噗呢。",
        "eg_we_pppm_w#1": "刺刺猪开心地摇着屁股！",
        # --- 惠比寿桑 ---
        "eg_we_ebis_d": E + "惠比寿桑在扮鬼脸！",
        "eg_we_ebis_l#0": E + "好痛痛痛。怪末完蛋了啊。",
        "eg_we_ebis_l#1": "攻占，告辞了！",
        "eg_we_ebis_ms12#0": E + "惠比寿桑用长摸了摸，",
        "eg_we_ebis_ms12#1": "收到了波奇里香火钱！",
        "eg_we_ebis_ms13#0": E + "惠比寿桑用长摸了摸，",
        "eg_we_ebis_ms13#1": "收到了波奇里香火钱！",
        "eg_we_ebis_ms2#0": E + "喜入中爆出最强的一发！",
        "eg_we_ebis_ms2#1": "惠比寿桑也觉得臭！",
        "eg_we_ebis_ms3": E + "闪耀惠比寿锁把喜入夜了起来。。",
        "eg_we_ebis_vo11": E + "怪末好白。",
        "eg_we_ebis_vo12#0": E + "攻况哎呀，其他战场也来静。",
        "eg_we_ebis_vo12#1": "惠比寿桑】雅的姿激。",
        "eg_we_ebis_vo21": E + "啊啊，屁要出来了。",
        "eg_we_ebis_vo21_a": E + "啊。。出来了。。",
        "eg_we_ebis_vo22#0": E + "攻况出来了。双方的初。",
        "eg_we_ebis_vo22#1": "这边好像也闻到了。",
        "eg_we_ebis_vo31": E + "长繰移战生外。闪耀惠比寿锁。",
        "eg_we_ebis_vo32#0": E + "攻况出来了。惠比寿桑的终结技。",
        "eg_we_ebis_vo32#1": "这下有效。",
        "eg_we_ebis_w": E + "好。这样怪末就好白了啊。。",
    }
