"""Colorful-egg battle lines B (hade–piku)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    H = "派手斯："
    B = "创可贴："
    K = "鸡："
    Y = "欲："
    N = "鸣门："
    A = "唉王："
    E = "艾格史莱姆："
    O = "站立蝌蚪："
    M = "艾格曼："
    F = "飞锅："
    J = "柔道家："
    U = "不动猿："
    C = "大叔泡饭："
    P = "皮克索："
    return {
        # --- 派手斯 ---
        "eg_cl_hade_d": H + "派手斯在换笑话段子。",
        "eg_cl_hade_l": H + "说冷笑话的是谁！",
        "eg_cl_hade_ms1": H + "在帮腔吗？",
        "eg_cl_hade_ms12": H + "逃【上被敲醒了。看来是戳中了攻",
        "eg_cl_hade_ms2": H + "不行！完全没笑配",
        "eg_cl_hade_ms22": H + "逃【上被敲醒了。看来是戳中了攻",
        "eg_cl_hade_ms3#0": H + "派手斯自己想到的事，实在",
        "eg_cl_hade_ms3#1": "有趣，自己乐着。。",
        "eg_cl_hade_vo11": H + "秃的斯明",
        "eg_cl_hade_vo12": H + "好强攻",
        "eg_cl_hade_vo13": H + "讨出——集",
        "eg_cl_hade_vo21": H + "舞终箱了。用这舞者。",
        "eg_cl_hade_vo22": H + "核恼的鲽，让开。",
        "eg_cl_hade_vo23#0": H + "那飞所空星休配吧！",
        "eg_cl_hade_vo23#1": "嗯星】配吧！嗯臭配力",
        "eg_cl_hade_vo24": H + "我家盖好了。耶。",
        "eg_cl_hade_vo25": H + "看那占，事上没有！讨厌！",
        "eg_cl_hade_vo26": H + "这酒，是我啊。",
        "eg_cl_hade_vo27": H + "这乌贼墨。真乌贼。",
        "eg_cl_hade_w": H + "后面请慢用！",
        # --- 创可贴 ---
        "eg_cl_106_d": B + "创可贴的黏有点怕了！",
        "eg_cl_106_l": B + "创可贴已经没……知的力了！",
        "eg_cl_106_ms1#0": B + "创可贴把占堵住了！",
        "eg_cl_106_ms1#1": "「看不见了，速度下降了。。",
        "eg_cl_106_ms11#0": B + "创可贴把占堵住了！",
        "eg_cl_106_ms11#1": "「看不见了，速度下降了。。",
        "eg_cl_106_ms2": B + "创可贴把对方撕了下来！",
        "eg_cl_106_ms21": B + "创可贴把对方撕了下来！",
        "eg_cl_106_ms3#0": B + "痛啊痛啊飞走吧",
        "eg_cl_106_ms3#1": "不可思议的咒语让能力反转了。。",
        "eg_cl_106_ms3_2#0": B + "痛啊痛啊飞走吧",
        "eg_cl_106_ms3_2#1": "不可思议的咒语让能力反转了。。",
        "eg_cl_106_vo1": B + "无语音",
        "eg_cl_106_vo2": B + "无语音",
        "eg_cl_106_vo3": B + "无语音",
        "eg_cl_106_w#0": B + "创可贴把间初明负输掉的这次靠",
        "eg_cl_106_w#1": "当成骄傲！",
        "eg_cl_106_ap#0": "新星弱筑波欲小空之望酱（25岁）的设计。",
        "eg_cl_106_ap#1": "创可贴！。。",
        # --- 鸡鸡穆乔 ---
        "eg_cl_tiki_d": Y + "欲的讨状，越来越友嫌心。",
        "eg_cl_tiki_l#0": Y + "欲直到现在还乐十着呢！",
        "eg_cl_tiki_l#1": "把界占打开。欲桑啊啊啊啊。。",
        "eg_cl_tiki_ms1#0": Y + "欲好臭的温柔界！",
        "eg_cl_tiki_ms1#1": "那姿让能力稍微反转了。",
        "eg_cl_tiki_ms2#0": K + "界用力拉板车。",
        "eg_cl_tiki_ms2#1": "控、控制不住！",
        "eg_cl_tiki_ms32#0": K + "细看，欲在呼呼大睡。",
        "eg_cl_tiki_ms32#1": "真是调皮的欲桑！",
        "eg_cl_tiki_vo11#0": K + "欲桑，来吃！",
        "eg_cl_tiki_vo11#1": "欲老是对不起！",
        "eg_cl_tiki_vo11#2": K + "那不是不能说的用坏吗？",
        "eg_cl_tiki_vo21#0": K + "欲桑要逃了。）·一般。",
        "eg_cl_tiki_vo21#1": "欲俺们是鸟！",
        "eg_cl_tiki_vo31#0": Y + "欲俺已经不行了！",
        "eg_cl_tiki_vo31#1": "界欲桑？欲桑啊啊啊啊。。",
        "eg_cl_tiki_w#0": Y + "欲俺们明了吗？",
        "eg_cl_tiki_w#1": "界对啊。我们的欲界气明了。。",
        # --- 鸣门 ---
        "eg_cl_nalt_d#0": N + "痛或不痛说不清。",
        "eg_cl_nalt_d#1": "用人事来说，就是金合不大。",
        "eg_cl_nalt_l": N + "怎么说呢，好像输了！",
        "eg_cl_nalt_ms1#0": N + "忍不住用脸去蹭。",
        "eg_cl_nalt_ms1#1": "蹭蹭蹭！",
        "eg_cl_nalt_ms11#0": N + "忍不住用脸去蹭。",
        "eg_cl_nalt_ms11#1": "蹭蹭蹭！",
        "eg_cl_nalt_ms12": N + "鸣门）·地黏黏糊糊。",
        "eg_cl_nalt_ms2": N + "看见了鸣门的里面。",
        "eg_cl_nalt_ms21": N + "看见了鸣门的里面。",
        "eg_cl_nalt_ms22#0": N + "把占。了。",
        "eg_cl_nalt_ms221#0": N + "把占。了。",
        "eg_cl_nalt_ms23": N + "不是蜻蜓。",
        "eg_cl_nalt_ms231": N + "不是蜻蜓。",
        "eg_cl_nalt_ms3": N + "被切片的鸣门箱了。",
        "eg_cl_nalt_w": N + "总之，好像明了。心",
        # --- 唉王 ---
        "eg_cl_azen_d": A + "唉王的下巴眼看要·。",
        "eg_cl_azen_l": A + "。",
        "eg_cl_azen_ms1": A + "唉王唉了一下。",
        "eg_cl_azen_ms11#0": A + "把挨过的伤害复世",
        "eg_cl_azen_ms11#1": "发动了唉王特攻。",
        "eg_cl_azen_ms2": A + "唉王更唉了。",
        "eg_cl_azen_ms21#0": A + "把挨过的伤害复世",
        "eg_cl_azen_ms21#1": "发动了唉风暴。",
        "eg_cl_azen_ms3": A + "唉王的唉电压被连力了。",
        "eg_cl_azen_ms31": A + "唉王果然还是唉。",
        "eg_cl_azen_vo1": A + "。",
        "eg_cl_azen_vo2": A + "。",
        "eg_cl_azen_vo3": A + "。。。",
        "eg_cl_azen_vo31": A + "唔嘎啊啊啊——。。",
        "eg_cl_azen_w": A + "。",
        # --- 艾格史莱姆 ---
        "eg_cl_egsl_d": E + "艾格史莱姆的飞」眼看要破！",
        "eg_cl_egsl_l": E + "艾格史莱姆被干掉了。",
        "eg_cl_egsl_ms1#0": "在艾格史莱姆周围",
        "eg_cl_egsl_ms1#1": "艾格史莱姆变得黏糊糊！",
        "eg_cl_egsl_ms11#0": "在艾格史莱姆周围",
        "eg_cl_egsl_ms11#1": "艾格史莱姆变得黏糊糊！",
        "eg_cl_egsl_ms12#0": E + "变得黏糊糊，",
        "eg_cl_egsl_ms121#0": E + "变得黏糊糊，",
        "eg_cl_egsl_ms2#0": "朝着艾格史莱姆",
        "eg_cl_egsl_ms2#1": "艾格史莱姆变得稀烂！",
        "eg_cl_egsl_ms21#0": "朝着艾格史莱姆",
        "eg_cl_egsl_ms21#1": "艾格史莱姆变得稀烂！",
        "eg_cl_egsl_ms3#0": E + "艾格史莱姆」着变得热乎乎。",
        "eg_cl_egsl_w": E + "艾格史莱姆在战斗里明了。",
        # --- 站立蝌蚪 ---
        "eg_cl_otam_d": O + "站立蝌蚪在抖。。",
        "eg_cl_otam_l": O + "站立蝌蚪效眠了！",
        "eg_cl_otam_ms1#0": O + "嘴巴一张一合",
        "eg_cl_otam_ms1#1": "把／人狠狠咬了。",
        "eg_cl_otam_ms11#0": O + "嘴巴一张一合",
        "eg_cl_otam_ms11#1": "把／人狠狠咬了。",
        "eg_cl_otam_ms2": O + "站立蝌蚪跳进了地编。",
        "eg_cl_otam_ms31": O + "站立蝌蚪消？成坐着的蛙了。。",
        "eg_cl_otam_ms32#0": O + "坐着的蛙蹦蹦跳跳",
        "eg_cl_otam_ms32#1": "在招惹对方。",
        "eg_cl_otam_ms321#0": O + "坐着的蛙蹦蹦跳跳",
        "eg_cl_otam_ms321#1": "在招惹对方。",
        "eg_cl_otam_ms33": O + "坐着的蛙消？回站立蝌蚪了。。",
        "eg_cl_otam_w": O + "站立蝌蚪好像在明着得意。",
        # --- 艾格曼 ---
        "eg_cl_eggm_d#0": M + "啪唧。",
        "eg_cl_eggm_d#1": "艾格曼的身体裂了缝。",
        "eg_cl_eggm_l": M + "地居然会败。",
        "eg_cl_eggm_ms1": M + "把当状淌下来了！",
        "eg_cl_eggm_ms11": M + "把当状淌下来了！",
        "eg_cl_eggm_ms2": M + "可是，对对方，不痛！",
        "eg_cl_eggm_ms21": M + "可是，对对方，不痛！",
        "eg_cl_eggm_ms3": M + "艾格曼连同艾格龙号一起终役了！",
        "eg_cl_eggm_vo1": M + "蛋拳。。",
        "eg_cl_eggm_vo2": M + "蛋踢。。",
        "eg_cl_eggm_vo3": M + "所上。艾格龙号。",
        "eg_cl_eggm_w#0": M + "藏在姿里的地之火，",
        "eg_cl_eggm_w#1": "在蛋的中」里梦着消失。",
        # --- 飞锅 ---
        "eg_cl_flyp_d": F + "嘎啦。飞锅落讨了！",
        "eg_cl_flyp_l": F + "输了呀斯？",
        "eg_cl_flyp_ms1": "被飞锅的终捨了。",
        "eg_cl_flyp_ms11": "被飞锅的终捨了。",
        "eg_cl_flyp_ms2": "被飞锅的测捨了。",
        "eg_cl_flyp_ms21": "被飞锅的测捨了。",
        "eg_cl_flyp_ms3": "被飞锅其他地捨了。",
        "eg_cl_flyp_ms31": "被飞锅其他地捨了。",
        "eg_cl_flyp_vo1": F + "脑门呀斯！",
        "eg_cl_flyp_vo2": F + "后背呀斯！",
        "eg_cl_flyp_vo3": F + "痛的地方呀斯！",
        "eg_cl_flyp_w": F + "明了呀斯！",
        # --- 柔道家 ---
        "eg_cl_judo_d": J + "柔道家觉得这场也是柔道！",
        "eg_cl_judo_l": J + "师傅。？原来是师傅",
        "eg_cl_judo_ms1#0": J + "柔道家打出了手刀。",
        "eg_cl_judo_ms1#1": "漂亮的手刀。。",
        "eg_cl_judo_ms2#0": J + "柔道家打出了踢。",
        "eg_cl_judo_ms2#1": "漂亮的踢。。",
        "eg_cl_judo_ms3#0": J + "柔道家打出了一切招。",
        "eg_cl_judo_ms3#1": "可是全大心白着心",
        "eg_cl_judo_vo1": J + "肋骨能带走几根？",
        "eg_cl_judo_vo2": J + "这招能埋熊吗？",
        "eg_cl_judo_vo3": J + "能拿到金牌吗？",
        "eg_cl_judo_w": J + "拳头是万国共通的",
        # --- 不动猿 ---
        "eg_cl_ugok_d": U + "就算痛也不动。",
        "eg_cl_ugok_l": U + "吾死也不动。啊。？",
        "eg_cl_ugok_ms1": U + "在唉着。",
        "eg_cl_ugok_ms11": "从上边漏出了上。",
        "eg_cl_ugok_ms2": U + "觉得是消的家伙。",
        "eg_cl_ugok_ms21": U + "觉得这家伙就好。",
        "eg_cl_ugok_ms3": U + "用魔的配测情点了点头！",
        "eg_cl_ugok_ms31": U + "明姿了。。",
        "eg_cl_ugok_vo1": U + "吾不动。",
        "eg_cl_ugok_vo2": U + "吵死了。逃也不动。",
        "eg_cl_ugok_vo3": U + "哼。那种事不知。",
        "eg_cl_ugok_w": U + "不动猿即教。",
        # --- 大叔泡饭 ---
        "eg_cl_otya_d": C + "英的茶稍微洒了。",
        "eg_cl_otya_l": C + "英的客人走大了啊！",
        "eg_cl_otya_ms1": C + "大叔泡饭把滚烫的汤砸上去了。",
        "eg_cl_otya_ms2": C + "大叔泡饭把茶泡了。",
        "eg_cl_otya_ms32": C + "大叔泡饭能力反转了。。",
        "eg_cl_otya_ms33": C + "大叔泡饭把汤汁卡在喉咙里，能力下降。",
        "eg_cl_otya_vo1": C + "嘛，英的泡饭也吃了再走！",
        "eg_cl_otya_vo2": C + "这茶啊，是这么用的！",
        "eg_cl_otya_vo3": C + "稍微，小了点啊！",
        "eg_cl_otya_vo32": C + "咳、咳、咳，谁、谁来，军。",
        "eg_cl_otya_w": C + "成了茶泡饭，我这个人",
        # --- 皮克索 ---
        "eg_cl_piku_d": P + "！",
        "eg_cl_piku_l": P + "！",
        "eg_cl_piku_ms1": P + "皮克索超现实地撞上去了。",
        "eg_cl_piku_ms21": P + "皮克索的测情丝毫没消！",
        "eg_cl_piku_ms22#0": P + "站起来了。",
        "eg_cl_piku_ms22#1": "攻击上升，防御下降了。。",
        "eg_cl_piku_ms221#0": P + "站起来了。",
        "eg_cl_piku_ms221#1": "攻击上升，防御下降了。。",
        "eg_cl_piku_ms3": P + "皮克索在超现实主义里崩飞了。",
        "eg_cl_piku_w": P + "！",
    }
