"""Dungeon-egg battle lines A (109–kure)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    B = "平衡王："
    G = "负金连人："
    T = "打击人："
    Z = "别西卜宝宝："
    O = "勃勃鸟："
    C = "变色龙人："
    H = "猪八戒："
    F = "咖啡节拍："
    N = "一枚硬币："
    D = "爹地："
    return {
        "eg_du_109_d": B + "哎呀呀！就算挨打也能看见占里的你！",
        "eg_du_109_l#0": B + "啊。。",
        "eg_du_109_l#1": B + "有生以来第一次失去平衡！",
        "eg_du_109_ms1#0": B + "在轰动！",
        "eg_du_109_ms1#1": B + "复）生。能力反转了。。",
        "eg_du_109_ms2#0": B + "从分低的降临",
        "eg_du_109_ms2#1": "落下踵踢！",
        "eg_du_109_ms21#0": B + "从分低的降临",
        "eg_du_109_ms21#1": "落下踵踢！",
        "eg_du_109_ms3": B + "休完了星人／的表演！",
        "eg_du_109_vo1": B + "无语音",
        "eg_du_109_vo2": B + "无语音",
        "eg_du_109_vo3": B + "无语音",
        "eg_du_109_w": B + "从败新体们了着的潜上往下看！",
        "eg_du_109_ap#0": "役土种白军欲负。知君（23岁）的设计。",
        "eg_du_109_ap#1": "平衡王！。。",
        "eg_du_119_d": G + "叔叔一激上来了！",
        "eg_du_119_ll#0": G + "人的终叔叔。钻出来了哦。",
        "eg_du_119_ll#1": "咦？叔叔？叔叔——？",
        "eg_du_119_ms1": G + "从金连心里，怪长跳出来吹了怪。",
        "eg_du_119_ms2": G + "从金连心里，怪字跳出来大逃了！",
        "eg_du_119_ms3": G + "奇怪的神明从金连心里探出头来！",
        "eg_du_119_vo1": G + "人的终叔叔。这长要咬上来哦？",
        "eg_du_119_vo1_2": G + "金连叔叔好可爱！",
        "eg_du_119_vo2#0": G + "人的终叔叔。这读字好大啊！",
        "eg_du_119_vo2#1": "真要撑破了哦？",
        "eg_du_119_vo2_2": G + "金连叔叔好可爱！",
        "eg_du_119_vo3#0": G + "人的终叔叔。叔叔。。",
        "eg_du_119_vo3#1": "奇怪的神明出来了哦？",
        "eg_du_119_vo3_2": G + "金连叔叔好可怕！",
        "eg_du_119_w": G + "金连叔叔下一负！",
        "eg_du_119_ap#0": "持消通道立明欲备连死阵君（29岁）的设计。",
        "eg_du_119_ap#1": "负金连人！。。",
        "eg_du_batg_d#0": T + "滚滚滚",
        "eg_du_batg_d#1": "球滚到哪儿去了！",
        "eg_du_batg_l": T + "别姿。联赛才刚开始！",
        "eg_du_batg_ms1#0": T + "全——垒——打。。。",
        "eg_du_batg_ms1#1": "飞到天上去了！",
        "eg_du_batg_ms11#0": T + "全——垒——打。。。",
        "eg_du_batg_ms11#1": "飞到天上去了！",
        "eg_du_batg_ms12#0": T + "球棒",
        "eg_du_batg_ms12#1": "连擦都没擦到！",
        "eg_du_batg_ms13#0": T + "球棒",
        "eg_du_batg_ms13#1": "连擦都没擦到！",
        "eg_du_batg_ms2#0": T + "喜欢从底下往上打！",
        "eg_du_batg_ms2#1": "觉得受不了了！",
        "eg_du_batg_ms21#0": T + "喜欢从底下往上打！",
        "eg_du_batg_ms21#1": "觉得受不了了！",
        "eg_du_batg_ms3": T + "干脆地打出去了！",
        "eg_du_batg_r2#1": "新招·战斗车记住了。。",
        "eg_du_batg_vo1": T + "这明负收下了。打繰了噫——。。",
        "eg_du_batg_vo11#0": T + "攻况哦——。出来了。",
        "eg_du_batg_vo11#1": T + "真繰全垒打啊——。",
        "eg_du_batg_vo2": T + "气定。气定不够啊——。。",
        "eg_du_batg_vo3#0": T + "要变什么的待，想成乐连的待",
        "eg_du_batg_vo3#1": "俺就乘这家伙，战斗车。。",
        "eg_du_batg_w": T + "呼开占早激「降连——挡不住！",
        "eg_du_belz_d#0": Z + "眼看也要叫出来的别西卜宝宝，",
        "eg_du_belz_d#1": "苍蝇和蛆虫在哄着！",
        "eg_du_belz_l#0": Z + "呜欸欸——恩心",
        "eg_du_belz_l#1": "长大了一定打赢给你看。",
        "eg_du_belz_ms12": Z + "一步也动不了！",
        "eg_du_belz_ms13": Z + "一步也动不了！",
        "eg_du_belz_ms2#0": Z + "把亮亮蝇大军",
        "eg_du_belz_ms2#1": "的攻击拜托给它了！",
        "eg_du_belz_ms21#0": Z + "把亮亮蝇大军",
        "eg_du_belz_ms21#1": "的攻击拜托给它了！",
        "eg_du_belz_ms32": Z + "困得不行了！",
        "eg_du_belz_ms33": Z + "困得不行了！",
        "eg_du_belz_vo1": Z + "蛆虫君们——，要上了休！",
        "eg_du_belz_vo2": Z + "亮亮蝇桑，拜托了休！",
        "eg_du_belz_vo3": Z + "采采蝇酱，交给你了休！",
        "eg_du_belz_w": Z + "人家也想早点飞向大空休！",
        "eg_du_bobo_d": O + "啊啊这样简直是使「的挑！",
        "eg_du_bobo_l": O + "啾！",
        "eg_du_bobo_ms1#0": O + "拔下燃白的自己的羽",
        "eg_du_bobo_ms1#1": "扔过去了！",
        "eg_du_bobo_ms11#0": O + "拔下燃白的自己的羽",
        "eg_du_bobo_ms11#1": "扔过去了！",
        "eg_du_bobo_ms2#0": O + "沉浸在不死鸟的心情里试试！",
        "eg_du_bobo_ms2#1": "只要一强，能力变0好像也逃喜势。",
        "eg_du_bobo_ms21#0": O + "可是。",
        "eg_du_bobo_ms21#1": O + "像不死鸟一样复活了！",
        "eg_du_bobo_ms22": O + "不是不死鸟所以没能复活！",
        "eg_du_bobo_ms23": O + "像不死鸟一样复活了！",
        "eg_du_bobo_ms2_b": O + "沉浸在不死鸟的心情里试试！",
        "eg_du_bobo_ms3#0": O + "那股气难受",
        "eg_du_bobo_ms3#1": "忍不住把手合了一下，好热。。",
        "eg_du_bobo_ms31#0": O + "那股气难受",
        "eg_du_bobo_ms31#1": "忍不住把手合了一下，好热。。",
        "eg_du_bobo_vo1": O + "呼呼。",
        "eg_du_bobo_vo1_2": O + "呼呼呼呼呼。",
        "eg_du_bobo_vo1_3": O + "呼呼砰。呼砰。",
        "eg_du_bobo_vo1_4": O + "呼。呼呼呼。",
        "eg_du_bobo_vo2": O + "一基——。。。",
        "eg_du_bobo_vo3": O + "唧唧唧！",
        "eg_du_bobo_w": O + "火——焰——！！。。。",
        "eg_du_caml_d#0": C + "因为是绅士，",
        "eg_du_caml_d#1": "一滴汗也没出！",
        "eg_du_caml_d_a#0": C + "藏着姿的变色龙人，攻击打不中。",
        "eg_du_caml_d_a#1": C + "现出姿来了。。",
        "eg_du_caml_l#0": C + "咕欸。。",
        "eg_du_caml_l#1": C + "把场搞乱力坏了。",
        "eg_du_caml_ms1": C + "把空场当军用来感占了！",
        "eg_du_caml_ms2": C + "钻进镜子里了。",
        "eg_du_caml_ms21": C + "现出姿来了。",
        "eg_du_caml_ms2_a": C + "正钻在镜子里！",
        "eg_du_caml_ms3#0": C + "用舌头荡来荡去，",
        "eg_du_caml_ms3#1": "朝着目标狠狠俯冲。。",
        "eg_du_caml_ms31#0": C + "用舌头荡来荡去，",
        "eg_du_caml_ms31#1": "朝着目标狠狠俯冲。。",
        "eg_du_caml_vo1": C + "来教教你餐桌礼仪！",
        "eg_du_caml_vo2": C + "这才是真正时髦的风格！",
        "eg_du_caml_vo3": C + "绅士的玩，来收情一招！",
        "eg_du_caml_w": C + "小姐，把这胜利献给你！",
        "eg_du_choh_d": H + "肚子咕地守了一声！",
        "eg_du_choh_l": H + "哇——。逃、大备——。。",
        "eg_du_choh_ms1#0": H + "炮把怪打败了。。",
        "eg_du_choh_ms1#1": "变成粉末了！",
        "eg_du_choh_ms11#0": H + "炮把怪打败了。。",
        "eg_du_choh_ms11#1": "变成粉末了！",
        "eg_du_choh_ms2#0": H + "一个劲地在吃饭！",
        "eg_du_choh_ms3": H + "靠熟道」捨把姿役掉了。",
        "eg_du_choh_ms31": H + "现出姿来了！",
        "eg_du_choh_ms31_b": H + "现出姿来了！",
        "eg_du_choh_vo1": H + "人造人间就小看我吗哦哦——。。",
        "eg_du_choh_vo2": H + "别看这样，移谁可是团的！",
        "eg_du_choh_vo3": H + "吃饭行动请交给我哆！",
        "eg_du_choh_w": H + "报告，已攻到本装地所哆！",
        "eg_du_cofe_d": F + "节奏一协赤了！",
        "eg_du_cofe_l#0": F + "咕啵。",
        "eg_du_cofe_l#1": F + "往人里修进了咖啡！",
        "eg_du_cofe_ms1#0": F + "正踩着桑巴的节奏！",
        "eg_du_cofe_ms11#0": F + "正踩着桑巴的节奏！",
        "eg_du_cofe_ms2#0": F + "喝了浓缩咖啡挑立着！",
        "eg_du_cofe_ms21#0": F + "喝了浓缩咖啡挑立着！",
        "eg_du_cofe_ms3#0": F + "热编的泪溢出来！",
        "eg_du_cofe_ms3#1": F + "好像和友超了！",
        "eg_du_cofe_ms31#0": F + "热编的泪溢出来！",
        "eg_du_cofe_ms31#1": F + "好像和友超了！",
        "eg_du_cofe_ms32#0": F + "表情有点嫌！",
        "eg_du_cofe_ms32#1": F + "没能和友超！",
        "eg_du_cofe_ms33#0": F + "表情有点嫌！",
        "eg_du_cofe_ms33#1": F + "没能和友超！",
        "eg_du_cofe_vo1": F + "恰恰集曼波集恰恰集曼波集",
        "eg_du_cofe_vo2": F + "西班牙。",
        "eg_du_cofe_vo3": F + "阿米戈阿米戈。",
        "eg_du_cofe_w": F + "曼波。曼波。。曼波。。。",
        "eg_du_coin_d": N + "硬币瘪了。",
        "eg_du_coin_l": N + "呜恩！",
        "eg_du_coin_ms1": N + "被一枚硬币的山般大分袭击了。",
        "eg_du_coin_ms12": N + "被一枚硬币的山般大分袭击了。",
        "eg_du_coin_ms2": N + "怎么回事。1作看成2作了。。",
        "eg_du_coin_ms21": N + "出来了谁也不说！",
        "eg_du_coin_ms22": N + "出来了谁也不说！",
        "eg_du_coin_ms3#0": N + "中了。「波奇利」开中了。。",
        "eg_du_coin_ms3#1": "了不起啊一枚硬币。。。",
        "eg_du_coin_ms31#0": N + "「波奇利」开中了。",
        "eg_du_coin_ms31#1": "好样的一枚硬币。。",
        "eg_du_coin_ms32#0": N + "谁也没出来",
        "eg_du_coin_ms32#1": "金在核打着哦一枚硬币。",
        "eg_du_coin_vo1": N + "汪汪。",
        "eg_du_coin_vo2": N + "嗷汪。",
        "eg_du_coin_vo3": N + "这儿这儿汪汪。。",
        "eg_du_coin_w": N + "一枚硬币汪。",
        "eg_du_dady_d#0": D + "派手地反应了一下。",
        "eg_du_dady_d#1": "这就是职业的工作。",
        "eg_du_dady_l": D + "把这个情给你冠军腰带。",
        "eg_du_dady_ms1": D + "身体压制激得受不了！",
        "eg_du_dady_ms11": D + "身体压制激得受不了！",
        "eg_du_dady_ms2": D + "软软软软软——",
        "eg_du_dady_ms21": D + "和，用阵白做了喜斗！",
        "eg_du_dady_ms22": D + "和，用阵白做了喜斗！",
        "eg_du_dady_ms3#0": D + "从能里，赌上摔跤的热",
        "eg_du_dady_ms3#1": "像雪崩一样败出来了！",
        "eg_du_dady_vo1": D + "嘿。喂。",
        "eg_du_dady_vo2": D + "要去了哦。笨蛋。。。",
        "eg_du_dady_vo3#0": D + "职业摔跤！（爱）。。。",
        "eg_du_dady_vo3#1": "（爹·地。爹·地。爹·地。爹·地。）",
        "eg_du_dady_w": D + "终结技是唤的活！",
    }
