"""Legend-egg battle lines A (kegg–excv)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    K = "艾格曼王："
    B = "蛋土箱："
    G = "石像鬼："
    H = "凉凉。："
    O = "奥炖："
    F = "最终果冻："
    C = "滚滚虫："
    D = "哈迪斯："
    S = "特卖："
    E = "石中剑："
    return {
        # --- 艾格曼王 ---
        "eg_le_kegg_d": K + "不愧是艾格曼王。一点小事毫不动摇！",
        "eg_le_kegg_l": K + "败了。。",
        "eg_le_kegg_ms1": K + "王者小槌和普通小槌，理由可不一样。",
        "eg_le_kegg_ms2#0": K + "艾格曼王没能加油！",
        "eg_le_kegg_ms2#1": "毕竟是爷爷！",
        "eg_le_kegg_ms21#0": K + "艾格曼王加了油，",
        "eg_le_kegg_ms21#1": "全部威力上升了。。",
        "eg_le_kegg_ms21_b#0": K + "艾格曼王加了油，",
        "eg_le_kegg_ms3#0": "艾格曼王睡着了！",
        "eg_le_kegg_ms3#1": "起床惊吓。也许比平时疼！",
        "eg_le_kegg_ms31": "艾格曼王睡着了！",
        "eg_le_kegg_ms32#0": "艾格曼王睡着了！",
        "eg_le_kegg_ms32#1": "起床惊吓。也许比平时疼！",
        "eg_le_kegg_ms33": "艾格曼王睡着了！",
        "eg_le_kegg_ms3_b#0": "艾格曼王睡着了！",
        "eg_le_kegg_ms3_b#1": "起床惊吓。",
        "eg_le_kegg_ms3_c#0": "艾格曼王睡着了！",
        "eg_le_kegg_ms3_c#1": "起床惊吓。",
        "eg_le_kegg_vo1": K + "王————者小槌————。。",
        "eg_le_kegg_vo2#0": K + "俺要是认真起来",
        "eg_le_kegg_vo2#1": "你们不值一拧。。",
        "eg_le_kegg_vo21": K + "唔嗯嗯嗯嗯嗯。。",
        "eg_le_kegg_vo3#0": K + "超级兴奋",
        "eg_le_kegg_vo3#1": "外延黄金阳光百万",
        "eg_le_kegg_vo3#2": K + "脱氧核糖瑞士虫锗光————束！",
        "eg_le_kegg_w": K + "是蛋怪之长。。",
        # --- 蛋土箱 ---
        "eg_le_177_d": B + "蛋土箱鼓起来了！",
        "eg_le_177_l": B + "噗喵啊啊。。",
        "eg_le_177_ms1": B + "蛋土箱从箱子里放出臭气！",
        "eg_le_177_ms1_2#0": B + "蛋土箱从箱子里放出臭气！",
        "eg_le_177_ms1_3#0": B + "蛋土箱从箱子里放出臭气！",
        "eg_le_177_ms2": B + "蛋土箱的缎带把人勒紧了！",
        "eg_le_177_ms21": B + "蛋土箱的缎带把人勒紧了！",
        "eg_le_177_ms2_2#0": B + "蛋土箱的缎带把人勒紧了！",
        "eg_le_177_ms2_2#1": "动弹不得了！",
        "eg_le_177_ms2_3#0": B + "蛋土箱的缎带把人勒紧了！",
        "eg_le_177_ms2_3#1": "动弹不得了！",
        "eg_le_177_ms3": B + "蛋土箱把人关进箱子里了！",
        "eg_le_177_ms3_2": B + "蛋土箱把人关进箱子里了！",
        "eg_le_177_ms3_3": B + "蛋土箱没法把人关进箱子里！",
        "eg_le_177_ms3_4": B + "蛋土箱没法把人关进箱子里！",
        "eg_le_177_vo1": B + "噗喵！",
        "eg_le_177_vo2": B + "噗噗噗纽喵！",
        "eg_le_177_vo3": B + "噗噗。喵。。",
        "eg_le_177_w": B + "噗喵噗喵。",
        "eg_le_177_ap#0": "合星种十小欲自由一终桑（13）的设计。",
        "eg_le_177_ap#1": "蛋土箱！。。",
        # --- 石像鬼 ---
        "eg_le_grcl_d": G + "石像鬼从屋檐上掉下来了！",
        "eg_le_grcl_l#0": G + "这可对付不了。",
        "eg_le_grcl_l#1": "石像鬼一占入地跳着逃走了！",
        "eg_le_grcl_ms1#0": "对石像鬼蹑手蹑脚靠近，",
        "eg_le_grcl_ms1#1": "挠了一下——。。",
        "eg_le_grcl_ms11#0": "对石像鬼蹑手蹑脚靠近，",
        "eg_le_grcl_ms11#1": "挠了一下——。。",
        "eg_le_grcl_ms2#0": G + "石像鬼石化了！",
        "eg_le_grcl_ms2_a": G + "石像鬼石化了！",
        "eg_le_grcl_ms2_b": G + "石像鬼正在石化！",
        "eg_le_grcl_ms2_c#0": G + "石化了的石像鬼把全部伤害变成了1。。",
        "eg_le_grcl_ms2_c#1": "石像鬼变回来了！",
        "eg_le_grcl_ms3#0": "石像鬼",
        "eg_le_grcl_ms3#1": "在弹簧弯的地方被干掉了。",
        "eg_le_grcl_ms31#0": "石像鬼",
        "eg_le_grcl_ms31#1": "在弹簧弯的地方被干掉了。",
        "eg_le_grcl_vo1": G + "悄悄悄悄！",
        "eg_le_grcl_vo2": G + "不在不在哇！",
        "eg_le_grcl_vo3": G + "蹦蹦！",
        "eg_le_grcl_w": G + "跳。踏。跃。。",
        # --- 凉凉。 ---
        "eg_le_hyak_d": H + "凉凉。的身体在抖抖颤。。",
        "eg_le_hyak_l": H + "赢了啊，米蕾优。",
        "eg_le_hyak_ms1#0": H + "凉凉。",
        "eg_le_hyak_ms1#1": "咔嚓砍了力。",
        "eg_le_hyak_ms12#0": H + "凉凉。",
        "eg_le_hyak_ms12#1": "咔嚓砍了力。",
        "eg_le_hyak_ms22#0": H + "用豆腐角，",
        "eg_le_hyak_ms22#1": "被干掉了。",
        "eg_le_hyak_ms221#0": H + "用豆腐角，",
        "eg_le_hyak_ms221#1": "被干掉了。",
        "eg_le_hyak_ms23": H + "果然豆腐角没能成。",
        "eg_le_hyak_ms32#0": "凉凉。头嗡地疼起来，",
        "eg_le_hyak_ms321#0": "凉凉。头嗡地疼起来，",
        "eg_le_hyak_ms33": "凉凉。毫不客气地吃了。",
        "eg_le_hyak_ms331": "凉凉。毫不客气地吃了。",
        "eg_le_hyak_vo1": H + "殿下不力，你这可要容。",
        "eg_le_hyak_vo2": H + "对你们，这就够了啊。",
        "eg_le_hyak_vo3#0": H + "哇哈哈。。就是这个啊。",
        "eg_le_hyak_vo3#1": "殿的水晶啊。。",
        "eg_le_hyak_w": H + "怎么将也不行的可怕啊。",
        # --- 奥炖 ---
        "eg_le_oden_d": O + "墨稍微漏出来了。",
        "eg_le_oden_l": O + "章鱼啾！",
        "eg_le_oden_ms1": "把奥炖的身体劈开了。",
        "eg_le_oden_ms11": "把奥炖的身体劈开了。",
        "eg_le_oden_ms12#0": "从上连把奥炖吧唧劈开了。。",
        "eg_le_oden_ms12#1": "呀嗬，队勇剑真是劈活绝佳。",
        "eg_le_oden_ms13#0": "从上连把奥炖吧唧劈开了。。",
        "eg_le_oden_ms13#1": "呀嗬，队勇剑真是劈活绝佳。",
        "eg_le_oden_ms2": O + "奥炖用枪咕噜咕噜搅了。",
        "eg_le_oden_ms3#0": O + "奥炖用枪咕噜咕噜搅了。",
        "eg_le_oden_ms3#1": "溺在／合里了！",
        "eg_le_oden_ms31#0": O + "奥炖身体的捕，／上见了。",
        "eg_le_oden_ms32": O + "奥炖怒气爆发，攻击上升了。。",
        "eg_le_oden_ms4#0": O + "奥炖用枪咕噜咕噜搅了。",
        "eg_le_oden_ms4#1": "溺在／合里了！",
        "eg_le_oden_vo1": O + "灾难————————————。。",
        "eg_le_oden_vo2": O + "喏，喏！舒服吧？",
        "eg_le_oden_vo3": O + "热起来了哇。",
        "eg_le_oden_w": O + "啾啾章鱼啊！",
        # --- 最终果冻 ---
        "eg_le_fzer_d": F + "最终果冻像布丁一样颤着！",
        "eg_le_fzer_l": F + "哼，最终的待解结束了吗！",
        "eg_le_fzer_ms1#0": "对最终果冻",
        "eg_le_fzer_ms1#1": "已经厌烦了！",
        "eg_le_fzer_ms11#0": "对最终果冻",
        "eg_le_fzer_ms11#1": "已经厌烦了！",
        "eg_le_fzer_ms2#0": "变成最终果冻的了！",
        "eg_le_fzer_ms21#0": "变成最终果冻的了！",
        "eg_le_fzer_ms21_a": "变成最终果冻的了！",
        "eg_le_fzer_ms2_a": "变成最终果冻的了！",
        "eg_le_fzer_ms3#0": F + "里面一样，好吃2倍。。",
        "eg_le_fzer_ms3#1": "最终果冻的分裂攻击。",
        "eg_le_fzer_vo1#0": F + "喂喂。那是什么択的听法。",
        "eg_le_fzer_vo1#1": F + "明知是殿还要闹事。？",
        "eg_le_fzer_vo2#0": F + "嘿嘿再也不复了——",
        "eg_le_fzer_vo2#1": "你是俺的了——。。",
        "eg_le_fzer_vo3": F + "最终果冻要分裂给你看。",
        "eg_le_fzer_w": F + "切，还不会输给从弱来的家伙。",
        # --- 滚滚虫 ---
        "eg_le_koro_d": C + "滚滚虫要被压扁。。",
        "eg_le_koro_l": C + "咕唧。滚滚虫被压扁了！",
        "eg_le_koro_ms1": C + "滚滚虫滚来滚去撞上了！",
        "eg_le_koro_ms2": C + "滚滚虫从択抽出细丝来了！",
        "eg_le_koro_ms21#0": "被滚滚虫的丝缠住了！",
        "eg_le_koro_ms22#0": "被滚滚虫的丝缠住了！",
        "eg_le_koro_ms3": C + "滚滚虫转生飞走了！",
        "eg_le_koro_ms31#0": "滚滚虫靠合的圣，能力反转。。",
        "eg_le_koro_ms31_b#0": "滚滚虫靠合的圣，将军复活。。",
        "eg_le_koro_ms32#0": "滚滚虫靠合的圣，能力反转。。",
        "eg_le_koro_ms32_b#0": "滚滚虫靠合的圣，将军复活。。",
        "eg_le_koro_ms3_b": C + "滚滚虫转生飞走了！",
        "eg_le_koro_ms3_sel1": C + "把合的圣给谁？",
        "eg_le_koro_ms3_sel2#0": C,
        "eg_le_koro_vo3": C + "哪里有合我口味的男子汉呢？",
        "eg_le_koro_w": C + "滚滚虫活下来了。。",
        # --- 哈迪斯 ---
        "eg_le_hdes_d": D + "哈迪斯觉得无力很稀奇。",
        "eg_le_hdes_d1": D + "哈迪斯觉得无力很稀奇。",
        "eg_le_hdes_l": D + "不、不能信。。殿是合吗。？",
        "eg_le_hdes_ms1": D + "恶魔气场把人包吞了。",
        "eg_le_hdes_ms11": D + "恶魔气场把人包吞了。",
        "eg_le_hdes_ms2": "被哈迪斯的恐怖操住了。",
        "eg_le_hdes_ms21": "被哈迪斯的恐怖操住了。",
        "eg_le_hdes_ms22": "忍住了哈迪斯的恐怖。",
        "eg_le_hdes_ms23": "忍住了哈迪斯的恐怖。",
        "eg_le_hdes_ms3": D + "地狱的火焰把人烧吞了。",
        "eg_le_hdes_ms31": D + "地狱的火焰把人烧吞了。",
        "eg_le_hdes_vo1": D + "死，才是食气的灵魂。",
        "eg_le_hdes_vo2": D + "毁灭，才是操一切之物。",
        "eg_le_hdes_vo3": D + "不知恐惧的体们啊。尝尝我的恐怖吧。",
        "eg_le_hdes_w": D + "绕过恐怖，在死渊边沉睡。",
        # --- 特卖 ---
        "eg_le_sale_d": S + "火还在烧，货还剩着。",
        "eg_le_sale_l": S + "已经卖完了！",
        "eg_le_sale_ms1#0": S + "用核心客定的激安特价，把",
        "eg_le_sale_ms1#1": "防御部下降了。。",
        "eg_le_sale_ms11#0": S + "用核心客定的激安特价，把",
        "eg_le_sale_ms11#1": "防御部下降了。。",
        "eg_le_sale_ms12#0": S + "用核心客定的激安特价，把全体的",
        "eg_le_sale_ms12#1": "防御部下降了。。",
        "eg_le_sale_ms2": S + "被特卖10％连了，能力反转了。。",
        "eg_le_sale_ms21": S + "特卖用便宜认真了。",
        "eg_le_sale_ms3": S + "特卖一声，全是围着特价与的人。",
        "eg_le_sale_vo1": S + "欢迎光临。欢迎光临。欢迎光临。欢迎光临。",
        "eg_le_sale_vo2": S + "的话10％连积分服务中。",
        "eg_le_sale_vo3": S + "喂。这样的话拿走吧强盗。。",
        "eg_le_sale_w": S + "自由可不能便宜卖。",
        # --- 石中剑 ---
        "eg_le_excv_d": E + "石中剑刃崩了。",
        "eg_le_excv_l": E + "传说之剑会败！",
        "eg_le_excv_ms1": "被石中剑真正劈开了。",
        "eg_le_excv_ms11": "被石中剑真正劈开了。",
        "eg_le_excv_ms112": E + "石中剑没能石中一下。",
        "eg_le_excv_ms2": "身和姿都被石中剑劈开了。",
        "eg_le_excv_ms21": "身和姿都被石中剑劈开了。",
        "eg_le_excv_ms3": "岂止被石中剑劈，已经乱七八糟。",
        "eg_le_excv_ms31": "岂止被石中剑劈，已经乱七八糟。",
        "eg_le_excv_ms32": E + "岂止被劈，已经乱七八糟。",
        "eg_le_excv_vo1": E + "石——中剑——。。",
        "eg_le_excv_vo2": E + "正——————宗——。。",
        "eg_le_excv_vo3": E + "绝对灭亡。诸神黄————昏。。",
        "eg_le_excv_w": E + "我的勇者啊。把俺入手吧。",
    }
