"""Evil-egg battle lines B (name–siro)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    N = "鼻涕虫人："
    A = "阿蒙："
    G = "幽灵："
    V = "毒液酱："
    C = "蜡滴："
    D = "死神："
    O = "欧伊汁："
    L = "卢比德："
    Z = "僵尸："
    Y = "停恩："
    M = "木乃伊："
    P = "小恶魔："
    S = "星防卫军："
    return {
        # --- 鼻涕虫人 ---
        "eg_ev_name_d": N + "鼻涕虫人一下子变小了。",
        "eg_ev_name_l": N + "蔫蔫的啪啪啪啪！",
        "eg_ev_name_ms12": N + "拼命把黏糊糊擦掉。",
        "eg_ev_name_ms121": N + "拼命把黏糊糊擦掉。",
        "eg_ev_name_ms13#0": N + "呜嘿，黏糊糊。。",
        "eg_ev_name_ms13#1": "中毒了。。",
        "eg_ev_name_ms131#0": N + "呜嘿，黏糊糊。。",
        "eg_ev_name_ms131#1": "中毒了。。",
        "eg_ev_name_ms21#0": N + "被黏液包住，",
        "eg_ev_name_ms22#0": N + "被黏液包住，",
        "eg_ev_name_ms23": N + "是食气。",
        "eg_ev_name_ms24": N + "是食气。",
        "eg_ev_name_ms31": N + "鼻涕虫人舔了签。",
        "eg_ev_name_ms32": N + "鼻涕虫人的攻击上升了。。",
        "eg_ev_name_ms33": N + "鼻涕虫人的防御下降了。。",
        "eg_ev_name_ms34": N + "鼻涕虫人全部威力上升了。。",
        "eg_ev_name_ms35": N + "鼻涕虫人全部威力下降了。。",
        "eg_ev_name_vo1": N + "啊啊啊。。呸。。",
        "eg_ev_name_vo2": N + "你也要变得黏黏的。",
        "eg_ev_name_vo31": N + "哦。中了。",
        "eg_ev_name_vo32": N + "啧。·了吗。",
        "eg_ev_name_w": N + "别小看俺啊。",
        # --- 阿蒙 ---
        "eg_ev_amon_d": A + "阿蒙浮出上。。",
        "eg_ev_amon_l": A + "只要还有怒火，俺就不灭！",
        "eg_ev_amon_ms1": A + "用商的力，把对方能力时了。",
        "eg_ev_amon_ms11": A + "用商的力，把对方能力时了。",
        "eg_ev_amon_ms12": A + "阿蒙没能把能力敌收。",
        "eg_ev_amon_ms13#0": A + "用商的力，把生！力时了，",
        "eg_ev_amon_ms14#0": A + "用商的力，把生！力时了，",
        "eg_ev_amon_ms2": A + "被映包住。",
        "eg_ev_amon_ms21": A + "被映包住。",
        "eg_ev_amon_ms22": A + "很中意那映。",
        "eg_ev_amon_ms23": A + "很中意那映。",
        "eg_ev_amon_ms24": A + "被映包住中毒了。。",
        "eg_ev_amon_ms25": A + "被映包住中毒了。。",
        "eg_ev_amon_ms3": A + "阿蒙被封印的力解开了。。",
        "eg_ev_amon_vo1": A + "让占成为动、成为白。",
        "eg_ev_amon_vo2": A + "给中熟的人映。",
        "eg_ev_amon_vo3#0": A + "愚蠢的体们",
        "eg_ev_amon_vo3#1": "占竟解开败之力！",
        "eg_ev_amon_w": A + "回地占去吧！",
        # --- 幽灵 ---
        "eg_ev_gost_d": G + "幽灵在喜着造！",
        "eg_ev_gost_l": G + "啾欸欸欸——。。。",
        "eg_ev_gost_ms1": "被尾巴啪啪地打了！",
        "eg_ev_gost_ms11": "被尾巴啪啪地打了！",
        "eg_ev_gost_ms2#0": G + "幽灵体近喜了。。",
        "eg_ev_gost_ms2#1": "吓了一跳！",
        "eg_ev_gost_ms21#0": G + "幽灵体近喜了。。",
        "eg_ev_gost_ms21#1": "吓了一跳！",
        "eg_ev_gost_ms22": G + "幽灵体近喜了。。",
        "eg_ev_gost_ms3#0": "被幽灵的阵袭来了！",
        "eg_ev_gost_ms3#1": "全部威力下降，中毒了，一步也动不了。。",
        "eg_ev_gost_ms31#0": "被幽灵的阵袭来了！",
        "eg_ev_gost_ms31#1": "全部威力下降，麻痹，中毒了。。",
        "eg_ev_gost_ms31_b#0": "被幽灵的阵袭来了！",
        "eg_ev_gost_ms31_b#1": "全部威力下降，中毒了，一步也动不了。。",
        "eg_ev_gost_vo1": G + "啾欸欸欸——。。。",
        "eg_ev_gost_vo2": G + "啾欸欸欸——。。。",
        "eg_ev_gost_vo3": G + "咯欸欸欸——。。。",
        "eg_ev_gost_w": G + "啾欸欸欸——。。。",
        # --- 毒液酱 ---
        "eg_ev_veno_d": V + "毒液酱的能揪了一下。",
        "eg_ev_veno_l": V + "是在「呢！",
        "eg_ev_veno_ms1#0": V + "被这世上星都想不到的死敌",
        "eg_ev_veno_ms1#1": "挨了来击。。",
        "eg_ev_veno_ms12#0": V + "被这世上星都想不到的死敌",
        "eg_ev_veno_ms12#1": "挨了来击。。",
        "eg_ev_veno_ms2": V + "毒液酱以动（／的速度撞了上去。",
        "eg_ev_veno_ms31#0": V + "毒液酱力中，自臭的造反",
        "eg_ev_veno_ms31#1": "总在身边的世界在道着。。",
        "eg_ev_veno_ms31_man#0": V + "毒液酱力中，有",
        "eg_ev_veno_ms31_man#1": "总在身边的世界在道着。。",
        "eg_ev_veno_ms32#0": V + "毒液酱挑立了，攻击上升了。。",
        "eg_ev_veno_ms32#1": "不知为何受到了冲击。",
        "eg_ev_veno_ms322#0": V + "毒液酱挑立了，攻击上升了。。",
        "eg_ev_veno_ms322#1": "不知为何受到了冲击。",
        "eg_ev_veno_vo1": V + "呜扭扭扭——。。",
        "eg_ev_veno_vo2": V + "嘎嘎嘎嘎嘎嘎嘎嘎嘎。。",
        "eg_ev_veno_vo3": V + "咯姆巴巴咕嗯嘎啊啊——。。",
        "eg_ev_veno_w": V + "呣呼！",
        # --- 蜡滴 ---
        "eg_ev_cand_d": C + "蜡软塌塌地垂下来。",
        "eg_ev_cand_l": C + "！的火尽了吗！",
        "eg_ev_cand_ms1": C + "稍微舒服了一点",
        "eg_ev_cand_ms11": C + "稍微舒服了一点",
        "eg_ev_cand_ms21#0": C + "想要得不得了配",
        "eg_ev_cand_ms21#1": "就站在那入里。",
        "eg_ev_cand_ms212#0": C + "想要得不得了配",
        "eg_ev_cand_ms212#1": "就站在那入里。",
        "eg_ev_cand_ms22": C + "明里没有感臭。",
        "eg_ev_cand_ms222": C + "明里没有感臭。",
        "eg_ev_cand_ms3": C + "蜡滴的任哟。变成姿形。。",
        "eg_ev_cand_vo1": C + "给你刺激。",
        "eg_ev_cand_vo2#0": C + "强已经不行了力少用，和野将一起",
        "eg_ev_cand_vo2#1": "姬改打熟的世界去？站了！",
        "eg_ev_cand_vo3": C + "好可没有啊！",
        "eg_ev_cand_w": C + "燃燃的咻。",
        # --- 死神 ---
        "eg_ev_deat_d": D + "忘掉了数道的生来之一。",
        "eg_ev_deat_l": D + "修用也加油死！",
        "eg_ev_deat_ms1": D + "死神用镰刀把对方力复了。",
        "eg_ev_deat_ms11": D + "死神用镰刀把对方力复了。",
        "eg_ev_deat_ms21": D + "死神的择连里，漏出了白骨的上。",
        "eg_ev_deat_ms22": D + "突然被干掉了。",
        "eg_ev_deat_ms221": D + "突然被干掉了。",
        "eg_ev_deat_ms23": D + "什么也没发生。",
        "eg_ev_deat_ms231": D + "什么也没发生。",
        "eg_ev_deat_ms31#0": D + "用也又掉下去了！",
        "eg_ev_deat_ms31#1": "死神的进，还形着！",
        "eg_ev_deat_ms32": D + "死神的防御下降了。。",
        "eg_ev_deat_vo1": D + "撤是，镰刀钓不到死。",
        "eg_ev_deat_vo2": D + "在效败的定心里抽着死。",
        "eg_ev_deat_vo3": D + "答题卡错了1格乐入了死！",
        "eg_ev_deat_w": D + "教·挑靠近了一十·死。",
        # --- 欧伊汁 ---
        "eg_ev_oiju_d": O + "力的效让平衡失了。",
        "eg_ev_oiju_l": O + "要吃的话，放进咖喱里薯！",
        "eg_ev_oiju_ms1": O + "、好好地打中了。",
        "eg_ev_oiju_ms12": O + "、好好地打中了。",
        "eg_ev_oiju_ms2": O + "占的「变成了间殿。",
        "eg_ev_oiju_ms21": O + "占的「变成了间殿。",
        "eg_ev_oiju_ms22": O + "欧伊汁点了点头。",
        "eg_ev_oiju_ms3#0": O + "欧伊汁被捕住的能量",
        "eg_ev_oiju_ms3#1": "把择烫伤了。。",
        "eg_ev_oiju_ms31#0": O + "欧伊汁被捕住的能量",
        "eg_ev_oiju_ms31#1": "把择烫伤了。。",
        "eg_ev_oiju_vo1": O + "薯。",
        "eg_ev_oiju_vo2": O + "薯薯豹。",
        "eg_ev_oiju_vo3": O + "薯黄油豹。",
        "eg_ev_oiju_w": O + "嗯。",
        # --- 卢比德 ---
        "eg_ev_lvid_d": L + "卢比德在忍着静。",
        "eg_ev_lvid_l": L + "待使来接，不需要卢比！",
        "eg_ev_lvid_ms1": L + "一根筋的反事，让卢比德的枪況了。",
        "eg_ev_lvid_ms2#0": L + "做了阵训，全部威力上升了。。",
        "eg_ev_lvid_ms2#1": "可是累了，能力掉了心",
        "eg_ev_lvid_ms3": L + "那是谁？谁？谁——。？",
        "eg_ev_lvid_ms31#0": L + "那是谁？谁？谁——。？",
        "eg_ev_lvid_ms31#1": "把能量敌收了。。",
        "eg_ev_lvid_ms32#0": L + "那是谁？谁？谁——。？",
        "eg_ev_lvid_ms32#1": "把能量敌收了。。",
        "eg_ev_lvid_vo1": L + "那任，收下了卢比。",
        "eg_ev_lvid_vo2": L + "形谁的任，给形谁的白体……卢比。",
        "eg_ev_lvid_vo3": L + "卢比德——。",
        "eg_ev_lvid_w": L + "才不会输给小恶魔卢比！",
        # --- 僵尸 ---
        "eg_ev_zomb_d#0": Z + "哇，恶心！",
        "eg_ev_zomb_d#1": "全身蛆虫在梦着往外爬。",
        "eg_ev_zomb_l": Z + "复、复活！",
        "eg_ev_zomb_ms1": Z + "打出拳的客占了。",
        "eg_ev_zomb_ms2": Z + "僵尸的身体心坏了。？",
        "eg_ev_zomb_ms3": Z + "号败的·吻嫌着，干净打中自己。？",
        "eg_ev_zomb_vo1#0": Z + "啵叽。。",
        "eg_ev_zomb_vo1#1": "胳膊！",
        "eg_ev_zomb_vo12": Z + "胳膊！",
        "eg_ev_zomb_vo2": Z + "治、治疗。",
        "eg_ev_zomb_vo3": Z + "这样就是号核了！",
        "eg_ev_zomb_w": Z + "也就这样了吧！",
        # --- 停恩 ---
        "eg_ev_151_d": Y + "停恩的面具稍微歪了！",
        "eg_ev_151_l": Y + "咔啦。停恩的生露出来了！",
        "eg_ev_151_ms1": Y + "龙的任现移到了停恩上！",
        "eg_ev_151_ms2": Y + "不可思议的机关让停恩的怪【了！",
        "eg_ev_151_ms3": Y + "靠外惑的合体力量停恩中逃心了！",
        "eg_ev_151_vo1": Y + "无语音",
        "eg_ev_151_vo2": Y + "无语音",
        "eg_ev_151_vo3": Y + "无语音",
        "eg_ev_151_w": Y + "停恩看起来在咧着上笑！",
        "eg_ev_151_ap#0": "军弱逃明欲赤书道体君（18岁）的设计。",
        "eg_ev_151_ap#1": "停恩！。。",
        # --- 木乃伊 ---
        "eg_ev_mamy_d": M + "木乃伊的中」悄悄露出来了！",
        "eg_ev_mamy_l": M + "一千用「可是很能造的味噌！",
        "eg_ev_mamy_ms1": M + "法老的移（只是落】）讨了。。",
        "eg_ev_mamy_ms2": M + "看见绷带的负，把占。了！",
        "eg_ev_mamy_ms21": M + "看见绷带的负，把占。了！",
        "eg_ev_mamy_ms3": M + "木乃伊绷带的中」是，。。",
        "eg_ev_mamy_ms31": M + "木乃伊绷带的中」是，。。",
        "eg_ev_mamy_vo1": M + "接下法老的移吧味噌。。",
        "eg_ev_mamy_vo2": M + "接下绷带的负吧味噌。。",
        "eg_ev_mamy_vo3": M + "造会出来吗？造会出来吗？",
        "eg_ev_mamy_w": M + "木乃伊是木乃伊味噌！",
        # --- 小恶魔 ---
        "eg_ev_ptdv_d": P + "小恶魔好像要靠。",
        "eg_ev_ptdv_l": P + "诶——。给我记住。。",
        "eg_ev_ptdv_ms1": P + "从小生）气的小鬼里，飞出了最强的踢。",
        "eg_ev_ptdv_ms2": "心情变成了小孩子。",
        "eg_ev_ptdv_ms21": "心情变成了小孩子。",
        "eg_ev_ptdv_ms32": P + "终末的打架里，姐姐潜入了。",
        "eg_ev_ptdv_vo1": P + "掉到地占去啾。",
        "eg_ev_ptdv_vo2": P + "变小吧啾。。",
        "eg_ev_ptdv_vo31#0": P + "小恶魔姐。这些人欺负人。",
        "eg_ev_ptdv_vo31#1": "敢啊喂。",
        "eg_ev_ptdv_w": P + "赢啦啾。",
        # --- 星防卫军（错位 ID，仍灌） ---
        "eg_ev_siro_vo1_sel1": S + "给谁治疗啊——？",
        "eg_ev_siro_vo3_sel3": S + "给谁复活啊——？",
    }
