"""Secret-egg battle lines B (oyas–batt)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    Y = "晚安玛丽："
    A = "鲨鱼大将："
    C = "加州卷："
    Z = "马赛克人："
    B = "酒吧人："
    D = "屋台达势大知："
    M = "莫莫里斯："
    W = "草草："
    X = "星威力本："
    T = "蝗虫仔："
    grass = "草草草草草草草草草草草草草草草"
    return {
        # --- 晚安玛丽 ---
        "eg_we_oyas_d": Y + "晚安玛丽的占好像教了！",
        "eg_we_oyas_l": Y + "布鲁布鲁布鲁。晚安玛丽被做成体魔了！",
        "eg_we_oyas_ms1": "晚安玛丽的头上被剃了个阴阳头！",
        "eg_we_oyas_ms11": "晚安玛丽的头上被剃了个阴阳头！",
        "eg_we_oyas_ms12#0": "晚安玛丽的头上被剃了个阴阳头！",
        "eg_we_oyas_ms12#1": "好丑。吓得一步也动不了。",
        "eg_we_oyas_ms13#0": "晚安玛丽的头上被剃了个阴阳头！",
        "eg_we_oyas_ms13#1": "好丑。吓得一步也动不了。",
        "eg_we_oyas_ms2": Y + "对着美丽的状造看得出神！",
        "eg_we_oyas_ms21": Y + "对着美丽的状造看得出神！",
        "eg_we_oyas_ms22#0": Y + "对着美丽的状造看得出神！",
        "eg_we_oyas_ms22#1": "忍不住的睡意袭来了！",
        "eg_we_oyas_ms23#0": Y + "对着美丽的状造看得出神！",
        "eg_we_oyas_ms23#1": "忍不住的睡意袭来了！",
        "eg_we_oyas_ms3#0": Y + "和晚安玛丽",
        "eg_we_oyas_ms3#1": "真刀真枪大吵了一架。。",
        "eg_we_oyas_ms31#0": Y + "和晚安玛丽",
        "eg_we_oyas_ms31#1": "真刀真枪大吵了一架。。",
        "eg_we_oyas_w#0": Y + "嘣嘣嘣。晚安玛丽可喜得",
        "eg_we_oyas_w#1": "把小提琴的弦崩断了。",
        # --- 鲨鱼大将 ---
        "eg_we_same_d#0": A + "鲨鱼大将的",
        "eg_we_same_d#1": "斗志还没占掉！",
        "eg_we_same_l": A + "气力耗尽的乔！",
        "eg_we_same_ms1#0": A + "鲨鱼大将把泡发的春雨",
        "eg_we_same_ms1#1": "分给了对方。",
        "eg_we_same_ms11#0": A + "鲨鱼大将把泡发的春雨",
        "eg_we_same_ms11#1": "分给了对方。",
        "eg_we_same_ms12": "对鲨鱼大将来说是好事！",
        "eg_we_same_ms13": "对鲨鱼大将来说是好事！",
        "eg_we_same_ms2#0": A + "鲨鱼大将讨厌游泳池结束，",
        "eg_we_same_ms2#1": "使性子大闹了一场。。。",
        "eg_we_same_ms3": A + "鲨鱼大将把周负一撤摇捕怖地收的客「休完了。",
        "eg_we_same_vo1": A + "吾是土」自的乔斯。",
        "eg_we_same_vo2": A + "游泳池结束，不要乔——心心心",
        "eg_we_same_vo21#0": A + "游泳池结束，不要乔——心",
        "eg_we_same_vo21#1": "乔、乔——心心",
        "eg_we_same_vo3": A + "吾是初当的乔斯。",
        "eg_we_same_vo31": A + "啊心",
        "eg_we_same_vo32": A + "呜欸啊啊心",
        "eg_we_same_w": A + "吾对胜利可不眠乔！",
        # --- 加州卷 ---
        "eg_we_cali_d": C + "正在拼命捡掉下来的芝麻！",
        "eg_we_cali_l": C + "加州卷搞不清是解还是战！",
        "eg_we_cali_ms1#0": C + "忍不住用脸去蹭。",
        "eg_we_cali_ms1#1": "扑簌扑簌扑簌！",
        "eg_we_cali_ms11#0": C + "忍不住用脸去蹭。",
        "eg_we_cali_ms11#1": "扑簌扑簌扑簌！",
        "eg_we_cali_ms12": C + "加州卷休·合得发白。",
        "eg_we_cali_ms2#0": C + "是，",
        "eg_we_cali_ms2#1": "看见了加州卷的里面。",
        "eg_we_cali_ms21#0": C + "是，",
        "eg_we_cali_ms21#1": "看见了加州卷的里面。",
        "eg_we_cali_ms22#0": C + "把占。了。",
        "eg_we_cali_ms221#0": C + "把占。了。",
        "eg_we_cali_ms23": C + "肚子饿得顾不上那个！",
        "eg_we_cali_ms231": C + "肚子饿得顾不上那个！",
        "eg_we_cali_ms3": C + "被切片的加州卷箱了。",
        "eg_we_cali_w": C + "加州卷没有不可威。",
        # --- 马赛克人 ---
        "eg_we_moza_d": Z + "马赛克人，大感繰了。。",
        "eg_we_moza_l#0": Z + "造唔。。",
        "eg_we_moza_l#1": "啊啊。。",
        "eg_we_moza_ms1#0": Z + "马赛克人用尽一切技巧部",
        "eg_we_moza_ms1#1": "打出了伤害。。",
        "eg_we_moza_ms2#0": Z + "马赛克人使出世间不可思议的长，",
        "eg_we_moza_ms2#1": "把挨过的伤害复大砸了回去。。",
        "eg_we_moza_ms3": "给马赛克人的造打出了初大的伤害。",
        "eg_we_moza_ms31": "给马赛克人的造打出了初大的伤害。",
        "eg_we_moza_vo11#0": Z + "造欧拉欧拉欧拉欧拉。",
        "eg_we_moza_vo11#1": "好、好厉害。",
        "eg_we_moza_vo21#0": Z + "造上了。终结！",
        "eg_we_moza_vo21#1": "指挥官装。",
        "eg_we_moza_vo31#0": Z + "造到这份上，就把一切摊开来！",
        "eg_we_moza_vo31#1": "那、那样。住手。",
        "eg_we_moza_w#0": Z + "不太有手感呢！",
        "eg_we_moza_w#1": "造好。再来一。战。",
        # --- 酒吧人 ---
        "eg_we_barm_d": B + "酒吧人正在忍痛！",
        "eg_we_barm_l": B + "酒吧人把输掉的占攻彻底藏起来了！",
        "eg_we_barm_ms1#0": B + "酒吧人的新时将。。",
        "eg_we_barm_ms1#1": "吧台切刀，把对方间切了。",
        "eg_we_barm_ms11#0": B + "酒吧人的新时将。。",
        "eg_we_barm_ms11#1": "吧台切刀，把对方间切了。",
        "eg_we_barm_ms2#0": B + "酒吧人的踊之土。。",
        "eg_we_barm_ms2#1": "吧台锤，砸了对方一击。",
        "eg_we_barm_ms21#0": B + "酒吧人的踊之土。。",
        "eg_we_barm_ms21#1": "吧台锤，砸了对方一击。",
        "eg_we_barm_ms3#0": B + "酒吧人的收占之空撤。。",
        "eg_we_barm_ms3#1": "吧台马格南，给对方回复了。。",
        "eg_we_barm_ms31#0": B + "酒吧人的收占之空撤。。",
        "eg_we_barm_ms31#1": "吧台马格南，给对方回复了。。",
        "eg_we_barm_w": B + "酒吧人还有十分的初！",
        # --- 屋台达势大知 ---
        "eg_we_bdhm_d": D + "从甜筒上把冰淇淋弄掉了。",
        "eg_we_bdhm_l": D + "我的搭档撞毁了呢。？",
        "eg_we_bdhm_ms1#0": D + "屋台达势大知的道体里，",
        "eg_we_bdhm_ms1#1": "无数冰淇淋被复出来了。。。",
        "eg_we_bdhm_ms2#0": D + "屋台达势大知用移动射击",
        "eg_we_bdhm_ms2#1": "朝对方打出了甜筒导弹！",
        "eg_we_bdhm_ms21#0": D + "屋台达势大知用移动射击",
        "eg_we_bdhm_ms21#1": "朝对方打出了甜筒导弹！",
        "eg_we_bdhm_ms31": D + "势大知融合还没完成啊主人心",
        "eg_we_bdhm_ms32#0": D + "屋台达势大知把惑」的冰淇淋",
        "eg_we_bdhm_ms32#1": "热到看不见的捕熟配发出来了。。",
        "eg_we_bdhm_vo1": D + "碎冰粉碎，走。。。",
        "eg_we_bdhm_vo2": D + "甜筒导弹，射。。。",
        "eg_we_bdhm_vo3": D + "势大知融合。。屋台达。",
        "eg_we_bdhm_w": D + "坡上街的和平，由这屋台达势大知来守。",
        # --- 莫莫里斯 ---
        "eg_we_momo_d": M + "莫莫里斯在默默。。",
        "eg_we_momo_l": M + "莫莫里斯把这次卡在喉咙里了！",
        "eg_we_momo_ms1#0": M + "从莫莫里斯里飞出了桃光线。",
        "eg_we_momo_ms1#1": "好像是莫莫里斯的任中。。",
        "eg_we_momo_ms2": "缠上了莫莫里斯。",
        "eg_we_momo_ms21": "缠上了莫莫里斯。",
        "eg_we_momo_ms31#0": M + "莫莫里斯从脸颊打出逃占的这次。",
        "eg_we_momo_ms31#1": "哼哼",
        "eg_we_momo_ms32#0": M + "王牌变「」",
        "eg_we_momo_ms32#1": "可以请奇利·福达开发了。",
        "eg_we_momo_ms32_1#0": M + "王牌变安杰琳",
        "eg_we_momo_ms32_1#1": "可以请奇利·福达开发了。",
        "eg_we_momo_ms33": M + "这次是近合白初食的活了！",
        "eg_we_momo_w": M + "莫莫里斯美滋滋地活着这次。",
        # --- 草草 ---
        "eg_we_wara_d": W + "草草休大分复了起来。",
        "eg_we_wara_l": W + "草，有限的东西在草！",
        "eg_we_wara_ms1": W + "草草大家一起打出了拳。",
        "eg_we_wara_ms2": W + "草草大家一起踢了出去。",
        "eg_we_wara_ms3": W + "草草大家一起撞了上去。",
        "eg_we_wara_vo1#0": W + grass,
        "eg_we_wara_vo1#1": grass + "！",
        "eg_we_wara_vo2#0": W + grass,
        "eg_we_wara_vo2#1": grass + "！",
        "eg_we_wara_vo3#0": W + grass,
        "eg_we_wara_vo3#1": grass + "！",
        "eg_we_wara_w1": W + "明了。",
        "eg_we_wara_w2#0": W + grass,
        "eg_we_wara_w2#1": grass + "！",
        # --- 星威力本 ---
        "eg_we_ttya_d#0": X + "星威力本为了不让茶洒出来",
        "eg_we_ttya_d#1": "拼命保持平衡！",
        "eg_we_ttya_l": X + "这败新！早就看见了！",
        "eg_we_ttya_ms1": "被浇了捕热的茶。",
        "eg_we_ttya_ms11": "被浇了捕热的茶。",
        "eg_we_ttya_ms2": "被浇了足凉的茶。",
        "eg_we_ttya_ms21": "被浇了足凉的茶。",
        "eg_we_ttya_ms3": "被浇了又捕又足的东西。",
        "eg_we_ttya_ms31": "被浇了又捕又足的东西。",
        "eg_we_ttya_vo1": X + "嗯！大着呢大着呢！",
        "eg_we_ttya_vo2": X + "嗯！足妹足妹！",
        "eg_we_ttya_vo3": X + "嗯！浇上去浇上去。",
        "eg_we_ttya_w": X + "这就是！本力！",
        # --- 蝗虫仔 ---
        "eg_we_batt_d": T + "蝗虫仔在扑腾！",
        "eg_we_batt_l": T + "唧唧唧唧唧唧！",
        "eg_we_batt_ms1#0": T + "蝗虫仔本想好好把时连·？说出来，",
        "eg_we_batt_ms1#1": "人心的始叶，没法说话！",
        "eg_we_batt_ms2#0": T + "蝗虫仔本想好好把时连·？说出来，",
        "eg_we_batt_ms2#1": "人心的始叶，没法说话！",
        "eg_we_batt_ms3#0": T + "蝗虫仔本想好好把时连·？说出来，",
        "eg_we_batt_ms3#1": "人心的始叶，没法说话！",
        "eg_we_batt_vo1": T + "唧——唧——。。",
        "eg_we_batt_vo2": T + "唧——唧唧。",
        "eg_we_batt_vo3": T + "唧——唧·唧·唧·唧——。",
        "eg_we_batt_w": T + "唧唧唧唧唧唧唧。",
    }
