"""Power-egg battle lines A (kawa–eggk)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    K = "臭负降号："
    Dr = "博士："
    C = "奇美拉王："
    R = "人体骑士："
    Ma = "正男："
    Ji = "次郎："
    Ta = "武："
    Wa = "涉："
    F = "全肌肉："
    Gy = "观众："
    B = "巴里·蟾蜍："
    An = "实况："
    L = "蓝龙："
    G = "水黾的炼金术师："
    Ed = "爱德华："
    Al = "阿尔冯斯："
    I = "海葵杰克："
    Da = "解说爹地："
    P = "豚悟空："
    E = "艾格曼骑士："
    return {
        # --- 臭负降号 ---
        "eg_pw_kawa_d": Dr + "手术的伤害。",
        "eg_pw_kawa_l": Dr + "俺的发明。？",
        "eg_pw_kawa_ms1#0": Dr + "把引擎发动了。",
        "eg_pw_kawa_ms1#1": "出汗了。",
        "eg_pw_kawa_ms11#0": Dr + "把引擎发动了。",
        "eg_pw_kawa_ms11#1": "出汗了。",
        "eg_pw_kawa_ms2#0": Dr + "把喇叭按响了。",
        "eg_pw_kawa_ms2#1": "吓得腿软了。",
        "eg_pw_kawa_ms21#0": Dr + "把喇叭按响了。",
        "eg_pw_kawa_ms21#1": "没注意到。",
        "eg_pw_kawa_ms22#0": Dr + "把喇叭按响了。",
        "eg_pw_kawa_ms22#1": "吓得腿软了。",
        "eg_pw_kawa_ms23#0": Dr + "把喇叭按响了。",
        "eg_pw_kawa_ms23#1": "没注意到。",
        "eg_pw_kawa_ms3#0": K + "臭负降号把痰吐掉了。",
        "eg_pw_kawa_ms3#1": "被那臭味吓掉了魂。",
        "eg_pw_kawa_ms31#0": K + "臭负降号把痰吐掉了。",
        "eg_pw_kawa_ms31#1": "舒舒服服地飞了。",
        "eg_pw_kawa_ms32#0": K + "臭负降号把痰吐掉了。",
        "eg_pw_kawa_ms32#1": "被那臭味吓掉了魂。",
        "eg_pw_kawa_ms33#0": K + "臭负降号把痰吐掉了。",
        "eg_pw_kawa_ms33#1": "舒舒服服地飞了。",
        "eg_pw_kawa_ms34#0": K + "臭负降号把痰吐掉了。",
        "eg_pw_kawa_ms34#1": "中毒了。。",
        "eg_pw_kawa_ms35#0": K + "臭负降号把痰吐掉了。",
        "eg_pw_kawa_ms35#1": "中毒了。。",
        "eg_pw_kawa_name": "为军弱烦恼的、出上死费君的设计队",
        "eg_pw_kawa_vo1": Dr + "首先切肉馅！",
        "eg_pw_kawa_vo12": K + "降号——嗡，——嗡。",
        "eg_pw_kawa_vo2": Dr + "这样如何？",
        "eg_pw_kawa_vo21": K + "降号听见了没，喂。？",
        "eg_pw_kawa_vo3": Dr + "要出舞之土了！",
        "eg_pw_kawa_vo32": K + "咕啊啦啦啦啦，呸。。",
        "eg_pw_kawa_w": Dr + "正按计划的反击啊！",
        # --- 奇美拉王 ---
        "eg_pw_kimr_d": C + "奇美拉王正刻着节拍！",
        "eg_pw_kimr_l#0": C + "技能不错嘛！",
        "eg_pw_kimr_l#1": "挺能干的嘛你们！",
        "eg_pw_kimr_ms1": C + "奇美拉王把自己轻松定了。。",
        "eg_pw_kimr_ms12": "奇美拉王有点没听懂！",
        "eg_pw_kimr_ms13": "奇美拉王有点没听懂！",
        "eg_pw_kimr_ms2": C + "奇美拉王把不愿战斗的日讨体夜美了！",
        "eg_pw_kimr_ms3": C + "奇美拉王把能了的连喜核了！",
        "eg_pw_kimr_vo1#0": C + "身体是三种力量的帅家伙",
        "eg_pw_kimr_vo1#1": "山羊狮子蛇",
        "eg_pw_kimr_vo1#2": C + "我们这帮帅奇美拉王。",
        "eg_pw_kimr_vo1#3": "听好了我们就是",
        "eg_pw_kimr_vo1#4": C + "我们这帮酷地奇美。",
        "eg_pw_kimr_vo1#5": "咚——————。。。",
        "eg_pw_kimr_vo2#0": C + "不打吗不龇牙吗",
        "eg_pw_kimr_vo2#1": C + "眼睛瞟开装没看见吗",
        "eg_pw_kimr_vo2#2": C + "你们就这还装吗",
        "eg_pw_kimr_vo2#3": C + "那套装腔作势的势。。",
        "eg_pw_kimr_vo2#4": "咚——————。。。",
        "eg_pw_kimr_vo3#0": C + "被无聊的主张连着，",
        "eg_pw_kimr_vo3#1": "跪在团力面前",
        "eg_pw_kimr_vo3#2": C + "被无聊的主张超了，",
        "eg_pw_kimr_vo3#3": "把大力的东西给俺形了",
        "eg_pw_kimr_vo3#4": C + "被无聊的主张拉成了同伴",
        "eg_pw_kimr_vo3#5": "再见再也不喜了",
        "eg_pw_kimr_vo3#6": C + "撤的大人没军，你们也从日那些家伙！",
        "eg_pw_kimr_vo3#7": "咚——————。。。",
        "eg_pw_kimr_w#0": C + "要骂爆了我们你们！",
        "eg_pw_kimr_w#1": "不向连喜献媚的奇美拉王。",
        # --- 人体骑士 ---
        "eg_pw_ngrd_d": R + "龙正在靠近。",
        "eg_pw_ngrd_l": R + "带着冷掉的人飞走了！",
        "eg_pw_ngrd_ms1": R + "龙动的力量把周围横扫了。",
        "eg_pw_ngrd_ms2": R + "龙把人扔了出去。",
        "eg_pw_ngrd_ms31": R + "来的食请用",
        "eg_pw_ngrd_ms32": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms33#0": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms33#1": "攻击上升了，防御下降了。。",
        "eg_pw_ngrd_ms34#0": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms34#1": "防御上升了，速度下降了。。",
        "eg_pw_ngrd_ms34_a#0": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms34_a#1": "防御上升了，攻击下降了。。",
        "eg_pw_ngrd_ms35#0": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms35#1": "速度上升了，攻击下降了。。",
        "eg_pw_ngrd_ms35_a#0": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms36#0": R + "龙把人换乘了！",
        "eg_pw_ngrd_ms36#1": "威力回到普通了。。",
        "eg_pw_ngrd_vo21": Ma + "呀——。",
        "eg_pw_ngrd_vo22": Ji + "呀——。",
        "eg_pw_ngrd_vo23": Ta + "哇——。",
        "eg_pw_ngrd_vo24": Wa + "呜呀——。",
        "eg_pw_ngrd_vo31": Ma + "交换完成了！",
        "eg_pw_ngrd_vo32": Ji + "俺还不想死啊。",
        "eg_pw_ngrd_vo33": Ta + "妈妈——。。",
        "eg_pw_ngrd_vo34": Wa + "不要啊不要啊",
        "eg_pw_ngrd_w1": Ma + "还、还活着。俺还活着哟。。",
        "eg_pw_ngrd_w2": Ji + "赢了！",
        "eg_pw_ngrd_w3": Ta + "来绝对不要啊。",
        "eg_pw_ngrd_w4": Wa + "净是这种役！",
        # --- 全肌肉 ---
        "eg_pw_full_d1": F + "全肌肉的肌肉在抽动。",
        "eg_pw_full_d2": F + "全肌肉露出了愉快的表情。",
        "eg_pw_full_d3": F + "全肌肉稍微不那么全了。",
        "eg_pw_full_l": F + "完败！",
        "eg_pw_full_ms1": F + "全肌肉露出了协编的笑。",
        "eg_pw_full_ms1_k": F + "全肌肉从身体发出不可思议的汁。",
        "eg_pw_full_ms2": "全肌肉把哑铃咔地吃了。",
        "eg_pw_full_ms3": F + "全肌肉把肌肉练到了肉体的极限。",
        "eg_pw_full_vo11": F + "哈哈——。哈哈哈。",
        "eg_pw_full_vo12": F + "啪啦隆。",
        "eg_pw_full_vo13": F + "看招。",
        "eg_pw_full_vo14": F + "哈哈哈哈哈哈哈哈哈。",
        "eg_pw_full_vo15": F + "满月。",
        "eg_pw_full_vo21": F + "哼哼嗯。",
        "eg_pw_full_vo22": F + "上客任力阵。",
        "eg_pw_full_vo23": F + "这有效啊。",
        "eg_pw_full_vo24": F + "咻咻。",
        "eg_pw_full_vo25": F + "唔嗯。",
        "eg_pw_full_vo31#0": F + "嗯姆喀啊啊啊。。",
        "eg_pw_full_vo31#1": Gy + "大哥——。好姿势——。",
        "eg_pw_full_vo32#0": F + "定了。。",
        "eg_pw_full_vo32#1": Gy + "大哥——。定住了——。",
        "eg_pw_full_vo33#0": F + "唔咕咕哈啊。。",
        "eg_pw_full_vo33#1": Gy + "大哥——。好性感——。",
        "eg_pw_full_vo34#0": F + "呜啦啦啦啊啊。。",
        "eg_pw_full_vo34#1": Gy + "大哥——。完美地看着——。",
        "eg_pw_full_vo35#0": F + "喝呀啊。。",
        "eg_pw_full_vo35#1": Gy + "大哥——。真的好猛。真的。",
        "eg_pw_full_w": F + "永久的肉体美。以是明情全肌肉。",
        # --- 巴里·蟾蜍 ---
        "eg_pw_bari_d": B + "巴里·蟾蜍吃了好的一击。",
        "eg_pw_bari_l#0": An + "巴里·蟾蜍，认输。",
        "eg_pw_bari_l#1": "400战无败传说，在此败北——。。",
        "eg_pw_bari_ms1#0": B + "巴里·蟾蜍力败打吃了50点伤害，可",
        "eg_pw_bari_ms1#1": "内啡肽分泌了，攻击上升了。。",
        "eg_pw_bari_ms12#0": B + "巴里·蟾蜍力败打吃了伤害，可",
        "eg_pw_bari_ms12#1": "内啡肽分泌了，攻击上升了。。",
        "eg_pw_bari_ms2#0": "巴里·蟾蜍激烈地蹬，",
        "eg_pw_bari_ms2#1": "被地面力摔了上去。",
        "eg_pw_bari_ms21#0": "巴里·蟾蜍激烈地蹬，",
        "eg_pw_bari_ms21#1": "被地面力摔了上去。",
        "eg_pw_bari_ms3#0": "巴里·蟾蜍被强大的一击",
        "eg_pw_bari_ms3#1": "眼睛去了，变成梦备。",
        "eg_pw_bari_ms31#0": "巴里·蟾蜍被强大的一击",
        "eg_pw_bari_ms31#1": "眼睛去了，变成梦备。",
        "eg_pw_bari_ms32": "巴里·蟾蜍被强大的一击眼睛去了。。",
        "eg_pw_bari_ms33": "巴里·蟾蜍被强大的一击眼睛去了。。",
        "eg_pw_bari_ms34#0": "巴里·蟾蜍被强大的一击眼睛去了。",
        "eg_pw_bari_ms35#0": "巴里·蟾蜍被强大的一击眼睛去了。",
        "eg_pw_bari_name": "为持消」烦恼的、坏一君的设计队",
        "eg_pw_bari_vo1#0": An + "出来了。德国过肩摔。",
        "eg_pw_bari_vo1#1": "守着不放。。",
        "eg_pw_bari_vo2#0": An + "哦——，从冲撞姿势水落。",
        "eg_pw_bari_vo2#1": "正是蛙跳入水的落。。",
        "eg_pw_bari_vo3#0": An + "巴里·蟾蜍认真出了。",
        "eg_pw_bari_vo3#1": "斗士的宿命吗，无限的河津挂。。",
        "eg_pw_bari_w": An + "不愧400战无败。人生生号败之人。。",
        # --- 蓝龙 ---
        "eg_pw_bldr_d#0": L + "蓝龙比起战斗，",
        "eg_pw_bldr_d#1": "满脑子都是那件事！",
        "eg_pw_bldr_l#0": L + "啊——啊——，输了！",
        "eg_pw_bldr_l#1": "这才是真正的蓝龙。",
        "eg_pw_bldr_ms1": L + "蓝龙想起了讨厌的事。。",
        "eg_pw_bldr_ms11": L + "叹息稍微少了。。",
        "eg_pw_bldr_ms12#0": L + "叹息稍微少了。。",
        "eg_pw_bldr_ms12#1": "无用的努力也稍微少了。。",
        "eg_pw_bldr_ms13": L + "叹息不会再少了！",
        "eg_pw_bldr_ms14": L + "叹息和无用的努力都不会再少了！",
        "eg_pw_bldr_ms2": L + "蓝龙受不了，叹了口气！",
        "eg_pw_bldr_ms21": "被激烈的寒气袭来了。。",
        "eg_pw_bldr_ms22#0": L + "蓝龙受不了，叹了口气！",
        "eg_pw_bldr_ms22#1": "被激烈的寒气袭来了。。",
        "eg_pw_bldr_ms23#0": L + "蓝龙受不了，叹了口气！",
        "eg_pw_bldr_ms23#1": "被激烈的寒气袭来了。。",
        "eg_pw_bldr_ms31": L + "蓝龙拼命去想高兴的事！",
        "eg_pw_bldr_ms31_2#0": L + "蓝龙拼命去想高兴的事！",
        "eg_pw_bldr_ms31_2#1": "可还是想了讨厌的事。。",
        "eg_pw_bldr_ms32": L + "可还是想了讨厌的事。。",
        "eg_pw_bldr_ms33#0": L + "冻人的激烈寒气",
        "eg_pw_bldr_ms33#1": "袭来了。。",
        "eg_pw_bldr_ms34#0": L + "冻人的激烈寒气",
        "eg_pw_bldr_ms34#1": "袭来了。。",
        "eg_pw_bldr_vo2": L + "哈——！",
        "eg_pw_bldr_vo3": L + "哈啊啊——！",
        "eg_pw_bldr_w": L + "蓝龙第一次有了高兴的回忆。",
        # --- 水黾的炼金术师 ---
        "eg_pw_tagm_actor1": "爱德华 体谁收入人（声优）",
        "eg_pw_tagm_actor2": "阿尔冯斯 体谁用坏容效（声优）",
        "eg_pw_tagm_actor3#3": "爱变收入人 阿变用坏容效",
        "eg_pw_tagm_d#0": G + "归来爱德华和阿尔冯斯！",
        "eg_pw_tagm_d#1": "这两人的中赖负敌是本星！",
        "eg_pw_tagm_l#0": Ed + "可恶，姿的待里俺是无力的！",
        "eg_pw_tagm_l#1": "阿尔冯斯：至少父亲能睡着就好了各位！",
        "eg_pw_tagm_ms1": G + "爱德华从地面炼成了落。",
        "eg_pw_tagm_ms2": G + "阿尔冯斯把投激的体决了军了。。",
        "eg_pw_tagm_ms3": G + "两人炼成了坏梦少用钢钢。。",
        "eg_pw_tagm_ms31#0": G + "变得有趣了。",
        "eg_pw_tagm_ms31#1": "这开。这有趣。不是周消。。",
        "eg_pw_tagm_ms32#0": G + "变得有趣了。",
        "eg_pw_tagm_ms32#1": "这开。这有趣。不是周消。。",
        "eg_pw_tagm_vo1#0": Ed + "你们踏进来就当成俺的。",
        "eg_pw_tagm_vo1#1": "给你们打趴，放马过来。",
        "eg_pw_tagm_vo11#0": Ed + "是宇宙役形啊。既然要打",
        "eg_pw_tagm_vo11#1": "自己被干掉的教回，也给我做好。",
        "eg_pw_tagm_vo2": Al + "要打的话，我也不会容谁！",
        "eg_pw_tagm_vo21": Al + "要是打架，连各位也不会输！",
        "eg_pw_tagm_vo3#0": Ed + "上啊——阿。",
        "eg_pw_tagm_vo3#1": "阿尔冯斯：嗯！交给我吧兄桑。",
        "eg_pw_tagm_vo31": Ed + "了阿漫画是钢钢。。",
        "eg_pw_tagm_vo32#0": Ed + "有趣无败梦客大。。",
        "eg_pw_tagm_vo32#1": "阿尔冯斯：日本第一的娱乐漫画。。",
        "eg_pw_tagm_w#0": Ed + "阿，绝对要把你的身体开回来。",
        "eg_pw_tagm_w#1": "阿尔冯斯：嗯，那时候兄桑也在一起！",
        # --- 海葵杰克 ---
        "eg_pw_isgn_d#0": I + "海葵杰克",
        "eg_pw_isgn_d#1": "因为排练和正式拍摄不一样，正在生气。",
        "eg_pw_isgn_l#0": An + "海葵杰克。3计数。",
        "eg_pw_isgn_l#1": "解说爹地：爪子还近呢！",
        "eg_pw_isgn_ms1#0": I + "想起新力电视入迷时的那报，",
        "eg_pw_isgn_ms1#1": "露出了静！",
        "eg_pw_isgn_ms11#0": I + "想起新力电视入迷时的那报，",
        "eg_pw_isgn_ms11#1": "露出了静！",
        "eg_pw_isgn_ms2": I + "的心真正燃起来了。",
        "eg_pw_isgn_ms21": I + "的心真正燃起来了。",
        "eg_pw_isgn_ms3#0": I + "的心真正起了鸡皮疙瘩。",
        "eg_pw_isgn_ms3#1": "能承受一切的摔角魂————。。。",
        "eg_pw_isgn_ms31#0": I + "的心真正起了鸡皮疙瘩。",
        "eg_pw_isgn_ms31#1": "能承受一切的摔角魂————。。。",
        "eg_pw_isgn_vo1": An + "海葵劈出来了————。。",
        "eg_pw_isgn_vo12#0": Da + "不错啊",
        "eg_pw_isgn_vo12#1": "那一劈有效果。",
        "eg_pw_isgn_vo2": An + "这就是摔角手小军的喜闘逆水平——。。",
        "eg_pw_isgn_vo21#0": Da + "海葵杰克啊",
        "eg_pw_isgn_vo21#1": "是用逆水平测力间的呢！",
        "eg_pw_isgn_vo3": An + "海葵杰克的连打啊——。。",
        "eg_pw_isgn_vo31#0": Da + "这、这是。？",
        "eg_pw_isgn_vo31#1": "海葵杰克认真出了。",
        "eg_pw_isgn_w#0": I + "来的是你。爹地——。。",
        "eg_pw_isgn_w#1": "解说爹地：哼，重量级决定战里打着呢！",
        # --- 豚悟空 ---
        "eg_pw_116_d": P + "豚悟空正强着！",
        "eg_pw_116_l": P + "才没有输呢！",
        "eg_pw_116_ms1#0": P + "体复出现的筋斗云轰隆轰隆！",
        "eg_pw_116_ms1#1": "只是很吵而已！",
        "eg_pw_116_ms2#0": P + "金箍棒合了！",
        "eg_pw_116_ms2#1": "可对豚悟空来说太重，拿不起来！",
        "eg_pw_116_ms3": "豚悟空有点想被沙悟净打！",
        "eg_pw_116_ms32": "豚悟空有点想被沙悟净打！",
        "eg_pw_116_vo1": P + "轰吧。筋斗云——。",
        "eg_pw_116_vo2": P + "伸吧。金箍棒——。",
        "eg_pw_116_vo3": P + "去吧。沙悟净——。",
        "eg_pw_116_vo32#0": P + "沙悟净喹————。。",
        "eg_pw_116_vo32#1": "豚悟空！",
        "eg_pw_116_vo32_b#0": P + "沙悟净咻————。",
        "eg_pw_116_vo32_b#1": "豚悟空！",
        "eg_pw_116_vo32_c#0": P + "沙悟净啪————。",
        "eg_pw_116_vo32_c#1": "豚悟空！",
        "eg_pw_116_vo32_d#0": P + "沙悟净嗯！",
        "eg_pw_116_vo32_d#1": "豚悟空！",
        "eg_pw_116_vo32_e#0": P + "沙悟净沙————。",
        "eg_pw_116_vo32_e#1": "豚悟空！",
        "eg_pw_116_w": P + "那是当然的！",
        "eg_pw_116_ap#0": "持消」负欲与本·生君（17）的设计。",
        "eg_pw_116_ap#1": "豚悟空！。。",
        # --- 艾格曼骑士 ---
        "eg_pw_eggk_d": E + "艾格曼骑士好歹用剑把攻击挡了！",
        "eg_pw_eggk_l#0": E + "即便俺被干掉，",
        "eg_pw_eggk_l#1": "继承弱、降静的战军，也一定会讨你！",
        "eg_pw_eggk_ms1": "身上对艾格曼骑士没有教！",
        "eg_pw_eggk_ms11": "身上对艾格曼骑士没有教！",
        "eg_pw_eggk_ms2#0": E + "艾格曼骑士的弱熟",
        "eg_pw_eggk_ms2#1": "刺了过去。。",
        "eg_pw_eggk_ms21#0": E + "艾格曼骑士的弱熟",
        "eg_pw_eggk_ms21#1": "刺了过去。。",
        "eg_pw_eggk_ms3#0": E + "第一骑士团用各自的力、技与气",
        "eg_pw_eggk_ms3#1": "连携攻击。",
        "eg_pw_eggk_ms31#0": E + "第一骑士团用各自的力、技与气",
        "eg_pw_eggk_ms31#1": "连携攻击。",
        "eg_pw_eggk_vo1#0": E + "大地上横行的大谁之物啊。",
        "eg_pw_eggk_vo1#1": "现在解开，讨殿。。",
        "eg_pw_eggk_vo2#0": E + "艾格曼骑士。上哦。。",
        "eg_pw_eggk_vo2#1": "蛋光————束。。",
        "eg_pw_eggk_vo3#0": E + "对力用技，对技用气，对气用力",
        "eg_pw_eggk_vo3#1": "这就是卵之骑士的战法！",
        "eg_pw_eggk_w#0": E + "大谁之物的分和选，",
        "eg_pw_eggk_w#1": "俺一根伤都没有！",
    }
