"""四次元煮蛋 / 煮蛋 / 4田川 lyrics battle lines."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    B = "四次元煮蛋："
    E = "绘美："
    K = "京子："
    G = "煮蛋："
    out: dict[str, str] = {}
    out.update(_boil(B, E, K))
    out.update(_egg(G))
    out.update(_yonda())
    return out


def _boil(B: str, E: str, K: str) -> dict[str, str]:
    return {
        "eg_bo_boil_at3_kata_1#0": E + "啊啊，",
        "eg_bo_boil_at3_kata_1#1": "一部的帅哥演起来好痛啊——！",
        "eg_bo_boil_at3_kata_10": K + "啊，差不多该把蛋放进微波炉了！",
        "eg_bo_boil_at3_kata_11": E + "就这样放着行吗？",
        "eg_bo_boil_at3_kata_12": K + "大概行吧？",
        "eg_bo_boil_at3_kata_13#0": E + "我可没教过他。",
        "eg_bo_boil_at3_kata_13#1": "是一真自己学会的。",
        "eg_bo_boil_at3_kata_13_a": K + "哈。？一真那儿来邮件了啊。",
        "eg_bo_boil_at3_kata_14#0": K + "诶。？超来气。。",
        "eg_bo_boil_at3_kata_14#1": "这份地址也打算给一真吗。",
        "eg_bo_boil_at3_kata_15": E + "撞号的信行，不是你推过去的吗。",
        "eg_bo_boil_at3_kata_16#0": K + "不是那个意思吧。？",
        "eg_bo_boil_at3_kata_16#1": "好好教啊。",
        "eg_bo_boil_at3_kata_17": E + "不要。",
        "eg_bo_boil_at3_kata_18": K + "拿出来看看（弱）",
        "eg_bo_boil_at3_kata_18_a#0": K + "拿出来啊",
        "eg_bo_boil_at3_kata_18_a#1": "绘美别碰。",
        "eg_bo_boil_at3_kata_18_b": K + "你这丑八怪。",
        "eg_bo_boil_at3_kata_18_c": E + "你才恶心。",
        "eg_bo_boil_at3_kata_19#0": K + "呀————。。",
        "eg_bo_boil_at3_kata_19#1": "绘美呀————。。",
        "eg_bo_boil_at3_kata_2": K + "诶，真的？一部的联谊的。？哈。？难道",
        "eg_bo_boil_at3_kata_20": K + "啊，好臭。",
        "eg_bo_boil_at3_kata_21": E + "煤气味。？",
        "eg_bo_boil_at3_kata_3": E + "难道什么难道，京子也是一真。？",
        "eg_bo_boil_at3_kata_4#0": K + "撞号了啊。",
        "eg_bo_boil_at3_kata_4#1": "咱们喜欢的人总是撞号。",
        "eg_bo_boil_at3_kata_5": E + "难道，邮箱什么的没教过吧？",
        "eg_bo_boil_at3_kata_6": K + "没教过。绘美呢。？",
        "eg_bo_boil_at3_kata_7": E + "我也没教过。",
        "eg_bo_boil_at3_kata_8#0": K + "那就行！可这也太巧了。？",
        "eg_bo_boil_at3_kata_8#1": "绘美居然把地址教出去！",
        "eg_bo_boil_at3_kata_9": E + "我这也快撑不住了啊！",
        "eg_bo_boil_d1": B + "那就是尔等的合心4？",
        "eg_bo_boil_d2": B + "无聊4！",
        "eg_bo_boil_d3": B + "那也叫实力4？",
        "eg_bo_boil_l1#0": B + "4，死了？本4会？",
        "eg_bo_boil_l1#1": "尔等，是要超越神4吗。？",
        "eg_bo_boil_l1_b": B + "4，死了？诶？本4会？",
        "eg_bo_boil_l2#0": B + "把四次元的心也做成了次元。",
        "eg_bo_boil_l2#1": "这位神啊。？",
        "eg_bo_boil_l3": B + "这就是本4的四次元4。？",
        "eg_bo_boil_l4#0": B + "库蒙吃掉的蛋怪们",
        "eg_bo_boil_l4#1": "被四次元煮蛋的食欲解雇了。",
        "eg_bo_boil_ms1#0": B + "完美且最强的一击",
        "eg_bo_boil_ms1#1": "砸了下去。",
        "eg_bo_boil_ms10#0": B + "四次元煮蛋放出了彻骨的周六夜动。",
        "eg_bo_boil_ms10#1": "所有状况心，都被抹掉了。。",
        "eg_bo_boil_ms2#0": B + "四次元煮蛋把大气拧弯，",
        "eg_bo_boil_ms2#1": "让次元鲣鱼的字跑了起来。。",
        "eg_bo_boil_ms21#0": B + "四次元煮蛋把大气拧弯，",
        "eg_bo_boil_ms21#1": "让次元陨石的字跑了起来。。",
        "eg_bo_boil_ms22#0": B + "四次元煮蛋把大气拧弯，",
        "eg_bo_boil_ms22#1": "让次元陨石的字跑了起来。。",
        "eg_bo_boil_ms3": B + "四次元煮蛋进入了四次元大灾变的准备。",
        "eg_bo_boil_ms31#0": B + "四次元煮蛋正在准备四次元大灾变。",
        "eg_bo_boil_ms31#1": "完成还要再等一会儿。",
        "eg_bo_boil_ms32#0": B + "四次元煮蛋正在准备四次元大灾变。",
        "eg_bo_boil_ms32#1": "马上就要完成了。",
        "eg_bo_boil_ms33#0": B + "四次元煮蛋正在准备四次元大灾变。",
        "eg_bo_boil_ms33#1": "已经到极限了。来了。。",
        "eg_bo_boil_ms34#0": B + "四次元大灾变发动。",
        "eg_bo_boil_ms34#1": "全次元被黑暗包住了。。",
        "eg_bo_boil_ms4#0": B + "什么。。",
        "eg_bo_boil_ms4#1": "章鱼表变成乌贼表了。",
        "eg_bo_boil_ms41#0": B + "什么。。",
        "eg_bo_boil_ms41#1": "乌贼表回到章鱼表了。",
        "eg_bo_boil_ms5#0": B + "四次元煮蛋",
        "eg_bo_boil_ms5#1": "把能力反转到粉红了。。",
        "eg_bo_boil_ms6": B + "四次元煮蛋打出了完熟力量的一击。",
        "eg_bo_boil_ms7#0": B + "挨了迷雾预言。",
        "eg_bo_boil_ms7#1": "倒数到0就会死掉。。",
        "eg_bo_boil_ms8#0": B + "「研究所」发生了生化危机。",
        "eg_bo_boil_ms8#1": "大家都变成了各种各样的状况。。",
        "eg_bo_boil_ms9#0": B + "四次元煮蛋",
        "eg_bo_boil_ms9#1": "拿起双电子步枪，一齐射击了。。",
        "eg_bo_boil_st#0": B + "欢迎尔等，来到吾之……（城！",
        "eg_bo_boil_st#1": "本4之名，是煮蛋！",
        "eg_bo_boil_st1#0": B + "愚蠢的家伙，身为勇气的能力者却要合力成军的人！",
        "eg_bo_boil_st1#1": "神啊本4是四次元煮蛋4。",
        "eg_bo_boil_st2#0": B + "为了把四次元恢复成神之世界",
        "eg_bo_boil_st2#1": "尔等，四次元的愚者全部击灭4。",
        "eg_bo_boil_vo101": B + "然后前往永远4。",
        "eg_bo_boil_vo102": B + "还能在现实里潜多久？",
        "eg_bo_boil_vo103": B + "以为这样就赢了4？",
        "eg_bo_boil_vo104": B + "永远的开始！",
        "eg_bo_boil_vo11": B + "那么，上4。",
        "eg_bo_boil_vo12": B + "来！",
        "eg_bo_boil_vo13": B + "到此为止4！",
        "eg_bo_boil_vo14": B + "过。煮蛋。。",
        "eg_bo_boil_vo21": B + "消失吧，碍眼4。",
        "eg_bo_boil_vo22": B + "连地球一起化成灰也无妨4。",
        "eg_bo_boil_vo23": B + "把祭典煽起来4，超越次元。",
        "eg_bo_boil_vo24": B + "四次元，陨石——。。",
        "eg_bo_boil_vo32": B + "这个世界，必须重置4。",
        "eg_bo_boil_vo33#0": B + "为了进化，丑陋的姿要睡去！",
        "eg_bo_boil_vo33#1": "那才是直达破坏姿的进化4。",
        "eg_bo_boil_vo34#0": B + "尔等的死，并非徒劳！",
        "eg_bo_boil_vo34#1": "会成为神之世界的基石4。",
        "eg_bo_boil_vo35": B + "呼哈哈，来了4。",
        "eg_bo_boil_vo36": B + "四次元大灾变——。。",
        "eg_bo_boil_vo41": B + "来个有趣的召唤4！",
        "eg_bo_boil_vo42": B + "等得住吗，这个笑话？",
        "eg_bo_boil_vo43": B + "乌贼也是。",
        "eg_bo_boil_vo44": B + "章鱼也是。",
        "eg_bo_boil_vo45#0": B + "给她的手指套上乌贼圈",
        "eg_bo_boil_vo45#1": "去求婚，她却说不要4，生乌贼气了4！",
        "eg_bo_boil_vo46": B + "彩色乌贼——。",
        "eg_bo_boil_vo51": B + "这就以为干掉本4了？",
        "eg_bo_boil_vo52": B + "这点程度，本4给自己改造看看4。",
        "eg_bo_boil_vo53": B + "变成粉红4。",
        "eg_bo_boil_vo54": B + "粉红美——人。",
        "eg_bo_boil_vo61": B + "结束了4。",
        "eg_bo_boil_vo62": B + "嘻嘻。嘻嘻。",
        "eg_bo_boil_vo63": B + "再见！",
        "eg_bo_boil_vo64": B + "力量——煮蛋。。",
        "eg_bo_boil_vo71": B + "接受吧，本4的预言。",
        "eg_bo_boil_vo72": B + "本4的预言，绝对打4。",
        "eg_bo_boil_vo73#0": B + "！",
        "eg_bo_boil_vo73#1": B + "的预言4。",
        "eg_bo_boil_vo74": B + "迷雾预言！",
        "eg_bo_boil_vo75": B + "迷雾预——言。。",
        "eg_bo_boil_vo81": B + "给尔等变成窝囊废4！",
        "eg_bo_boil_vo82": B + "这病毒，是如今的螺旋！",
        "eg_bo_boil_vo83#0": B + "病毒进化的变立，",
        "eg_bo_boil_vo83#1": "人类的场合，绝对追不上4。",
        "eg_bo_boil_vo84": B + "邪恶范——式。。",
        "eg_bo_boil_vo91": B + "杀了你4！",
        "eg_bo_boil_vo92#0": B + "目标锁定4！",
        "eg_bo_boil_vo92#1": "用这个结束这场争。",
        "eg_bo_boil_vo93#0": B + "艾格妈妈留给本4的未来之形里，",
        "eg_bo_boil_vo93#1": "你并不相配4！",
        "eg_bo_boil_vo94": B + "双电子步枪——。",
        "eg_bo_boil_w": B + "为人父母就该如此4！",
    }


def _egg(G: str) -> dict[str, str]:
    return {
        "eg_bo_egg_l": G + "（输掉了）",
        "eg_bo_egg_ms1": G + "煮蛋静静伫立着！",
        "eg_bo_egg_ms2": G + "煮蛋在放臭！",
        "eg_bo_egg_ms3#0": G + "煮蛋剧烈地熟了。",
        "eg_bo_egg_ms3#1": "会发生什么。？",
        "eg_bo_egg_ms3_b": G + "煮蛋剧烈地熟了。",
        "eg_bo_egg_vo31": G + "。。",
        "eg_bo_egg_w": G + "（看见了）",
    }


def _yonda() -> dict[str, str]:
    return {
        "eg_bo_yonda01_00": "作词作曲编曲 四次元女帝 植麦奇诺",
        "eg_bo_yonda01_02": "春先散去的那个人 如今一直在遥远次元的尽头",
        "eg_bo_yonda01_03": "两人一直永远活着 改写着历史 可是",
        "eg_bo_yonda01_04": "两人去过的次元战斗 小小圣剑咔嗒咔嗒响",
        "eg_bo_yonda01_05": "草莓白皮书哪怕再一次 连海也终究要死掉吗",
        "eg_bo_yonda01_06": "啊啊哀伤的女帝之座 如今我能做的",
        "eg_bo_yonda01_07": "啊啊重大的问题 只有向孩子们复仇",
        "eg_bo_yonda01_08": "啊啊重大的问题 只有向孩子们复仇",
        "eg_bo_yonda02_02": "夏祭两人相遇那天 捞金鱼 吃了巧克力香蕉呢",
        "eg_bo_yonda02_03": "炒面也吃过 可是卷心菜硬 肉渣也没有",
        "eg_bo_yonda02_04": "祭乐很快传来 四次元神社的境内",
        "eg_bo_yonda02_05": "你连本4的脸也不看 低声说喜欢的是你4",
        "eg_bo_yonda02_06": "呐 这场恋是玩的吗？ 燃烧的只有本4？",
        "eg_bo_yonda02_07": "呐 晒伤是烫伤吗？ 这颗心也起水泡4",
        "eg_bo_yonda02_08": "呐 晒伤是烫伤吗？ 这颗心也起水泡4",
        "eg_bo_yonda03_02": "天高马也肥的秋 吃逛两人一起胖了",
        "eg_bo_yonda03_03": "松茸柿子栗子饭 肥油秋刀鱼配萝卜泥",
        "eg_bo_yonda03_04": "恋人们手牵着手 在原宿一带约会",
        "eg_bo_yonda03_05": "你总是约去的 只有便宜连锁店",
        "eg_bo_yonda03_06": "对 枯叶看着的 是和（喜欢的东西）在一起的地方",
        "eg_bo_yonda03_06b": "对 枯叶看着的 是和（喜欢的东西）在一起的地方",
        "eg_bo_yonda03_07": "对 本4也摇着 在（你的名字）和你的夹缝",
        "eg_bo_yonda03_07b": "对 本4也摇着 在（你的名字）和你的夹缝",
        "eg_bo_yonda03_08": "对 本4也摇着 在（你的名字）和你的夹缝",
        "eg_bo_yonda03_08b": "对 本4也摇着 在（你的名字）和你的夹缝",
        "eg_bo_yonda04_02": "雪深冬的温泉 和猴子露天混浴了",
        "eg_bo_yonda04_03": "夜里缝的手套 反过来打了六下",
        "eg_bo_yonda04_04": "通宵两人打游戏 回过神已在你怀里",
        "eg_bo_yonda04_05": "细想你是不是早有预谋 就这样两人结上了吗",
        "eg_bo_yonda04_06": "呐 还要听到什么时候？ 该下指令了",
        "eg_bo_yonda04_07": "呐 还打算听下去？ 歌词也差不多结束4",
        "eg_bo_yonda04_08": "呐 还打算听下去？ 歌词也差不多结束4",
    }
