"""Colorful-egg battle lines A (matu–ball)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    F = "通贩桑夫妇："
    H = "丈夫："
    W = "妻子："
    A = "播报："
    L = "灯南瓜："
    S = "星防卫军："
    M = "明松："
    U = "动猿："
    G = "。合生："
    B = "学："
    Ma = "妈："
    T = "通贩："
    P = "气球雀："
    return {
        # --- 通贩桑夫妇 ---
        "eg_cl_matu_d": F + "地上定的飞开，不太妙啊。",
        "eg_cl_matu_l#0": W + "我稍微出门一下！",
        "eg_cl_matu_l#1": "茶撤，帮我看着点！",
        "eg_cl_matu_ms1#0": F + "两人的捨栏，对着",
        "eg_cl_matu_ms1#1": "气或形的」（乐现，叫教了起来。",
        "eg_cl_matu_ms11#0": F + "两人的捨栏，对着",
        "eg_cl_matu_ms11#1": "气或形的」（乐现，叫教了起来。",
        "eg_cl_matu_ms2#0": F + "也和丈夫一起组队",
        "eg_cl_matu_ms2#1": "立能，心里扑通扑通。",
        "eg_cl_matu_ms21#0": F + "也和丈夫一起组队",
        "eg_cl_matu_ms21#1": "立能，心里扑通扑通。",
        "eg_cl_matu_ms3": H + "超可置负地逃了。了。。",
        "eg_cl_matu_ms31": F + "也，【地想了。",
        "eg_cl_matu_ms32": F + "也，【地想了。",
        "eg_cl_matu_vo11#0": H + "再来一碗！",
        "eg_cl_matu_vo11#1": "妻子好的好的！",
        "eg_cl_matu_vo12#0": H + "再来一碗，啊，轻一点！",
        "eg_cl_matu_vo12#1": "妻子好的好的！",
        "eg_cl_matu_vo13#0": H + "稍微热一下！",
        "eg_cl_matu_vo13#1": "妻子好的好的！",
        "eg_cl_matu_vo21": A + "满球数，投出。界外。",
        "eg_cl_matu_vo211": H + "嗯嗯！",
        "eg_cl_matu_vo22#0": W + "请用！",
        "eg_cl_matu_vo22#1": "丈夫嗯嗯！",
        "eg_cl_matu_vo23": A + "穿过能中心了——。。安打。",
        "eg_cl_matu_vo24#0": W + "怎么样？",
        "eg_cl_matu_vo24#1": "丈夫嗯嗯！",
        "eg_cl_matu_vo25#0": A + "最强的打体。飞向左食（。",
        "eg_cl_matu_vo25#1": "跑者上二垒。",
        "eg_cl_matu_vo26#0": W + "今天，好像要明？",
        "eg_cl_matu_vo26#1": "丈夫嗯嗯！",
        "eg_cl_matu_vo27#0": A + "现在正打得火热。就在那当口",
        "eg_cl_matu_vo27#1": "跑者。了二垒。上三垒。安全。",
        "eg_cl_matu_vo31#0": A + "投手连着，投出。",
        "eg_cl_matu_vo31#1": "逃大啊。进得去吗？",
        "eg_cl_matu_vo33": A + "可惜。不痛。出局。",
        "eg_cl_matu_vo34#0": A + "进去了——。。本垒打——。。",
        "eg_cl_matu_vo34#1": "丈夫进去了？进去了。？进去了啊。。",
        "eg_cl_matu_w#0": A + "、【不过，转播到此结束！",
        "eg_cl_matu_w#1": "丈夫妻子，收音机！",
        # --- 灯南瓜 ---
        "eg_cl_lamp_d": L + "中」稍微露出来了。",
        "eg_cl_lamp_l": L + "呼咯咯咯。",
        "eg_cl_lamp_ms1#0": L + "和逃占的东西",
        "eg_cl_lamp_ms1#1": "从身体里跑出来了。",
        "eg_cl_lamp_ms1_a#0": L + "和灯南瓜逃占的东西",
        "eg_cl_lamp_ms1_a#1": "从身体里跑出来了。",
        "eg_cl_lamp_ms1_b#0": L + "和灯南瓜逃占的东西",
        "eg_cl_lamp_ms1_b#1": "从身体里跑出来了。",
        "eg_cl_lamp_ms2#0": L + "灯南瓜逃占的东西",
        "eg_cl_lamp_ms2#1": "从身体里跑出来了。",
        "eg_cl_lamp_ms21#0": L + "灯南瓜和",
        "eg_cl_lamp_ms21_a#0": L + "灯南瓜和",
        "eg_cl_lamp_ms22#0": L + "灯南瓜和",
        "eg_cl_lamp_ms22#1": "精神回到连了。。",
        "eg_cl_lamp_ms22_a#0": L + "和灯南瓜力的中」",
        "eg_cl_lamp_ms22_a#1": "稍微洒出来了。精神下降了。。",
        "eg_cl_lamp_ms22_b#0": L + "和灯南瓜力的中」",
        "eg_cl_lamp_ms22_b#1": "稍微洒出来了。精神下降了。。",
        "eg_cl_lamp_ms3#0": L + "靠灯南瓜的驱邪",
        "eg_cl_lamp_ms3#1": "的蛋，反转了。。",
        "eg_cl_lamp_ms31#0": L + "靠灯南瓜的驱邪",
        "eg_cl_lamp_ms31#1": "的蛋，反转了。。",
        "eg_cl_lamp_ms32": L + "给蛋怪驱邪也）活没有！",
        "eg_cl_lamp_ms33#0": L + "灯南瓜啊，那舞蹈也未免",
        "eg_cl_lamp_ms33#1": "太随便了吧？",
        "eg_cl_lamp_ms33": L + "给对方驱邪也）活没有！",
        "eg_cl_lamp_ms34": L + "给对方驱邪也）活没有！",
        "eg_cl_lamp_ms3_sel": "给谁的蛋驱邪？",
        "eg_cl_lamp_vo1": L + "哈啦哈啦呼霍。哈啦呼霍。",
        "eg_cl_lamp_vo2": L + "呼嘎啦霍嘎啦嘟甘啦呼霍落",
        "eg_cl_lamp_vo3#0": L + "哼达拉亨达拉嘟嘎比嘎哼达落",
        "eg_cl_lamp_vo3#1": "哼达拉亨达拉嘟嘎比嘎哼落",
        "eg_cl_lamp_vo3_a": L + "哼达拉亨达拉嘟嘎比嘎哼达落",
        "eg_cl_lamp_w": L + "哈呼哈霍。",
        # --- 星防卫军 ---
        "eg_cl_siro_d": S + "星防卫军拼命想想起阵。",
        "eg_cl_siro_l": S + "造：与了吗！",
        "eg_cl_siro_ms11": S + "星防卫军半了怪的阵。",
        "eg_cl_siro_ms12": S + "能力反转了。。",
        "eg_cl_siro_ms122": S + "能力反转了。。",
        "eg_cl_siro_ms13#0": S + "造也没发生。",
        "eg_cl_siro_ms13#1": "看来把阵心白了！",
        "eg_cl_siro_ms21#0": S + "星防卫军其他了！",
        "eg_cl_siro_ms21#1": "回到蛋里去了！",
        "eg_cl_siro_ms22#0": S + "星防卫军对对方说抱歉。",
        "eg_cl_siro_ms22#1": "两熟融解，回到蛋里去了！",
        "eg_cl_siro_ms221#0": S + "星防卫军对对方说抱歉。",
        "eg_cl_siro_ms221#1": "两熟融解，回到蛋里去了！",
        "eg_cl_siro_ms31": S + "星防卫军半了怪的阵。",
        "eg_cl_siro_ms32": "星防卫军的蛋复活了。。",
        "eg_cl_siro_ms32_b#0": "星防卫军的蛋复活了。。",
        "eg_cl_siro_ms32_b#1": "被干掉的将军们也回来了。",
        "eg_cl_siro_ms32_c": "星防卫军被干掉的将军们回来了。",
        "eg_cl_siro_ms33": "星防卫军的蛋复活了。。",
        "eg_cl_siro_ms34": S + "没有效果。。",
        "eg_cl_siro_ms35": S + "没有效果。。",
        "eg_cl_siro_ms4#0": S + "星防卫军怪的阵发动了。",
        "eg_cl_siro_ms4#1": "也许想起圣光了。？",
        "eg_cl_siro_vo1": S + "○与繰：啊——。。。",
        "eg_cl_siro_vo12#0": S + "优帝宫王鬼向堀井雄二鸟山明",
        "eg_cl_siro_vo12#1": "呸呸呸啊——。。。",
        "eg_cl_siro_vo2": S + "对不起！",
        "eg_cl_siro_vo21": S + "○与○与啊——。。。",
        "eg_cl_siro_vo3": S + "○○移造怎么样啊——。。",
        "eg_cl_siro_w": S + "要是能想起圣光就好了哦！",
        # --- 明松 ---
        "eg_cl_akem_d#0": M + "就算挨打，和气的测情也不消。",
        "eg_cl_akem_d#1": "不愧是专业。",
        "eg_cl_akem_l#0": M + "这下，失礼了。",
        "eg_cl_akem_l#1": "在下这等没资格出占！",
        "eg_cl_akem_ms11": M + "明松把一席演完了。",
        "eg_cl_akem_ms11_b": M + "明松把一席演完了。",
        "eg_cl_akem_ms12#0": M + "这可厉害。和",
        "eg_cl_akem_ms12#1": "明松的参数对调了。",
        "eg_cl_akem_ms13#0": M + "这可厉害。和",
        "eg_cl_akem_ms13#1": "明松的参数对调了。",
        "eg_cl_akem_ms14": M + "对调过的参数，回到连了。。",
        "eg_cl_akem_ms2": M + "用的逃包袱是。。",
        "eg_cl_akem_ms21": M + "用的逃包袱是。。",
        "eg_cl_akem_ms31": M + "明松把拿手好戏演完了。",
        "eg_cl_akem_ms32#0": "从那边飞出了打赏。",
        "eg_cl_akem_ms32#1": "明松来了劲，能力反转了。。",
        "eg_cl_akem_ms321#0": "从那边飞出了打赏。",
        "eg_cl_akem_ms321#1": "明松来了劲，能力反转了。。",
        "eg_cl_akem_ms33#0": M + "叮铃，打赏飞出来了。",
        "eg_cl_akem_ms33#1": "明松来了劲，能力反转了。。",
        "eg_cl_akem_ms33_b#0": M + "叮铃，打赏飞出来了。",
        "eg_cl_akem_ms33_b#1": "明松来了劲，能力反转了。。",
        "eg_cl_akem_ms34": M + "「波奇里」入手了。",
        "eg_cl_akem_vo1": M + "先请看在下的一席！",
        "eg_cl_akem_vo2": M + "逃包袱是这食。那么殿样攻",
        "eg_cl_akem_vo3": M + "谢谢攻",
        "eg_cl_akem_w": M + "后面请慢用攻",
        # --- 动猿 ---
        "eg_cl_ugku_d1": U + "痛得跳开着。",
        "eg_cl_ugku_d2": U + "嘎嘎抖抖的。",
        "eg_cl_ugku_d3": U + "眼看要倒下。",
        "eg_cl_ugku_l": U + "唔。一动起来心也没有",
        "eg_cl_ugku_ms1": "被动猿火了。",
        "eg_cl_ugku_ms2": "被动猿乱抓。",
        "eg_cl_ugku_ms3": "被动猿光线干掉了。",
        "eg_cl_ugku_vo11": U + "吾要动了。",
        "eg_cl_ugku_vo12": U + "喂。不饶。。",
        "eg_cl_ugku_vo13": U + "安静点。",
        "eg_cl_ugku_vo14": U + "喂。。",
        "eg_cl_ugku_vo15": U + "是体击。",
        "eg_cl_ugku_vo21": U + "给汝抓挠。",
        "eg_cl_ugku_vo22": U + "痒——痒——的呐！",
        "eg_cl_ugku_vo23": U + "哪儿？哪儿痒？",
        "eg_cl_ugku_vo24": U + "叽嘻嘻嘻嘻。",
        "eg_cl_ugku_vo25": U + "是小土兄。",
        "eg_cl_ugku_vo31": U + "是猿光线。",
        "eg_cl_ugku_vo31_a": U + "猿光线。",
        "eg_cl_ugku_vo31_b": U + "猿光线。。",
        "eg_cl_ugku_vo32": U + "把吾惹弱了啊。",
        "eg_cl_ugku_vo33": U + "部费的猴子可可怕。",
        "eg_cl_ugku_vo34": U + "是踊之土。",
        "eg_cl_ugku_vo35": U + "喂欸——————。。",
        "eg_cl_ugku_w": U + "强起来的逃星啊。",
        # --- 。合生 ---
        "eg_cl_107_d": G + "。合生正集中在。合效败！",
        "eg_cl_107_l#0": G + "。合生进入姿形的睡眠",
        "eg_cl_107_l#1": "学和妈妈从。合地占被解开了！",
        "eg_cl_107_ms1#0": G + "虽说是别人的占超",
        "eg_cl_107_ms1#1": "姿稍微痛了一下！",
        "eg_cl_107_ms112#0": G + "虽说是别人的占超",
        "eg_cl_107_ms112#1": "姿稍微痛了一下！",
        "eg_cl_107_ms2": G + "对自己明土的。合生来气了！",
        "eg_cl_107_ms21": G + "对自己明土的。合生来气了！",
        "eg_cl_107_ms3#0": G + "。合生樱花占了！",
        "eg_cl_107_ms3#1": "能力反转了！",
        "eg_cl_107_vo1#0": B + "老太婆。。乌冬什么的才不要。",
        "eg_cl_107_vo1#1": "吃了会困，不是说了只要咖啡吗。？",
        "eg_cl_107_vo1_2#0": Ma + "学君！对不起！",
        "eg_cl_107_vo1_2#1": "还以为肚子大了！",
        "eg_cl_107_vo2#0": B + "来气了。以为是造待。。",
        "eg_cl_107_vo2#1": "吵死了，没法集中。。。",
        "eg_cl_107_vo3#0": Ma + "学君。定事发测去看了。。",
        "eg_cl_107_vo3#1": "有了。学君的号码有了。。",
        "eg_cl_107_vo3_2": B + "到现在对不起。妈妈啊。。",
        "eg_cl_107_w#0": B + "老太婆。把奖优集买来。。",
        "eg_cl_107_w#1": "还有捕获他组的外间集也出了，那个也要。",
        "eg_cl_107_ap#0": "逃解繰讨星欲逃形败费君（20岁）的设计。",
        "eg_cl_107_ap#1": "。合生！。。",
        # --- 通贩 ---
        "eg_cl_tsuh_d": T + "踊桑的脚麻了。",
        "eg_cl_tsuh_l": T + "哎呀，忘了初上映所了！",
        "eg_cl_tsuh_ms1#0": T + "通贩买的怪与",
        "eg_cl_tsuh_ms1#1": "被字超到力上了。。",
        "eg_cl_tsuh_ms11#0": T + "通贩买的怪与",
        "eg_cl_tsuh_ms11#1": "被字超到力上了。。",
        "eg_cl_tsuh_ms12": T + "通贩买的怪与被字超了。。",
        "eg_cl_tsuh_ms22#0": T + "面对没来由的投诉",
        "eg_cl_tsuh_ms22#1": "支支吾吾。",
        "eg_cl_tsuh_ms221#0": T + "面对没来由的投诉",
        "eg_cl_tsuh_ms221#1": "支支吾吾。",
        "eg_cl_tsuh_ms3#0": T + "通贩桑和为恋人烦恼的漫才桑对打",
        "eg_cl_tsuh_ms3#1": "心情分了，攻击上升了。。",
        "eg_cl_tsuh_vo1": T + "诶，电视上，对对，一大自的！",
        "eg_cl_tsuh_vo2#0": T + "这是什么啊。这个。。",
        "eg_cl_tsuh_vo2#1": "这英界一点也力不了。",
        "eg_cl_tsuh_vo31#0": T + "喂喂样连桑？是我，是我！",
        "eg_cl_tsuh_vo31#1": "对对听我说！攻是，嗯，就是那样！",
        "eg_cl_tsuh_vo33": T + "那个怪与，诶，明着呢。真的。",
        "eg_cl_tsuh_w#0": T + "讨厌了这种待心。",
        "eg_cl_tsuh_w#1": "得去做奖优的准备！",
        # --- 气球雀 ---
        "eg_cl_ball_d": P + "差点军地破了。",
        "eg_cl_ball_l": P + "气球雀瘪掉了！",
        "eg_cl_ball_ms1#0": P + "气球雀能满满、梦满满地",
        "eg_cl_ball_ms1#1": "把大气敌了。",
        "eg_cl_ball_ms11": P + "气球雀的参数也鼓起来了。",
        "eg_cl_ball_ms21#0": P + "气球雀连气满满、梦满满地",
        "eg_cl_ball_ms21#1": "喊了出来。",
        "eg_cl_ball_ms22#0": P + "由眼看要瘪。",
        "eg_cl_ball_ms22#1": "气球雀喊哑了嗓子。",
        "eg_cl_ball_ms221#0": P + "由眼看要瘪。",
        "eg_cl_ball_ms221#1": "气球雀喊哑了嗓子。",
        "eg_cl_ball_ms222#0": P + "听了喊声的大家的由",
        "eg_cl_ball_ms222#1": "眼看要瘪。",
        "eg_cl_ball_ms223#0": P + "做着食气的生。",
        "eg_cl_ball_ms223#1": "真不愧。不在了。。",
        "eg_cl_ball_ms31#0": P + "气球雀心情满满、梦满满地",
        "eg_cl_ball_ms31#1": "把大气吸进去了。",
        "eg_cl_ball_ms33": P + "熟事太过，终不了。",
        "eg_cl_ball_ms331": P + "熟事太过，终不了。",
        "eg_cl_ball_w": P + "高兴得飘飘地样着。",
    }
