"""Game-over scenes. Skip debug selector lines."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    S = "塞巴斯蒂安："
    INE = "卡特莉·伊奈："
    INU = "卡特莉·伊努："
    G = "将军："
    M = "马蒂斯："
    Y = "雪子："
    MOM = "马蒂斯之母："
    HD = "我殿："
    Q = "？？？？"
    return {
        # --- all: wipe on 卡特莉·德·奥马尔 ---
        "gameover_all01": "报告：已进入卡特莉·德·奥马尔。",
        "gameover_all02": S + "什、什么的说？",
        "gameover_all03#0": S + "卡特莉·伊奈大人，卡特莉·伊努大人。",
        "gameover_all03#1": "二位请脱出。",
        "gameover_all04": S + "卡特莉·伊奈大人请脱出。",
        "gameover_all05": G + "怎么了？",
        "gameover_all06#0": "报告：卡特莉·伊奈大人，卡特莉·伊努大人。",
        "gameover_all06#1": "二位请脱出。",
        "gameover_all07": "报告：卡特莉·伊奈大人。请尽快脱出。",
        "gameover_all08#0": INE + "别说傻话呀。",
        "gameover_all08#1": "我们的婚礼该怎么办呀？",
        "gameover_all09#0": INE + "我们才不会变成败将呀。",
        "gameover_all09#1": "要是不能和我的丈夫办婚礼，",
        "gameover_all09#2": "就把这宇宙归于梦里去。",
        "gameover_all10#0": INU + "哈啊？",
        "gameover_all10#1": "都到这份上了，又在说听不懂的话！",
        "gameover_all11#0": S + "卡、卡特莉·伊奈大人。",
        "gameover_all11#1": "究竟，要做什么的说？",
        "gameover_all12#0": G + "卡、卡特莉·伊奈大人。",
        "gameover_all12#1": "究竟，要做什么？",
        "gameover_all13#0": INE + "把这艘卡特莉·德·奥马尔的船体",
        "gameover_all13#1": "给我熔毁掉。",
        "gameover_all14": S + "卡特莉·伊奈大人。",
        "gameover_all15": G + "卡特莉·伊奈大人。",
        "gameover_all16": INE + "再见了，我的丈夫。",
        "gameover_all17": "（哔）……",
        "gameover_all18": INU + "那个，是雨刷的开关啊！",
        "gameover_all19#0": INE + "糟糕。",
        "gameover_all19#1": "太想改变来世的婚礼，",
        "gameover_all19#2": "一不小心按错了呀。",
        "gameover_all20#0": S + "卡、卡特莉·伊奈大人。",
        "gameover_all20#1": "请活下去，活着",
        "gameover_all21#0": G + "卡特莉·伊奈大人。",
        "gameover_all21#1": "不可鲁莽。",
        "gameover_all21#2": "请脱出，活下去",
        "gameover_all22": INE + "再见了，现世。",
        "gameover_all23": "（哔）……",
        "gameover_all24a#0": "于是",
        "gameover_all24a#1": "卡特莉·德·奥马尔的船体",
        "gameover_all24a#2": "开始了熔毁！",
        "gameover_all24b#0": "从船体涌向中枢的强大热与压力发生了，",
        "gameover_all24b#1": "宛如卡特莉·伊奈的怒火本身，",
        "gameover_all24b#2": "不仅这颗星，连宇宙本身都被吞没进去！",
        "gameover_all24c#0": "仿佛永恒的时间流逝，",
        "gameover_all24c#1": "宇宙眼看要归于梦中，",
        "gameover_all24c#2": "那里却诞生了新生命的爆发！",
        "gameover_all24d#0": "正是新宇宙的诞生！",
        "gameover_all24d#1": "那宇宙，被无数卡特莉·伊奈所支配！",
        "gameover_all24e#0": "宇宙始友金潜气新打气眠友强",
        "gameover_all24e#1": "足定梦复费改大妹",
        "gameover_all24e#2": "——NO ONE 使知喜惑 ON大——",
        "gameover_all25": S + "什、什么的说？",
        "gameover_all26#0": S + "卡特莉·伊努大人。",
        "gameover_all26#1": "你请尽快脱出。",
        "gameover_all27": INU + "诶？",
        "gameover_all28": S + "我来拖时间的说。",
        "gameover_all29#0": G + "殿下。",
        "gameover_all29#1": "英雄之棺已被用上。",
        "gameover_all30": S + "喂，别管我。",
        "gameover_all31": INU + "老头子！",
        "gameover_all32#0": S + "卡特莉·伊努大人，请活下去，",
        "gameover_all32#1": "传达我们的遗志。",
        "gameover_all33": INU + "老、老头子——……",
        "gameover_all34#0": S + "！",
        "gameover_all34#1": "全员，从卡特莉·德·奥马尔脱出的说！",
        "gameover_all35#0": G + "诶？",
        "gameover_all35#1": G + "殿下呢？",
        "gameover_all36": S + "我留在这里！",
        "gameover_all37#0": G + "怎么会。",
        "gameover_all37#1": G + "我们也留下。",
        "gameover_all38": "英雄之棺已被用上。",
        "gameover_all39": S + "全员撤退……",
        "gameover_all40": G + "殿下。",
        "gameover_all41#0": S + "死的只要老头子就够了。",
        "gameover_all41#1": "你们要活下去，",
        "gameover_all41#2": "传达我们的遗志。",
        "gameover_all42#0": G + "殿下。",
        "gameover_all42#1": G + "殿下——……",
        "gameover_all43": G + "诶？",
        "gameover_all44#0": G + "不，这艘卡特莉·德·奥马尔",
        "gameover_all44#1": "只交给我们。",
        "gameover_all45": G + "呜、哇啊啊——……",
        "gameover_all46": INU + "打啊！",
        "gameover_all47": G + "打。",
        "gameover_all48": INU + "要逃吗？",
        "gameover_all49": G + "要逃吗？",
        "gameover_all50#0": "这艘卡特莉·德·奥马尔要是坠落，",
        "gameover_all50#1": "殿下一行人，要回到哪里去？",
        "gameover_all51": G + "！",
        "gameover_all52#0": INU + "这里要是没了，",
        "gameover_all52#1": "大家，要回哪儿去啊。",
        "gameover_all53#0": G + "这艘卡特莉·德·奥马尔要是坠落，",
        "gameover_all53#1": "殿下一行人，要回到哪里去？",
        "gameover_all54": "英雄之棺已被用上。",
        "gameover_all55": G + "呜哦哦哦——……",
        "gameover_all56#0": G + "别管——！",
        "gameover_all56#1": "我们要死守卡特莉·德·奥马尔。",
        "gameover_all57": G + "哦……",
        # --- h: 成人频道恶搞 ---
        "gameover_h01#0": S + "嗯，果然有料成人频道",
        "gameover_h01#1": "专用女优齐全，很有看头的说。",
        "gameover_h01#2": "现在，是专用的粉红",
        "gameover_h02#0": S + "谁啊。正好的时候！",
        "gameover_h02#1": "哦、是你乱闯进来",
        "gameover_h02#2": "的意思吗！",
        "gameover_h03#0": S + "塞巴斯蒂安？？",
        "gameover_h03#1": "谁啊，叫那么不帅名字的家伙！",
        "gameover_h03#2": "是我吗？我是我殿啊。",
        "gameover_h04#0": HD + "我的姿，在看的人活着的时候",
        "gameover_h04#1": "会看成最让人费心的那个人的姿的说！",
        "gameover_h05#0": HD + "你在现世的糊涂样，我可记着呢！",
        "gameover_h05#1": "从今天起，就在这里当我的用人",
        "gameover_h05#2": "活下去的说，在这永恒时间的客人之中呐！",
        "gameover_h06#0": HD + "首先开头，把我中意的",
        "gameover_h06#1": "偶像二人组给入手过来！",
        "gameover_h07#0": HD + "出道的名字、性也微妙地不同的",
        "gameover_h07#1": "○负备O终的第一组枫叶卸",
        "gameover_h07#2": "已经进到最终回入手置进了的说！",
        "gameover_h08#0": HD + "哦，差不多是商业新闻的时间了呐！",
        "gameover_h08#1": "那两连合并弱的费生状况",
        "gameover_h08#2": "究竟会是怎样一番光景呐！",
        "gameover_h09#0": HD + "什么，你还在啊。",
        "gameover_h09#1": "怎么？我？？",
        "gameover_h10#0": HD + "喂，体育时间。了。",
        "gameover_h10#1": "解说可要自己召唤来赚的说！",
        "gameover_h11#0": HD + "网上拍卖的入手是禁止的呐。",
        "gameover_h11#1": "在这天上界，可没被承认的说！",
        "gameover_h12#0": HD + "直到拿到传说的枫叶卸（所开优）",
        "gameover_h12#1": "不许回来哦。",
        # --- nuc ---
        "gameover_nuc01": INE + "！",
        "gameover_nuc02": "宇宙死友体潜气新打气眠友强",
        "gameover_nuc02a": "定梦复费改逃",
        "gameover_nuc02b": "——投撤飞感亲逃怖——",
        # --- pro: 阿尔玛之月全灭 ---
        "gameover_pro01#0": G + "殿下。",
        "gameover_pro01#1": "敌军，到了我国的星。",
        "gameover_pro01_a#0": G + "了、了不得了。",
        "gameover_pro01_a#1": "敌军，到了我国的星。",
        "gameover_pro02": S + "什、什么的说？",
        "gameover_pro03": INE + "难、难道，我的丈夫他……？",
        "gameover_pro04#0": S + "卡特莉·伊奈大人。",
        "gameover_pro04#1": "请定定神。",
        "gameover_pro05": INE + "呵！",
        "gameover_pro06": S + "卡、卡特莉·伊奈大人？",
        "gameover_pro07": INE + "呵呵！",
        "gameover_pro08": INU + "伊奈？",
        "gameover_pro09": S + "卡特莉·伊奈大人？",
        "gameover_pro10": INE + "有精神呀。",
        "gameover_pro11": INU + "哈啊？",
        "gameover_pro12": S + "诶？",
        "gameover_pro13#0": INE + "没有我丈夫的世界",
        "gameover_pro13#1": "根本没有价值！",
        "gameover_pro14#0": INE + "既然一样没价值，",
        "gameover_pro14#1": "那就消失到真正的地球去呀。",
        "gameover_pro14#2": "用我们的手……",
        "gameover_pro15": S + "卡、卡特莉·伊奈大人。",
        "gameover_pro16": INU + "等、等一下，认真的？",
        "gameover_pro17#0": "于是",
        "gameover_pro17#1": "卡特莉·伊奈的神之力发动了！",
        "gameover_pro18#0": "长达十九年半的战争结束，",
        "gameover_pro18#1": "世界变成了虚无！",
        "gameover_pro19": S + "难、难道殿下他。",
        "gameover_pro20#0": S + "！",
        "gameover_pro20#1": "全员，从星球脱出的说！",
        "gameover_pro21#0": G + "诶？",
        "gameover_pro21#1": G + "殿下呢？",
        "gameover_pro22": S + "我留在这里！",
        "gameover_pro23": INU + "诶？",
        "gameover_pro24#0": G + "怎么会。",
        "gameover_pro24#1": G + "我们也留下。",
        "gameover_pro25#0": S + "死的只要老头子就够了。",
        "gameover_pro25#1": "你们要活下去，",
        "gameover_pro25#2": "传达我们的遗志。",
        "gameover_pro26": INU + "老头子。",
        "gameover_pro27#0": G + "别管殿下——！",
        "gameover_pro27#1": "我们要死守阿尔玛之月。",
        "gameover_pro28": G + "哦……",
        "gameover_pro29": INU + "都是笨蛋啊，大家。",
        "gameover_pro30#0": G + "了、了不得了。",
        "gameover_pro30#1": "敌军到了我国的星。",
        "gameover_pro31": G + "什、什么——？",
        "gameover_pro32#0": G + "难、难道",
        "gameover_pro32#1": "殿下他。",
        "gameover_pro33": G + "呜、哇啊啊——……",
        "gameover_pro34": INU + "打啊！",
        "gameover_pro35": G + "打。",
        "gameover_pro36": INU + "要逃吗？",
        "gameover_pro37": G + "要逃吗？",
        "gameover_pro38": G + "！",
        "gameover_pro39#0": INU + "这里要是没了，",
        "gameover_pro39#1": "大家，要回哪儿去啊。",
        "gameover_pro40#0": G + "这颗阿尔玛之月星要是坠落，",
        "gameover_pro40#1": "殿下一行人，要回到哪里去？",
        "gameover_pro41": "英雄之棺已被用上。",
        "gameover_pro42": G + "呜哦哦哦——……",
        "gameover_pro43#0": G + "别管——！",
        "gameover_pro43#1": "我们要死守阿尔玛之月星。",
        "gameover_pro44": G + "哦……",
        # --- tue: 马蒂斯全灭 ---
        "gameover_tue01": M + "这里，是哪里？",
        "gameover_tue02": Q + "马蒂斯！",
        "gameover_tue03": M + "谁、是谁？",
        "gameover_tue04": Q + "哥哥！",
        "gameover_tue05": M + "雪、雪子？",
        "gameover_tue06#0": Q + "已经，不必再勉强",
        "gameover_tue06#1": "开心了！",
        "gameover_tue07": M + "老妈。",
        "gameover_tue08": Y + "可怜的哥哥！",
        "gameover_tue09": M + "诶？",
        "gameover_tue10#0": MOM + "来，欢迎你！",
        "gameover_tue10#1": "好好地睡吧，一起！",
        "gameover_tue11#0": M + "你、你在说什么啊。",
        "gameover_tue11#1": "俺还得继续战斗呢。",
        "gameover_tue12": Y + "哥哥！",
        "gameover_tue13#0": M + "这里，难道。",
        "gameover_tue13#1": "俺，已经死了吗？",
        "gameover_tue14": MOM + "欢迎你，马蒂斯！",
        "gameover_tue15": M + "呜、呜哦哦哦……",
    }
