"""Planet help, dungeon telops, egg-world boss99, 中美合 leftover."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    A = "中美合："
    Q = "？？？？"
    return {
        # planet help
        "planet_00_help#0": "阿尔玛之月的人激所烦恼的",
        "planet_00_help#1": "自然勇的星！",
        "planet_00_help#2": "降临在半熟英雄的中枢",
        "planet_00_star": "·",
        "planet_01_help#0": "充满气与力·的",
        "planet_01_help#1": "蔷薇之金所协的星",
        "planet_01_help#2": "爱做梦的出入在此烦恼",
        "planet_01_star": "·",
        "planet_02_help#0": "状不足的",
        "planet_02_help#1": "干燥的星",
        "planet_02_help#2": "好战的出入在此烦恼",
        "planet_02_star": "··",
        "planet_03_help#0": "充满状的",
        "planet_03_help#1": "终好力「的星",
        "planet_03_help#2": "能感到不可思议的力量",
        "planet_03_star": "··",
        "planet_04_help#0": "怪物走来走去的",
        "planet_04_help#1": "被赤殿的熟投住的星",
        "planet_04_help#2": "感觉不到人的姿",
        "planet_04_star": "··",
        "planet_05_help#0": "靠分强的·大",
        "planet_05_help#1": "开发出来的星",
        "planet_05_help#2": "没有活着的生命体",
        "planet_05_star": "···",
        "planet_06_help#0": "与半熟英雄相比",
        "planet_06_help#1": "不可思议的入择",
        "planet_06_help#2": "连向（大心",
        "planet_06_star": "？？？",
        "planet_07_help#0": "相对半熟英雄出现的",
        "planet_07_help#1": "从次元的夹缝",
        "planet_07_help#2": "有什么在呼唤",
        "planet_07_star": "····",
        "planet_08": "？白择好早星",
        "planet_08_help#0": "红色的使和：的休",
        "planet_08_help#1": "还有友的亲昵之造",
        "planet_08_help#2": "彼此交织的星",
        "planet_08_star": "·····",
        # dungeon title cards
        "dg_telop_01": "——起始的迷宫——",
        "dg_telop_02#0": "——起始迷宫的",
        "dg_telop_02#1": "金之迷宫——",
        "dg_telop_03": "——：与溪流的」合——",
        "dg_telop_04": "——谁也不知道的欲周——",
        "dg_telop_05": "——天使守护的合现之里——",
        "dg_telop_06": "——魔界花的，——",
        "dg_telop_07": "——见役穴——",
        "dg_telop_08#0": "——湿润合现的优初",
        "dg_telop_08#1": "以及将们梦的修——",
        "dg_telop_09": "——失去的待沉睡的入口——",
        "dg_telop_10": "——蛋世界——",
        "dg_telop_fri": "——系统破裂洞——",
        "dg_telop_mon": "——坏光的淤滞——",
        "dg_telop_sun": "——寂静的穴——",
        "dg_telop_thu": "——映以的光——",
        "dg_telop_tue": "——捕见的夹缝——",
        "dg_telop_wed": "——状中的（大心——",
        # egg world super bosses (katakana speech → 汉字)
        "dg_boss99_1": "蛋怪变地球酱",
        "dg_boss99_1_mes#0": Q + "憎恶复仇复杂的心",
        "dg_boss99_1_mes#1": "想利用蛋世界的",
        "dg_boss99_1_mes#2": "力量的人们！",
        "dg_boss99_1_mes#3": Q + "相信人类",
        "dg_boss99_1_mes#4": "至今被背叛过多少次。",
        "dg_boss99_2": "蛋怪变红龙",
        "dg_boss99_2_mes#0": Q + "相信人类",
        "dg_boss99_2_mes#1": "至今被背叛过多少次！",
        "dg_boss99_2_mes#2": Q + "除了仅有的一次",
        "dg_boss99_2_mes#3": "好事一件也没有。",
        "dg_boss99_3": "蛋怪变哈迪斯",
        "dg_boss99_3_mes#0": Q + "除了仅有的一次！",
        "dg_boss99_3_mes#1": Q + "对",
        "dg_boss99_3_mes#2": "相信了半熟之物们的",
        "dg_boss99_3_mes#3": "那个决断除外呐。",
        "dg_boss99_4": "难道是你们！",
        # 中美合 leftover battle
        "ch6_101": "中美合",
        "ch6_101_at2": "当场打",
        "ch6_101_atk1": "周力",
        "ch6_101_d": A + "看起来完全不像。",
        "ch6_101_l#0": A + "居然会输啊！",
        "ch6_101_l#1": "嘿，稍微动了一下！",
        "ch6_101_ms1#0": A + "以眼里看不见的威复感",
        "ch6_101_ms1#1": "连动一下都不能。",
        "ch6_101_ms11#0": A + "今日的天气很差，生",
        "ch6_101_ms11#1": "看不清楚。",
        "ch6_101_ms2#0": A + "失所不大的待消地（",
        "ch6_101_ms2#1": "袭了过来。",
        "ch6_101_w": A + "是当近的魔小！",
    }
