"""Hidden-note / secret trump battle lines (奥义)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    S = "塞巴斯蒂安："
    F = "弗莱迪："
    R = "鲁奈："
    P = "彭普蒂："
    M = "梅尔克里："
    return {
        "okunote_coming_ms": "嘎啊——……受到了打击。",
        "okunote_coming_tk#0": "其实，到现在都还小着来着",
        "okunote_coming_tk#1": "（咕哝咕哝）的说！",
        "okunote_cook_ms#0": "吓得把手一松把蛋弄掉了！",
        "okunote_cook_ms#1": "的蛋碎掉了。",
        "okunote_cook_ms2": "吓得把手一松把蛋弄掉了！",
        "okunote_cook_tk#0": "请你吃我珍藏的土」自！",
        "okunote_cook_tk#1": "啊心",
        "okunote_daijin_ms": "塞巴斯蒂安发动了新的殿下攻击。",
        "okunote_daijin_tk": S + "熟·强情攻击大友友强的说。",
        "okunote_daiz_ms": "塞巴斯蒂安发动了新的殿下攻击。",
        "okunote_daiz_tk": S + "间·殿下攻击威的说。",
        "okunote_eejyanai_ms": "被祭典的逃中气迷住了！",
        "okunote_eejyanai_tk": "有何不可。有何不可。有何不可。",
        "okunote_frid_ms#0": "有威严的弗莱迪把身份藏起来，做了个可爱的动作！",
        "okunote_frid_ms#1": "熟逃了，防御大幅下降……",
        "okunote_frid_tk": F + "俺可是人类呀——！呜嗯呜嗯！",
        "okunote_gyaku_ms#0": "向摇摆星许了战斗胜利的愿！",
        "okunote_gyaku_ms#1": "力量涌上来了！",
        "okunote_gyaku_ms2": "向摇摆星许了能和长团的愿！",
        "okunote_gyaku_tk": "啊。摇摆星。得许个愿才行。",
        "okunote_hero_ms": "的鼻屎大爆炸了。",
        "okunote_hero_tk#0": "抠抠",
        "okunote_hero_tk#1": "嘣。",
        "okunote_look_ms": "呀。对假货的初将跪拜着！",
        "okunote_look_tk#0": "喂。退下退下。把这位当成何人姿复。",
        "okunote_look_tk#1": "敢问，前方乃占部队大人。",
        "okunote_manjyuu_ms#0": "听了那个，",
        "okunote_manjyuu_ms#1": "用馒头攻过来了。好吃。能力恢复了。",
        "okunote_manjyuu_tk#0": "我这世上最【的东西就是馒头！",
        "okunote_manjyuu_tk#1": "一想馒头的事连夜也睡不着！",
        "okunote_maru_ms#0": "马蒂斯的任之踢",
        "okunote_maru_ms#1": "回复到了。",
        "okunote_maru_tk#0": "超级黄金金属斧炸弹打击光线",
        "okunote_maru_tk#1": "最终神闪耀马蒂斯踢……",
        "okunote_meru_ms": "的头上掉下来了木盆！",
        "okunote_meru_tk": M + "嗯！出来了哦！是待激木盆哪。",
        "okunote_modoki_ms#0": "硬来做了龙骑士！",
        "okunote_modoki_ms#1": "休·总会有办法的！",
        "okunote_modoki_tk": "生」也能飞啊……",
        "okunote_okesta_ms": "，【。没中。日了状……",
        "okunote_okesta_tk": "来，是！的时间了。",
        "okunote_papa_ms": "太好了。拿到波奇利零花钱了。",
        "okunote_papa_tk#0": "好——好！对我心爱可爱的",
        "okunote_papa_tk#1": "爸爸给你零花钱！",
        "okunote_park_ms": "被过山车碾了……",
        "okunote_park_tk": "过山车啊——。耶——……",
        "okunote_penp_ms": "彭普蒂把仆从们召唤来了！",
        "okunote_penp_tk": P + "出来吧。吾之仆从们。",
        "okunote_runa_ms": "鲁奈把靠近的所有体都温柔地样回了！",
        "okunote_runa_tk": R + "对靠近又害怕的人，活食也没有呀！",
        "okunote_sixhit_ms": "地解。挨了6下……",
        "okunote_sixhit_tk": "手套以外是什么？",
        "okunote_sparta_ms#0": "的将军们不情愿地体击了！",
        "okunote_sparta_ms#1": "将军死上了！",
        "okunote_sparta_ms2": "大慌了！",
        "okunote_sparta_tk#0": "体击——……由收——。……拿到「的",
        "okunote_sparta_tk#1": "我与10作给哦——……放下——。不放吗——……",
        "okunote_tooku_ms": "被飞到了某处远处！",
        "okunote_tooku_ms2": "没有被飞走！",
        "okunote_tooku_tk#0": "我们成为使，无论多远都远落",
        "okunote_tooku_tk#1": "远落远落",
        "okunote_use": "使出了。！",
        "okunote_usi_ms": "做了心的诅咒，报应却回到了自己身上！",
        "okunote_usi_tk#0": "好恨啊——好悔啊——这份怨！",
        "okunote_usi_tk#1": "去享受！变弱！变成不！去死！",
        "okunote_yoiko_ms": "世上也有不知道比较好的事！",
        "okunote_yoiko_tk#0": "咚咔。啪唧。砰。咯嘣咯嘣。哗。",
        "okunote_yoiko_tk#1": "哧溜哧溜。啪滋啪滋。啪嚓啪嚓。啾噜。",
        "okunote_yomu_ms": "为了万一配了待世的不！",
        "okunote_yomu_tk#0": "就算尽写些金钱逃复",
        "okunote_yomu_tk#1": "也抓不住客人的心！",
    }
