"""Egg-world remaining bosses, beta telop, guest Martis, leftover UI."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    Q = "？？？？"
    M = "马蒂斯："
    return {
        "dg_boss91": "蛋怪变蓝龙",
        "dg_boss91_mes": Q + "回去。",
        "dg_boss92": "蛋怪变巨型妖精",
        "dg_boss92_mes": Q + "请回去。",
        "dg_boss93": "蛋怪变天龙",
        "dg_boss93_mes#0": Q + "这里不是人",
        "dg_boss93_mes#1": "该来的地方。",
        "dg_boss94": "蛋怪变巴哈穆乔",
        "dg_boss94_mes#0": Q + "再往前",
        "dg_boss94_mes#1": "你想求的是什么。",
        "dg_boss95": "蛋怪变巴尔",
        "dg_boss95_mes": Q + "已经没有回头的气了呢。",
        "dg_boss96": "蛋怪变创可贴",
        "dg_boss96_mes#0": Q + "用尽我们的全力",
        "dg_boss96_mes#1": "阻止你们。",
        "dg_boss97": "蛋怪变亚历克桑达。",
        "dg_boss97_mes#0": Q + "居然会有拥有",
        "dg_boss97_mes#1": "如此力量的人。",
        "dg_boss98": "蛋怪变天空公主",
        "dg_boss98_mes#0": Q + "你们再往前探访",
        "dg_boss98_mes#1": "会有什么改变吗。",
        "dg_kaihatsu": "——半熟英雄4开发军——",
        "dg_kami": "蛋怪变神",
        "dg_zoud": "蛋怪变象三大王",
        "dg_beta#0": "测试回的迷宫",
        "dg_beta#1": "到这里为止！",
        "dg_beta#2": "可有合心玩到吗！",
        "dg_beta2#0": "降下写下、字在诸星的迷宫",
        "dg_beta2#1": "选择、场地的食",
        "dg_beta2#2": "请合心享受！",
        "alpha_maltis#0": M + "哦！",
        "alpha_maltis#1": "小队人数少，看起来挺呛啊。",
        "alpha_maltis#2": M + "嘛，。是周目啊！",
        "alpha_maltis#3": "俺感动的那段情节就跳过",
        "alpha_maltis#4": "来给你们当力。",
        "alpha_maltis2#1": "半捕英雄·马蒂斯成为了同伴。",
        "ev_telop_DQ": "大事先生，感谢您的静摇。",
        "fmenu_defence_castle_any#0": "，",
        "fmenu_gen_01_2#2": "要不要买点什么啊？",
        "menumes_composite_select_egg#0": "从打向阿尔玛之月收来的秘密蛋力里",
        "menumes_composite_select_egg#1": "输入解开优先的密码！",
        "ev_comp_movie#0": "用不用的那边",
        "ev_comp_movie#1": "星喜道军的凯阿尔",
        "ev_comp_movie#2": "快点",
        "sysmes_dic_term#4": "把终殿的名字放上，",
        "sysmes_dic_term#5": "这1连……",
        "sysmes_dic_term#8": "阵降",
        "sysmes_dic_term#9": "阵降",
        "sysmes_dic_term#10": "体",
        "sysmes_dungeon_bonus_term#1": "号分乐姿",
        "sysmes_dungeon_bonus_term#3": "：复读臭",
        "sysmes_dungeon_bonus_term#4": "层",
        "sysmes_field_bonus_term#0": "殿",
        "sysmes_field_bonus_term#1": "通关用坏",
        "sysmes_field_bonus_term#2": "置的奖励",
        "sysmes_field_bonus_term#7": "临坏",
        "sysmes_field_bonus_term#9": "定使",
        "sysmes_sound_list#10": "捨所以新队长",
        "sysmes_sound_list#24": "情形潜气",
        "sysmes_sound_list#37": "怪",
    }
