"""Eggmon / unit collection complete events. Debug menus left untranslated."""
from __future__ import annotations

INE = "卡特莉·伊奈："
INU = "卡特莉·伊努："
AKE = "明松："
OME = "恭喜鸟："


def by_id() -> dict[str, str]:
    return {
        # ----- eggmon complete -----
        "ev_comp_egg1#0": f"{AKE}蛋怪图鉴",
        "ev_comp_egg1#1": "收集完成。",
        "ev_comp_egg2#0": f"{OME}呼、呼、呼",
        "ev_comp_egg2#1": "呼——！",
        "ev_comp_egg3": f"{INE}恭喜呀。",
        "ev_comp_egg4": f"{OME}恭喜。",
        "ev_comp_egg5#0": f"{INE}比起前作翻了一倍的",
        "ev_comp_egg5#1": "200只蛋怪居然全收集了",
        "ev_comp_egg5#2": "挺能干的呀",
        "ev_comp_egg6#0": f"{INE}能做到这份上的，史克威尔艾尼克斯",
        "ev_comp_egg6#1": "调试部里也只有老练测试员那种程度哟！",
        "ev_comp_egg7": f"{INE}诶？既然收集完了，要给点什么？",
        "ev_comp_egg8#0": "嗯。",
        "ev_comp_egg8#1": "不要。",
        "ev_comp_egg9#0": f"{INE}那就，对我丈夫",
        "ev_comp_egg9#1": "保密哦呀",
        "ev_comp_egg9#2": "闭上眼睛！",
        "ev_comp_egg10#0": f"{INE}对我丈夫",
        "ev_comp_egg10#1": "会保密的呀",
        "ev_comp_egg10#2": "来，闭上眼睛！",
        "ev_comp_egg11": f"{INE}嗯啾呀呀",
        "ev_comp_egg12": f"{OME}恭喜。",
        "ev_comp_egg13#0": f"{AKE}嗯，总之",
        "ev_comp_egg13#1": "蛋怪图鉴收集完成。",
        "ev_comp_egg14": f"{INE}恭喜恭喜呀呀",
        "ev_comp_egg15": f"{OME}恭喜。。",
        "ev_comp_egg16#0": f"{AKE}蛋怪图鉴",
        "ev_comp_egg16#1": "收集完成。",
        "ev_comp_egg17#0": f"{OME}呼、呼、呼",
        "ev_comp_egg17#1": "呼——！",
        "ev_comp_egg18": f"{OME}恭喜恭喜。",
        "ev_comp_egg19#0": f"{INU}两百多只蛋怪",
        "ev_comp_egg19#1": "居然全收集，闲得够可以吧？",
        "ev_comp_egg20#0": f"{INU}史克威尔艾尼克斯调试部的",
        "ev_comp_egg20#1": "测试员都哭着求饶了啊！",
        "ev_comp_egg20#2": "没别的事干吗？",
        "ev_comp_egg21#0": "嗯。",
        "ev_comp_egg21#1": "有啊。",
        "ev_comp_egg22#0": f"{INU}不过能做到这份上",
        "ev_comp_egg22#1": "还是得说声谢谢！",
        "ev_comp_egg23": f"{INU}别那么较真啊！",
        "ev_comp_egg24#0": f"{AKE}不不不，真是辛苦了。",
        "ev_comp_egg24#1": "非常感谢。",
        "ev_comp_egg24#2": "蛋怪图鉴收集完成。",
        "ev_comp_egg25": f"{OME}恭喜恭喜。",
        # ----- unit complete -----
        "ev_comp_gen1": f"{AKE}部队名鉴收集完成。",
        "ev_comp_gen2#0": f"{OME}呼、呼、呼",
        "ev_comp_gen2#1": "呼——！",
        "ev_comp_gen3": f"{INE}恭喜恭喜呀呀",
        "ev_comp_gen4": f"{OME}恭喜。",
        "ev_comp_gen5#0": f"{INE}比起前作又翻了一倍的",
        "ev_comp_gen5#1": "将近500人的部队居然全收集了",
        "ev_comp_gen5#2": "超厉害的呀",
        "ev_comp_gen6#0": f"{INE}史克威尔艾尼克斯调试部也",
        "ev_comp_gen6#1": "绝对不行。把调试模式开给我。这么",
        "ev_comp_gen6#2": "哭着求来着。嗯呼呀",
        "ev_comp_gen7#0": f"{INE}收集完了，想要奖励吧？",
        "ev_comp_gen7#1": "奖·励·呀",
        "ev_comp_gen8#0": "嗯。",
        "ev_comp_gen8#1": "不要。",
        "ev_comp_gen9#0": f"{INE}嗯，对我丈夫",
        "ev_comp_gen9#1": "会保密的！",
        "ev_comp_gen9#2": "来。",
        "ev_comp_gen10": f"{INE}脸红什么的好可爱呀",
        "ev_comp_gen11#0": "吵死了。",
        "ev_comp_gen11#1": "我才没有。",
        "ev_comp_gen12#0": f"{INE}下定决心，变漂亮吧。",
        "ev_comp_gen12#1": "来。",
        "ev_comp_gen13#0": f"{INE}这会儿怎样都无所谓呀",
        "ev_comp_gen13#1": "快呀",
        "ev_comp_gen14": f"{AKE}快，逃吧。趁现在。。",
        "ev_comp_gen15#0": f"{INE}干什么呀。",
        "ev_comp_gen15#1": "我可是最强亮相啊。。",
        "ev_comp_gen16": f"{AKE}呃，部队名鉴收集完成。",
        "ev_comp_gen17#0": f"{INE}才不是恭喜呀。",
        "ev_comp_gen17#1": "喂，你们给我闭嘴。",
        "ev_comp_gen18": f"{AKE}噫。",
        "ev_comp_gen19": f"{OME}恭喜！鸟。。",
        "ev_comp_gen20": f"{AKE}部队名鉴收集完成。",
        "ev_comp_gen21#0": f"{OME}呼、呼、呼",
        "ev_comp_gen21#1": "呼——！",
        "ev_comp_gen22": f"{OME}恭喜恭喜。",
        "ev_comp_gen23": f"{INU}将近500人的部队，全收集。？",
        "ev_comp_gen24": f"{INU}我认输了，做到这份上是真的！",
        "ev_comp_gen25": f"{INU}所以，想要点什么？",
        "ev_comp_gen26#0": "嗯。",
        "ev_comp_gen26#1": "无所谓啦",
        "ev_comp_gen27": f"{INU}真拿你没办法！",
        "ev_comp_gen28": f"{INU}别大意啊。",
        "ev_comp_gen29": f"{INU}来。",
        "ev_comp_gen30#0": f"{INU}开玩笑的。",
        "ev_comp_gen30#1": "光心跳一下，也算好礼物了吧？",
        "ev_comp_gen31#0": f"{AKE}啊，心跳是真的",
        "ev_comp_gen31#1": "不不不，真是辛苦了。",
        "ev_comp_gen31#2": "部队名鉴收集完成。",
        "ev_comp_gen32": f"{OME}恭喜恭喜。",
    }
