"""Planet minigames: Dead Gun bowling, chicken curling, cattle catch, etc."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    return {
        # ----- Friday: cattle mutilation catcher -----
        "ev_mini_fri01#0": "塞巴斯蒂安：呣，弗莱迪现。",
        "ev_mini_fri01#1": "那是。。",
        "ev_mini_fri02#0": "弗莱迪：被牛只切割过的",
        "ev_mini_fri02#1": "部队一样啊！",
        "ev_mini_fri02#2": "居然藏在这种地方！",
        "ev_mini_fri03": "塞巴斯蒂安：又来了的说。",
        "ev_mini_fri04#0": "弗莱迪：好！",
        "ev_mini_fri04#1": "把那章鱼修好",
        "ev_mini_fri04#2": "再来一次牛只切割！",
        "ev_mini_fri05#0": "塞巴斯蒂安：那、那种事可能",
        "ev_mini_fri05#1": "唔。？",
        "ev_mini_fri06#0": "播音员：好。。Tiki Tiki",
        "ev_mini_fri06#1": "部队捕捉。",
        "ev_mini_fri07#0": "播音员：这是用外星人",
        "ev_mini_fri07#1": "去抓部队的游戏。",
        "ev_mini_fri07#2": "唔。？",
        "ev_mini_fri08#0": "塞巴斯蒂安：哈！",
        "ev_mini_fri08#1": "仿佛做了什么梦",
        "ev_mini_fri08#2": "哦哦。？",
        "ev_mini_fri09": "塞巴斯蒂安：居然，部队数量增加了人。",
        "ev_mini_fri10#0": "塞巴斯蒂安：哈！",
        "ev_mini_fri10#1": "仿佛做了什么梦！",
        "ev_mini_fri11#0": "塞巴斯蒂安：哟，弗莱迪现！",
        "ev_mini_fri11#1": "来，休息到此为止",
        "ev_mini_fri11#2": "回战场吧的说！",
        "ev_mini_fri12": "可外星人　能移动",
        # ----- Monday: chicken curling -----
        "ev_mini_mon01#0": "塞巴斯蒂安：殿下——。",
        "ev_mini_mon01#1": "又把我的宝贝书给狗",
        "ev_mini_mon01#2": "吃掉了——。。",
        "ev_mini_mon02#0": "鲁奈：啊。、",
        "ev_mini_mon02#1": "那里刚磨过",
        "ev_mini_mon03#0": "播音员：好。。Tiki Tiki",
        "ev_mini_mon03#1": "鸡肉冰壶。",
        "ev_mini_mon04#0": "播音员：这项竞技，是竞滑行的",
        "ev_mini_mon04#1": "停下距离的游戏！",
        "ev_mini_mon05#0": "播音员：鲁奈用刷子磨冰的话",
        "ev_mini_mon05#1": "滑行距离就会变长！",
        "ev_mini_mon06#0": "播音员：把速度调整好",
        "ev_mini_mon06#1": "请停得正正好。",
        "ev_mini_mon07": "鲁奈：准备好了，？",
        "ev_mini_mon08#0": "嗯。",
        "ev_mini_mon08#1": "不行。",
        "ev_mini_mon09": "鲁奈：那就，开始。",
        "ev_mini_mon10a#0": "鲁奈：那、那样",
        "ev_mini_mon10a#1": "回去吧？",
        "ev_mini_mon10b#0": "鲁奈：啰嗦。",
        "ev_mini_mon10b#1": "上吧，。。",
        "ev_mini_mon11": "播音员：那么，开始投掷。。",
        "ev_mini_mon12#0": "播音员：啊——。",
        "ev_mini_mon12#1": "投球过线。。",
        "ev_mini_mon13#0": "。的分数　点",
        "ev_mini_mon13#1": "最高分　点",
        "ev_mini_mon14": "鲁奈：对不起，",
        "ev_mini_mon15": "鲁奈：做得不错呢，。",
        "ev_mini_mon16#0": "嗯。",
        "ev_mini_mon16#1": "不行。",
        "ev_mini_mon17#0": "鲁奈：那、那样",
        "ev_mini_mon17#1": "过分。",
        "ev_mini_mon18": "磨冰",
        # ----- Sunday: Dead Gun bowling -----
        "ev_mini_sun01#0": "塞巴斯蒂安：殿下——。",
        "ev_mini_sun01#1": "拿我的新作王牌来玩",
        "ev_mini_sun01#2": "请停手。",
        "ev_mini_sun02": "塞巴斯蒂安：唔唔又是Dead Gun。",
        "ev_mini_sun03#0": "塞巴斯蒂安：没办法的说！",
        "ev_mini_sun03#1": "殿下，这次可以吗？",
        "ev_mini_sun04#0": "播音员：好。。Tiki Tiki",
        "ev_mini_sun04#1": "Dead Gun保龄。",
        "ev_mini_sun05#0": "播音员：这项竞技，发射",
        "ev_mini_sun05#1": "竞打倒的瓶数！",
        "ev_mini_sun06#0": "播音员：机会有2次。。",
        "ev_mini_sun06#1": "2发以内打出补中或全中的话",
        "ev_mini_sun06#2": "还能再来1局。",
        "ev_mini_sun07#0": "播音员：连续10局以内",
        "ev_mini_sun07#1": "请冲击最高分。",
        "ev_mini_sun08#0": "塞巴斯蒂安：来，殿下，",
        "ev_mini_sun08#1": "准备好了吗的说？",
        "ev_mini_sun09#0": "嗯。",
        "ev_mini_sun09#1": "不行。",
        "ev_mini_sun10": "塞巴斯蒂安：那就，开始的说。",
        "ev_mini_sun11": "塞巴斯蒂安：现在才怕就晚了的说！",
        "ev_mini_sun12#0": "游戏",
        "ev_mini_sun12#1": "○蓄力／松开发射",
        "ev_mini_sun13#0": "塞巴斯蒂安：殿下，漂亮。",
        "ev_mini_sun13#1": "全中的说。。",
        "ev_mini_sun14#0": "塞巴斯蒂安：殿下，是补中的说。",
        "ev_mini_sun14#1": "再来一局的说！",
        "ev_mini_sun15": "塞巴斯蒂安：居然殿下，是洗沟。？",
        "ev_mini_sun16#0": "塞巴斯蒂安：呣！",
        "ev_mini_sun16#1": "殿下，无奈，到此为止的说！",
        "ev_mini_sun17#0": "。的分数　点",
        "ev_mini_sun17#1": "最高分　点",
        "ev_mini_sun18#0": "塞巴斯蒂安：殿下，",
        "ev_mini_sun18#1": "可有尽兴的说？",
        "ev_mini_sun19#0": "嗯。",
        "ev_mini_sun19#1": "不行。",
        "ev_mini_sun20": "塞巴斯蒂安：那么，下个月再期待！",
        # ----- Thursday: bat memory -----
        "ev_mini_thu01#0": "彭普蒂：哼！",
        "ev_mini_thu01#1": "号·头又晕得更厉害了！",
        "ev_mini_thu02": "彭普蒂：稍微练练脑力吧！",
        "ev_mini_thu03#0": "播音员：好。。Tiki Tiki",
        "ev_mini_thu03#1": "蝙蝠神经衰弱。",
        "ev_mini_thu04": "播音员：神经衰弱，知道的吧？",
        "ev_mini_thu05#0": "嗯。",
        "ev_mini_thu05#1": "不知道。",
        "ev_mini_thu06#0": "播音员：那么",
        "ev_mini_thu06#1": "鼓起劲上吧。。",
        "ev_mini_thu07#0": "播音员：蝙蝠背面画着凡·派·雅，",
        "ev_mini_thu07#1": "以及其他角色各2个！",
        "ev_mini_thu08#0": "播音员：选2只蝙蝠，选中的蝙蝠背面",
        "ev_mini_thu08#1": "是同一角色就算完成一对。",
        "ev_mini_thu08#2": "不同就翻回去！",
        "ev_mini_thu09#0": "播音员：让全部角色都完成一对",
        "ev_mini_thu09#1": "就过关。",
        "ev_mini_thu10#0": "播音员：尽量又快又少手数",
        "ev_mini_thu10#1": "过关就能拿高分。",
        "ev_mini_thu11p": "派：嘛，好好",
        "ev_mini_thu11v": "凡：占。了可不管啊。",
        "ev_mini_thu11y": "雅：休息，彭普蒂。",
        "ev_mini_thu12": "播音员：那么魔小的发测。",
        "ev_mini_thu13#0": "时间　",
        "ev_mini_thu13#1": "最佳　",
        "ev_mini_thu13#2": "手数　。",
        "ev_mini_thu13#3": "最佳　。",
        "ev_mini_thu14#0": "。的分数　点",
        "ev_mini_thu14#1": "最高分　点",
        "ev_mini_thu15p": "派：还行吧",
        "ev_mini_thu15v": "凡：哼。",
        "ev_mini_thu15y": "雅：好厉害，彭普蒂。",
        "ev_mini_thu16p": "派：说的不是这个！",
        "ev_mini_thu16v": "凡：啊啊！",
        "ev_mini_thu16y": "雅：逃喜势？彭普蒂！",
        "ev_mini_thu17#0": "SELECT　选择蝙蝠",
        "ev_mini_thu17#1": "○　翻开",
        # ----- Tuesday: hero pose -----
        "ev_mini_tue01#0": "马蒂斯：终于到手了。",
        "ev_mini_tue01#1": "半捕英雄君。。",
        "ev_mini_tue02#0": "马蒂斯：集齐重装王道之力的道",
        "ev_mini_tue02#1": "最新健身机吗。",
        "ev_mini_tue03#0": "马蒂斯：只要有这家伙，什么姿势",
        "ev_mini_tue03#1": "都能摆出来。",
        "ev_mini_tue04#0": "播音员：好。。Tiki Tiki",
        "ev_mini_tue04#1": "英雄造型装",
        "ev_mini_tue05": "马蒂斯：电视机前的半捕粉丝们，让你们等了。",
        "ev_mini_tue06#0": "马蒂斯：这是为了半捕英雄君号。",
        "ev_mini_tue06#1": "为研究帅姿势而开发的",
        "ev_mini_tue06#2": "最新健身机。",
        "ev_mini_tue07#0": "马蒂斯：只要配合它摆姿势",
        "ev_mini_tue07#1": "你的英雄范也会直线上升。",
        "ev_mini_tue08": "播音员：！",
        "ev_mini_tue09": "马蒂斯：上了。",
        "ev_mini_tue10": "半捕英雄君：显示得分哦",
        "ev_mini_tue11#0": "。的分数　点",
        "ev_mini_tue11#1": "最高分　点",
        "ev_mini_tue12": "马蒂斯：好，还过得去。",
        "ev_mini_tue13": "马蒂斯：可恶。",
        "ev_mini_tue14#0": "",
        "ev_mini_tue14#1": "○",
        "ev_mini_tue14#2": "",
        "ev_mini_tue14#3": "与",
        # ----- Wednesday: Mercury fortune -----
        "ev_mini_wed01": "梅尔克里",
        "ev_mini_wed02": "梅尔克里：且让吾来占你的运势！",
        "ev_mini_wed03": "梅尔克里：想知道什么哪？",
        "ev_mini_wed04#0": "恋的事",
        "ev_mini_wed04#1": "健康的事",
        "ev_mini_wed04#2": "运势的事",
        "ev_mini_wed05#0": "梅尔克里：那就，听吾的战斗哪！",
        "ev_mini_wed05#1": "好吗？",
        "ev_mini_wed06#0": "嗯。",
        "ev_mini_wed06#1": "不行。",
        "ev_mini_wed07": "梅尔克里：就是那个结局哪！",
        "ev_mini_wed08#0": "梅尔克里：嚯，你中意的是",
        "ev_mini_wed08#1": "叫做！",
        "ev_mini_wed09": "梅尔克里：不可撒谎哪！",
    }
