"""Next-episode-style ending preview (ev_end_pre) plus debug assistant warp."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    return {
        # ----- tokusatsu-style next-episode preview -----
        "ev_end_pre01#0": "降临地球、带来和平的七位半熟英雄！",
        "ev_end_pre01#1": "能守护和平的半熟英雄们，终于，游戏业界",
        "ev_end_pre01#2": "最强之敌挡在了面前。",
        "ev_end_pre02#0": "艾格曼，能胜过巴哈姆特吗。？",
        "ev_end_pre02#1": "然后，半熟英雄，会泡在赌场里吗。？",
        "ev_end_pre03": "这一次，半熟英雄史上最初的最终任务",
        "ev_end_pre04#0": "卡特莉·伊奈：星海尽头婚礼之梦破碎的卡特莉·伊奈！",
        "ev_end_pre04#1": "美丽姿容被践踏者的怒火终于爆发。",
        "ev_end_pre04#2": "憎恶全宇宙的叛乱开始了。",
        "ev_end_pre05#0": "卡特莉·伊奈：这一次，半熟英雄系列完结篇",
        "ev_end_pre05#1": "全宇宙里最漂亮的就是我呀。",
        "ev_end_pre06": "卡特莉·伊奈：你说呀。",
        "ev_end_pre07": "佐佐木功：诶？",
        "ev_end_pre08": "卡特莉·伊奈：是决胜台词呀。",
        "ev_end_pre09": "佐佐木功：啊，不是，这可没写啊！",
        "ev_end_pre10#0": "卡特莉·伊奈：好啦，你说呀。",
        "ev_end_pre10#1": "要比平时更起劲哦。",
        "ev_end_pre10#2": "知道吗？要充满热情哦。",
        "ev_end_pre11": "佐佐木功：服了啊！",
        "ev_end_pre12#0": "卡特莉·伊奈：星海尽头婚礼之梦破碎的卡特莉·伊奈！",
        "ev_end_pre12#1": "美丽姿容被践踏者的怒火终于爆发。",
        "ev_end_pre12#2": "憎恶全宇宙的叛乱开始了。",
        "ev_end_pre13#0": "卡特莉·伊奈：这一次，半熟英雄系列完结篇",
        "ev_end_pre13#1": "全宇宙里最漂亮的就是我呀。",
        "ev_end_pre14": "佐佐木功：Egg Keeeck。。",
        "ev_end_pre15#0": "卡特莉·伊奈：好，辛苦了。",
        "ev_end_pre15#1": "我呀，想吃烤肉呀",
        "ev_end_pre15#2": "这之后，带我去好不好？",
        "ev_end_pre16#0": "佐佐木功：诶？不是，那个",
        "ev_end_pre16#1": "工作上还有安排啊！",
        "ev_end_pre17#0": "卡特莉·伊奈：来，走吧。",
        "ev_end_pre17#1": "我肚子饿扁了呀",
        "ev_end_pre17#2": "吃什么好呢。",
        "ev_end_pre18": "佐佐木功：不、不要啊，所以说。",
        "ev_end_pre19#0": "卡特莉·伊奈：先来特上牛小排和上舌盐，还有",
        "ev_end_pre19#1": "特上牛小排和上里脊和特上牛小排和上横膈膜，还有",
        "ev_end_pre19#2": "特上牛小排和极上西冷，再来唐培里侬呀",
        "ev_end_pre20": "佐佐木功：来、来、来人啊——。",
        # ----- debug assistant (staff-room warp) -----
        "ev_assistant1#0": "助手：你好，英雄！",
        "ev_assistant1#1": "助手：我在这儿，",
        "ev_assistant1#2": "其实并不是作为游戏角色出现的！",
        "ev_assistant1#3": "助手：有人拜托我，去半熟英雄4的",
        "ev_assistant1#4": "开发组里带路！",
        "ev_assistant1#5": "助手：虽然有点麻烦，",
        "ev_assistant1#6": "还是带你去开发组吧！",
        "ev_assistant1#7": "助手：来，闭上眼睛！",
        "ev_assistant2#0": "助手：哎呀，英雄！",
        "ev_assistant2#1": "已经要回去了吗？",
        "ev_assistant2_2#0": "是",
        "ev_assistant2_2#1": "不是",
        "ev_assistant2_3#0": "助手：明白了！",
        "ev_assistant2_3#1": "来，闭上眼睛！",
        "ev_assistant2_4": "助手：想回去的时候，跟我说一声哦！",
    }
