"""Test / sample-disc leftover Japanese (not ASCII English)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    S = "塞巴斯蒂安："
    INE = "卡特莉·伊奈："
    INU = "卡特莉·伊努："
    R = "鲁奈："
    M = "马蒂斯："
    ME = "梅尔克里："
    P = "彭普蒂："
    F = "弗莱迪："
    PA = "派："
    VA = "凡："
    YA = "雅："
    SB = "塞巴斯酱："
    return {
        "test_battle_trump": "感觉使用了！",
        "test_battle_trump_accept": "使用了！！",
        "test_cannot_enter_alpha": "周目的话，这里进不去哦。",
        "test_cannot_enter_beta": "体验版的话，这里进不去哦。",
        "test_clear#1": "通关。",
        "test_disable_alpha": "周目的话，做不到哦。",
        "test_disable_beta": "体验版的话，做不到哦。",
        "test_gameover#1": "游戏结束",
        "test_gameover01": S + "主人公殿",
        "test_gameover02": S + "主人公殿。",
        "test_gameover03#0": S + "相当",
        "test_gameover03#1": "做噩梦来着的说！",
        "test_gameover04#0": S + "是做了什么讨厌的梦，",
        "test_gameover04#1": "才那样的吗？",
        "test_gameover04#2": "在这儿睡着，可是会误了说明的说！",
        "test_gameover05#0": S + "你说什么？",
        "test_gameover05#1": "梦见阿尔玛之月军被敌军击溃",
        "test_gameover05#2": "了，是这个意思吗？",
        "test_gameover06#1": "有那种感觉",
        "test_gameover07#0": S + "那样的话会做噩梦也不无道理的说！",
        "test_gameover07#1": "不过，请放心！",
        "test_gameover07#2": "世界的和平，已经再次打开了的说。",
        "test_gameover08#0": INE + "就是呀。",
        "test_gameover08#1": "降临的上优、大喜惑佐玛的话",
        "test_gameover08#2": "我们一口气就给扫掉了呀",
        "test_gameover09#0": R + "一时还以为会怎样",
        "test_gameover09#1": "梦占，世界的和平已经再次打开了。",
        "test_gameover10": M + "哎呀，真是够呛的一仗。",
        "test_gameover11": ME + "！",
        "test_gameover12": ME + "正是迷雾蛋的启示哪！",
        "test_gameover13#0": P + "眠在妖精星的民",
        "test_gameover13#1": "不久也会迎来被置的时候吧！",
        "test_gameover14#0": VA + "这样！",
        "test_gameover14#1": PA + "世界就和平！",
        "test_gameover14#2": YA + "了嘛。",
        "test_gameover15#0": F + "话说回来，主人公睡着了",
        "test_gameover15#1": "还真是帮了大忙啊。",
        "test_gameover16#0": F + "那场临战里头",
        "test_gameover16#1": "一蹦一蹦地生出来",
        "test_gameover16#2": "真是受不了啊。",
        "test_gameover17#0": INU + "话说",
        "test_gameover17#1": "赶紧办婚礼吧！",
        "test_gameover18": INE + "对了呀",
        "test_gameover19#0": INE + "来，我的丈夫",
        "test_gameover19#1": "来入的准备已经大世了呀",
        "test_gameover20#0": INE + "戴上一殿的面纱",
        "test_gameover20#1": "没捕消地接了吻之后",
        "test_gameover20#2": "那挑立还没教完就冲进淋浴",
        "test_gameover21#0": INE + "过了临的一待之后",
        "test_gameover21#1": "卡路里消耗也一定不是半世",
        "test_gameover21#2": "初分会非常大，我们",
        "test_gameover22#0": INE + "大鲔和海胆和大鲔和",
        "test_gameover22#1": "鲍鱼和大鲔和近虾和大鲔和星鳗和",
        "test_gameover22#2": "大鲔和鲑鱼籽和大鲔和香槟呀",
        "test_memcard_slot_check#0": "正在检查存储卡（PS2）！",
        "test_memcard_slot_check#1": "请不要拔插槽1·2的存储卡（PS2）或",
        "test_memcard_slot_check#2": "手柄之类的！",
        "test_monthly_which_person#0": "卡特莉·伊奈",
        "test_monthly_which_person#1": "卡特莉·伊努",
        "test_movie_player#0": "影片播放器",
        "test_movie_player#1": "结尾",
        "test_movie_player#2": "开头",
        "test_movie_player#3": "演示",
        "test_movie_player#4": "序章标志",
        "test_movie_player#5": "序章标题",
        "test_movie_player#6": "浪漫标志",
        "test_movie_player#7": "浪漫标题",
        "test_movie_player#8": "重装标志",
        "test_movie_player#9": "重装标题",
        "test_movie_player#10": "宝瓶标志",
        "test_movie_player#11": "宝瓶标题",
        "test_movie_player#12": "榆木标志",
        "test_movie_player#13": "榆木标题",
        "test_movie_player#14": "我思故我在标志",
        "test_movie_player#15": "我思故我在标题",
        "test_movie_player#16": "星使的鲸标志",
        "test_movie_player#17": "星使的鲸标题",
        "test_movie_player#18": "过场○人生",
        "test_movie_player#19": "过场鲁奈1",
        "test_movie_player#20": "过场鲁奈2",
        "test_movie_player#21": "过场鲁奈3",
        "test_movie_player#22": "过场鲁奈4",
        "test_movie_player#23": "过场彭普蒂",
        "test_movie_player#24": "过场梅尔克里",
        "test_movie_player#25": "过场弗莱迪1",
        "test_movie_player#26": "过场弗莱迪2",
        "test_movie_player#27": "过场弗莱迪3",
        "test_movie_player#28": "过场教复殿下",
        "test_movie_player#29": "我明攻飞所",
        "test_movie_player#30": "我明攻",
        "test_movie_player#31": "我飞所明攻",
        "test_movie_player#32": "我飞所",
        "test_movie_player#33": "我明攻",
        "test_movie_player#34": "我飞所",
        "test_movie_player#35": "我大感谢",
        "test_movie_player#36": "我妹小",
        "test_movie_player#37": "中美合周力",
        "test_movie_player#38": "中美合当场打",
        "test_movie_player#39": "中美合再大感谢",
        "test_movie_player#40": "中美合被干掉",
        "test_movie_player#41": "记事",
        "test_movie_player#42": "兔美战场",
        "test_movie_player#43": "持是和哈瓦那辣椒",
        "test_movie_player#44": "赤叶外郎",
        "test_movie_player#45": "木岛「以地",
        "test_movie_player#46": "堂吉诃德",
        "test_movie_player#47": "过场马蒂斯",
        "test_movie_player#48": "重装副标题",
        "test_movie_player2#0": "影片库",
        "test_movie_player2#1": "开头再战。半熟英雄",
        "test_movie_player2#2": "演示",
        "test_movie_player2#3": "阿尔玛之月改标志",
        "test_movie_player2#4": "阿尔玛之月改标题",
        "test_movie_player2#5": "阿尔玛之月改过场",
        "test_movie_player2#6": "浪漫改标志",
        "test_movie_player2#7": "浪漫改标题",
        "test_movie_player2#8": "浪漫改过场1",
        "test_movie_player2#9": "浪漫改过场2",
        "test_movie_player2#10": "浪漫改过场3",
        "test_movie_player2#11": "浪漫改过场4",
        "test_movie_player2#12": "重装改标志",
        "test_movie_player2#13": "重装改标题1",
        "test_movie_player2#14": "重装改标题2",
        "test_movie_player2#15": "重装改过场",
        "test_movie_player2#16": "宝瓶改标志",
        "test_movie_player2#17": "宝瓶改标题",
        "test_movie_player2#18": "宝瓶改过场",
        "test_movie_player2#19": "榆木改标志",
        "test_movie_player2#20": "榆木改标题",
        "test_movie_player2#21": "榆木改过场",
        "test_movie_player2#22": "我思故我在改标志",
        "test_movie_player2#23": "我思故我在改标题",
        "test_movie_player2#24": "我思故我在改过场1",
        "test_movie_player2#25": "我思故我在改过场2",
        "test_movie_player2#26": "我思故我在改过场3",
        "test_movie_player2#27": "星使的鲸改标志",
        "test_movie_player2#28": "星使的鲸改标题",
        "test_movie_player2#29": "星使的鲸改过场",
        "test_movie_player2#30": "变形。卡特莉攻击速度型",
        "test_movie_player2#31": "变形。卡特莉攻击守卫型",
        "test_movie_player2#32": "变形。卡特莉速度攻击型",
        "test_movie_player2#33": "变形。卡特莉速度守卫型",
        "test_movie_player2#34": "变形。卡特莉守卫攻击型",
        "test_movie_player2#35": "变形。卡特莉守卫速度型",
        "test_movie_player2#36": "中美合改大感谢",
        "test_movie_player2#37": "中美合改妹小",
        "test_movie_player2#38": "中美合改周力",
        "test_movie_player2#39": "中美合改当场打",
        "test_movie_player2#40": "中美合改再大感谢",
        "test_movie_player2#41": "中美合改被干掉",
        "test_movie_player2#42": "结尾半熟6团9（姿54）",
        "test_no_dungeon_extra#0": "体验版的话，打空部队",
        "test_no_dungeon_extra#1": "进不了迷宫！",
        "test_pre_title#0": "从最初开始",
        "test_pre_title#1": "从续关开始",
        "test_pre_title_mes1": "了……",
        "test_pre_title_mes2": "输掉了……",
        "test_stop_alpha": "周目的话，只能做到这里",
        "test_stop_beta": "体验版的话，只能做到这里",
        "test_telop#0": "字幕测试",
        "test_telop#1": "没关系",
        "test_worldmap_bug#0": SB + "这里对殿下还军反的说！",
        "test_worldmap_bug#1": "还有，漏洞在",
        "test_worldmap_intro": SB + "是世界地图的说！",
    }
