"""Dungeon tutorial (丹·琼斯 / 被俘者)."""
from __future__ import annotations


def by_id() -> dict[str, str]:
    D = "丹·琼斯："
    C = "被俘者："
    return {
        "dg_tutorial01": D + "你们像是新人呐？",
        "dg_tutorial01_3#0": D + "这样啊！",
        "dg_tutorial01_3#1": "那就，关于这座迷宫",
        "dg_tutorial01_3#2": "我也没时间给你们细讲了呐？",
        "dg_tutorial01_4#0": D + "明白了！我不会放弃的！",
        "dg_tutorial01_4#1": "你们就按自己想走的路，",
        "dg_tutorial01_4#2": "以自己想要的速度前进便是！",
        "dg_tutorial01_5#0": D + "嗯！",
        "dg_tutorial01_5#1": "你们是抱着什么理由进来的",
        "dg_tutorial01_5#2": "那不是我该管的事",
        "dg_tutorial01_5#3": D + "可我也不想这座迷宫里",
        "dg_tutorial01_5#4": "再添多余的尸体！",
        "dg_tutorial01_5#5": D + "就给你们",
        "dg_tutorial01_5#6": "一点忠告吧！",
        "dg_tutorial01_5#7": "先只讲一点点！",
        "dg_tutorial01_5#8": D + "首先想教你们的",
        "dg_tutorial01_5#9": "只有三件事！",
        "dg_tutorial01_5#10": "什么也不说，给我好好听着！",
        "dg_tutorial01_5#11": D + "「左摇杆」移动自己，",
        "dg_tutorial01_5#12": "「右摇杆」转动镜头！",
        "dg_tutorial01_5#13": D + "用左摇杆不断向前走的同时",
        "dg_tutorial01_5#14": "偶尔大胆转转右摇杆就好！",
        "dg_tutorial01_5#15": "没什么，马上就会习惯的！",
        "dg_tutorial01_5#16": D + "战斗和平时一样打就行！",
        "dg_tutorial01_5#17": "和在地上的时候一样！",
        "dg_tutorial01_5#18": "○是耐力，是菜单！",
        "dg_tutorial01_5#19": D + "然后，查看我们这些人、",
        "dg_tutorial01_5#20": "门、宝箱之类的时候",
        "dg_tutorial01_5#21": "要用△！",
        "dg_tutorial01_5#22": D + "先这三件就够了！",
        "dg_tutorial01_5#23": "给我好好记住！",
        "dg_tutorial01_5#24": D + "还有很多不懂的事吧",
        "dg_tutorial01_5#25": "那些就慢慢再说明！",
        "dg_tutorial02#0": D + "嗯，又来了呐！",
        "dg_tutorial02#1": D + "在这座迷宫前进，可习惯了？",
        "dg_tutorial02#2": "也不是那么坏的地方吧！",
        "dg_tutorial02#3": D + "只要把这里搜一遍",
        "dg_tutorial02#4": "光装备就能提升威力的王牌",
        "dg_tutorial02#5": "据说能入手好几张呐！",
        "dg_tutorial02#6": D + "不过一松劲就会回不了原来的世界",
        "dg_tutorial02#7": "在这儿一直徘徊下去！",
        "dg_tutorial02#8": D + "那种事",
        "dg_tutorial02#9": "可不想听到吧？",
        "dg_tutorial02#10": D + "所以再让我给一点忠告",
        "dg_tutorial02#11": "可以吗！",
        "dg_tutorial02#12": "在迷宫里活下去的窍门！",
        "dg_tutorial02#13": D + "那么",
        "dg_tutorial02#14": "就来说明两种门吧！",
        "dg_tutorial02_2#0": D + "这是「用钥匙开的门」！",
        "dg_tutorial02_2#1": "用叫做「门钥匙」的王牌之类",
        "dg_tutorial02_2#2": "就可以打开！",
        "dg_tutorial02_2#3": D + "钥匙的名字每颗星都稍微不同！",
        "dg_tutorial02_2#4": "钥匙要么在宝箱里，要么有人拿着",
        "dg_tutorial02_2#5": "要好好搜索楼层呐！",
        "dg_tutorial02_3#0": D + "这就是「用拉杆开的门」！",
        "dg_tutorial02_3#1": "开着的和关着的两种",
        "dg_tutorial02_3#2": "会在同一层里！",
        "dg_tutorial02_3#3": D + "找到开着的拉杆门之后",
        "dg_tutorial02_3#4": "这一层的某处",
        "dg_tutorial02_3#5": "也一定有关着的拉杆门！",
        "dg_tutorial02_4#0": D + "用的就是这个「拉杆」！",
        "dg_tutorial02_4#1": "不过，已经开着的",
        "dg_tutorial02_4#2": "再扳拉杆就会关上，要注意呐！",
        "dg_tutorial02_5#0": D + "要是从诸星的迷宫过来的",
        "dg_tutorial02_5#1": "这些门大概已经眼熟了吧！",
        "dg_tutorial02_5#2": D + "总之",
        "dg_tutorial02_5#3": "先前进、去享受看看！",
        "dg_tutorial02_5#4": D + "失败是不会有的！",
        "dg_tutorial02_5#5": "以你们，一定能撑下去！",
        "dg_tutorial02_5#6": D + "！",
        "dg_tutorial02_5#7": D + "好像带着不可思议的力量",
        "dg_tutorial02_5#8": "以你们的话，呐！",
        "dg_tutorial03#0": D + "我倒是想过",
        "dg_tutorial03#1": "你们的部队，好像带着能召唤蛋怪的",
        "dg_tutorial03#2": "蛋呐！",
        "dg_tutorial03#3": D + "你们会到这儿来",
        "dg_tutorial03#4": "总觉得有什么奇妙的东西！",
        "dg_tutorial03#5": D + "详细的，不该在这儿说明！",
        "dg_tutorial03#6": "没什么，时日一到自然会明白！",
        "dg_tutorial03#7": "自然会，呐！",
        "dg_tutorial03#8": D + "那么，就来把门和通路",
        "dg_tutorial03#9": "再说明两件吧！",
        "dg_tutorial03_2#0": D + "这是「用炸弹开的门」！",
        "dg_tutorial03_2#1": "用叫做「扔炸弹」的王牌",
        "dg_tutorial03_2#2": "就可以打开！",
        "dg_tutorial03_2#3": D + "不过，扔炸弹",
        "dg_tutorial03_2#4": "战斗里也能用，是张强力王牌！",
        "dg_tutorial03_2#5": "得想想怎么用才行呐！",
        "dg_tutorial03_3#0": D + "然后，这是「单向通行的通路」！",
        "dg_tutorial03_3#1": "正如所见，只能往一个方向走的通路！",
        "dg_tutorial03_3#2": "给我好好想清楚再来！",
        "dg_tutorial03_4#0": D + "不过，要小心！",
        "dg_tutorial03_4#1": "这类门的情报",
        "dg_tutorial03_4#2": "不会显示在未完成的小地图上！",
        "dg_tutorial03_4#3": D + "想查看门之类的情报",
        "dg_tutorial03_4#4": "就从菜单选「迷宫地图」",
        "dg_tutorial03_4#5": "确认门和楼梯的位置！",
        "dg_tutorial03_4#6": D + "对了，已经和那个打过了吗？",
        "dg_tutorial03_4#7": D + "对尸体搭话也没用哦！",
        "dg_tutorial03_4#8": "眼睛完全闭上了！",
        "dg_tutorial03_4#9": D + "一定是以和我们不同的样子",
        "dg_tutorial03_4#10": "迷进这座迷宫",
        "dg_tutorial03_4#11": "来的吧！",
        "dg_tutorial03_4#12": D + "那么，从我这儿",
        "dg_tutorial03_4#13": "给一条战斗方面的忠告！",
        "dg_tutorial03_4#14": D + "这座迷宫里能入手很多王牌！",
        "dg_tutorial03_4#15": "但要把全部带回去",
        "dg_tutorial03_4#16": "毕竟是做不到的吧！",
        "dg_tutorial03_4#17": D + "所以，入手的王牌",
        "dg_tutorial03_4#18": "到了紧要关头就尽管用！",
        "dg_tutorial03_4#19": D + "太依赖蛋怪的话",
        "dg_tutorial03_4#20": "关键时刻蛋怪的能力",
        "dg_tutorial03_4#21": "已经所剩无几，说不定会卡住！",
        "dg_tutorial03_4#22": D + "记住比较好！",
        "dg_tutorial03_4#23": "然后小心，慢慢地，前进吧！",
        "dg_tutorial03_4#24": D + "被迷宫迷住、陷进去",
        "dg_tutorial03_4#25": "把现实世界的事忘掉",
        "dg_tutorial03_4#26": "那本身也是件可悲的事呐！",
        "dg_tutorial04#0": D + "嗯，又来了呐！",
        "dg_tutorial04#1": "这儿也是个不错的入口吧！",
        "dg_tutorial04#2": D + "探索这座迷宫的话",
        "dg_tutorial04#3": "光装备就能提升威力的王牌",
        "dg_tutorial04#4": "据说能入手好几张呐！",
        "dg_tutorial04#5": D + "哎呀，这话已经说过了吗？",
        "dg_tutorial04#6": "上了年纪就会糊涂，不行啊！",
        "dg_tutorial04#7": D + "嗯！",
        "dg_tutorial04#8": "那么，关于迷宫里放着的",
        "dg_tutorial04#9": "各种东西来说明吧！",
        "dg_tutorial04_2#0": D + "这就是「坛子」！",
        "dg_tutorial04_2#1": "打破它说不定能入手王牌！",
        "dg_tutorial04_3#0": D + "然后，这是「宝箱」！",
        "dg_tutorial04_3#1": "你们也见过几次了吧！",
        "dg_tutorial04_3#2": D + "里面有有效的道具，",
        "dg_tutorial04_3#3": "也有被安了陷阱的情况呐！",
        "dg_tutorial04_4#0": D + "然后，「上锁的宝箱」！",
        "dg_tutorial04_4#1": "这要用敌人掉的「小钥匙」",
        "dg_tutorial04_4#2": "那种王牌来打开！",
        "dg_tutorial04_4#3": D + "里面装的是「门钥匙」！",
        "dg_tutorial04_4#4": "也就是说不开的话",
        "dg_tutorial04_4#5": "就没法往前走！",
        "dg_tutorial04_4#6": D + "再说一遍，查看这类宝箱、",
        "dg_tutorial04_4#7": "查看门、对人搭话的时候",
        "dg_tutorial04_4#8": "要用△！",
        "dg_tutorial04_5#0": D + "无论何时都不能忘记的是",
        "dg_tutorial04_5#1": "绝对不要硬来！",
        "dg_tutorial04_5#2": D + "用敌人掉的王牌「能回去吗」",
        "dg_tutorial04_5#3": "就能立刻回到进来的入口！",
        "dg_tutorial04_5#4": D + "回复将军也好",
        "dg_tutorial04_5#5": "把王牌集中整理也好",
        "dg_tutorial04_5#6": "怎么都推荐回到地上去呐！",
        "dg_tutorial04_5#7": D + "然后",
        "dg_tutorial04_5#8": "这是我最后的忠告！",
        "dg_tutorial04_5#9": D + "你们",
        "dg_tutorial04_5#10": "是不是一直被「落穴」耍到现在！",
        "dg_tutorial04_5#11": D + "还有，有好几处楼梯的楼层",
        "dg_tutorial04_5#12": "迷路的情况也不少吧！",
        "dg_tutorial04_5#13": D + "那种时候，先停下来一次",
        "dg_tutorial04_5#14": "去确认整体地图！",
        "dg_tutorial04_5#15": D + "落穴一定是往下掉！",
        "dg_tutorial04_5#16": "楼梯一定连到不同楼层的同一处降临！",
        "dg_tutorial04_5#17": D + "打开整体地图后，按方向键",
        "dg_tutorial04_5#18": "也能确认上楼的位置！",
        "dg_tutorial04_5#19": D + "自己这前要去哪里",
        "dg_tutorial04_5#20": "已经走到了哪里",
        "dg_tutorial04_5#21": "要养成时常确认的习惯，不许忘！",
        "dg_tutorial04_5#22": D + "那么",
        "dg_tutorial04_5#23": "我能教的，就这些了！",
        "dg_tutorial04_5#24": D + "前路还长！",
        "dg_tutorial04_5#25": "剩下的，就由你们慢慢",
        "dg_tutorial04_5#26": "边走边想吧！",
        "dg_tutorial04_5#27": D + "！",
        "dg_tutorial04_5#28": D + "诸星上的小迷宫",
        "dg_tutorial04_5#29": "在地下10层，据说在争某种优先！",
        "dg_tutorial04_5#30": D + "然后，与英雄相比",
        "dg_tutorial04_5#31": "直到地下100层的巨大迷宫",
        "dg_tutorial04_5#32": "你们在那前方，会看见什么呢！",
        # --- always helper ---
        "dg_tutorial_always01#0": C + "对这座迷宫的被俘者",
        "dg_tutorial_always01#1": "：想问什么？",
        "dg_tutorial_always02_1#0": "询问关于修复",
        "dg_tutorial_always02_1#1": "询问关于门",
        "dg_tutorial_always02_1#2": "询问关于王牌",
        "dg_tutorial_always02_1#3": "询问关于宝箱",
        "dg_tutorial_always02_1#4": "询问关于回去的方法",
        "dg_tutorial_always02_2#0": "想传送到民中的层",
        "dg_tutorial_always02_2#1": "询问关于修复",
        "dg_tutorial_always02_2#2": "询问关于门",
        "dg_tutorial_always02_2#3": "询问关于王牌",
        "dg_tutorial_always02_2#4": "询问关于宝箱",
        "dg_tutorial_always02_2#5": "询问关于回去的方法",
        "dg_tutorial_always03#0": C + "「左摇杆」移动自己，",
        "dg_tutorial_always03#1": "「右摇杆」转动镜头！",
        "dg_tutorial_always03#2": C + "○消耗耐力，",
        "dg_tutorial_always03#3": "打开菜单！",
        "dg_tutorial_always03#4": C + "查看什么的时候用△！",
        "dg_tutorial_always03#5": "记住比较好！",
        "dg_tutorial_always03#6": C + "：还想问别的吗？",
        "dg_tutorial_always04#0": C + "「用钥匙开的门」",
        "dg_tutorial_always04#1": "用王牌的钥匙来开！",
        "dg_tutorial_always04#2": C + "「用拉杆开的门」，用同一层里的",
        "dg_tutorial_always04#3": "拉杆来做开闭的修复！",
        "dg_tutorial_always04#4": C + "「用炸弹开的门」用扔炸弹打开，",
        "dg_tutorial_always04#5": "「单向通行的通路」是单行道！",
        "dg_tutorial_always04#6": "记住比较好！",
        "dg_tutorial_always04#7": C + "：还想问别的吗？",
        "dg_tutorial_always05#0": C + "从坛子和宝箱，或者和对方战斗之后",
        "dg_tutorial_always05#1": "有时能入手王牌！",
        "dg_tutorial_always05#2": C + "这些会收进菜单里能打开的",
        "dg_tutorial_always05#3": "「宝物袋」！",
        "dg_tutorial_always05#4": C + "王牌里有用来开门的钥匙、",
        "dg_tutorial_always05#5": "装备后能提升威力的东西等等",
        "dg_tutorial_always05#6": "有利的很多！",
        "dg_tutorial_always05#7": C + "另外，从：等人的移动星",
        "dg_tutorial_always05#8": "把王牌带进这座迷宫时",
        "dg_tutorial_always05#9": "装备好再到这里来就行！",
        "dg_tutorial_always05#10": C + "「宝物袋」能装的数量有限制！",
        "dg_tutorial_always05#11": "不过，据说某处有人会把那袋子",
        "dg_tutorial_always05#12": "给变大！",
        "dg_tutorial_always05#13": C + "：还想问别的吗？",
        "dg_tutorial_always06#0": C + "要打开「上锁的宝箱」",
        "dg_tutorial_always06#1": "需要王牌「小钥匙」！",
        "dg_tutorial_always06#2": C + "里面常常装着「门钥匙」！",
        "dg_tutorial_always06#3": "要在迷宫里往前走",
        "dg_tutorial_always06#4": "就有必要打开这「上锁的宝箱」！",
        "dg_tutorial_always06#5": C + "：还想问别的吗？",
        "dg_tutorial_always07#0": C + "要从这座迷宫脱出",
        "dg_tutorial_always07#1": "下到地下1层，或者",
        "dg_tutorial_always07#2": "使用王牌「能回去吗」！",
        "dg_tutorial_always07#3": C + "迷宫里不能存档！",
        "dg_tutorial_always07#4": "随时注意别把「能回去吗」用光",
        "dg_tutorial_always07#5": "这点很有必要呐！",
        "dg_tutorial_always07#6": C + "：还想问别的吗？",
        "dg_tutorial_always08#0": C + "：在这颗星的迷宫里",
        "dg_tutorial_always08#1": "还不能说已经攒够了",
        "dg_tutorial_always08#2": "足以传送的情况！",
        "dg_tutorial_always08#3": C + "：还想问别的吗？",
        "dg_tutorial_always09#0": C + "很好！",
        "dg_tutorial_always09#1": "把眼睛闭上吧！",
        "dg_tutorial_always09#2": "把你送到相称的层去！",
    }
